#!/usr/bin/env python3
"""Build forecast selection, lifecycle, override and publication-profile contracts."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
ROOT=Path(__file__).resolve().parent; AS_OF="2026-08-26"
def s(k,t,a,u,support,limit): return {"source_id":f"source.fgl.{k}","title":t,"authority":a,"url":u,"retrieved":AS_OF,"source_kind":"primary_or_official","supports":support,"does_not_prove":limit}
SOURCES=[
 s("gneiting.raftery","Strictly Proper Scoring Rules, Prediction, and Estimation","Gneiting and Raftery","https://doi.org/10.1198/016214506000001437","proper scoring rules align probabilistic forecast reports with declared outcome and scoring semantics","One proper score is not a universal selection objective or business utility."),
 s("hyndman.koehler","Another Look at Measures of Forecast Accuracy","Hyndman and Koehler","https://doi.org/10.1016/j.ijforecast.2006.03.001","forecast error measures have scale, zero, intermittency and comparability limitations","MASE or another measure does not decide model selection by itself."),
 s("tashman.rolling","Out-of-sample Tests of Forecasting Accuracy","Leonard Tashman","https://doi.org/10.1016/S0169-2070(00)00065-0","origin policy, window, refitting and multiple test periods materially define an evaluation","Rolling origin does not eliminate selection bias or future regime change."),
 s("diebold.mariano","Comparing Predictive Accuracy","Diebold and Mariano","https://doi.org/10.1080/07350015.1995.10524599","comparative predictive accuracy requires an exact loss differential and dependence treatment","A statistical comparison is not selection or publication authority."),
 s("m4","The M4 Competition: Results, Findings, Conclusion and Way Forward","Makridakis et al.","https://doi.org/10.1016/j.ijforecast.2018.06.001","large heterogeneous series collections expose method rankings, combinations and baseline dependence","Competition rank does not prove fitness for a different population or purpose."),
 s("m5.accuracy","The M5 Accuracy Competition: Results, Findings and Conclusions","Makridakis et al.","https://doi.org/10.1016/j.ijforecast.2021.11.013","hierarchical retail evaluation uses exact scales, weights, horizons and baselines","A leaderboard is not operational selection governance."),
 s("m5.uncertainty","The M5 Uncertainty Competition: Results, Findings and Conclusions","Makridakis et al.","https://doi.org/10.1016/j.ijforecast.2021.10.005","quantile forecasts and uncertainty evaluation require level-, horizon- and hierarchy-specific scoring","Quantile competition results do not qualify every distributional forecast."),
 s("monash.archive","Monash Time Series Forecasting Archive","Godahewa et al.","https://doi.org/10.48550/arXiv.2105.06643","dataset frequency, horizon, missingness, domain and series characteristics must remain explicit","Archive coverage is not target-population representativeness."),
 s("wmo.hydro.verify","Guidelines on the Verification of Hydrological Forecasts","World Meteorological Organization","https://wmo.int/media/news/wmo-issues-guidelines-verification-of-hydrological-forecasts","accuracy, bias, reliability, resolution, sharpness and usefulness are distinct verification dimensions","Hydrological guidance does not define general enterprise approval policy."),
 s("wmo.impact","Guidelines on Multi-hazard Impact-based Forecast and Warning Services","World Meteorological Organization","https://etrp.wmo.int/pluginfile.php/16270/mod_resource/content/0/wmo_1150_en.pdf","forecast, impact interpretation, warning, communication and response are distinct stages","A forecast product is not a warning or authorized response."),
 s("wmo.grib2","GRIB2 Documentation","WMO / NOAA NCEP","https://www.nco.ncep.noaa.gov/pmb/docs/grib2/grib2_doc/","reference time, forecast time, parameter, level, grid, process and table edition are explicit carrier semantics","GRIB encoding does not define business target or forecast approval."),
 s("fildes.adjustment","Effective Forecasting and Judgmental Adjustments","Fildes, Goodwin, Lawrence and Nikolopoulos","https://doi.org/10.1016/j.ijforecast.2008.11.010","human adjustments can help or harm and require scope, reason and empirical evaluation","Human judgment is not inherently superior or authorized."),
 s("davydenko.adjustment","Measuring Forecasting Accuracy: Judgmental Adjustments","Davydenko and Fildes","https://doi.org/10.1016/j.ijforecast.2012.09.002","base-relative adjustment value depends on suitable accuracy and bias measures","A positive aggregate score does not justify every override."),
 s("fildes.goodwin","Against Your Better Judgment?","Fildes and Goodwin","https://doi.org/10.1287/inte.1070.0309","written reasons, limited intervention and track-record evaluation improve adjustment governance","Organizational recommendations do not issue authority."),
 s("fva.2025","Forecast Value Added in Demand Planning","Fildes, Goodwin and De Baets","https://doi.org/10.1016/j.ijforecast.2024.07.006","forecast value added evaluates successive process interventions against declared baselines","FVA is not causal proof or a universal objective."),
 s("principles","Principles of Forecasting","International Institute of Forecasters","https://forecastingprinciples.com/","forecast methods, judgment, evaluation and organizational processes require explicit choices","A principles repository is not a conformance-qualified implementation."),
 s("w3c.prov","PROV-O","W3C","https://www.w3.org/TR/prov-o/","entity, activity, agent, plan, derivation, revision and invalidation are distinct","Provenance does not prove forecast quality or authority."),
 s("w3c.prov.constraints","PROV Constraints","W3C","https://www.w3.org/TR/prov-constraints/","generation, use, invalidation and derivation obey identity and ordering constraints","PROV ordering does not supply forecast lifecycle policy."),
 s("w3c.dcat3","Data Catalog Vocabulary v3","W3C","https://www.w3.org/TR/vocab-dcat-3/","dataset series, versions, distributions and catalog records retain separate identities","DCAT is not a forecast-definition or recall state machine."),
 s("datacite.versioning","Versioning","DataCite","https://support.datacite.org/docs/versioning","major versions receive separate identifiers and directional previous/new-version relations","DOI practice does not decide forecast revision materiality."),
 s("oasis.cap","Common Alerting Protocol 1.2","OASIS","https://docs.oasis-open.org/emergency/cap/v1.2/CAP-v1.2.html","initial, update, cancel, acknowledgement and error messages retain identifiers and references","CAP alert semantics do not turn every forecast into a warning."),
 s("cloudevents","CloudEvents 1.0","CNCF","https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md","event identity, source, type, subject, time and data schema form an interoperable envelope","Envelope delivery does not define forecast meaning or consumer acknowledgement."),
 s("activitystreams","Activity Streams 2.0","W3C","https://www.w3.org/TR/activitystreams-vocabulary/","create, update, delete, accept, reject and announce remain typed activities","An activity vocabulary is not a total forecast lifecycle."),
 s("humantask","WS-HumanTask 1.1","OASIS","https://docs.oasis-open.org/bpel4people/ws-humantask-1.1-spec-cs-01.html","potential owner, actual owner, claim, completion, delegation, deadline and escalation are distinct","Human-task completion is not forecast approval."),
 s("dmn","Decision Model and Notation 1.5","Object Management Group","https://www.omg.org/spec/DMN/1.5/About-DMN","decision tables and hit policies make precedence and overlap explicit","DMN evaluation does not issue selection or override authority."),
 s("iso8601","ISO 8601-1:2019 Date and Time","ISO","https://www.iso.org/standard/70907.html","date/time representations require explicit calendar and offset semantics","A timestamp does not define availability, origin or horizon."),
 s("rfc3339","Date and Time on the Internet","IETF","https://www.rfc-editor.org/rfc/rfc3339","Internet timestamp syntax preserves offset and ordering representation","RFC 3339 does not define forecast time roles."),
 s("crossmark","Crossmark","Crossref","https://www.crossref.org/documentation/crossmark/","corrections, retractions and updates are linked visible status changes","Metadata publication does not prove every consumer updated."),
]

NAMES=["selection_profile","selection_appraisal","forecast_definition","forecast_edition","override_policy","override_lifecycle","override_value","publication_profile"]
Q={
 "selection_profile":"Which candidate, baseline, evaluation, metric, robustness, admissibility and decision-evidence rules govern one forecast-selection study?",
 "selection_appraisal":"Given one accepted profile and immutable evaluation evidence, which candidates remain admissible and what bounded selection recommendation follows?",
 "forecast_definition":"What immutable target, unit, temporal, information, output, hierarchy, purpose and authority contract defines a forecast series?",
 "forecast_edition":"How do definition editions, runs, artifacts, approvals, revisions, expiries and supersession transition without rewriting vintages?",
 "override_policy":"Which actors, scopes, reasons, evidence, bounds, conflicts, expiries and maker-checker rules permit forecast override proposals?",
 "override_lifecycle":"How are override proposal, review, approval, application, rejection, withdrawal, expiry and supersession reduced while preserving the base?",
 "override_value":"Against which exact base, outcome vintage, horizons, slices and measures did an applied override add or destroy forecast value?",
 "publication_profile":"Which forecast identity, vintage, uncertainty, audience, purpose, disclosure, expiry, subscription, revision and recall bindings permit generic publication protocols?",
}
OUT={
 "selection_profile":["candidate execution","provider qualification","selection approval","forecast fitting"],"selection_appraisal":["authority judgment","method execution","publication","business choice"],"forecast_definition":["observed data truth","estimator implementation","forecast run","planning"],"forecast_edition":["artifact storage","method execution","publication transport","business action"],"override_policy":["person identity","authority issuance","proposal approval","forecast mutation"],"override_lifecycle":["authority issuance","base-forecast deletion","external write","business decision"],"override_value":["causal attribution","worker performance judgment","selection approval","future override authority"],"publication_profile":["generic publication execution","transport delivery","consumer acceptance","warning/action authority"]}
CONTEXTS=[{"context_id":f"context.forecast.{n}","name":n.replace('_',' ').title(),"sovereign_question":Q[n],"inside":[x.replace('_',' ') for x in n.split()]+["identity","edition","authority evidence","time cut","policy","typed refusal","canonical digest"],"outside":OUT[n],"owner":f"authority.forecast.{n}","status":"specified_candidate"} for n in NAMES]
DEC={
 "selection_profile":["profile_identity","profile_edition","forecast_definition_ref","candidate_population","candidate_admission","provider_qualification_floor","baseline_set","naive_baseline_policy","evaluation_design_ref","origin_and_horizon_cut","outcome_vintage","metric_set","proper_score_requirement","metric_orientation","metric_scaling","metric_precedence","aggregation_weights","evaluation_slices","minimum_slice_support","robustness_rule","uncertainty_of_comparison","multiple_comparisons","complexity_cost","operational_constraints","selection_options","abstention_rule","approval_handoff","profile_digest"],
 "selection_appraisal":["appraisal_identity","profile_ref","evaluation_evidence_cut","candidate_execution_identity","baseline_execution_identity","evidence_completeness","metric_applicability","slice_coverage","leakage_status","comparison_method","uncertainty_status","robustness_status","rank_instability","baseline_skill","operational_feasibility","resource_cost","failure_history","provider_scope","candidate_exclusions","selection_frontier","recommendation_kind","abstention_reason","defeaters","residual","appraisal_digest"],
 "forecast_definition":["definition_identity","definition_edition","target_semantic_ref","population_and_unit","grain","quantity_and_unit","calendar","frequency","observation_identity","revision_and_vintage","availability_time","outcome_finality","origin_policy","horizon_set","information_cut","covariate_availability","missingness","censoring","output_form","quantile_or_interval_levels","hierarchy_ref","purpose","consumer_contract","sensitivity_and_disclosure","definition_digest"],
 "forecast_edition":["edition_identity","definition_ref","run_identity","method_binding_ref","fit_artifact_ref","forecast_artifact_ref","information_cut_ref","origin","horizons","generation_time","approval_state","state_machine","artifact_admission","cut_alignment","revision_reason","revision_materiality","supersession_relation","effective_time","expiry","outcome_join_state","evaluation_refs","concurrency","idempotency","edition_digest"],
 "override_policy":["policy_identity","policy_edition","forecast_definition_ref","eligible_actor_roles","competence_evidence","authority_scope","maker_checker","segregation","eligible_forecast_states","eligible_horizons","eligible_targets","reason_taxonomy","evidence_requirement","magnitude_bound","direction_bound","shape_and_coherence","uncertainty_adjustment","conflict_precedence","combination_rule","expiry","withdrawal","emergency_posture","disclosure","ex_post_evaluation","policy_digest"],
 "override_lifecycle":["override_identity","proposal_edition","base_forecast_ref","proposer_identity","proposal_time","scope","delta_or_replacement","reason","evidence_refs","reviewer_identity","authority_evidence","state_machine","decision","decision_reason","application_order","conflict_set","combination_result","applied_forecast_ref","expiry","withdrawal","supersession","concurrency","idempotency","lifecycle_digest"],
 "override_value":["evaluation_identity","override_ref","base_forecast_ref","applied_forecast_ref","outcome_vintage","origin_horizon_join","eligible_case_cut","metric_set","metric_applicability","base_score","override_score","value_added","bias_change","calibration_change","slice_results","directional_asymmetry","small_adjustment_effect","uncertainty","multiple_comparisons","selection_effect","causal_status","residual","evaluation_digest"],
 "publication_profile":["profile_identity","profile_edition","forecast_definition_ref","eligible_edition_states","required_selection_evidence","required_override_evidence","approval_authority","publication_authority","audience","purpose","visibility","disclosure","origin_horizon_fields","information_cut_fields","uncertainty_fields","vintage_fields","limitations","effective_time","expiry","subscription_population","delivery_semantics","acknowledgement_semantics","revision_classification","supersession_policy","recall_authority","recall_scope","in_flight_disposition","profile_digest"],
}
CTX={n:f"context.forecast.{n}" for n in NAMES}; DECISION_ROWS=[{"decision_id":f"decision.fgl.{n}.{d}","owner_context":CTX[n],"question":f"What exact {d.replace('_',' ')} applies?","default":None,"default_law":"forbidden","binding_phase":"intent_or_compile_time","status":"declared"} for n in NAMES for d in DEC[n]]
OPSPEC={
 "selection_profile":["validate_declaration","compile_candidate_and_baseline_contract","compile_evaluation_and_metric_contract","compile_robustness_and_cost_contract","compile_decision_handoff","seal_profile","semantic_diff"],
 "selection_appraisal":["validate_evidence_cut","evaluate_candidate_admissibility","compare_candidates_to_baselines","evaluate_slice_robustness","construct_selection_frontier","appraise_selection","explain_appraisal"],
 "forecast_definition":["validate_declaration","compile_target_and_temporal_contract","compile_information_contract","compile_output_and_hierarchy_contract","compile_purpose_and_disclosure_contract","seal_definition","semantic_diff"],
 "forecast_edition":["validate_command","reduce_command","admit_forecast_artifact","open_run_edition","approve_or_reject_edition","supersede_edition","evaluate_expiry","reconcile_outcome_join"],
 "override_policy":["validate_declaration","compile_actor_and_authority_rules","compile_scope_and_bound_rules","compile_conflict_and_combination_rules","compile_expiry_and_evaluation_rules","seal_policy","semantic_diff"],
 "override_lifecycle":["validate_proposal","validate_reviewer_authority","reduce_command","resolve_conflicts","apply_authorized_override","withdraw_or_expire_override","supersede_override","explain_transition"],
 "override_value":["validate_evaluation_cut","join_base_override_and_outcomes","evaluate_metric_applicability","compute_forecast_value_added","evaluate_slices_and_bias","classify_value_evidence","seal_evaluation"],
 "publication_profile":["validate_declaration","compile_edition_admission","compile_audience_and_disclosure","compile_subscription_and_acknowledgement","compile_revision_and_recall","seal_profile","map_to_generic_publication_contracts","semantic_diff"],
}
def op(n,x): return {"operation_ref":f"operation.fgl.{n}.{x}","input_types":[n.title().replace('_','')+"Input",n.title().replace('_','')+"Policy"],"output_type":f"Result<{x.title().replace('_','')},ForecastGovernanceRefusal>","purity":"pure"}
OPS={n:[op(n,x) for x in OPSPEC[n]] for n in NAMES}
DEPS={"selection_profile":["library.method_kernels.forecast_evaluation"],"selection_appraisal":["library.forecast.selection.profile.compiler","library.review.adjudication.reducer"],"forecast_definition":["library.method_kernels.time_series_semantics"],"forecast_edition":["library.forecast.definition.compiler","library.method_kernels.forecast_estimators","library.method_kernels.forecast_reconciliation"],"override_policy":["library.forecast.definition.compiler"],"override_lifecycle":["library.forecast.override.policy.compiler","library.forecast.edition.lifecycle","library.review.adjudication.reducer"],"override_value":["library.forecast.override.lifecycle","library.method_kernels.forecast_evaluation"],"publication_profile":["library.forecast.edition.lifecycle","library.forecast.override.value.evaluator","library.data_product_publication.product_edition","library.data_product_publication.publication_protocol","library.data_product_publication.consumer_change","library.data_product_publication.recall_exit"]}
LIBID={"selection_profile":"library.forecast.selection.profile.compiler","selection_appraisal":"library.forecast.selection.appraiser","forecast_definition":"library.forecast.definition.compiler","forecast_edition":"library.forecast.edition.lifecycle","override_policy":"library.forecast.override.policy.compiler","override_lifecycle":"library.forecast.override.lifecycle","override_value":"library.forecast.override.value.evaluator","publication_profile":"library.forecast.publication.profile.compiler"}
LAW={
 "selection_profile":["Candidate admission, baseline choice, evaluation design, metrics, slices, robustness and cost are prospective decisions.","Best historical score is not universal future superiority or selection authority."],
 "selection_appraisal":["Score, rank, admissibility, recommendation, authorized selection and production activation are distinct.","Appraisal may abstain when evidence is incomplete, unstable or non-comparable."],
 "forecast_definition":["Target, observation, actual, forecast, plan, decision and outcome are distinct.","Event, availability, recording, revision, origin, horizon, generation, publication and expiry times are non-interchangeable."],
 "forecast_edition":["Definition, edition, fit/run occurrence, forecast artifact and publication occurrence have separate identities.","A new information cut, material revision or artifact change creates a new edition and preserves predecessors."],
 "override_policy":["Human or generated judgment obeys identical scope, authority, evidence, conflict and evaluation laws.","Override policy cannot issue identity, competence, approval or publication authority."],
 "override_lifecycle":["Base, proposed, approved, applied, withdrawn, expired and superseded forecasts remain separately addressable.","Proposal, review, approval, application and value evidence are distinct occurrences."],
 "override_value":["Forecast value added is baseline-, metric-, population-, horizon- and outcome-vintage-specific evidence.","Ex-post improvement is not causal proof, worker appraisal or perpetual override authority."],
 "publication_profile":["Forecast-specific admission metadata composes generic publication, consumer-change and recall protocols rather than duplicating them.","Approval, publication intent, delivery, acknowledgement, consumption, warning, decision and action are distinct."],
}
REF={n:[x.replace(' ','').title()+"Missing" for x in ["identity","edition","authority","time cut","policy","evidence","scope","digest"]] for n in NAMES}
LIBRARIES=[]
for n in NAMES:
 LIBRARIES.append({"library_id":LIBID[n],"owner_context":CTX[n],"name":n.replace('_',' ').title(),"library_kind":"policy_compiler_pure" if n.endswith("profile") or n in {"forecast_definition","override_policy","publication_profile"} else "state_or_policy_evaluator_pure","purpose":Q[n],"public_types":[n.title().replace('_','')+x for x in ("Id","Edition","Policy","Evidence","Result","Refusal")],"operation_refs":[x["operation_ref"] for x in OPS[n]],"decision_refs":[f"decision.fgl.{n}.{d}" for d in DEC[n]],"laws":LAW[n]+["Every material choice is explicit; no provider, environment, model, LLM or agent supplies a semantic default.","A model, LLM or agent may propose or explain only; it cannot waive refusals, approve selection or override, seal editions, publish, recall, acknowledge consumption or authorize action."],"refusals":REF[n],"dependencies":DEPS[n],"effect_boundary":"pure_effect_intents" if n in {"forecast_edition","override_lifecycle","publication_profile"} else "pure_no_io","explicitly_not_owned":OUT[n],"conformance_oracles":[f"{n.replace('_',' ')} decision tables",f"{n.replace('_',' ')} negative twins","canonical digest and replay properties","two independent implementation differential tests"],"qualification_required":False,"qualified_implementation_count":0,"status":"specified","evidence_refs":[x["source_id"] for x in SOURCES]})

METHODS={"value":["method.business.jtbd","method.business.capability_map"],"semantic":["method.domain.ddd","method.domain.terminology"],"behavior":["method.domain.eventstorming","method.work.statecharts"],"authority":["method.trust.threat_model","method.systems.stpa"],"consistency":["method.formal.design_by_contract","method.formal.alloy"],"variability":["method.variability.foda","method.variability.decision_model"],"software":["method.architecture.coupling","method.architecture.hexagonal"],"operation":["method.operations.resilience","method.operations.sre"],"economics":["method.operations.finops","method.business.product_split_merge"],"empirical":["method.evidence.systematic_review","method.evidence.red_team"],"analytical":["method.formal.property_testing","method.analytics.forecast_verification"],"system":["method.systems.stpa","method.trust.fmea_fta"]}
FIND={"value":"Selection, versioning, override and publication recur across demand, finance, capacity, risk, weather and health forecasting.","semantic":"Observation, forecast, adjustment, approved edition, publication, warning, plan and action have different truth status.","behavior":"Profiles compile, appraisals evaluate evidence, and lifecycle contracts reduce total transitions.","authority":"Candidate appraisal, selection approval, override, publication, warning and action require different issuers.","consistency":"Information cuts, vintages, immutable editions, supersession and acknowledgement need separate consistency rules.","variability":"Baselines, metrics, slices, methods, override bounds, audiences, expiry and recall vary independently.","software":"Evaluation, lifecycle, override and generic publication mechanics have different dependencies and replacement rates.","operation":"Late actuals, revisions, partial delivery, stale subscriptions and concurrency require explicit unknown states.","economics":"Accuracy, calibration, service cost, adjustment effort, inventory cost and decision utility are different quantities.","empirical":"Forecasting research, WMO operations and version/publication standards expose complementary seams.","analytical":"Proper scores, error measures, comparisons and FVA have exact applicability contracts.","system":"Leakage, rank instability, stale vintages, unjustified overrides and unpropagated recall are hazards."}
LENSES=[{"lens_id":f"lens.fgl.{k}","lens":k,"question":"What does this lens require of forecast governance seams?","finding":v,"boundary_consequence":"Preserve eight forecast-specific contracts and import generic adjudication/publication mechanics.","method_refs":METHODS[k],"status":"applied"} for k,v in FIND.items()]
VERDICTS=[{"verdict_id":"verdict.fgl.selection","subject_refs":[LIBID["selection_profile"],LIBID["selection_appraisal"],"library.review.adjudication.reducer"],"disposition":"profile_appraisal_and_authority_judgment_are_distinct","rationale":"Metric comparison cannot acquire selection authority.","status":"candidate_boundary_adjudicated_not_ratified"},{"verdict_id":"verdict.fgl.definition-edition","subject_refs":[LIBID["forecast_definition"],LIBID["forecast_edition"]],"disposition":"immutable_definition_separate_from_occurrence_lifecycle","rationale":"Definition semantics and run/artifact transitions change for different reasons.","status":"candidate_boundary_adjudicated_not_ratified"},{"verdict_id":"verdict.fgl.override-three","subject_refs":[LIBID["override_policy"],LIBID["override_lifecycle"],LIBID["override_value"]],"disposition":"policy_occurrence_and_ex_post_evidence_are_distinct","rationale":"An authorized application and later FVA evaluation have different time and truth.","status":"candidate_boundary_adjudicated_not_ratified"},{"verdict_id":"verdict.fgl.publication-import","subject_refs":[LIBID["publication_profile"],"library.data_product_publication.publication_protocol","library.data_product_publication.consumer_change","library.data_product_publication.recall_exit"],"disposition":"forecast_profile_composes_generic_publication","rationale":"Forecast metadata is domain-specific; publication effects, consumer change and recall mechanics are reusable.","status":"candidate_boundary_adjudicated_not_ratified"}]
NEG=[
 ("best_score","The smallest historical error automatically wins.","Apply the prospective multi-dimensional selection profile."),("leaderboard","A competition winner is universally superior.","Re-evaluate on the exact target population and purpose."),("baseline_none","A sophisticated candidate needs no naive baseline.","Require declared baseline evidence."),("metric_universal","One error metric is universally meaningful.","Bind scale, output form, horizon and decision use."),("rank_stable","A point ranking proves robust superiority.","Retain uncertainty, slices and rank instability."),("slice_hide","Aggregate accuracy may hide harmful slices.","Evaluate declared slices and support."),("cost_ignore","Accuracy dominates latency and operating cost.","Apply the declared objective and constraints."),("appraise_approve","An appraisal recommendation approves selection.","Require external authority judgment."),("agent_select","An agent may select the plausible best model.","Emit an attributed proposal only."),
 ("target_observation","Target definition and observed value are the same identity.","Reference external target meaning and separate occurrences."),("actual_final","The latest actual is final.","Bind revision and finality policy."),("timestamp_role","One timestamp covers origin, availability and publication.","Bind every time role explicitly."),("definition_run","A forecast definition is a forecast run.","Create separate edition and occurrence identities."),("run_artifact","Successful run proves an admitted artifact.","Validate artifact shape, cut and digest."),("latest_cut","A run may silently use the latest data.","Bind an immutable information cut."),("edit_published","A published forecast may be edited in place.","Create a linked successor edition."),("version_number","A larger version number proves supersession.","Require explicit directional relation."),("expiry_delete","Expiry deletes historical forecasts.","Transition status and preserve evidence."),
 ("human_better","A human adjustment is inherently better.","Evaluate it against the preserved base."),("machine_better","An algorithmic base may never be overridden.","Apply the accepted override policy and evidence."),("proposal_approval","An override proposal is approved.","Require an attributable judgment occurrence."),("manager_authority","Management role implies override authority.","Validate exact current authority scope."),("maker_checker_same","The proposer may approve by default.","Apply declared segregation rules."),("reason_free","A small adjustment needs no reason.","Apply policy to every proposal."),("replace_base","Applying an override overwrites the base.","Preserve base, proposal, decision and applied edition."),("combine_order","Conflicting overrides may be applied in arrival order.","Use explicit precedence or refuse."),("expired_apply","An expired override remains applicable.","Refuse or open a new proposal."),("agent_override","An agent may approve its generated override.","Keep generation and authority separate."),
 ("fva_causal","Positive FVA proves the override caused improvement.","Report comparative evidence and causal status separately."),("fva_global","Positive aggregate FVA proves value on every horizon.","Retain slice and horizon evidence."),("outcome_latest","Override evaluation may use revised actuals silently.","Bind exact outcome vintage."),("metric_switch","FVA may choose a favorable metric after outcomes.","Use the prospective evaluation contract."),("one_win","One successful override grants future authority.","Keep authority external and editioned."),("worker_score","Override value is automatically employee performance.","Require separate employment/assessment authority."),
 ("approve_publish","Approval is successful publication.","Emit intent and reconcile exact receipts."),("publish_consume","Publication proves consumption.","Track delivery and acknowledgement separately."),("delivery_ack","Transport delivery proves understanding or safe use.","Retain consumer acknowledgement semantics."),("forecast_warning","A forecast is automatically a warning.","Require a separate warning product and authority."),("warning_action","A warning authorizes action.","Hand off to external decision/effect authority."),("recall_delete","Recall deletes the forecast.","Preserve edition and linked recall evidence."),("recall_complete","Issuing recall proves all consumers updated.","Track population, propagation and acknowledgements."),("supersede_recall","Supersession and recall are interchangeable.","Apply distinct lifecycle transitions."),("generic_omit","Generic publication metadata is enough for forecasts.","Bind origin, horizons, cut, vintage and uncertainty profile."),("profile_duplicate","Forecast code should reimplement generic publication/recall.","Compose shared data-product protocols."),("one_impl","One implementation proves portability.","Require two independent qualified implementations."),
]
NEGATIVES=[{"negative_id":f"negative.fgl.{k}","unsafe_inference":u,"required_behavior":b,"status":"active"} for k,u,b in NEG]
COMPILER=[]
for l in LIBRARIES:
 stem=l["library_id"].removeprefix("library."); req=f"requirement.{stem}.implementation"; offer=f"offer.{stem}.reference"
 COMPILER += [{"record_kind":"capability_requirement","requirement_id":req,"subject_ref":l["library_id"],"required_operations":l["operation_refs"],"required_decisions":l["decision_refs"],"fallback_law":"refuse","status":"declared"},{"record_kind":"capability_offer","offer_id":offer,"subject_ref":l["library_id"],"claimed_operations":l["operation_refs"],"qualified_implementation_count":0,"portable":False,"selectable":False,"status":"specified_unimplemented"},{"record_kind":"binding_rule","binding_rule_id":f"binding.{stem}","requirement_ref":req,"offer_ref":offer,"structural_match":True,"selectable":False,"selection_law":"Structural match never promotes an unqualified or non-portable implementation.","status":"declared"}]
PROFILES=[{"record_kind":"qualification_profile","receipt_id":f"profile.{l['library_id'].removeprefix('library.')}","subject_ref":l["library_id"],"edition":1,"claim":f"An exact implementation conforms to {l['name']} laws and refusals.","scope":["exact provider version","exact build and target","exact configuration","exact operation set"],"fixtures":l["conformance_oracles"],"oracles":l["conformance_oracles"],"configuration":{},"environment":{},"results":[],"limitations":["Unexecuted profile; proves no capability.","Passing proves only exact scoped conformance."],"invalidation_triggers":["provider/dependency change","target/configuration change","oracle edition change"],"validity":{"from":None,"until":None},"status":"template_not_executed"} for l in LIBRARIES]
GAP_CLASSES={"coverage":(["subject_grain","behavior"],["reviewed domain inventory","negative-case saturation evidence"]),"authority":(["authority_effect_safety"],["named ratifier decision","authority provenance"]),"evidence":(["information_uncertainty","proof"],["claim-to-primary-source appraisal","conflict adjudication"]),"implementation":(["representation_evolution","resources"],["independent implementation receipt","executable law results"]),"qualification":(["proof","behavior_resources"],["two independent conformance receipts","portability and replay evidence"])}
GAPS=[{"gap_id":f"gap.fgl.{kind}.v1","gap_class":kind,"semantic_axes":axes,"scope_refs":[x["library_id"] for x in LIBRARIES],"closure_evidence":evidence,"blocked_outputs":["canonical source authority","selectable compiler offer","completion claim"],"status":"OPEN"} for kind,(axes,evidence) in GAP_CLASSES.items()]
CONTROL_SCHEMA={"$schema":"https://json-schema.org/draft/2020-12/schema","$id":"https://san.example/spec/corpus-control-v1.schema.json","type":"object","additionalProperties":False,"required":["gap_id","gap_class","semantic_axes","scope_refs","closure_evidence","blocked_outputs","status"],"properties":{"gap_id":{"type":"string","minLength":1},"gap_class":{"enum":sorted(GAP_CLASSES)},"semantic_axes":{"type":"array","minItems":1,"items":{"type":"string"}},"scope_refs":{"type":"array","minItems":1,"items":{"type":"string"}},"closure_evidence":{"type":"array","minItems":1,"items":{"type":"string"}},"blocked_outputs":{"type":"array","minItems":1,"items":{"type":"string"}},"status":{"const":"OPEN"}}}
FILES={"sources.jsonl":SOURCES,"bounded-contexts.jsonl":CONTEXTS,"decision-points.jsonl":DECISION_ROWS,"boundary-lens-adjudication.jsonl":LENSES,"boundary-verdicts.jsonl":VERDICTS,"library-contracts.jsonl":LIBRARIES,"compiler-contracts.jsonl":COMPILER,"qualification-profiles.jsonl":PROFILES,"negative-twins.jsonl":NEGATIVES,"gaps.jsonl":GAPS}
def render(xs): return "\n".join(json.dumps(x,sort_keys=True,separators=(",",":"),ensure_ascii=False) for x in xs)+"\n"
def main():
 ROOT.mkdir(parents=True,exist_ok=True); files={}
 for n,xs in FILES.items():
  p=render(xs); (ROOT/n).write_text(p); files[n]={"records":len(xs),"sha256":hashlib.sha256(p.encode()).hexdigest()}
 schema_payload=json.dumps(CONTROL_SCHEMA,indent=2,sort_keys=True)+"\n"; (ROOT/"corpus-control.schema.json").write_text(schema_payload); files["corpus-control.schema.json"]={"sha256":hashlib.sha256(schema_payload.encode()).hexdigest()}
 (ROOT/"manifest.json").write_text(json.dumps({"manifest_id":"forecast_governance_lifecycle_v0_1_0","as_of":AS_OF,"edition":1,"status":"specified_unimplemented_open_world","files":files,"completion_claim":False,"qualified_implementation_count":0},indent=2,sort_keys=True)+"\n")
 print(f"BUILD PASS fgl: {len(SOURCES)} sources, {len(CONTEXTS)} contexts, {len(DECISION_ROWS)} decisions, {len(LIBRARIES)} libraries, {sum(map(len,OPS.values()))} operations, {len(LENSES)} lenses, {len(NEGATIVES)} negative twins")
if __name__=="__main__": main()
