#!/usr/bin/env python3
"""Build addressable-content selector and bounded document-rendition contracts."""
from __future__ import annotations
import hashlib, json
from pathlib import Path
ROOT = Path(__file__).resolve().parent
AS_OF = "2026-08-26"
def render(rows): return "\n".join(json.dumps(r, sort_keys=True, separators=(",", ":"), ensure_ascii=False) for r in rows) + "\n"
def s(k,t,a,u,p,n): return {"source_id":f"source.acr.{k}","title":t,"authority":a,"url":u,"retrieved":AS_OF,"source_kind":"primary_or_official","supports":p,"does_not_prove":n}
SOURCES = [
 s("annotation.model","Web Annotation Data Model","W3C","https://www.w3.org/TR/annotation-model/","targets, specific resources, selectors, states, refinement, rendering software and source identity are distinct","A selector does not guarantee that a changing target remains resolvable."),
 s("annotation.protocol","Web Annotation Protocol","W3C","https://www.w3.org/TR/annotation-protocol/","annotation containers/pages and HTTP representations have explicit protocol identities","Protocol retrieval does not establish selector semantics or access authority."),
 s("annotation.vocab","Web Annotation Vocabulary","W3C","https://www.w3.org/TR/annotation-vocab/","selector, state, purpose and lifecycle terms have published identifiers","Vocabulary use does not prove semantic conformance."),
 s("media.fragments","Media Fragments URI 1.0","W3C","https://www.w3.org/TR/media-frags/","temporal, spatial, track and named media fragments require media-specific dimensions and units","A fragment URI does not prove byte- or frame-stable identity."),
 s("rfc5147","URI Fragment Identifiers for text/plain","IETF","https://www.rfc-editor.org/rfc/rfc5147","character/line ranges require exact encoding, counting and integrity considerations","Text positions are brittle under normalization or revision."),
 s("rfc3986","Uniform Resource Identifier Generic Syntax","IETF","https://www.rfc-editor.org/rfc/rfc3986","resource identity, representation and fragment processing are distinct URI concerns","URI equality does not establish content occurrence equality."),
 s("jsonpointer","JSON Pointer","IETF","https://www.rfc-editor.org/rfc/rfc6901","representation-scoped path tokens address a value in one JSON document","A pointer is not durable domain identity and may fail after edits."),
 s("xpath31","XML Path Language XPath 3.1","W3C","https://www.w3.org/TR/xpath-31/","node selection binds an expression, static/dynamic context and XDM edition","XPath syntax alone does not resolve against arbitrary content."),
 s("selectors4","Selectors Level 4","W3C","https://www.w3.org/TR/selectors-4/","tree-element matching has editioned selector syntax and scoping","CSS selectors do not identify text spans, pixels or business entities."),
 s("svg2","Scalable Vector Graphics 2","W3C","https://www.w3.org/TR/SVG2/","SVG geometry, coordinate systems, transforms and rendering order are explicit","An SVG path without viewport/transform state is not a resolved target."),
 s("iiif.image","IIIF Image API 3.0","IIIF Consortium","https://iiif.io/api/image/3.0/","region, size, rotation, quality, format and pixel dimensions are explicit image request semantics","An image request does not prove annotation target identity or authorization."),
 s("iiif.presentation","IIIF Presentation API 3.0","IIIF Consortium","https://iiif.io/api/presentation/3.0/","canvas, annotation page, content resource and spatial/temporal targeting have separate identities","A canvas is a presentation abstraction, not source truth."),
 s("webvtt","WebVTT","W3C","https://www.w3.org/TR/webvtt1/","timed cues bind time ranges, text and rendering settings","Cue timing is not universal media-frame identity."),
 s("pdf2","ISO 32000-2:2020 PDF 2.0","ISO","https://www.iso.org/standard/75839.html","PDF files, readers, writers, interactive processors, pages, fonts and rendering behaviors are distinct","Format conformance does not guarantee identical pixels across processors."),
 s("rfc8118","The application/pdf Media Type","IETF","https://www.rfc-editor.org/rfc/rfc8118","PDF may contain scripts, multimedia, attachments, links, forms and external references with security implications","A PDF media type does not make active content safe."),
 s("pdf.grammar","Arlington PDF Model","PDF Association","https://github.com/pdf-association/arlington-pdf-model","machine-readable PDF object grammar constrains editions and feature predicates","Grammar validation does not prove visual fidelity or safe rendering."),
 s("pdfa","ISO 19005 PDF/A overview","PDF Association","https://pdfa.org/resource/iso-19005-pdfa/","archival profiles constrain external dependencies, fonts, color and active content","PDF/A conformance is not a universal rendition profile."),
 s("css.page","CSS Paged Media Module Level 3","W3C","https://www.w3.org/TR/css-page-3/","page boxes, size, orientation, margins, counters and renderer conformance are explicit","The working draft does not prove cross-renderer pixel equivalence."),
 s("css.break","CSS Fragmentation Module Level 3","W3C","https://www.w3.org/TR/css-break-3/","fragmentation, breaks, widows, orphans and overflow affect pagination","A page count is not stable without the complete style/font/layout closure."),
 s("html","HTML Living Standard","WHATWG","https://html.spec.whatwg.org/multipage/rendering.html","rendering depends on user-agent rules, replaced elements, embedded content, scripting and environment","HTML bytes alone do not determine one rendition."),
 s("opentype","OpenType specification","Microsoft Typography","https://learn.microsoft.com/en-us/typography/opentype/spec/","font tables, glyphs, variation axes, layout and shaping features affect text geometry","A font family name does not identify exact font bytes or shaping behavior."),
 s("woff2","WOFF File Format 2.0","W3C","https://www.w3.org/TR/WOFF2/","web-font representation and decompression have exact format and resource concerns","WOFF2 validity does not establish licensing or rendering fitness."),
 s("unicode.bidi","Unicode Bidirectional Algorithm UAX #9","Unicode Consortium","https://www.unicode.org/reports/tr9/","text display order depends on an editioned bidi algorithm and directional properties","Logical character order does not alone determine visual positions."),
 s("unicode.linebreak","Unicode Line Breaking Algorithm UAX #14","Unicode Consortium","https://www.unicode.org/reports/tr14/","line-break opportunities depend on Unicode properties, tailoring and edition","Default line breaking is not locale- or product-universal."),
 s("unicode.normalization","Unicode Normalization Forms UAX #15","Unicode Consortium","https://www.unicode.org/reports/tr15/","canonically equivalent text may have different code-unit positions","Normalization must not silently invalidate or relocate selectors."),
 s("icc","ICC.1:2022 Image technology colour management","International Color Consortium","https://www.color.org/specification/ICC.1-2022-05.pdf","device/source/destination profiles and rendering intents influence color reproduction","A color-profile name does not prove exact perceptual equivalence."),
 s("csp3","Content Security Policy Level 3","W3C","https://www.w3.org/TR/CSP3/","resource loading and script execution can be constrained by explicit policy","CSP is not a complete untrusted-document sandbox."),
 s("zip","ZIP File Format specification","PKWARE","https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT","container entries, compression, sizes and encryption require bounded parsing","Declared compressed sizes cannot be trusted as resource budgets."),
]
CONTEXTS = [
 {"context_id":"context.addressable_content.selector","name":"Addressable Content Selector","sovereign_question":"Which typed selector and state, bound to one exact source occurrence and representation, identifies an intended content segment without claiming successful resolution?","inside":["source occurrence/ref","representation/state ref","selector kind/edition","position/quote/path/geometry/time","coordinate and normalization policy","refinement","canonical digest"],"outside":["network retrieval","source identity authority","resolution execution","annotation body","artifact mutation"],"owner":"authority.addressable_content.selector","status":"specified_candidate"},
 {"context_id":"context.addressable_content.resolution","name":"Content Target Resolution","sovereign_question":"Under one exact representation and resolver profile, does a selector resolve to none, one, many, ambiguous, stale or loss-bearing segments with retained evidence?","inside":["resolver profile","representation cut","selector applicability","normalization/coordinates","candidate segments","ambiguity","staleness","residual","resolution receipt"],"outside":["ambient retrieval","annotation correctness","business identity","source mutation","review acceptance"],"owner":"authority.addressable_content.resolution","status":"specified_candidate"},
 {"context_id":"context.document_rendition.profile","name":"Bounded Document Rendition Profile","sovereign_question":"Which exact document, renderer, resources, fonts, layout, locale, color, active-content and finite-budget decisions define one rendition attempt?","inside":["document occurrence","container/profile","renderer contract","font/resource closure","page geometry","DPI","locale/timezone","color profile","active-content policy","budgets","plan digest"],"outside":["resource retrieval","renderer implementation qualification","page execution","OCR/content extraction","business acceptance"],"owner":"authority.document_rendition.profile","status":"specified_candidate"},
 {"context_id":"context.document_rendition.evaluation","name":"Bounded Document Rendition Evaluation","sovereign_question":"What pages, warnings, omissions, substitutions, truncation, residual and evidence result from evaluating one accepted rendition plan through a supplied renderer algebra?","inside":["accepted plan","renderer algebra binding","page sequence","page surfaces","resource use","warnings/errors","substitutions","coverage","truncation","result digest"],"outside":["ambient filesystem/network","renderer qualification","OCR/layout analysis","document truth","output acceptance"],"owner":"authority.document_rendition.evaluation","status":"specified_candidate"},
]
DECISIONS = {
 "selector":["selector_identity","selector_edition","source_occurrence_identity","source_representation_identity","source_state_or_time","media_type_and_profile","selector_kind","selector_syntax_edition","fragment_dimension","text_encoding","unicode_normalization","text_quote_prefix_suffix","text_position_unit","line_and_column_counting","tree_path_context","json_pointer_context","coordinate_reference_frame","origin_axis_orientation","geometry_units","spatial_region","temporal_timebase","temporal_precision","open_closed_bounds","range_endpoints","refinement_order","multiple_selectors","fallback_and_choice","canonicalization","selector_digest"],
 "resolution":["accepted_selector_ref","representation_cut","resolver_profile","media_profile_support","retrieval_prohibition","normalization_pipeline","tree_or_graph_model","text_segmentation","coordinate_transform","time_mapping","quote_match_policy","position_match_policy","path_match_policy","geometry_match_policy","candidate_cardinality","ambiguity_policy","stale_source_policy","revision_mapping","tolerance","information_loss","resource_budget","resolution_digest"],
 "profile":["rendition_plan_identity","document_occurrence_ref","document_digest","container_and_format_profile","decryption_authority_ref","renderer_contract_ref","renderer_edition","target_page_model","page_size_orientation_margins","resolution_and_pixel_format","font_resource_closure","font_substitution_policy","shaping_engine_and_edition","unicode_edition","locale_and_language","timezone_clock","style_resource_closure","image_media_resource_closure","color_profile_and_intent","transparency_blending","active_content_policy","macro_script_form_media_policy","external_link_policy","network_filesystem_policy","embedded_object_policy","archive_decompression_policy","maximum_pages","maximum_dimensions_pixels","memory_cpu_time_budget","cancellation","warning_and_error_policy","partial_result_policy","canonical_plan_digest"],
 "evaluation":["accepted_plan_ref","exact_document_bytes","renderer_algebra_binding","resource_closure_digest","input_validation","page_evaluation_order","parallel_equivalence","font_realization","substitution_recording","active_content_enforcement","resource_use_accounting","page_identity","page_surface_identity","page_coordinate_frame","warning_precedence","error_precedence","partial_page_policy","truncation_policy","cancellation_result","coverage_measure","residual_representation","determinism_check","cross_renderer_equivalence","result_digest"],
}
CTX={"selector":CONTEXTS[0]["context_id"],"resolution":CONTEXTS[1]["context_id"],"profile":CONTEXTS[2]["context_id"],"evaluation":CONTEXTS[3]["context_id"]}
DECISION_ROWS=[{"decision_id":f"decision.acr.{o}.{n}","owner_context":CTX[o],"question":f"What exact {n.replace('_',' ')} applies?","default":None,"default_law":"forbidden","binding_phase":"intent_or_compile_time","status":"declared"} for o,ns in DECISIONS.items() for n in ns]
def op(o,n,i,out): return {"operation_ref":f"operation.acr.{o}.{n}","input_types":i,"output_type":f"Result<{out},AddressableContentRenditionRefusal>","purity":"pure"}
OPS={
 "selector":[op("selector","validate_selector_declaration",["ContentSelectorDeclaration","SelectorPolicy"],"ValidatedSelectorDeclaration"),op("selector","bind_source_occurrence_and_state",["ValidatedSelectorDeclaration","SourceOccurrenceCut","SourceBindingPolicy"],"SourceBoundSelector"),op("selector","typecheck_selector",["SourceBoundSelector","MediaProfileCut","SelectorTypePolicy"],"TypedContentSelector"),op("selector","compile_selector_refinement",["TypedContentSelector","RefinementPolicy"],"RefinedContentSelector"),op("selector","canonicalize_selector",["RefinedContentSelector","SelectorCanonicalizationPolicy"],"AcceptedContentSelector"),op("selector","compare_selectors",["AcceptedContentSelector","AcceptedContentSelector","SelectorEquivalencePolicy"],"SelectorComparison"),op("selector","explain_selector",["AcceptedContentSelector","ExplanationScope","ResourceBudget"],"SelectorExplanation")],
 "resolution":[op("resolution","validate_resolution_request",["AcceptedContentSelector","RepresentationCut","ResolverProfile"],"ValidatedResolutionRequest"),op("resolution","compile_resolution_plan",["ValidatedResolutionRequest","ResolutionPolicy"],"ContentResolutionPlan"),op("resolution","resolve_selector",["ContentResolutionPlan","FiniteRepresentation","ContentResolverAlgebra","ResourceBudget"],"ContentResolutionCandidateSet"),op("resolution","classify_resolution_cardinality",["ContentResolutionCandidateSet","CardinalityPolicy"],"ContentResolutionClassification"),op("resolution","evaluate_resolution_staleness",["ContentResolutionClassification","SourceOccurrenceCut","StalenessPolicy"],"ContentResolutionResult"),op("resolution","compare_resolutions",["ContentResolutionResult","ContentResolutionResult","ResolutionEquivalencePolicy"],"ResolutionComparison"),op("resolution","explain_resolution",["ContentResolutionResult","ExplanationScope","ResourceBudget"],"ResolutionExplanation")],
 "profile":[op("profile","validate_rendition_request",["DocumentRenditionRequest","RenditionProfilePolicy"],"ValidatedRenditionRequest"),op("profile","inspect_document_container_profile",["ValidatedRenditionRequest","DocumentContainerAlgebra","InspectionBudget"],"DocumentContainerProfile"),op("profile","resolve_finite_resource_closure",["ValidatedRenditionRequest","ProvidedResourceCut","ResourceClosurePolicy"],"FiniteRenditionResourceClosure"),op("profile","compile_font_text_layout_profile",["FiniteRenditionResourceClosure","FontLayoutPolicy"],"FontTextLayoutProfile"),op("profile","compile_page_color_profile",["ValidatedRenditionRequest","PageColorPolicy"],"PageColorRenditionProfile"),op("profile","compile_active_content_sandbox",["DocumentContainerProfile","ActiveContentPolicy"],"ActiveContentSandboxContract"),op("profile","compile_rendition_plan",["ValidatedRenditionRequest","DocumentContainerProfile","FiniteRenditionResourceClosure","FontTextLayoutProfile","PageColorRenditionProfile","ActiveContentSandboxContract"],"AcceptedDocumentRenditionPlan"),op("profile","compare_rendition_plans",["AcceptedDocumentRenditionPlan","AcceptedDocumentRenditionPlan"],"RenditionPlanSemanticDiff"),op("profile","explain_rendition_plan",["AcceptedDocumentRenditionPlan","ExplanationScope","ResourceBudget"],"RenditionPlanExplanation")],
 "evaluation":[op("evaluation","validate_rendition_execution",["AcceptedDocumentRenditionPlan","ExactDocumentBytes","DocumentRendererAlgebra"],"ValidatedRenditionExecution"),op("evaluation","evaluate_document_pages",["ValidatedRenditionExecution","RenditionExecutionBudget"],"DocumentPagePartialSet"),op("evaluation","merge_page_partials",["DocumentPagePartialSet","PageMergePolicy"],"OrderedDocumentPageSet"),op("evaluation","classify_render_warnings_errors",["OrderedDocumentPageSet","RendererDiagnosticSet","DiagnosticPolicy"],"RenditionDiagnosticClassification"),op("evaluation","derive_rendition_coverage",["OrderedDocumentPageSet","RenditionDiagnosticClassification","CoveragePolicy"],"RenditionCoverage"),op("evaluation","construct_rendition_result",["OrderedDocumentPageSet","RenditionDiagnosticClassification","RenditionCoverage","ResidualPolicy"],"DocumentRenditionResult"),op("evaluation","compare_rendition_results",["DocumentRenditionResult","DocumentRenditionResult","RenditionEquivalencePolicy"],"RenditionComparison"),op("evaluation","explain_rendition_result",["DocumentRenditionResult","ExplanationScope","ResourceBudget"],"RenditionExplanation")],
}
SHARED=[
 "Source identity, occurrence, representation, state, selector, resolved segment, document bytes, rendition plan, page result and extracted content graph are distinct identities.",
 "Selector syntax validity, media applicability, successful resolution, unique resolution, semantic correctness and review acceptance are distinct states.",
 "Resolution and rendition perform no ambient network or filesystem access; every external byte and capability is supplied through an exact finite closure.",
 "None, one, many, ambiguous, stale, truncated, unsupported, denied, malformed and resource-exhausted remain distinct outcomes.",
 "Rendition success does not prove completeness, visual equivalence, accessibility, document truth, OCR fitness or business acceptance.",
 "Font family names, renderer product names, URLs and current environment never substitute for digest-addressed editions and resources.",
 "Models or agents may propose selectors, resource mappings or diagnostics but cannot invent target identity, fetch ambient resources, waive sandboxing, assert fidelity or accept output.",
]
TYPES={
 "selector":["ContentSelectorId","ContentSelectorEdition","ContentSelectorDeclaration","SourceOccurrenceRef","SourceRepresentationRef","SourceStateRef","SelectorKind","TypedContentSelector","RefinedContentSelector","AcceptedContentSelector","SelectorComparison","SelectorRefusal"],
 "resolution":["RepresentationCut","ResolverProfile","ContentResolutionPlan","FiniteRepresentation","ContentResolverAlgebra","ResolvedContentSegment","ContentResolutionCandidateSet","ContentResolutionClassification","ContentResolutionResult","ResolutionResidual","ResolutionRefusal"],
 "profile":["DocumentRenditionPlanId","DocumentRenditionRequest","DocumentContainerProfile","ProvidedResourceCut","FiniteRenditionResourceClosure","FontTextLayoutProfile","PageColorRenditionProfile","ActiveContentSandboxContract","AcceptedDocumentRenditionPlan","RenditionPlanRefusal"],
 "evaluation":["ExactDocumentBytes","DocumentRendererAlgebra","ValidatedRenditionExecution","DocumentPagePartial","DocumentPageSurface","OrderedDocumentPageSet","RenditionDiagnosticClassification","RenditionCoverage","DocumentRenditionResult","RenditionComparison","RenditionRefusal"],
}
def lib(o,i,n,k,r,deps,laws,refs,excl,oracles): return {"library_id":i,"name":n,"library_kind":k,"semantic_owner_context":CTX[o],"status":"specified","candidate_responsibility":r,"effect_boundary":"pure_no_io","public_types":TYPES[o],"public_traits":["".join(x.title() for x in i.split('.')[1:])+"Algebra"],"operation_refs":[x["operation_ref"] for x in OPS[o]],"operations":OPS[o],"decision_refs":[x["decision_id"] for x in DECISION_ROWS if f".{o}." in x["decision_id"]],"configuration_contracts":[o.title()+"Policy"],"laws":SHARED+laws,"invariants":["all decisions are explicit and no-default","all external resources, profiles, policies and budgets are digest-bound","semantic operations are deterministic for exact inputs and supplied algebras","model and agent outputs remain non-authoritative proposals"],"error_contracts":refs+["UnsupportedEdition","InvalidConfiguration","ResourceBudgetExceeded"],"dependencies":deps,"evidence_refs":[x["source_id"] for x in SOURCES],"oracles":oracles+["two independent implementations and cross-provider differential results"],"gaps":["No implementation is qualified; exact selector, resolver, renderer and adversarial-document conformance remains required."],"must_not_own":excl,"qualification_required":False}
LIBRARIES=[
 lib("selector","library.addressable_content.selector.compiler","Addressable Content Selector Compiler","semantic_pure","compile one typed canonical selector bound to an exact source occurrence, representation/state, media profile, coordinates, normalization and refinement policy",[],["A selector identifies intended addressing semantics and does not assert that a segment exists.","Quote, position, path, geometry and temporal selectors retain their distinct robustness and failure modes."],["SelectorIdentityMissing","SourceOccurrenceUnbound","RepresentationUnbound","MediaProfileUnsupported","SelectorKindUnsupported","TextUnitAmbiguous","CoordinateFrameMissing","TimebaseMissing","RefinementInvalid","SelectorCanonicalizationFailed"],["source identity authority","network retrieval","resolution execution","annotation body","artifact mutation"],["W3C selector examples","Unicode normalization/position twins","coordinate/timebase fixtures","canonical digest properties"]),
 lib("resolution","library.addressable_content.selector.resolver","Addressable Content Selector Resolver","algorithm_pure","resolve an accepted selector over one supplied finite representation and classify none/one/many/ambiguous/stale results with loss and evidence",["library.addressable_content.selector.compiler"],["Resolution never silently selects one candidate when the accepted cardinality policy says ambiguous.","Revision mapping is an explicit loss-bearing operation and never mutates the original selector identity."],["SelectorUnaccepted","RepresentationMismatch","ResolverProfileUnsupported","SelectorInapplicable","NoMatch","MultipleMatches","ResolutionAmbiguous","SourceStateStale","RevisionMappingMissing","ResolutionLossUnaccepted","ResolutionBudgetExceeded"],["ambient retrieval","annotation correctness","business entity identity","source mutation","review acceptance"],["selector/media cross-product corpus","zero/one/many cardinality tables","revision mutation twins","cross-resolver differential fixtures"]),
 lib("profile","library.document.rendition.profile.compiler","Bounded Document Rendition Profile Compiler","policy_pure","compile an immutable rendition plan from exact document bytes/profile, renderer contract, finite resource/font/style closure, page/color/text environment, sandbox and budgets",["library.method_kernels.document_container_semantics","library.spt.use_policy_compiler"],["A rendition plan is closed only when every permitted external resource is supplied by digest and every active-content class is explicitly allowed or refused.","Renderer, shaping, Unicode, font, locale, timezone, color and page-profile editions are material inputs."],["DocumentOccurrenceUnbound","DocumentProfileUnsupported","DecryptionAuthorityMissing","RendererContractUnbound","ResourceClosureIncomplete","FontMissing","FontSubstitutionUnbound","PageProfileMissing","ColorProfileMissing","ActiveContentPolicyMissing","EmbeddedObjectUnsupported","RenditionBudgetInvalid"],["network/filesystem retrieval","renderer implementation qualification","page execution","OCR/extraction","output acceptance"],["resource-closure mutation tests","font/layout/page golden plans","active-content decision tables","plan digest reproducibility"]),
 lib("evaluation","library.document.rendition.evaluator","Bounded Document Rendition Evaluator","algorithm_pure","evaluate one accepted rendition plan through a supplied renderer algebra and retain ordered pages, substitutions, diagnostics, coverage, truncation and residual evidence",["library.document.rendition.profile.compiler"],["Page surfaces are outputs under one exact rendition plan and never replace source document identity.","Parallel page rendering is permitted only when order, shared state, fonts, counters and resource effects are equivalent under the accepted plan."],["RenditionPlanUnaccepted","DocumentDigestMismatch","RendererAlgebraMissing","ResourceDigestMismatch","SandboxViolation","PageLimitExceeded","PixelLimitExceeded","RenditionCancelled","RendererFailure","PartialPageUnaccepted","RenditionTruncated","RenditionEquivalenceInconclusive"],["ambient I/O","renderer qualification","OCR/layout analysis","document truth","business acceptance"],["malformed/active-content adversarial corpus","font/substitution/color golden pages","budget/cancellation fault injection","two-renderer semantic and pixel-difference corpus"]),
]
METHODS={"value":["method.business.jtbd","method.business.capability_map"],"semantic":["method.domain.ddd","method.domain.terminology","method.information.conceptual_data"],"behavior":["method.domain.eventstorming","method.work.statecharts","method.work.dmn"],"authority":["method.trust.threat_model","method.systems.stpa"],"consistency":["method.domain.ddd","method.formal.alloy","method.formal.design_by_contract"],"variability":["method.variability.foda","method.variability.decision_model"],"software":["method.architecture.coupling","method.architecture.hexagonal","method.variability.algebraic_api"],"operation":["method.operations.resilience","method.operations.capacity","method.operations.sre"],"economics":["method.operations.finops","method.business.product_split_merge"],"empirical":["method.evidence.systematic_review","method.evidence.repository_mining","method.evidence.red_team"],"analytical":["method.analytics.or","method.formal.property_testing","method.formal.theorem_proving"],"system":["method.systems.stpa","method.trust.fmea_fta","method.strategy.systems_thinking"]}
LENSES=[
 ("value","Stable target addressing recurs across annotation/review; bounded rendition recurs across document workflows.","Share four exact mechanics while products retain outcome meaning."),("semantic","Source, selector, resolution, document, plan, page and content graph have distinct identities.","Use four contexts and four libraries."),("behavior","Selectors and profiles compile; resolution and rendering evaluate supplied finite carriers.","Keep compilers separate from evaluators."),("authority","Source identity, decryption, retrieval, rendering, review and acceptance have separate authorities.","Never infer authority from resolvability."),("consistency","Revision-bound selectors and digest-closed plans prevent floating targets and ambient resources.","Reject stale refs and resource drift."),("variability","Media selectors, coordinates, fonts, layout, locale, color, active content and budgets vary independently.","Expose all as no-default decisions."),("software","Selector syntax/resolution and rendition planning/evaluation have distinct dependencies and replacement cadence.","Retain four libraries."),("operation","Malformed containers, decompression, active content and huge pages demand cancellation and finite budgets.","Return typed refusals and residuals."),("economics","Resolution, font/resource closure and page rendering have separate compute/storage costs.","Bind resource accounting."),("empirical","W3C/IETF/IIIF selectors and PDF/CSS/Unicode/ICC rendering specs expose complementary seams.","Generalize standards without provider defaults."),("analytical","Ambiguity, staleness, coverage and cross-renderer equivalence are declared relations, not booleans.","Require differential and metamorphic oracles."),("system","Floating targets, silent font substitution, active-content execution and partial-as-complete results are hazards.","Fail closed and preserve diagnostics.")]
LENS_ROWS=[{"lens_id":f"lens.acr.{n}","lens":n,"question":"What does this lens require of addressable content and bounded rendition?","finding":f,"boundary_consequence":c,"method_refs":METHODS[n],"status":"applied"} for n,f,c in LENSES]
VERDICTS=[
 {"verdict_id":"verdict.acr.selector-split","subject_refs":["library.addressable_content.selector.compiler","library.addressable_content.selector.resolver"],"disposition":"compile_then_resolve","rationale":"Selector meaning and canonical identity must exist without a live representation; resolution has media-specific algorithms, ambiguity, staleness and cost.","status":"candidate_boundary_adjudicated_not_ratified"},
 {"verdict_id":"verdict.acr.rendition-split","subject_refs":["library.document.rendition.profile.compiler","library.document.rendition.evaluator","library.cbv.renderer_adapter"],"disposition":"exact_document_rendition_supersedes_generic_renderer_placeholder_for_document_pages","rationale":"Presentation-IR rendering does not own untrusted document resource closure, fonts, active content, page budgets, substitutions or coverage. Planning and evaluation remain separate.","status":"candidate_boundary_adjudicated_not_ratified"},
 {"verdict_id":"verdict.acr.no-content-graph-merge","subject_refs":["library.document.rendition.evaluator","library.method_kernels.document_content_graph"],"disposition":"rendition_output_then_optional_content_analysis","rationale":"Rendered pages are representation results; reading order, OCR, layout and extracted content graphs are downstream analytical interpretations.","status":"candidate_boundary_adjudicated_not_ratified"},
]
NEG=[
 ("uri_occurrence","A URI uniquely identifies one immutable content occurrence.","Bind occurrence, representation and state."),("fragment_resolve","A valid fragment syntax guarantees resolution.","Run media-profile resolution."),("selector_entity","A selector identifies a business entity.","Keep content addressing and domain identity separate."),("position_stable","Text offsets survive edits and normalization.","Bind representation/normalization and detect staleness."),("quote_unique","A text quote resolves uniquely.","Use prefix/suffix/cardinality policy."),("path_durable","XPath, CSS selector or JSON Pointer is durable identity.","Bind exact tree/document revision."),("pixel_absolute","Pixel coordinates are absolute across renditions.","Bind coordinate frame, transforms and resolution."),("time_frame","A timestamp uniquely identifies a media frame.","Bind timebase, precision and boundary semantics."),("latest_target","A selector may float to the latest source revision.","Require explicit revision mapping."),("first_match","Resolver may choose the first of multiple matches.","Apply explicit ambiguity policy."),("resolve_correct","Successful resolution proves annotation correctness.","Keep addressing and judgment separate."),("network_help","Resolver may fetch missing resources from the network.","Require a supplied finite representation."),("agent_reanchor","An agent may silently reanchor a stale target.","Emit an attributed mapping proposal and residual."),
 ("bytes_pages","Document bytes uniquely determine rendered pages.","Bind the complete rendition plan."),("format_safe","A recognized PDF/HTML/office format is safe to render.","Apply active-content, container and budget policies."),("renderer_name","A renderer product name identifies exact behavior.","Bind implementation contract and edition/digest."),("font_family","A font family name closes font resources.","Bind exact font bytes and shaping profile."),("substitute_equal","A substituted font is visually equivalent.","Record substitution and evaluate declared equivalence."),("default_locale","Host locale/timezone may supply rendering defaults.","Bind them explicitly."),("url_fetch","External URLs may be fetched during rendering.","Supply digest-addressed resources or refuse."),("script_needed","Scripts/macros may run because the document requires them.","Apply explicit sandbox/active-content policy."),("declared_size","Container-declared sizes are safe allocation budgets.","Enforce independent decompression/memory limits."),("page_success","A successful call proves every page rendered.","Return page coverage and partial/truncation state."),("warning_success","Warnings can be discarded after successful rendering.","Classify and retain diagnostics."),("parallel_equal","Pages can always render independently in parallel.","Prove counters/shared-state/resource equivalence."),("same_pixels","Same pixels prove semantic rendition equivalence.","Bind accessibility/text/structure and allowed differences."),("different_pixels","Different pixels prove semantic failure.","Evaluate the declared equivalence/tolerance profile."),("render_extract","Rendered pages are the document content graph.","Run separate OCR/layout/content analysis."),("render_truth","A faithful rendition proves document claims are true.","Keep representation and factual acceptance separate."),("agent_fidelity","A model may declare a visually plausible rendition faithful.","Require deterministic evidence and qualified comparison."),("one_renderer","One renderer's golden output proves portability.","Require two independent qualified implementations."),
]
NEGATIVE_ROWS=[{"negative_id":f"negative.acr.{k}","unsafe_inference":u,"required_behavior":b,"status":"active"} for k,u,b in NEG]
COMPILER=[]
for l in LIBRARIES:
 stem=l["library_id"].removeprefix("library."); req=f"requirement.{stem}.implementation"; off=f"offer.{stem}.reference"
 COMPILER += [{"record_kind":"capability_requirement","requirement_id":req,"subject_ref":l["library_id"],"required_operations":l["operation_refs"],"required_decisions":l["decision_refs"],"fallback_law":"refuse","status":"declared"},{"record_kind":"capability_offer","offer_id":off,"subject_ref":l["library_id"],"claimed_operations":l["operation_refs"],"qualified_implementation_count":0,"portable":False,"selectable":False,"status":"specified_unimplemented"},{"record_kind":"binding_rule","binding_rule_id":f"binding.{stem}","requirement_ref":req,"offer_ref":off,"structural_match":True,"selection_law":"Structural match never promotes an unqualified or non-portable implementation.","selectable":False,"status":"declared"}]
FILES={"sources.jsonl":SOURCES,"bounded-contexts.jsonl":CONTEXTS,"decision-points.jsonl":DECISION_ROWS,"boundary-lens-adjudication.jsonl":LENS_ROWS,"boundary-verdicts.jsonl":VERDICTS,"library-contracts.jsonl":LIBRARIES,"compiler-contracts.jsonl":COMPILER,"negative-twins.jsonl":NEGATIVE_ROWS}
def main():
 ROOT.mkdir(parents=True,exist_ok=True); ds={}
 for n,rs in FILES.items():
  p=render(rs); (ROOT/n).write_text(p); ds[n]={"records":len(rs),"sha256":hashlib.sha256(p.encode()).hexdigest()}
 (ROOT/"manifest.json").write_text(json.dumps({"manifest_id":"addressable_content_rendition_v0_1_0","as_of":AS_OF,"edition":1,"status":"specified_unimplemented_open_world","files":ds,"completion_claim":False,"qualified_implementation_count":0},indent=2,sort_keys=True)+"\n")
 print(f"BUILD PASS acr: {len(SOURCES)} sources, {len(CONTEXTS)} contexts, {len(DECISION_ROWS)} decisions, {len(LIBRARIES)} libraries, {sum(len(v) for v in OPS.values())} operations, {len(LENS_ROWS)} lenses, {len(NEGATIVE_ROWS)} negative twins")
if __name__=="__main__": main()
