"""Spec output formatting."""

from datetime import datetime

def format_spec(
    idea: str,
    layer_outputs: dict,
    probe_history: list,
    final_confidence: float,
    risks: list
) -> str:
    """
    Format the complete spec as markdown.

    Args:
        idea: Original idea
        layer_outputs: Dict of layer_name -> content
        probe_history: List of all probe results
        final_confidence: Final confidence score
        risks: List of identified risks

    Returns:
        Formatted markdown spec
    """
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    spec = f"""# Specification: {idea}

**Generated:** {timestamp}
**Confidence Score:** {final_confidence:.2f}
**Status:** {"✅ Ready for Implementation" if final_confidence >= 0.7 else "⚠️ Needs Refinement"}

---

"""

    # Add each layer's output
    layer_order = ["business", "product", "technical", "implementation"]
    for layer_name in layer_order:
        if layer_name in layer_outputs:
            spec += layer_outputs[layer_name] + "\n\n"

    # Add risks section
    spec += "---\n\n## Identified Risks\n\n"
    if risks:
        for i, risk in enumerate(risks, 1):
            spec += f"{i}. {risk}\n"
    else:
        spec += "No significant risks identified.\n"

    spec += "\n"

    # Add probe validation summary
    spec += "---\n\n## Validation Summary\n\n"
    spec += f"**Total Probes Run:** {len(probe_history)}\n"

    passed = sum(1 for p in probe_history if p["result"]["passed"])
    failed = len(probe_history) - passed

    spec += f"**Passed:** {passed}  \n"
    spec += f"**Failed:** {failed}  \n"
    spec += f"**Final Confidence:** {final_confidence:.2f}\n\n"

    # Show failed probes if any
    failed_probes = [p for p in probe_history if not p["result"]["passed"]]
    if failed_probes:
        spec += "### Failed Probes\n\n"
        for probe_result in failed_probes:
            probe = probe_result["probe"]
            result = probe_result["result"]
            spec += f"**Q:** {probe['question']}\n"
            spec += f"**A:** {result['reasoning']}\n"
            if "concerns" in result and result["concerns"]:
                spec += f"**Concerns:** {', '.join(result['concerns'])}\n"
            spec += "\n"

    # Add next steps
    spec += "---\n\n## Next Steps\n\n"
    if final_confidence >= 0.7:
        spec += "1. Review this specification with stakeholders\n"
        spec += "2. Set up development environment\n"
        spec += "3. Begin implementation starting with [first step from Implementation Layer]\n"
        spec += "4. Iterate based on feedback\n"
    else:
        spec += "This spec needs refinement before implementation:\n"
        for probe_result in failed_probes:
            if "concerns" in probe_result["result"]:
                for concern in probe_result["result"]["concerns"]:
                    spec += f"- Address: {concern}\n"

    spec += "\n---\n\n*Generated by Spec Agent v1.0 (GLM 4.7)*\n"

    return spec


def save_spec(spec: str, filename: str = None):
    """Save spec to file."""
    if filename is None:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"spec_{timestamp}.md"

    with open(filename, "w") as f:
        f.write(spec)

    return filename
