#!/usr/bin/env python3
"""Platform Estate & Tenancy Administration product boundary and exact local seams."""

from __future__ import annotations

from typing import Any

from platform_product_enrichment import AUTOMATION, CENTRAL_REGISTRY, DDD_FIELDS, artifact, binding, library, requirement


ESTATE = "product.platform_estate_tenancy_administration"
ESTATE_LIBRARIES = {
    "library.platform.estate.hierarchy",
    "library.platform.estate.container_lifecycle",
    "library.platform.estate.policy_attachment",
    "library.platform.estate.admin_delegation_binding",
    "library.platform.estate.region_capacity_binding",
    "library.platform.estate.change_plan",
    "library.platform.estate.reconciliation",
    "library.platform.estate.exit_manifest",
}


def _source(ident: str, title: str, publisher: str, uri: str, claim: str, limit: str) -> dict[str, Any]:
    return {"source_id": ident, "source_class": "official_specification_or_documentation", "title": title, "publisher": publisher, "uri": uri, "retrieved_at": "2026-08-27", "claim": claim, "scope_limit": limit}


def _dossier() -> dict[str, Any]:
    truth = {
        "sovereign_question": "How can a platform administrator create, organize, bind, govern, suspend, recover, move, and retire organization, account, project and workspace containers without confusing tenancy with identity, authorization, runtime capacity, content ownership, billing or provider implementation?",
        "users": ["platform_estate_administrator", "organization_administrator", "workspace_administrator", "platform_product_owner", "security_policy_owner", "capacity_administrator", "assurance_reviewer"],
        "harmed_parties": ["tenant_user", "resource_owner", "data_subject", "billing_owner", "downstream_consumer", "platform_operator", "regulated_workload_owner"],
        "jobs": ["govern one identified estate hierarchy", "create and move administrative containers", "attach and explain inherited policy scopes", "bind containers to qualified regions capacities and editions", "delegate administration without transferring policy meaning", "suspend delete restore and purge with evidence", "export the hierarchy bindings policies and residual obligations for exit"],
        "measurable_outcomes": ["unowned_container_count", "invalid_parent_transition_count", "effective_policy_explanation_coverage", "region_capacity_binding_conformance", "orphan_recovery_time", "deletion_restore_success", "verified_estate_export_coverage", "stale_administration_grant_count"],
        "negative_mission": "Does not own human or workload identity, authentication, authorization-policy meaning, product content, runtime scheduling, physical capacity truth, cost allocation, invoices, data residency interpretation, application workspaces or business-domain records.",
    }
    ddd = {
        "domain_vision_statement": "Own the governed administrative estate from root organization through account, project and workspace containers, including parentage, scoped attachments, bindings and recoverable lifecycle evidence.",
        "subdomain_classification": {"core": ["estate_hierarchy_and_parentage", "administrative_container_lifecycle", "attachment_and_inheritance_scope", "estate_change_and_exit"], "supporting": ["administrative_delegation_binding", "region_capacity_binding", "reconciliation_and_orphan_recovery"], "generic_or_imported": ["principal_identity", "authentication", "authorization_decision", "policy_language", "resource_capacity", "billing", "runtime_control", "content_catalog", "secrets", "observability"]},
        "bounded_context_boundary": {"inside": ["organization and estate identity", "container kinds and parent edges", "account project workspace administrative identity", "container lifecycle", "policy attachment occurrence and effective-scope explanation", "administrative delegation binding", "region edition and capacity bindings", "move suspend delete restore purge and exit state"], "outside": ["principal identity proof", "authorization decision semantics", "resource scheduling", "workspace content", "analytical session state", "commercial contract", "invoice or ledger", "provider qualification", "data-use interpretation"]},
        "ubiquitous_language_policy": {"terms": {"Estate": "one administratively governed hierarchy under an identified root", "Container": "identified administrative scope with at most one effective parent in one hierarchy edition", "Account": "provider-facing administrative and isolation occurrence, not a billing account unless explicitly bound", "Project": "administrative grouping and service scope, not a business project", "Workspace": "administrative content container, not an analytical workspace or runtime session", "Attachment": "editioned association of an external policy or control to one scope", "EffectiveScope": "trace explaining which attachments apply through declared inheritance rules", "EstateBinding": "validity-scoped association to provider region edition capacity or account occurrence", "Orphaned": "container whose required administrative owner binding is absent", "Purge": "irreversible authorized destruction after retention and dependency gates"}, "homonym_rules": ["tenant is not principal", "account is not billing account", "project is not project-management project", "workspace is not analysis state", "policy attachment is not policy decision", "capacity binding is not capacity availability", "delete is not purge"]},
        "context_map": [{"neighbor_ref": "neighbor.identity_policy", "relationship": "customer_supplier_with_acl", "translation": "import principal grants policy editions and authorization decisions without owning them"}, {"neighbor_ref": "product.runtime_resource_control", "relationship": "customer_supplier", "translation": "publish administrative scopes and consume qualified capacity or runtime bindings"}, {"neighbor_ref": "product.finops_allocation", "relationship": "customer_supplier", "translation": "publish estate scope identities without owning allocation or billing"}, {"neighbor_ref": "product.data_product_developer_platform", "relationship": "customer_supplier", "translation": "provide account project and workspace targets without owning paved-path content"}, {"neighbor_ref": "component.provider_qualification", "relationship": "customer_supplier", "translation": "consume exact provider occurrence and capability receipts"}],
        "anti_corruption_layers": ["acl.aws_organizations", "acl.google_resource_manager", "acl.azure_management_groups", "acl.snowflake_organizations", "acl.fabric_workspaces", "acl.identity_authorization", "acl.runtime_capacity", "acl.billing_finance"],
        "published_language": ["EstateId", "EstateEdition", "ContainerId", "ContainerKind", "ParentEdge", "AttachmentId", "PolicyEditionRef", "EffectiveScopeTrace", "AdministrativeGrantRef", "RegionBinding", "CapacityBinding", "EstateChangePlan", "ContainerLifecycleReceipt", "EstateExitManifest"],
        "value_objects": ["EstateId", "EstateEdition", "ContainerId", "ContainerKind", "ParentEdgeId", "AttachmentId", "PolicyEditionRef", "AuthorityRef", "RegionRef", "CapacityOfferRef", "ProviderOccurrenceRef", "LifecycleReason", "RetentionDeadline", "EvidenceRef", "PlanDigest"],
        "entities": ["Estate", "AdministrativeContainer", "ParentEdge", "PolicyAttachment", "AdministrativeDelegationBinding", "EstateBinding", "EstateChangePlan", "LifecycleCase", "EstateExitManifest"],
        "aggregates": [{"root": "Estate", "members": ["root", "container index", "hierarchy edition", "structural constraints"], "consistency": "one root and no cycles; every live non-root container has exactly one effective parent"}, {"root": "AdministrativeContainer", "members": ["identity", "kind", "parent edge", "attachments", "bindings", "lifecycle"], "consistency": "identity is immutable and lifecycle or move commands preserve governed dependencies"}, {"root": "EstateChangePlan", "members": ["source edition", "target graph", "policy impact", "binding impact", "active work disposition", "rollback plan"], "consistency": "a move or deletion cannot hide inherited-policy, region, capacity, content or active-work consequences"}],
        "aggregate_roots": ["Estate", "AdministrativeContainer", "EstateChangePlan"],
        "aggregate_invariants": ["one estate has exactly one root", "a live non-root container has exactly one parent", "parent graph is acyclic", "identity is not a mutable display name or URL", "moving a container creates a new hierarchy edition and recalculates effective attachment scope", "attachment does not issue or evaluate the referenced policy", "administrative delegation cannot exceed or outlive the external grant", "region or capacity binding does not prove availability or authorization", "delete remains recoverable until an explicit purge gate", "purge refuses while retention dependency export or active-work obligations remain", "provider DTO names never become canonical kinds"],
        "commands": ["create_estate", "create_container", "rename_container", "move_container", "attach_policy", "detach_policy", "bind_administrator", "bind_region", "bind_capacity", "suspend_container", "request_delete", "restore_container", "request_purge", "reconcile_estate", "plan_estate_exit", "verify_estate_export"],
        "domain_events": ["estate_created", "container_created", "container_renamed", "container_moved", "policy_attached", "policy_detached", "administrator_bound", "region_bound", "capacity_bound", "container_suspended", "container_delete_requested", "container_restored", "container_purge_requested", "estate_reconciled", "estate_exit_planned", "estate_export_verified"],
        "refusal_failure_catalog": ["root_already_exists", "container_identity_conflict", "parent_missing", "parent_kind_incompatible", "hierarchy_cycle", "cross_estate_move_unplanned", "policy_edition_unknown", "inheritance_rule_unknown", "administrative_grant_missing", "administrative_grant_expired", "provider_occurrence_unqualified", "region_prohibited", "capacity_offer_unknown", "active_work_unresolved", "retention_gate_open", "dependent_container_exists", "restore_window_expired", "purge_authority_missing", "reconciliation_unknown", "exit_manifest_incomplete"],
        "domain_services": ["HierarchyValidationService", "EffectiveAttachmentProjectionService", "AdministrativeBindingService", "EstateBindingCompatibilityService", "EstateChangePlanningService", "OrphanRecoveryService", "EstateExitVerificationService"],
        "application_services": ["CreateEstateUseCase", "MoveContainerUseCase", "AttachPolicyUseCase", "BindWorkspaceCapacityUseCase", "RecoverOrphanedContainerUseCase", "DeleteRestorePurgeUseCase", "ExportEstateUseCase"],
        "repositories": ["EstateRepository", "AdministrativeContainerRepository", "AttachmentRepository", "EstateBindingRepository", "EstateChangePlanRepository", "LifecycleCaseRepository"],
        "factories": ["EstateFactory", "ContainerFactory", "ParentEdgeFactory", "PolicyAttachmentFactory", "EstateBindingFactory", "EstateChangePlanFactory", "EstateExitManifestFactory"],
        "specifications": ["SingleRootSpecification", "AcyclicHierarchySpecification", "ParentKindCompatibilitySpecification", "EffectiveAttachmentCompletenessSpecification", "AdministrativeGrantValiditySpecification", "EstateBindingCompatibilitySpecification", "MoveImpactClosureSpecification", "PurgeSafetySpecification", "EstateExitCompletenessSpecification"],
        "state_machine": {"AdministrativeContainer": ["requested", "active", "suspended", "orphaned", "move_pending", "delete_requested", "recoverable_deleted", "restore_pending", "purge_pending", "purged", "unknown", "refused"], "EstateChangePlan": ["draft", "validated", "authorized", "effects_pending", "reconciling", "applied", "rolled_back", "partially_applied", "unknown", "refused"], "law": "delete and purge are distinct; unknown provider outcomes are reconciled before retry and historical hierarchy editions remain immutable"},
        "policies_and_reactions": ["when parentage changes recompute effective attachment traces and affected bindings", "when an administrator grant expires mark the container orphaned without deleting content", "when a capacity or region binding becomes invalid suspend affected provisioning intents", "when deletion is requested freeze new child creation and enumerate dependencies", "when a provider effect is unknown reconcile before retry", "when purge is requested require retention export active-work and authority gates"],
        "sagas_and_process_managers": ["ContainerCreationProcess", "ContainerMoveProcess", "PolicyAttachmentChangeProcess", "RegionCapacityRebindingProcess", "OrphanRecoveryProcess", "DeleteRestorePurgeProcess", "CrossProviderEstateExitProcess"],
        "read_models_and_projections": ["EstateTreeView", "ContainerLifecycleView", "EffectivePolicyAttachmentView", "AdministrativeDelegationView", "RegionCapacityBindingView", "OrphanedContainerView", "DeletionRecoveryQueue", "EstateChangeImpactView", "EstateExitReadinessView"],
        "integration_event_policy": "Only canonical estate/container identities, hierarchy editions, attachment references, binding decisions, lifecycle requests/receipts and exit manifests cross the boundary; provider DTOs, credentials, policy bodies, authorization decisions, content and invoices do not.",
        "concurrency_and_idempotency": ["hierarchy changes use optimistic estate edition", "container creation idempotency binds estate parent kind and client request", "move serializes per container and validates source and target editions", "attachment identity binds scope policy edition and inheritance profile", "provider effects use separate occurrence identities and receipts", "delete restore and purge commands serialize per container", "unknown effects reconcile before a new attempt"],
        "time_model": ["hierarchy validity differs from recording time", "parent and attachment relationships are bitemporal", "administrative grants have independent validity", "region capacity and provider bindings have observed and expiry times", "deletion has request retention recovery and purge times", "historical hierarchy and effective-scope explanations remain reproducible"],
        "event_storming_swimlanes": ["enterprise_platform_owner", "estate_administrator", "identity_authority", "policy_authority", "provider_qualification", "capacity_administrator", "runtime_control", "workspace_owner", "assurance_reviewer", "support_operator"],
        "nonfunctional_laws": ["deterministic hierarchy and inheritance projection for frozen editions", "finite graph traversal and impact budgets", "no hidden provider effects in semantic libraries", "complete parent attachment binding and lifecycle trace", "tenant and estate isolation", "cooperative cancellation with explicit unknown outcome", "recoverable deletion before authorized purge", "provider-neutral export", "optional model or agent removal preserves every estate function"],
    }
    assert set(ddd) == DDD_FIELDS
    return {"dossier_id": "ddd.platform.platform_estate_tenancy_administration", "record_kind": "product_ddd_dossier", "edition": 1, "product_ref": ESTATE, "status": "candidate_not_ratified", "product_truth": truth, "strategic_and_tactical_ddd": ddd}


def enrich_platform_estate(source: dict[str, Any]) -> dict[str, Any]:
    refs = ["evidence.aws.organizations", "evidence.gcp.resource_hierarchy", "evidence.azure.management_groups", "evidence.snowflake.organizations", "evidence.fabric.workspaces"]
    source["sources"].extend([
        _source("evidence.aws.organizations", "Managing organizational units", "Amazon Web Services", "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_manage_ous.html", "AWS persists one organization root, nested organizational units, accounts, moves and inherited policy controls.", "AWS constructs are provider evidence; they do not define a universal estate model or qualify an occurrence."),
        _source("evidence.gcp.resource_hierarchy", "About resource hierarchy", "Google Cloud", "https://docs.cloud.google.com/resource-manager/docs/cloud-platform-resource-hierarchy", "Google persists organization, folder and project hierarchy, exactly-one-parent structure, policy inheritance and lifecycle state.", "Google resource kinds and policy behavior require an anti-corruption layer."),
        _source("evidence.azure.management_groups", "Organize resources with management groups", "Microsoft Azure", "https://learn.microsoft.com/en-us/azure/governance/management-groups/overview", "Azure persists one directory-rooted management hierarchy, subscription parentage, moves and inherited policy/access scopes.", "Azure hierarchy limits and Entra coupling are provider-specific."),
        _source("evidence.snowflake.organizations", "Introduction to organizations and managing accounts", "Snowflake", "https://docs.snowflake.com/en/user-guide/organizations", "Snowflake persists first-class organizations and accounts across regions/clouds with administrator-owned account lifecycle, editions and deletion.", "Snowflake accounts are not universal tenant, billing-account or workspace identities."),
        _source("evidence.fabric.workspaces", "Manage workspaces", "Microsoft Fabric", "https://learn.microsoft.com/en-us/fabric/admin/portal-workspaces", "Fabric persists workspace identity, tenant membership, capacity binding, lifecycle states, deletion retention and administrative recovery.", "Fabric workspace content and analytics semantics remain outside estate administration."),
    ])
    truth = _dossier()["product_truth"]
    source["artifacts"].append({**artifact(ESTATE, "product", "Platform Estate & Tenancy Administration", "semantic.platform_estate", "Operate administrative hierarchy, attachment, binding and recoverable container lifecycle across provider estates.", refs), "status": "strong_product_candidate", "adoption_unit": True, "operated": True, "sovereign_question": truth["sovereign_question"], "users": truth["users"], "harmed_parties": truth["harmed_parties"], "jobs": truth["jobs"], "outcomes": truth["measurable_outcomes"], "negative_mission": truth["negative_mission"], "automation_modality": AUTOMATION})
    semantics = [
        ("semantic.platform_estate", "Platform estate", "identified hierarchy root, edition and governed container graph"),
        ("semantic.estate_container", "Administrative container", "organization, account, folder, project or workspace administrative scope and lifecycle"),
        ("semantic.estate_attachment", "Estate attachment", "scope-bound external policy/control reference and effective inheritance trace"),
        ("semantic.estate_binding", "Estate binding", "validity-scoped provider, region, edition and capacity association"),
        ("semantic.estate_change", "Estate change", "impact-complete move, suspend, delete, restore, purge or exit plan and receipts"),
    ]
    source["artifacts"].extend(artifact(i, "semantic_contract", n, i, d, refs) for i,n,d in semantics)
    capabilities = [
        ("capability.govern_estate_hierarchy", "Govern estate hierarchy", "semantic.platform_estate"),
        ("capability.reduce_container_lifecycle", "Reduce container lifecycle", "semantic.estate_container"),
        ("capability.project_effective_attachments", "Project effective attachments", "semantic.estate_attachment"),
        ("capability.bind_estate_administration", "Bind estate administration", "semantic.estate_attachment"),
        ("capability.bind_estate_region_capacity", "Bind estate region and capacity", "semantic.estate_binding"),
        ("capability.plan_estate_change", "Plan estate change", "semantic.estate_change"),
        ("capability.reconcile_estate", "Reconcile estate", "semantic.estate_change"),
        ("capability.export_estate", "Export estate", "semantic.estate_change"),
    ]
    source["artifacts"].extend(artifact(i, "capability", n, owner, f"Typed capability owned by {owner}.", refs) for i,n,owner in capabilities)
    source["artifacts"].extend([
        artifact("implementation.aws_organizations", "implementation", "AWS Organizations", None, "Observed unqualified organization, OU and account administration implementation.", ["evidence.aws.organizations"]),
        artifact("implementation.gcp_resource_manager", "implementation", "Google Cloud Resource Manager", None, "Observed unqualified organization, folder and project hierarchy implementation.", ["evidence.gcp.resource_hierarchy"]),
        artifact("implementation.azure_management_groups", "implementation", "Azure Management Groups", None, "Observed unqualified management-group and subscription hierarchy implementation.", ["evidence.azure.management_groups"]),
        artifact("implementation.snowflake_organizations", "implementation", "Snowflake Organizations", None, "Observed unqualified organization and account lifecycle implementation.", ["evidence.snowflake.organizations"]),
        artifact("implementation.fabric_workspaces", "implementation", "Microsoft Fabric Workspaces", None, "Observed unqualified tenant workspace and capacity lifecycle implementation.", ["evidence.fabric.workspaces"]),
    ])
    source["boundary_decisions"].append({"decision_id": "decision.platform.estate_tenancy", "subject_ref": ESTATE, "disposition": "strong_product_candidate", "rationale": "Unrelated cloud and data-platform providers independently expose an adopted administrator job, persistent hierarchy/container state, attachment inheritance, binding and deletion/recovery lifecycle. Identity, authorization, runtime, FinOps and content remain external.", "split_test": {axis: {"score": 2 if axis != "economics" else 1, "finding": "Independent providers expose this boundary; commercial isolation is observed through administrative adoption but requires buyer validation.", "evidence_refs": refs} for axis in ["user","job","adoption","semantics","authority","lifecycle","operation","economics","interface","market_evidence"]}, "evidence_refs": refs})
    source["ownership"].extend({"meaning_id": f"meaning.{i.removeprefix('semantic.')}", "term": n, "owner_ref": i, "invariant": f"{n} cannot be inferred from provider names, identity grants, resource usage, billing records or workspace content.", "must_not_be_owned_by": ["neighbor.identity_policy", "product.runtime_resource_control", "product.finops_allocation"]} for i,n,_ in semantics)
    libs = [
        library("library.platform.estate.hierarchy", ESTATE, "semantic.platform_estate", ["capability.govern_estate_hierarchy"], ["EstateId","EstateEdition","ContainerId","ContainerKind","ParentEdge","HierarchyDiagnostic"], ["create_root","add_container","move_container","validate_hierarchy","explain_parentage"], ["kind_compatibility","cross_estate_move_policy","cycle_policy"], ["one_root","one_parent_per_live_nonroot","acyclic","identity_is_not_display_name"], ["root_conflict","parent_missing","kind_incompatible","cycle_detected"], [], "pure_no_io", refs),
        library("library.platform.estate.container_lifecycle", ESTATE, "semantic.estate_container", ["capability.reduce_container_lifecycle"], ["ContainerCommand","ContainerState","RetentionWindow","LifecycleReceipt"], ["validate_command","reduce_transition","plan_restore","authorize_purge"], ["retention_policy","orphan_policy","purge_policy"], ["delete_is_not_purge","purged_is_terminal","unknown_is_not_failed"], ["illegal_transition","retention_open","dependency_exists","purge_authority_missing"], ["library.platform.estate.hierarchy"], "pure_effect_intents", refs),
        library("library.platform.estate.policy_attachment", ESTATE, "semantic.estate_attachment", ["capability.project_effective_attachments"], ["Attachment","PolicyEditionRef","InheritanceProfile","EffectiveScopeTrace"], ["attach","detach","project_effective_scope","explain_inheritance"], ["inheritance_profile","override_policy","unknown_policy_policy"], ["attachment_is_not_policy_decision","trace_retains_every_ancestor_and_rule"], ["policy_unknown","inheritance_rule_unknown","conflicting_attachment"], ["library.platform.estate.hierarchy"], "pure_no_io", refs),
        library("library.platform.estate.admin_delegation_binding", ESTATE, "semantic.estate_attachment", ["capability.bind_estate_administration"], ["AdministrativeGrantRef","ContainerScope","DelegationBinding","BindingValidity"], ["bind_grant","validate_scope","expire_binding","explain_administration"], ["grant_precedence","expiry_policy","orphan_policy"], ["role_label_is_not_authority","binding_cannot_exceed_or_outlive_grant"], ["grant_missing","grant_expired","scope_exceeds_grant"], ["library.platform.estate.hierarchy"], "pure_no_io", refs),
        library("library.platform.estate.region_capacity_binding", ESTATE, "semantic.estate_binding", ["capability.bind_estate_region_capacity"], ["ContainerRef","ProviderOccurrenceRef","RegionRef","CapacityOfferRef","EstateBinding"], ["evaluate_compatibility","bind_region","bind_capacity","invalidate_binding"], ["residency_constraint_profile","capacity_binding_policy","expiry_policy"], ["binding_is_not_availability_or_authorization","provider_identity_does_not_define_semantics"], ["provider_unqualified","region_prohibited","offer_incompatible","binding_expired"], ["library.platform.estate.hierarchy"], "pure_no_io", refs),
        library("library.platform.estate.change_plan", ESTATE, "semantic.estate_change", ["capability.plan_estate_change"], ["EstateChangeRequest","AffectedContainerSet","AttachmentDiff","BindingDiff","ActiveWorkDisposition","EstateChangePlan"], ["compute_impact","plan_move","plan_delete","plan_restore","plan_rollback"], ["impact_closure_policy","active_work_policy","rollback_policy"], ["plan_is_not_effect","every_descendant_attachment_binding_and_active_work_is_accounted"], ["impact_incomplete","active_work_unresolved","rollback_unknown"], ["library.platform.estate.hierarchy","library.platform.estate.policy_attachment","library.platform.estate.region_capacity_binding","library.platform.estate.container_lifecycle"], "pure_no_io", refs),
        library("library.platform.estate.reconciliation", ESTATE, "semantic.estate_change", ["capability.reconcile_estate"], ["DesiredEstateEdition","ProviderEffectIntent","ProviderObservation","ReconciliationReceipt","ResidualDrift"], ["emit_effect_intents","ingest_observation","reconcile","classify_residual"], ["retry_policy","unknown_outcome_policy","drift_policy"], ["desired_is_not_observed_or_accepted","unknown_effect_is_reconciled_before_retry"], ["effect_unauthorized","provider_unknown","observation_conflict","residual_unclassified"], ["library.platform.estate.change_plan"], "effectful_runtime", refs, "backend_spi"),
        library("library.platform.estate.exit_manifest", ESTATE, "semantic.estate_change", ["capability.export_estate"], ["EstateSnapshot","HierarchyExport","AttachmentExport","BindingExport","ActiveWorkDisposition","ResidualObligation","EstateExitManifest"], ["compile_exit_manifest","verify_export","record_residual","close_exit"], ["export_profile","secret_exclusion_policy","residual_policy"], ["data_export_is_not_estate_exit","credentials_and_provider_private_state_do_not_leak"], ["dependency_unresolved","export_unverified","residual_owner_missing"], ["library.platform.estate.change_plan"], "pure_effect_intents", refs),
    ]
    source["libraries"].extend(libs)
    source["requirements"].extend(requirement(f"requirement.platform.estate.{cap.split('.')[-1]}", ESTATE, cap, phase, refusal) for cap,phase,refusal in [
        ("capability.govern_estate_hierarchy","compile_time","estate_hierarchy_unbound"), ("capability.reduce_container_lifecycle","runtime","container_lifecycle_unbound"), ("capability.project_effective_attachments","compile_time","attachment_projection_unbound"), ("capability.bind_estate_administration","compile_time","administration_binding_unbound"), ("capability.bind_estate_region_capacity","target_binding","estate_target_binding_unbound"), ("capability.plan_estate_change","compile_time","estate_change_planner_unbound"), ("capability.reconcile_estate","runtime","estate_reconciler_unbound"), ("capability.export_estate","runtime","estate_exit_unbound")])
    source["offers"].extend({"offer_id": f"offer.{impl.split('.')[-1]}.estate", "provider_ref": impl, "capability_refs": ["capability.govern_estate_hierarchy", "capability.reduce_container_lifecycle"], "qualified_implementation_count": 0, "portable": False, "status": "observed_unqualified", "evidence_refs": evs} for impl,evs in [
        ("implementation.aws_organizations",["evidence.aws.organizations"]), ("implementation.gcp_resource_manager",["evidence.gcp.resource_hierarchy"]), ("implementation.azure_management_groups",["evidence.azure.management_groups"]), ("implementation.snowflake_organizations",["evidence.snowflake.organizations"]), ("implementation.fabric_workspaces",["evidence.fabric.workspaces"])])
    source["relations"].extend([
        {"relation_id": "relation.suite.packages.platform_estate", "from_ref": "suite.data_analytics_platform", "predicate": "packages", "to_ref": ESTATE, "binding_phase": "authoring"},
        {"relation_id": "relation.developer.requires.estate", "from_ref": "product.data_product_developer_platform", "predicate": "requires", "to_ref": ESTATE, "binding_phase": "deployment_time"},
        {"relation_id": "relation.estate.requires.identity", "from_ref": ESTATE, "predicate": "requires", "to_ref": "neighbor.identity_policy", "binding_phase": "compile_time"},
        {"relation_id": "relation.estate.requires.runtime", "from_ref": ESTATE, "predicate": "requires", "to_ref": "product.runtime_resource_control", "binding_phase": "target_binding"},
    ])
    source["crosswalks"].append({"legacy_ref": "candidate.product.platform_estate_tenancy_administration", "canonical_refs": [ESTATE], "disposition": "promote_exact"})
    exact = {
        "library.platform.estate.hierarchy": ["library.platform-commercial-support.tenant-identity", "library.platform-commercial-support.account_identity"],
        "library.platform.estate.container_lifecycle": ["library.lpe.record-lifecycle", "library.product_composition.environment_lifecycle"],
        "library.platform.estate.policy_attachment": ["library.csp.authority.policy-algebra"],
        "library.platform.estate.admin_delegation_binding": ["library.csp.authority.delegation-graph"],
        "library.platform.estate.region_capacity_binding": ["library.runtime-resource.resource-topology", "library.runtime-resource.demand-offer-compatibility"],
        "library.platform.estate.change_plan": ["library.product_composition.environment_lifecycle", "library.smf.compatibility_diff"],
        "library.platform.estate.reconciliation": ["library.runtime-resource.runtime-receipts"],
        "library.platform.estate.exit_manifest": ["library.platform-commercial-support.exit-manifest", "library.platform-commercial-support.export-transfer-port"],
    }
    source["binding_maps"].extend(binding(local, exact[local], ESTATE, CENTRAL_REGISTRY) for local in sorted(ESTATE_LIBRARIES))
    source["ddd_dossiers"].append(_dossier())
    source["negative_tests"].extend([
        {"test_id": "negative.estate.tenant_principal", "prohibited_claim": "A tenant or account identity proves a principal, authentication or authorization.", "expected_result": "import exact external identity and authorization decisions"},
        {"test_id": "negative.estate.attachment_decision", "prohibited_claim": "A policy attached to an ancestor proves a specific action is authorized.", "expected_result": "project effective scope then request the owning policy decision"},
        {"test_id": "negative.estate.workspace_analysis", "prohibited_claim": "A provider workspace is an analytical workspace, runtime session or accepted content state.", "expected_result": "retain distinct administrative content analytical and runtime identities"},
        {"test_id": "negative.estate.binding_capacity", "prohibited_claim": "A region or capacity binding proves physical capacity is available.", "expected_result": "request a current qualified resource offer and admission decision"},
        {"test_id": "negative.estate.delete_purge", "prohibited_claim": "Deleting a container proves its content and obligations are permanently purged.", "expected_result": "retain recovery retention dependency export and purge gates"},
        {"test_id": "negative.estate.provider_universal", "prohibited_claim": "One provider hierarchy or workspace model defines the universal estate ontology.", "expected_result": "translate through the provider ACL and retain residuals"},
    ])
    source["non_collapse_laws"].extend([
        "estate != tenant != principal != authorization domain",
        "organization != account != billing account != project != workspace != runtime session",
        "policy attachment != effective-scope trace != policy decision != enforcement effect",
        "region or capacity binding != qualified offer != availability != admission != allocation",
        "suspend != delete request != recoverable deletion != irreversible purge",
    ])
    source["scope"] += " Platform estate and tenancy administration is a separate horizontal product boundary."
    return source
