"""Evidence-bounded upstream demand-surface delta, 2026-08-27."""

SOURCES = [
    ("source.upstream.3gpp-nwdaf", "3GPP TS 23.288 / ETSI TS 123 288", "3GPP/ETSI", "https://www.etsi.org/deliver/etsi_ts/123200_123299/123288/18.11.00_60/ts_123288v181100p.pdf", "NWDAF exposes request/subscription analytics services to consumers; analytics output is not consumer application logic or control authority."),
    ("source.upstream.iso-21508-2026", "ISO 21508:2026 Earned value management", "ISO", "https://www.iso.org/standard/87899.html", "EVM integrates cost, schedule and scope across public/private organizations of any size, sector, project, programme or portfolio."),
    ("source.upstream.primavera", "Oracle Primavera Cloud Schedule Management", "Oracle", "https://docs.oracle.com/cd/E80480_01/English/user_guides/schedule_management_user_guide/primavera_schedule_management_user.pdf", "Primavera operates schedules, baselines, contracts, potential change orders, costs, payment applications and approvals as distinct state."),
    ("source.upstream.semi-e134", "SEMI E134-1225 Data Collection Management", "SEMI", "https://store-us.semi.org/products/e13400-semi-e134-specification-for-data-collection-management", "Named data-collection plans own event/exception/trace selection, state-machine execution, on-demand acquisition, output and equipment-performance constraints."),
    ("source.upstream.semi-e190", "SEMI E190-1124 Equipment Data Publication", "SEMI", "https://store-us.semi.org/products/e19000-semi-e190-specification-for-equipment-data-publication-edp", "Equipment-data categories and shareable/nonshareable access concepts are explicit and supplier/user access is negotiated."),
    ("source.upstream.asam-ods", "ASAM ODS 6.2.1", "ASAM", "https://www.asam.net/standards/detail/ods/", "Test-data management covers test systems, measurement devices, measured/calculated data, calibration, instrumentation and testing workflows."),
    ("source.upstream.sec-edgar", "SEC EDGAR filing technical specifications and manual", "U.S. SEC", "https://www.sec.gov/submit-filings/technical-specifications", "Submission types bind form-specific taxonomy/schema editions and validation; submissions receive acceptance or suspension outcomes."),
    ("source.upstream.odk", "ODK form audit and submission management", "ODK", "https://docs.getodk.org/central-api-submission-management/", "Forms, submissions and server audit logs retain distinct identity and lifecycle."),
    ("source.upstream.fhir-specimen", "HL7 FHIR R5 Specimen", "HL7", "https://hl7.org/fhir/specimen.html", "Specimens own collection, origin, processing, condition, parentage, status and container concerns independently of observations and reports."),
    ("source.upstream.fhir-diagnostic", "HL7 FHIR R5 DiagnosticReport", "HL7", "https://hl7.org/fhir/diagnosticreport.html", "Reports bind specimens and observations, have final/amended/retracted lifecycle, and remain distinct from individual results."),
    ("source.upstream.stix-2-1", "STIX 2.1", "OASIS", "https://docs.oasis-open.org/cti/stix/v2.1/errata01/stix-v2.1-errata01.pdf", "Observed Data records what was seen; a Sighting is a distinct intelligence assertion about what the observation implies."),
    ("source.upstream.edrm-2", "EDRM 2.0", "EDRM", "https://edrm.net/edrm-projects/edrm-2-0/", "Evidence production spans identification, preservation, collection, processing, review, analysis, production, presentation and disposition."),
    ("source.upstream.energistics", "Energistics WITSML/RESQML/PRODML architecture", "Energistics", "https://energistics.org/witsml-developers-users", "Well/drilling, earth/reservoir and production models are separate domain standards sharing a common technical architecture and transfer protocol."),
    ("source.upstream.gs1-traceability", "GS1 Global Traceability and EPCIS", "GS1", "https://ref.gs1.org/standards/global-traceability/2.0.0/", "Traceable-object identity, critical tracking events, transformations, aggregation and key data elements are independently represented across parties."),
    ("source.upstream.iab-ads", "IAB Tech Lab ads.txt and programmatic provenance", "IAB Tech Lab", "https://iabtechlab.com/ads.txt/", "Publisher inventory authorization and seller-chain transparency are separate from auction, exposure and conversion state."),
    ("source.upstream.acord-pc", "ACORD Property & Casualty Data Standards", "ACORD", "https://www-dev.acord.org/standards-architecture/acord-data-standards/Property_Casualty_Data_Standards", "Messages and transaction sequences support insurance processes but do not themselves become policy, coverage, claim or payment business state."),
    ("source.upstream.fix", "FIX Standards", "FIX Trading Community", "https://www.fixtrading.org/standards/", "FIX separates pre-trade, market-data, order/execution and post-trade messaging domains and identifiers."),
    ("source.upstream.isda-cdm", "ISDA Common Domain Model", "ISDA", "https://www.isda.org/2019/10/14/isda-common-domain-model/", "CDM represents financial-product, trade and lifecycle-event semantics independently of transport messages."),
    ("source.upstream.dcsa-track-trace", "DCSA Track & Trace Standard", "DCSA", "https://dcsa.org/standards/track-and-trace", "Container-shipping track/trace uses governed shipment, equipment and transport event identities across parties."),
    ("source.upstream.openrtb", "OpenRTB 2.x", "IAB Tech Lab", "https://github.com/InteractiveAdvertisingBureau/openrtb2.x", "OpenRTB represents auction requests, bids, wins and impression/fulfillment notifications without owning conversion or causal attribution."),
    ("source.upstream.quantconnect", "QuantConnect Research, Backtesting and Live Trading", "QuantConnect", "https://www.quantconnect.com/docs/v2/cloud-platform/backtesting/results", "The provider independently preserves backtest, optimization, paper and live result occurrences as different evidence states."),
    ("source.upstream.fed-stress", "Supervisory Stress Test Methodology", "U.S. Federal Reserve", "https://www.federalreserve.gov/supervisionreg/dfa-stress-tests.htm", "Supervisory stress testing binds scenarios, as-of submissions, methodology, projections, quality review and supervisory consequences."),
    ("source.upstream.isa-tab", "ISA Abstract Model", "ISA Tools", "https://isa-tools.org/format/specification.html", "ISA separates investigation, study and assay identities and preserves sample-to-assay experimental context."),
    ("source.upstream.ebi-biosamples", "BioSamples", "EMBL-EBI", "https://www.ebi.ac.uk/biosamples/docs/", "Research samples have accession, attributes, relationships, curation and release independently of downstream datasets."),
    ("source.upstream.ghg-protocol", "GHG Protocol Standards and Guidance", "GHG Protocol", "https://ghgprotocol.org/standards-guidance", "GHG inventory accounting owns organizational/operational boundaries and Scope 1, 2 and 3 accounting separately from disclosure filing."),
    ("source.upstream.ifrs-s2", "IFRS S2 Climate-related Disclosures", "IFRS Foundation", "https://www.ifrs.org/issued-standards/ifrs-sustainability-standards-navigator/ifrs-s2-climate-related-disclosures/", "Climate-risk, scenario and disclosure requirements are distinct from the underlying GHG inventory ledger."),
    ("source.upstream.aws-organizations", "AWS Organizations", "Amazon Web Services", "https://docs.aws.amazon.com/organizations/latest/userguide/orgs_introduction.html", "Organization, account hierarchy, policy attachment/inheritance and account lifecycle are first-class administrative state."),
    ("source.upstream.snowflake-org", "Organizations and accounts", "Snowflake", "https://docs.snowflake.com/en/user-guide/organizations", "Organizations, accounts, regions and administrative roles are independently persisted platform-estate state."),
    ("source.upstream.iso-14224", "ISO 14224:2016", "ISO", "https://www.iso.org/standard/64076.html", "Equipment, failure and maintenance data are separately classified for reliability and maintenance operations."),
    ("source.upstream.mimosa", "MIMOSA Open Standards", "MIMOSA", "https://www.mimosa.org/mimosa-standards/", "Asset registry, condition, maintenance and reliability information are exchanged through explicit operational semantics."),
    ("source.upstream.fda-capa", "Corrective and Preventive Actions", "U.S. FDA", "https://www.fda.gov/inspections-compliance-enforcement-and-criminal-investigations/inspection-guides/corrective-and-preventive-actions-capa", "CAPA governs investigation, cause, corrective action, implementation and effectiveness verification rather than merely recording quality metrics."),
    ("source.upstream.iso-31000", "ISO 31000 Risk management", "ISO", "https://www.iso.org/iso-31000-risk-management.html", "Risk management separates identification, analysis, evaluation, treatment, monitoring and communication."),
    ("source.upstream.nist-rmf", "NIST Risk Management Framework", "NIST", "https://csrc.nist.gov/projects/risk-management/about-rmf", "RMF separates control selection, implementation, assessment, authorization and monitoring."),
    ("source.upstream.worldcc", "Contract Management Lifecycle", "World Commerce & Contracting", "https://www.worldcc.com/Resources/Content-Hub/View/ArticleId/11461/Contract-Management-Standard", "Contract management spans creation, negotiation, approval, execution, obligation/performance, change, renewal and closeout lifecycles."),
    ("source.upstream.ocds", "Open Contracting Data Standard", "Open Contracting Partnership", "https://standard.open-contracting.org/latest/en/", "Public contracting distinguishes planning, tender, award, contract and implementation records and releases."),
]

DEMAND_SURFACES = [
    ("authoritative-declarations", ["regulatory_filing", "industry_message", "certificate", "submission_package", "plan_order_authorization"]),
    ("acquisition-artifacts", ["collection_plan", "instrument", "measurement_campaign", "observation", "sample", "media_signal_document", "telemetry_subscription"]),
    ("operated-state", ["case", "order_trade_claim_shipment", "experiment_campaign", "facility_asset", "engineering_model_twin"]),
    ("analytical-objects", ["question", "population_cohort", "feature_metric", "method_run", "result_uncertainty", "finding_comparison"]),
    ("decision-chain", ["finding", "proposal", "decision", "authorization", "effect", "receipt", "review_reversal"]),
    ("evidence-chain", ["source", "occurrence", "admitted_value", "derived_result", "assertion", "evidence", "verification", "appraisal"]),
    ("time-and-grain", ["identity", "occurrence", "valid_time", "observation_time", "processing_time", "publication_time", "revision_vintage", "as_of_cut"]),
    ("cross-organization-exchange", ["sender", "receiver", "authority", "contract", "schema_edition", "acknowledgement", "custody", "provenance", "exit"]),
]

UNIVERSAL_LAWS = [
    ("analytics-service-not-application-or-control", "analytics service != application logic != control effect", ["source.upstream.3gpp-nwdaf"]),
    ("observation-not-assertion", "observation != interpreted assertion", ["source.upstream.stix-2-1", "source.upstream.fhir-diagnostic"]),
    ("message-not-business-state", "process message != business aggregate state", ["source.upstream.acord-pc"]),
    ("source-not-evidence-production", "source document != collected evidence occurrence != processed review derivative != responsive assertion != production artifact", ["source.upstream.edrm-2"]),
    ("measurement-not-engineering-model", "measurement != well model != reservoir interpretation != simulation model != production observation", ["source.upstream.energistics"]),
    ("traceability-not-inventory", "master item != physical traceable instance != logistics event != custody != genealogy transformation != inventory position", ["source.upstream.gs1-traceability"]),
    ("test-not-laboratory-sample", "engineering test run != laboratory specimen lifecycle", ["source.upstream.asam-ods", "source.upstream.fhir-specimen"]),
    ("filing-not-report", "regulatory filing package != analytical report != submission attempt != regulator acknowledgement", ["source.upstream.sec-edgar"]),
    ("instrument-not-response", "collection instrument edition != deployment != response occurrence != admitted answer", ["source.upstream.odk"]),
    ("policy-not-provisioning", "access policy decision != entitlement issuance != provisioning effect != access-use receipt", ["source.upstream.semi-e190"]),
    ("project-plan-not-authorized-baseline", "planning alternative != authorized delivery baseline != progress observation != forecast-at-completion != approved change", ["source.upstream.iso-21508-2026", "source.upstream.primavera"]),
    ("inventory-not-ad-event", "publisher inventory != auction opportunity != bid != winning bid != impression != conversion", ["source.upstream.iab-ads"]),
    ("ad-auction-exposure-attribution", "advertising auction != impression or exposure != conversion event != attribution claim != causal effect", ["source.upstream.openrtb"]),
    ("evidence-discovery-stages", "preservation != collection != processing != review != production", ["source.upstream.edrm-2"]),
    ("quant-evidence-states", "research hypothesis != backtest != optimization study != paper deployment != live deployment", ["source.upstream.quantconnect"]),
    ("trade-lifecycle-chain", "market data != order != execution != trade lifecycle event != allocation != confirmation != settlement", ["source.upstream.fix", "source.upstream.isda-cdm"]),
    ("shipment-not-generic-event", "commercial order != fulfillment decomposition != physical shipment record != invoice != revenue posting", ["source.upstream.dcsa-track-trace"]),
    ("ghg-not-disclosure", "GHG inventory != metric != climate scenario analysis != disclosure filing", ["source.upstream.ghg-protocol", "source.upstream.ifrs-s2"]),
    ("condition-maintenance-chain", "condition signal != failure finding != maintenance strategy != authorized work order != executed maintenance receipt", ["source.upstream.iso-14224", "source.upstream.mimosa"]),
    ("quality-capa-chain", "inspection or laboratory result != nonconformance != investigation or cause != disposition != corrective action != effectiveness verification", ["source.upstream.fda-capa"]),
    ("risk-control-chain", "risk != metric != control != control test != treatment != acceptance or authorization", ["source.upstream.iso-31000", "source.upstream.nist-rmf"]),
    ("contract-obligation-chain", "document != agreement != obligation != amendment != implementation receipt", ["source.upstream.worldcc", "source.upstream.ocds"]),
]

BOUNDARY_HYPOTHESES = [
    ("project-portfolio-controls", "Project & Portfolio Controls", "PROMOTE_STRONG_HORIZONTAL_PRODUCT", "Owns authorized delivery baselines, schedule/cost/progress control, changes and performance evidence; remains separate from choosing future plans.", ["source.upstream.iso-21508-2026", "source.upstream.primavera"]),
    ("test-measurement-data-operations", "Test & Measurement Data Operations", "PROMOTE_PRESUMPTIVE_HORIZONTAL_PRODUCT", "Owns test-system configuration, unit under test, test plan/run, measurement channels, calibration context and evidence.", ["source.upstream.semi-e134", "source.upstream.asam-ods"]),
    ("regulatory-filing-submission-operations", "Regulatory Filing & Submission Operations", "PROMOTE_PRESUMPTIVE_HORIZONTAL_PRODUCT", "Owns filing packages, rule/taxonomy editions, validation, attempts, acknowledgements and correction/amendment.", ["source.upstream.sec-edgar"]),
    ("structured-collection-instrument-operations", "Structured Data Collection & Instrument Operations", "PROMOTE_PRESUMPTIVE_HORIZONTAL_PRODUCT", "Owns instrument/question editions, control flow, deployment, response occurrences, audit, validation and offline synchronization.", ["source.upstream.odk"]),
    ("laboratory-sample-operations", "Laboratory Sample Operations", "PROMOTE_PRESUMPTIVE_SEPARATE_PRODUCT", "Owns specimen/sample identity, collection, custody, preparation, analytical method binding, result review and release; imports measurement libraries.", ["source.upstream.fhir-specimen", "source.upstream.fhir-diagnostic"]),
    ("engineering-model-digital-twin-operations", "Engineering Model & Digital Twin Operations", "DO_NOT_PROMOTE_YET_EXTRACT_CONFIGURATION_VERSION_CHANGE_CONTRACTS", "Edition, configuration, baseline, variant and change semantics recur, but carriers and operated jobs differ across systems, product definition, BIM and reservoir models.", ["source.upstream.energistics"]),
    ("traceability-genealogy-operations", "Traceability & Genealogy Operations", "PROMOTE_PRESUMPTIVE_HORIZONTAL_PRODUCT", "Owns traceable-object occurrences, custody/event history, transformations, genealogy corrections and cross-party trace evidence; not ETA analytics.", ["source.upstream.gs1-traceability"]),
    ("data-access-entitlement-provisioning", "Data Access Entitlement & Provisioning", "SPLIT_FROM_POLICY_RESEARCH_REQUIRED", "Data-use policy decides; a separate lifecycle may issue/revoke entitlements and execute provisioning with receipts.", ["source.upstream.semi-e190"]),
    ("analytics-subscription-delivery", "Analytics Subscription & Delivery", "RETAIN_AS_EXACT_LIBRARY_SEAM_NOT_PRODUCT", "NWDAF supports a reusable request/subscription/delivery/feedback contract but not yet a separately adopted product lifecycle.", ["source.upstream.3gpp-nwdaf"]),
    ("ediscovery", "eDiscovery", "REHOME_INTO_EXISTING_PRODUCT_GRAPH", "Use the evidence-production lifecycle to deepen Case Investigation, Assurance, Document Review and Dataset Curation rather than make a legal-industry product horizontal.", ["source.upstream.edrm-2"]),
    ("stress-resilience-analysis", "Stress & Resilience Analysis Operations", "CONTINUE_CROSS_VERTICAL_FALSIFICATION", "A governed scenario/as-of/method/run/QA/review/action cycle exceeds simulation, but finance, cyber, continuity and supply-chain replacement tests remain required.", ["source.upstream.fed-stress"]),
    ("research-study-assay-data-operations", "Research Study & Assay Data Operations", "PROMOTE_PRESUMPTIVE_HORIZONTAL_PRODUCT", "Owns investigation/study/assay design, subject/sample context and sample-to-assay provenance while downstream datasets remain separate artifacts.", ["source.upstream.isa-tab", "source.upstream.ebi-biosamples"]),
    ("pricing-revenue-management", "Pricing & Revenue Management Operations", "PROMOTE_STRONG_HORIZONTAL_PRODUCT", "Owns guardrails, contextual input cuts, recommendations, override/approval, effective offer publication, realized outcomes and evaluation above forecast and optimization methods.", ["source.upstream.openrtb"]),
    ("sustainability-accounting-disclosure", "Sustainability Accounting & Disclosure Operations", "PROMOTE_PRESUMPTIVE_HORIZONTAL_PRODUCT", "Owns assurance-grade inventory/accounting and disclosure assembly while jurisdictional vocabulary, scenario analysis and regulatory filing remain separate.", ["source.upstream.ghg-protocol", "source.upstream.ifrs-s2"]),
    ("platform-estate-tenancy-administration", "Platform Estate & Tenancy Administration", "PROMOTE_STRONG_HORIZONTAL_PRODUCT", "Owns organization/account/workspace/project hierarchy, region/capacity bindings, policy inheritance, admin delegation and suspension/deletion/recovery state.", ["source.upstream.aws-organizations", "source.upstream.snowflake-org"]),
    ("asset-reliability-maintenance", "Asset Reliability & Maintenance Operations", "PROMOTE_STRONG_HORIZONTAL_PRODUCT", "Owns asset/failure/maintenance strategies, plans, work orders, execution and reliability evidence while condition analytics remains a supplier.", ["source.upstream.iso-14224", "source.upstream.mimosa"]),
    ("nonconformance-corrective-action", "Nonconformance & Corrective Action Operations", "PROMOTE_STRONG_HORIZONTAL_PRODUCT", "Owns deviation/nonconformance, investigation, disposition, CAPA, implementation, effectiveness verification and closure authority without absorbing Data Quality Operations.", ["source.upstream.fda-capa"]),
    ("enterprise-risk-control", "Enterprise Risk & Control Operations", "PROMOTE_STRONG_PROVISIONAL_HORIZONTAL_PRODUCT", "Owns risk registers, controls, assessments, treatments, residual risk, acceptance/authorization and monitoring while assurance remains independent.", ["source.upstream.iso-31000", "source.upstream.nist-rmf"]),
    ("contract-obligation-lifecycle", "Contract & Obligation Lifecycle Operations", "PROMOTE_STRONG_HORIZONTAL_PRODUCT", "Owns agreement formation, effective editions, obligations, milestones, amendment, renewal and implementation receipts; procurement vocabulary stays in packs.", ["source.upstream.worldcc", "source.upstream.ocds"]),
    ("quant-strategy-research", "Quant Strategy Research", "RETAIN_AS_FINANCE_SOLUTION_PACK", "Compose Notebook, Simulation, Experimentation, Optimization and trading contracts while preserving research/backtest/paper/live evidence states.", ["source.upstream.quantconnect", "source.upstream.fix"]),
]

CONTRACTS = [
    "acquisition-plan", "acquisition-run-attempt", "acquisition-output", "acquisition-termination-refusal",
    "analytics-subscription", "analytics-delivery", "analytics-feedback", "analytics-accuracy-assessment",
    "filing-package", "filing-rule-taxonomy-edition", "filing-validation", "submission-attempt", "regulator-acknowledgement", "filing-correction-amendment",
    "instrument-definition-edition", "instrument-deployment", "response-occurrence", "response-audit", "offline-sync-reconciliation",
    "test-system-configuration", "unit-or-specimen-under-test", "test-plan", "test-run", "measurement-channel-result", "calibration-context", "test-evidence-publication",
    "specimen-identity", "specimen-collection-custody", "specimen-processing", "analytical-method-binding", "laboratory-result-release",
    "preservation-directive", "collected-evidence-occurrence", "processing-derivation", "review-coding", "privilege-assertion", "production-set", "redaction-decision", "production-receipt",
    "traceable-object-occurrence", "critical-tracking-event", "genealogy-transformation", "custody-transfer", "trace-correction",
    "access-entitlement", "entitlement-revocation", "provisioning-effect", "access-use-receipt",
    "authorized-delivery-baseline", "progress-status-cut", "project-change-request", "forecast-at-completion", "earned-value-assessment",
    "transaction-lifecycle", "instrument-reference", "market-data-occurrence", "order-lifecycle", "execution-occurrence", "trade-lifecycle-event", "allocation", "position", "valuation", "margin-collateral", "confirmation-state", "settlement-state",
    "physical-logistics-record", "shipment-record", "transport-event", "custody-handoff", "domain-operational-measurement",
    "auction-opportunity", "bid-occurrence", "impression-exposure", "conversion-event", "attribution-claim", "incremental-effect-estimate",
    "research-hypothesis", "backtest-occurrence", "optimization-study", "paper-deployment", "live-deployment",
    "stress-scenario-edition", "stress-subject-as-of-cut", "stress-methodology-edition", "stress-run", "stress-quality-review", "resilience-action",
    "investigation-study-assay", "experimental-design", "research-sample-accession", "sample-assay-provenance", "research-object-release",
    "price-policy-guardrail", "price-recommendation", "price-override", "effective-offer-publication", "realized-price-outcome",
    "engineering-configuration", "engineering-baseline", "engineering-variant", "engineering-change",
    "ghg-inventory-boundary", "emissions-activity", "emissions-factor-edition", "ghg-accounting-entry", "climate-disclosure-package",
    "tenant-hierarchy", "account-workspace-lifecycle", "policy-inheritance", "administrative-delegation", "estate-recovery",
    "asset-failure-occurrence", "maintenance-strategy", "maintenance-plan", "maintenance-work-order", "maintenance-execution-receipt", "reliability-assessment",
    "nonconformance-case", "investigation-cause", "disposition-decision", "corrective-preventive-action", "effectiveness-verification",
    "risk-register-entry", "control-definition", "control-test", "risk-treatment", "residual-risk", "risk-acceptance-authorization",
    "agreement-edition", "contract-obligation", "contract-milestone", "contract-amendment", "contract-renewal", "obligation-performance-receipt",
    "extreme-value-method", "compositional-statistics", "directional-statistics", "bayesian-optimization", "inverse-problem", "audio-speech-analysis", "chemometrics-spectroscopy", "discrete-event-simulation", "value-at-risk-expected-shortfall", "marketing-mix-model", "uplift-model", "difference-in-differences", "instrumental-variable", "small-area-estimation",
]

VERTICAL_PACKS = [
    ("ad-tech", ["auction_request", "bid", "deal", "seller_authorization", "impression", "exposure", "conversion", "attribution_claim", "incremental_effect_estimate", "activation_receipt"]),
    ("insurance", ["policy", "exposure_unit", "insured_object", "peril", "coverage", "claim", "claim_feature", "reserve_development", "catastrophe_event", "payment", "jurisdiction"]),
    ("genomics-clinical", ["phenotype_case", "variant_representation", "repository_access", "workflow_execution", "data_use_authorization", "qc_metric"]),
    ("semiconductor", ["equipment_control", "equipment_data_acquisition", "collection_plan", "equipment_data_entitlement"]),
    ("oil-gas", ["well_drilling_measurement", "earth_reservoir_model", "simulation_model", "production_observation", "transfer_protocol"]),
    ("capital-markets", ["instrument_reference", "market_data", "order", "execution", "trade", "allocation", "position", "valuation", "margin_collateral", "confirmation", "settlement"]),
    ("logistics-shipping", ["commercial_order", "fulfillment_line", "shipment_record", "equipment_event", "transport_event", "custody_handoff", "invoice", "revenue_posting"]),
    ("quant-investment", ["research_hypothesis", "backtest", "optimization_study", "paper_deployment", "live_deployment", "position", "risk", "performance_attribution"]),
    ("scientific-research", ["investigation", "study", "assay", "sample_accession", "experimental_design", "measurement_run", "research_object", "dataset_release"]),
    ("sustainability", ["organizational_boundary", "operational_boundary", "scope_1_2_3_inventory", "climate_scenario", "assurance", "disclosure_filing"]),
    ("finance-accounting", ["business_transaction", "subledger_event", "journal_entry", "posted_balance", "reconciliation_item", "closed_period_statement"]),
    ("procurement", ["supplier_profile", "qualification", "sourcing_eligibility", "purchase_order", "receipt", "supplier_invoice", "posting", "payment"]),
    ("asset-intensive-operations", ["asset_registry", "condition_signal", "failure_finding", "maintenance_strategy", "work_order", "execution_receipt", "reliability_assessment"]),
]
