#!/usr/bin/env python3
"""Build reusable human-work, review, agreement, consensus and adjudication contracts."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
AS_OF = "2026-08-26"


def render(rows: list[dict]) -> str:
    return "\n".join(json.dumps(r, sort_keys=True, separators=(",", ":"), ensure_ascii=False) for r in rows) + "\n"


def s(key: str, title: str, authority: str, url: str, supports: str, limit: str) -> dict:
    return {"source_id": f"source.hwra.{key}", "title": title, "authority": authority, "url": url,
            "retrieved": AS_OF, "source_kind": "primary_or_official", "supports": supports,
            "does_not_prove": limit}


SOURCES = [
    s("oasis.humantask", "WS-HumanTask 1.1", "OASIS", "https://docs.oasis-open.org/bpel4people/ws-humantask-1.1-spec-cs-01.html", "human-task definitions distinguish potential/actual owners, excluded owners, stakeholders, administrators, nomination, claim, delegation, release, deadlines, escalation and terminal states", "A service-oriented human-task model does not define annotation meaning or worker competence."),
    s("oasis.bpel4people", "WS-BPEL Extension for People 1.1", "OASIS", "https://docs.oasis-open.org/bpel4people/bpel4people-1.1-spec-cs-01.html", "people activities, task coordination and process integration are separate contracts", "Process integration does not establish task outcome truth."),
    s("omg.cmmn", "Case Management Model and Notation 1.1", "Object Management Group", "https://www.omg.org/spec/CMMN/1.1/About-CMMN", "cases, case-file items, human tasks, discretionary planning, sentries, milestones and lifecycle are editioned constructs", "CMMN is not a universal review-issue ontology."),
    s("omg.bpmn", "Business Process Model and Notation 2.0.2", "Object Management Group", "https://www.omg.org/spec/BPMN/2.0.2/PDF", "user tasks, activities, boundary events and escalation occur within explicit process semantics", "A BPMN user task does not prove assignment authority or competence."),
    s("omg.dmn", "Decision Model and Notation 1.5", "Object Management Group", "https://www.omg.org/spec/DMN/1.5/About-DMN", "decision rules and hit policies make overlap, priority, order and collection explicit", "DMN evaluation does not issue human adjudication authority."),
    s("w3c.prov", "PROV-O", "W3C", "https://www.w3.org/TR/prov-o/", "agents, activities, entities, plans, attribution, association, derivation, revision, invalidation and delegation are distinct", "Provenance does not prove competence, agreement or correctness."),
    s("w3c.prov.constraints", "PROV Constraints", "W3C", "https://www.w3.org/TR/prov-constraints/", "generation, usage, invalidation, derivation and association obey identity and ordering constraints", "PROV constraints do not define review precedence."),
    s("w3c.activitystreams", "Activity Streams 2.0", "W3C", "https://www.w3.org/TR/activitystreams-vocabulary/", "create, update, delete, accept, reject, offer, assign and resolve-like activities can retain actor/object/target identity", "Activity vocabulary is not a complete task or issue state machine."),
    s("ietf.jsonpatch", "JSON Patch", "IETF", "https://www.rfc-editor.org/rfc/rfc6902", "ordered changes and test preconditions provide an explicit structural correction representation", "A structural patch does not prove semantic correction or authority."),
    s("cvat.review", "Review mode", "CVAT", "https://docs.cvat.ai/docs/manual/advanced/review/", "review findings are anchored to annotation work and corrected through an attributable workflow", "CVAT workflow does not define a universal issue lifecycle."),
    s("cvat.consensus", "Consensus-based annotation", "CVAT", "https://docs.cvat.ai/docs/qa-analytics/consensus/", "independent replicas, merging, per-result scores, overwrite hazards and post-merge review are separate stages", "A merged result or score is not accepted ground truth."),
    s("cvat.autoqa", "Automated QA and ground-truth jobs", "CVAT", "https://docs.cvat.ai/docs/manual/advanced/analytics-and-monitoring/auto-qa/", "comparison against a reference job produces conflicts and quality evidence for review", "A reference job does not become universally correct by configuration."),
    s("cvat.analytics", "Analytics and monitoring", "CVAT", "https://docs.cvat.ai/docs/manual/advanced/analytics-and-monitoring/", "work duration, job state and quality observations are different operational evidence", "Productivity telemetry does not prove annotation correctness."),
    s("labelstudio.agreement", "Agreement and consensus", "Label Studio", "https://labelstud.io/guide/stats.html", "agreement depends on overlap, label configuration and selected matching/comparison semantics", "A displayed agreement percentage is not method-independent truth."),
    s("labelstudio.quality", "Annotation quality and review", "Label Studio", "https://labelstud.io/guide/quality", "review, agreement, consensus and ground-truth workflows have distinct roles", "One product workflow does not qualify a reusable implementation."),
    s("cohen.kappa", "A Coefficient of Agreement for Nominal Scales", "Jacob Cohen", "https://doi.org/10.1177/001316446002000104", "chance-corrected agreement for two raters on nominal scales requires a specified population and marginal model", "Cohen kappa is not applicable to every scale, rater design or missingness pattern."),
    s("cohen.weighted", "Weighted kappa", "Jacob Cohen", "https://doi.org/10.1037/h0026256", "partial disagreement weights change the meaning of agreement for ordered categories", "Weights are not universal or authority-free defaults."),
    s("fleiss.kappa", "Measuring nominal scale agreement among many raters", "Joseph Fleiss", "https://doi.org/10.1037/h0031619", "multi-rater nominal agreement has a distinct sampling and marginal model", "Fleiss kappa is not interchangeable with Cohen kappa or consensus."),
    s("krippendorff.alpha", "Computing Krippendorff's Alpha-Reliability", "Klaus Krippendorff", "https://repository.upenn.edu/entities/publication/cd5c0360-6d25-4c28-b458-944dd1984076", "agreement can support variable coders, missing values and declared distance functions", "Alpha does not choose the correct distance, unitization or acceptance threshold."),
    s("icc.shroutfleiss", "Intraclass correlations: uses in assessing rater reliability", "Shrout and Fleiss", "https://doi.org/10.1037/0033-2909.86.2.420", "continuous-rating reliability depends on the named ICC model, effects and unit of analysis", "An ICC number without its model is uninterpretable."),
    s("dawid.skene", "Maximum likelihood estimation of observer error-rates", "Dawid and Skene", "https://doi.org/10.2307/2346806", "latent-class aggregation can estimate observer error and a candidate latent result under explicit probabilistic assumptions", "A latent estimate is not adjudication or ground truth."),
    s("snorkel.labelmodel", "Snorkel: rapid training data creation with weak supervision", "Ratner et al.", "https://doi.org/10.14778/3157794.3157797", "probabilistic source-accuracy/dependency modeling is a selectable aggregation method", "Weak supervision does not eliminate review, authority or validation."),
    s("iso.5725", "ISO 5725-1:2023 Accuracy of measurement methods and results", "ISO", "https://www.iso.org/standard/69418.html", "agreement, repeatability and reproducibility are scoped to stipulated conditions", "Measurement-method agreement is not automatically annotation reliability."),
    s("iso.19011", "ISO 19011:2018 auditing management systems", "ISO", "https://www.iso.org/standard/70017.html", "audit evidence, findings, conclusions, competence and independence are distinct", "Audit guidance does not define annotation consensus mathematics."),
    s("nist.ai.rmf", "AI Risk Management Framework 1.0", "NIST", "https://nvlpubs.nist.gov/nistpubs/ai/NIST.AI.100-1.pdf", "human oversight roles, measurement limits, documentation and contestability must be explicit", "A risk framework does not supply product-specific acceptance authority."),
]

CONTEXTS = [
    {"context_id": "context.human_work.task_definition", "name": "Human Work Definition", "sovereign_question": "Which immutable work definition states the task, inputs, outputs, roles, competence, segregation, completion, deadline, disclosure and evidence requirements?", "inside": ["task definition identity", "work subject and scope", "input/output contracts", "potential roles", "competence requirements", "segregation and blinding", "deadlines", "completion policy", "canonical digest"], "outside": ["person identity", "credential issuance", "actual assignment", "work execution", "outcome acceptance"], "owner": "authority.human_work.task_definition", "status": "specified_candidate"},
    {"context_id": "context.human_work.assignment", "name": "Human Work Assignment", "sovereign_question": "Which authorized and competent actor may claim or receive one task under a finite lease, and how are delegation, release, suspension, escalation and late completion reconciled?", "inside": ["assignment identity", "potential and actual owner", "eligibility evidence", "claim/assign", "lease/fence", "delegation", "release", "suspension", "deadline/escalation proposals", "completion receipt reconciliation"], "outside": ["identity authority", "qualification issuance", "physical notification", "work result meaning", "result acceptance"], "owner": "authority.human_work.assignment", "status": "specified_candidate"},
    {"context_id": "context.review.issue", "name": "Evidence-Anchored Review Issue", "sovereign_question": "How is one review finding anchored, classified, discussed, corrected, verified, resolved, reopened and closed without erasing the challenged artifact or dissent?", "inside": ["issue identity", "subject and anchor", "finding and severity", "claim/evidence", "discussion", "correction refs", "verification", "resolution", "reopen", "closure"], "outside": ["artifact mutation", "business acceptance", "work assignment mechanics", "agreement computation", "adjudication authority"], "owner": "authority.review.issue", "status": "specified_candidate"},
    {"context_id": "context.review.agreement", "name": "Agreement and Reliability Measurement", "sovereign_question": "Under one exact rater design, population, measurement scale, matching, missingness, weighting and sampling policy, what agreement or reliability evidence can be computed?", "inside": ["study design", "rater and unit cuts", "independence/blinding evidence", "matching/alignment", "scale and distance", "metric applicability", "estimate", "uncertainty", "residual", "diagnostics"], "outside": ["consensus derivation", "adjudication", "ground truth", "worker qualification", "acceptance threshold authority"], "owner": "authority.review.agreement", "status": "specified_candidate"},
    {"context_id": "context.review.consensus", "name": "Consensus Derivation", "sovereign_question": "Given eligible independent judgments and one accepted rule, what consensus candidate, tie, abstention, dissent or unresolved result follows without claiming truth?", "inside": ["rule edition", "eligible judgment cut", "vote/value alignment", "weights", "quorum", "threshold", "tie and abstention", "method binding", "consensus candidate", "dissent and residual"], "outside": ["agreement measurement", "human adjudication", "ground-truth acceptance", "worker assignment", "source correction"], "owner": "authority.review.consensus", "status": "specified_candidate"},
    {"context_id": "context.review.adjudication", "name": "Review Adjudication", "sovereign_question": "Which authorized judgment occurrence resolves or preserves a scoped conflict using an exact evidence cut, precedence law, reasons, defeaters and appeal path?", "inside": ["case and conflict identity", "adjudicator authority", "evidence cut", "precedence", "judgment", "reasons", "dissent", "defeaters", "appeal/reopen", "decision ledger event"], "outside": ["authority issuance", "consensus computation", "ground-truth edition release", "artifact mutation", "business effect"], "owner": "authority.review.adjudication", "status": "specified_candidate"},
]

DECISIONS = {
    "task_definition": ["task_family_identity", "task_edition_identity", "work_subject_ref", "input_contract", "output_contract", "potential_owner_roles", "excluded_owner_roles", "administrator_and_stakeholder_roles", "competence_requirements", "segregation_of_duties", "blinding_and_information_access", "instructions_and_policy_refs", "completion_condition", "start_deadline", "completion_deadline", "calendar_and_clock", "escalation_rules", "delegation_constraints", "privacy_and_disclosure", "evidence_requirements", "resource_budget", "definition_digest"],
    "assignment": ["assignment_identity", "task_occurrence_ref", "candidate_actor_cut", "eligibility_and_competence_evidence", "authority_scope", "potential_owner_selection", "claim_or_direct_assignment", "actual_owner_uniqueness", "overlap_and_replication", "lease_duration", "fencing_token", "heartbeat_or_renewal", "delegation", "forwarding", "release", "suspend_resume", "skip_or_cancel", "start_and_completion_time", "deadline_evaluation", "escalation_action", "late_submission", "idempotency_scope", "unknown_completion", "assignment_digest"],
    "issue": ["issue_identity", "review_case_ref", "challenged_artifact_ref", "anchor_and_revision", "finding_type", "severity_and_priority", "reporter_identity", "claim_and_evidence", "comments_and_replies", "assignee_ref", "state_machine", "correction_proposal_ref", "correction_occurrence_ref", "verification_evidence", "resolution_code", "resolution_reason", "duplicate_relation", "reopen_policy", "closure_authority", "retention_and_disclosure", "issue_digest"],
    "agreement": ["study_identity", "measurement_question", "unit_of_analysis", "population_cut", "rater_cut", "rater_design", "independence_and_blinding", "judgment_edition", "scale_type", "category_or_value_alignment", "object_matching", "distance_or_disagreement_function", "weights", "missingness", "abstention", "chance_model", "metric_family", "applicability_preconditions", "sampling_design", "uncertainty_method", "confidence_level", "stratification", "minimum_information", "degenerate_case", "multiple_comparison", "estimate_digest"],
    "consensus_rule": ["rule_identity", "rule_edition", "eligible_judgment_contract", "population_and_subject_cut", "eligibility_evidence", "independence_requirement", "vote_or_value_alignment", "duplicate_judgment_policy", "weight_source", "weight_normalization", "quorum", "threshold", "majority_plurality_unanimity", "priority_and_precedence", "tie_policy", "abstention_and_missing", "veto_or_dissent", "probabilistic_method_ref", "method_parameters", "uncertainty_and_abstain", "default_refusal", "rule_digest"],
    "consensus_eval": ["accepted_rule_ref", "eligible_judgment_cut", "input_order", "alignment_result", "excluded_judgment_evidence", "realized_quorum", "realized_weights", "method_binding", "randomness_if_any", "candidate_identity", "confidence_or_score", "tie_state", "dissent_preservation", "residual", "evaluation_budget", "receipt_digest"],
    "adjudication": ["adjudication_case_identity", "conflict_identity", "adjudicator_identity", "authority_and_independence_evidence", "segregation_of_duties", "evidence_cut", "admissibility", "precedence_law", "burden_and_standard", "consensus_and_metric_evidence_role", "defeaters", "judgment_options", "abstain_recuse_escalate", "reason_requirement", "dissent_preservation", "appeal_and_reopen", "effective_time", "supersession", "ledger_event", "adjudication_digest"],
}
CONTEXT = {"task_definition": CONTEXTS[0]["context_id"], "assignment": CONTEXTS[1]["context_id"], "issue": CONTEXTS[2]["context_id"], "agreement": CONTEXTS[3]["context_id"], "consensus_rule": CONTEXTS[4]["context_id"], "consensus_eval": CONTEXTS[4]["context_id"], "adjudication": CONTEXTS[5]["context_id"]}
DECISION_ROWS = [{"decision_id": f"decision.hwra.{owner}.{name}", "owner_context": CONTEXT[owner], "question": f"What exact {name.replace('_', ' ')} applies?", "default": None, "default_law": "forbidden", "binding_phase": "intent_or_compile_time", "status": "declared"} for owner, names in DECISIONS.items() for name in names]


def op(owner: str, name: str, inputs: list[str], output: str) -> dict:
    return {"operation_ref": f"operation.hwra.{owner}.{name}", "input_types": inputs, "output_type": f"Result<{output},HumanWorkReviewRefusal>", "purity": "pure"}


OPS = {
    "task_definition": [op("task_definition", "validate_task_declaration", ["HumanTaskDeclaration", "TaskDefinitionPolicy"], "ValidatedHumanTaskDeclaration"), op("task_definition", "compile_role_and_competence_requirements", ["ValidatedHumanTaskDeclaration", "RoleCompetencePolicy"], "TaskRoleRequirements"), op("task_definition", "compile_completion_and_deadline_contract", ["ValidatedHumanTaskDeclaration", "CalendarCut", "DeadlinePolicy"], "TaskCompletionDeadlineContract"), op("task_definition", "compile_disclosure_and_evidence_contract", ["ValidatedHumanTaskDeclaration", "DisclosureEvidencePolicy"], "TaskDisclosureEvidenceContract"), op("task_definition", "compile_human_task_definition", ["ValidatedHumanTaskDeclaration", "TaskRoleRequirements", "TaskCompletionDeadlineContract", "TaskDisclosureEvidenceContract"], "HumanTaskDefinition"), op("task_definition", "compare_task_definitions", ["HumanTaskDefinition", "HumanTaskDefinition"], "TaskDefinitionSemanticDiff"), op("task_definition", "explain_task_definition", ["HumanTaskDefinition", "ExplanationScope", "ResourceBudget"], "TaskDefinitionExplanation")],
    "assignment": [op("assignment", "derive_eligible_candidates", ["HumanTaskDefinition", "CandidateActorCut", "EligibilityEvidenceCut", "AssignmentPolicy"], "EligibleCandidateSet"), op("assignment", "validate_assignment_command", ["AssignmentRevision", "AssignmentCommand", "EligibleCandidateSet", "AssignmentPolicy"], "ValidatedAssignmentCommand"), op("assignment", "reduce_assignment_command", ["AssignmentRevision", "ValidatedAssignmentCommand"], "AssignmentTransition"), op("assignment", "evaluate_assignment_deadlines", ["AssignmentRevision", "ClockCut", "CalendarCut", "DeadlinePolicy"], "DeadlineEvaluation"), op("assignment", "compile_escalation_intents", ["DeadlineEvaluation", "EscalationPolicy"], "EscalationIntentSet"), op("assignment", "classify_completion_receipt", ["AssignmentRevision", "WorkSubmissionReceipt", "CompletionPolicy"], "SubmissionClassification"), op("assignment", "reconcile_assignment_state", ["AssignmentRevision", "ObservedWorkStateCut", "AssignmentReconciliationPolicy"], "AssignmentReconciliation"), op("assignment", "explain_assignment", ["AssignmentRevision", "ExplanationScope", "ResourceBudget"], "AssignmentExplanation")],
    "issue": [op("issue", "validate_review_finding", ["ReviewFinding", "ReviewIssuePolicy"], "ValidatedReviewFinding"), op("issue", "open_review_issue", ["ValidatedReviewFinding", "ReviewCaseRef"], "ReviewIssueRevision"), op("issue", "validate_issue_command", ["ReviewIssueRevision", "ReviewIssueCommand", "ReviewIssuePolicy"], "ValidatedReviewIssueCommand"), op("issue", "reduce_issue_command", ["ReviewIssueRevision", "ValidatedReviewIssueCommand"], "ReviewIssueTransition"), op("issue", "bind_correction_and_verification", ["ReviewIssueRevision", "CorrectionEvidence", "VerificationEvidence", "CorrectionVerificationPolicy"], "IssueResolutionEvidence"), op("issue", "evaluate_issue_resolution", ["ReviewIssueRevision", "IssueResolutionEvidence", "ResolutionPolicy"], "IssueResolutionDecision"), op("issue", "compare_issue_revisions", ["ReviewIssueRevision", "ReviewIssueRevision"], "IssueSemanticDiff"), op("issue", "explain_review_issue", ["ReviewIssueRevision", "ExplanationScope", "ResourceBudget"], "ReviewIssueExplanation")],
    "agreement": [op("agreement", "validate_agreement_study", ["AgreementStudyDeclaration", "AgreementPolicy"], "ValidatedAgreementStudy"), op("agreement", "align_judgment_units", ["ValidatedAgreementStudy", "JudgmentOccurrenceCut", "AlignmentPolicy"], "AlignedJudgmentMatrix"), op("agreement", "evaluate_metric_applicability", ["ValidatedAgreementStudy", "AlignedJudgmentMatrix", "AgreementMetricContract"], "MetricApplicability"), op("agreement", "evaluate_agreement_metric", ["MetricApplicability", "AlignedJudgmentMatrix", "AgreementMetricAlgebra", "ResourceBudget"], "AgreementEstimate"), op("agreement", "estimate_agreement_uncertainty", ["AgreementEstimate", "AlignedJudgmentMatrix", "UncertaintyPolicy"], "AgreementUncertainty"), op("agreement", "stratify_agreement", ["AlignedJudgmentMatrix", "StratificationPolicy", "AgreementMetricAlgebra"], "StratifiedAgreementSet"), op("agreement", "compare_agreement_estimates", ["AgreementEstimate", "AgreementEstimate", "ComparisonPolicy"], "AgreementComparison"), op("agreement", "explain_agreement_evidence", ["AgreementEstimate", "AgreementUncertainty", "ExplanationScope"], "AgreementEvidenceExplanation")],
    "consensus_rule": [op("consensus_rule", "validate_consensus_rule", ["ConsensusRuleDeclaration", "ConsensusRulePolicy"], "ValidatedConsensusRule"), op("consensus_rule", "compile_eligibility_and_alignment", ["ValidatedConsensusRule", "JudgmentContractCut"], "ConsensusEligibilityAlignmentContract"), op("consensus_rule", "compile_quorum_weight_and_tie", ["ValidatedConsensusRule", "ConsensusCombinationPolicy"], "ConsensusCombinationContract"), op("consensus_rule", "bind_consensus_method", ["ValidatedConsensusRule", "ConsensusMethodContract", "MethodBindingPolicy"], "BoundConsensusMethod"), op("consensus_rule", "compile_consensus_rule", ["ValidatedConsensusRule", "ConsensusEligibilityAlignmentContract", "ConsensusCombinationContract", "BoundConsensusMethod"], "AcceptedConsensusRule"), op("consensus_rule", "compare_consensus_rules", ["AcceptedConsensusRule", "AcceptedConsensusRule"], "ConsensusRuleSemanticDiff"), op("consensus_rule", "explain_consensus_rule", ["AcceptedConsensusRule", "ExplanationScope", "ResourceBudget"], "ConsensusRuleExplanation")],
    "consensus_eval": [op("consensus_eval", "validate_consensus_input_cut", ["AcceptedConsensusRule", "JudgmentOccurrenceCut"], "ValidatedConsensusInput"), op("consensus_eval", "align_eligible_judgments", ["ValidatedConsensusInput", "ConsensusEligibilityAlignmentContract"], "AlignedEligibleJudgments"), op("consensus_eval", "evaluate_quorum_and_weights", ["AlignedEligibleJudgments", "ConsensusCombinationContract"], "RealizedConsensusInputs"), op("consensus_eval", "evaluate_consensus", ["RealizedConsensusInputs", "BoundConsensusMethod", "ConsensusEvaluationBudget"], "ConsensusCandidate"), op("consensus_eval", "preserve_dissent_and_residual", ["ConsensusCandidate", "AlignedEligibleJudgments", "ResidualPolicy"], "ConsensusResult"), op("consensus_eval", "compare_consensus_results", ["ConsensusResult", "ConsensusResult", "ConsensusEquivalencePolicy"], "ConsensusComparison"), op("consensus_eval", "explain_consensus_result", ["ConsensusResult", "ExplanationScope", "ResourceBudget"], "ConsensusExplanation")],
    "adjudication": [op("adjudication", "validate_adjudication_request", ["AdjudicationRequest", "AdjudicationPolicy"], "ValidatedAdjudicationRequest"), op("adjudication", "validate_adjudicator_authority", ["ValidatedAdjudicationRequest", "AuthorityEvidenceCut", "IndependencePolicy"], "AuthorizedAdjudicationRequest"), op("adjudication", "construct_admissible_evidence_cut", ["AuthorizedAdjudicationRequest", "CandidateEvidenceSet", "AdmissibilityPolicy"], "AdmissibleEvidenceCut"), op("adjudication", "evaluate_precedence_and_defeaters", ["AdmissibleEvidenceCut", "PrecedencePolicy"], "AdjudicationEvidenceAssessment"), op("adjudication", "validate_adjudication_judgment", ["AdjudicationEvidenceAssessment", "ProposedJudgment", "JudgmentPolicy"], "ValidatedAdjudicationJudgment"), op("adjudication", "reduce_adjudication", ["AdjudicationCaseRevision", "ValidatedAdjudicationJudgment"], "AdjudicationTransition"), op("adjudication", "plan_appeal_or_reopen", ["AdjudicationTransition", "ChallengeEvidence", "AppealPolicy"], "AdjudicationChallengePlan"), op("adjudication", "explain_adjudication", ["AdjudicationTransition", "ExplanationScope", "ResourceBudget"], "AdjudicationExplanation")],
}

SHARED_LAWS = [
    "Task definition, task occurrence, assignment, lease, work attempt, submission, review issue, agreement estimate, consensus candidate, adjudication judgment and accepted artifact edition are distinct identities.",
    "Potential owner, actual owner, performer, reviewer, adjudicator, approver and acceptance authority are distinct roles.",
    "Assignment validates externally issued identity, competence and authority evidence but never issues them.",
    "Completion of human work proves only a scoped submission occurrence; it does not prove correctness, review, consensus, adjudication or acceptance.",
    "Agreement is metric-, population-, scale-, matching-, missingness- and design-specific evidence, never universal truth.",
    "Consensus is the result of a declared combination rule; it neither erases dissent nor becomes adjudication or ground truth by arithmetic.",
    "Adjudication is an attributable scoped judgment under external authority and retained reasons, defeaters and appeal; it is not a metric.",
    "A correction, resolution, closure, consensus, adjudication, acceptance and recall are different occurrences and none erases prior evidence.",
    "Models and agents may propose assignments, findings, alignments, metrics, consensus candidates or reasons but cannot issue competence, waive conflicts, adjudicate, accept truth or authorize effects.",
]

TYPES = {
    "task_definition": ["HumanTaskDefinitionId", "HumanTaskDefinitionEdition", "HumanTaskDeclaration", "HumanTaskDefinition", "TaskRoleRequirements", "CompetenceRequirement", "SegregationRule", "TaskCompletionDeadlineContract", "TaskDisclosureEvidenceContract", "TaskDefinitionRefusal"],
    "assignment": ["AssignmentId", "AssignmentRevision", "AssignmentCommand", "AssignmentEvent", "EligibleCandidateSet", "AssignmentLease", "FencingToken", "DeadlineEvaluation", "EscalationIntent", "SubmissionClassification", "AssignmentReconciliation", "AssignmentRefusal"],
    "issue": ["ReviewIssueId", "ReviewIssueRevision", "ReviewFinding", "ReviewAnchor", "ReviewIssueCommand", "ReviewIssueEvent", "IssueResolutionEvidence", "IssueResolutionDecision", "IssueSemanticDiff", "ReviewIssueRefusal"],
    "agreement": ["AgreementStudyId", "AgreementStudyDeclaration", "RaterDesign", "MeasurementScale", "JudgmentOccurrenceCut", "AlignedJudgmentMatrix", "AgreementMetricContract", "MetricApplicability", "AgreementEstimate", "AgreementUncertainty", "AgreementRefusal"],
    "consensus_rule": ["ConsensusRuleId", "ConsensusRuleEdition", "ConsensusRuleDeclaration", "ConsensusEligibilityAlignmentContract", "ConsensusCombinationContract", "ConsensusMethodContract", "BoundConsensusMethod", "AcceptedConsensusRule", "ConsensusRuleRefusal"],
    "consensus_eval": ["ValidatedConsensusInput", "AlignedEligibleJudgments", "RealizedConsensusInputs", "ConsensusCandidate", "ConsensusResult", "ConsensusResidual", "DissentSet", "ConsensusComparison", "ConsensusRefusal"],
    "adjudication": ["AdjudicationCaseId", "AdjudicationCaseRevision", "AdjudicationRequest", "AuthorityEvidenceCut", "AdmissibleEvidenceCut", "AdjudicationEvidenceAssessment", "AdjudicationJudgment", "AdjudicationTransition", "AdjudicationChallengePlan", "AdjudicationRefusal"],
}


def lib(owner: str, ident: str, name: str, kind: str, responsibility: str, effect: str, deps: list[str], laws: list[str], refusals: list[str], exclusions: list[str], oracles: list[str]) -> dict:
    return {"library_id": ident, "name": name, "library_kind": kind, "semantic_owner_context": CONTEXT[owner], "status": "specified", "candidate_responsibility": responsibility, "effect_boundary": effect, "public_types": TYPES[owner], "public_traits": ["".join(x.title() for x in ident.split(".")[1:]) + "Algebra"], "operation_refs": [x["operation_ref"] for x in OPS[owner]], "operations": OPS[owner], "decision_refs": [x["decision_id"] for x in DECISION_ROWS if f".{owner}." in x["decision_id"]], "configuration_contracts": [f"{owner.title().replace('_', '')}Policy"], "laws": SHARED_LAWS + laws, "invariants": ["all decisions are explicit and no-default", "semantic transitions are deterministic for exact inputs", "identities, editions, authority/evidence cuts, clocks and policies are digest-bound", "optional models and agents retain proposal-only status"], "error_contracts": refusals + ["UnsupportedEdition", "InvalidConfiguration", "ResourceBudgetExceeded"], "dependencies": deps, "evidence_refs": [x["source_id"] for x in SOURCES], "oracles": oracles + ["two independent implementations and cross-provider differential results"], "gaps": ["No implementation is qualified; exact-scope human-task, review, metric, consensus and authority conformance remains required."], "must_not_own": exclusions, "qualification_required": False}


LIBRARIES = [
    lib("task_definition", "library.human_work.task_definition.compiler", "Human Work Definition Compiler", "semantic_pure", "compile one immutable work definition with exact subject, contracts, roles, competence, segregation, blinding, completion, deadline, disclosure and evidence requirements", "pure_no_io", [], ["A role requirement references an external identity/competence vocabulary and does not create a person or credential.", "Task instructions and completion conditions are editioned semantic inputs rather than prose defaults."], ["TaskIdentityMissing", "WorkSubjectUnbound", "InputContractMissing", "OutputContractMissing", "RoleRequirementAmbiguous", "CompetenceRequirementUnbound", "SegregationConflict", "CompletionConditionMissing", "DeadlineAmbiguous", "DisclosurePolicyMissing"], ["person identity", "credential issuance", "assignment", "work execution", "outcome acceptance"], ["role/segregation decision tables", "completion/deadline state fixtures", "canonical definition digests"]),
    lib("assignment", "library.human_work.assignment.reducer", "Human Work Assignment Reducer", "state_pure", "derive eligible candidates and reduce claim, assign, delegate, release, suspend, resume, expire, escalate and completion-reconciliation events under finite lease and fencing semantics", "pure_effect_intents", ["library.human_work.task_definition.compiler", "library.runtime-resource.lease-fencing", "library.csp.authority.authority-scope"], ["Only one actual-owner lease is valid unless an explicit replicated/overlap design says otherwise.", "A stale or expired assignment cannot authorize a late submission; classification preserves the rejected attempt."], ["TaskDefinitionUnbound", "CandidateCutMissing", "EligibilityEvidenceMissing", "AssigneeIneligible", "CompetenceUnproven", "SegregationViolation", "AssignmentConflict", "LeaseExpired", "FenceStale", "DelegationForbidden", "DeadlineStateUnknown", "LateSubmission", "CompletionUnknown"], ["identity or credential authority", "physical notification", "work-result semantics", "review or acceptance", "human resource employment policy"], ["total assignment state model", "lease/fence concurrency tests", "deadline/calendar fixtures", "unknown completion fault injection"]),
    lib("issue", "library.review.issue.lifecycle", "Evidence-Anchored Review Issue Lifecycle", "state_pure", "open and evolve one issue anchored to an exact artifact revision through discussion, correction, verification, resolution, reopen and closure while retaining original evidence", "pure_effect_intents", ["library.lpe.claim-argument-core", "library.lpe.prov-statement-algebra","library.lpe.provenance-assertion"], ["An issue anchor never floats silently across artifact revisions.", "Resolved and closed are distinct; closure cannot erase the finding, challenged artifact or correction history."], ["ReviewAnchorUnresolved", "ArtifactRevisionMismatch", "FindingInvalid", "IssueTransitionInvalid", "CorrectionEvidenceMissing", "VerificationMissing", "ResolutionReasonMissing", "ClosureAuthorityMissing", "ReopenEvidenceMissing", "ConcurrentIssueCommand"], ["artifact mutation", "work assignment mechanics", "agreement/consensus", "adjudication authority", "business acceptance"], ["total issue state model", "anchor/revision mutation twins", "correction-verification decision tables", "reopen/closure history tests"]),
    lib("agreement", "library.agreement.measurement.evaluator", "Agreement and Reliability Measurement Evaluator", "algorithm_pure", "validate a rater study, align exact judgment units, establish metric applicability, evaluate a supplied agreement algebra and retain uncertainty, strata, diagnostics and residuals", "pure_no_io", ["library.csp.quantity.probability-core", "library.csp.quantity.uncertainty-propagation"], ["Observed agreement, chance-corrected agreement, reliability, accuracy against a reference and consensus are different quantities.", "The metric name without rater design, scale, population, matching, missingness, distance, weights and uncertainty is incomplete."], ["StudyDesignIncomplete", "PopulationCutOpen", "RaterCutOpen", "JudgmentAlignmentAmbiguous", "ScaleUnsupported", "DistanceFunctionMissing", "MissingnessPolicyMissing", "MetricInapplicable", "DegenerateMarginals", "InsufficientInformation", "UncertaintyInestimable"], ["consensus derivation", "adjudication", "ground truth", "worker qualification", "acceptance threshold"], ["Cohen/Fleiss/alpha/ICC published fixtures", "metric applicability negative corpus", "permutation and replication properties", "uncertainty coverage simulations"]),
    lib("consensus_rule", "library.consensus.rule.compiler", "Consensus Rule Compiler", "policy_pure", "compile exact eligibility, alignment, independence, weight, quorum, threshold, priority, tie, abstention, dissent and method bindings into one immutable accepted rule", "pure_no_io", ["library.csp.decision.decision-table", "library.csp.quantity.probability-core"], ["Majority, plurality, unanimity, weighted vote, priority rule and probabilistic latent-label inference are different methods.", "A rule may return unresolved or abstain; it cannot silently manufacture quorum or suppress dissent."], ["RuleIdentityMissing", "JudgmentContractUnbound", "EligibilityRuleMissing", "AlignmentAmbiguous", "WeightSourceUnbound", "QuorumMissing", "ThresholdInvalid", "TiePolicyMissing", "AbstentionPolicyMissing", "MethodContractUnbound", "RuleNondeterministic"], ["judgment collection", "agreement measurement", "human adjudication", "ground-truth acceptance", "business effect"], ["quorum/tie/abstention truth tables", "weight normalization properties", "DMN policy comparison fixtures", "method-binding mutation twins"]),
    lib("consensus_eval", "library.consensus.evaluator", "Consensus Evaluator", "algorithm_pure", "evaluate one accepted consensus rule over an exact eligible judgment cut and retain excluded inputs, realized quorum/weights, score, ties, dissent and residual", "pure_no_io", ["library.consensus.rule.compiler"], ["Input order cannot change an order-independent rule result; order-sensitive rules declare that fact.", "Consensus score is scoped evidence and never a probability of truth unless a qualified method contract explicitly defines it."], ["ConsensusRuleUnaccepted", "JudgmentCutMismatch", "JudgmentIneligible", "AlignmentFailed", "QuorumUnmet", "WeightRealizationInvalid", "ConsensusTie", "ConsensusUnresolved", "MethodUnavailable", "EvaluationResidualUnaccepted", "ConsensusBudgetExceeded"], ["judgment issuance", "agreement measurement", "adjudication", "truth acceptance", "source mutation"], ["majority/plurality/weighted fixtures", "input permutation properties", "quorum/tie negative twins", "probabilistic-method differential tests"]),
    lib("adjudication", "library.review.adjudication.reducer", "Review Adjudication Reducer", "policy_pure", "validate an authority-scoped adjudication request, construct an admissible evidence cut, apply precedence and defeaters, validate reasons and reduce judgment, appeal or reopen transitions", "pure_effect_intents", ["library.review.issue.lifecycle", "library.csp.decision.judgment-port", "library.csp.decision.decision-ledger", "library.lpe.claim-argument-core"], ["A consensus candidate or agreement estimate is evidence input and never binds the adjudicator automatically.", "Adjudication preserves the conflict, evidence cut, reasons, dissent and challenge path and cannot retroactively erase occurrences."], ["ConflictUnbound", "AdjudicatorAuthorityMissing", "AdjudicatorConflict", "SegregationViolation", "EvidenceInadmissible", "PrecedenceAmbiguous", "StandardUnbound", "DefeaterUnresolved", "JudgmentUnsupported", "ReasonMissing", "AppealPathMissing", "AdjudicationVersionConflict"], ["authority issuance", "consensus computation", "ground-truth release", "artifact mutation", "business effect"], ["authority/independence decision tables", "evidence precedence and defeater corpus", "total adjudication/appeal state model", "dissent retention tests"]),
]

METHODS = {"value": ["method.business.jtbd", "method.business.capability_map"], "semantic": ["method.domain.ddd", "method.domain.terminology", "method.information.conceptual_data"], "behavior": ["method.domain.eventstorming", "method.work.statecharts", "method.work.dmn"], "authority": ["method.trust.threat_model", "method.systems.stpa"], "consistency": ["method.domain.ddd", "method.formal.alloy", "method.formal.design_by_contract"], "variability": ["method.variability.foda", "method.variability.decision_model"], "software": ["method.architecture.coupling", "method.architecture.hexagonal", "method.variability.algebraic_api"], "operation": ["method.operations.resilience", "method.operations.capacity", "method.operations.sre"], "economics": ["method.operations.finops", "method.business.product_split_merge"], "empirical": ["method.evidence.systematic_review", "method.evidence.repository_mining", "method.evidence.red_team"], "analytical": ["method.analytics.or", "method.formal.property_testing", "method.formal.theorem_proving"], "system": ["method.systems.stpa", "method.trust.fmea_fta", "method.strategy.systems_thinking"]}
LENSES = [
    ("value", "Assignment, issue management, agreement, consensus and adjudication recur across annotation, quality, MDM, assurance and enterprise cases.", "Share mechanics while products retain work meaning and acceptance."),
    ("semantic", "Task, assignment, issue, estimate, consensus and judgment have different identities and truth status.", "Use six contexts and seven libraries."),
    ("behavior", "Definitions compile; assignment/issues/adjudication reduce state; agreement/consensus evaluate finite inputs.", "Separate compilers, reducers and evaluators."),
    ("authority", "Identity, competence, assignment, review, adjudication and acceptance have different issuers.", "Validate references without minting authority."),
    ("consistency", "Leases/fences, immutable evidence cuts, revision anchors and appeal histories need distinct consistency rules.", "Keep aggregates small and link by exact refs."),
    ("variability", "Roles, competence, metrics, scales, quorum, weights, ties and precedence vary independently.", "Expose all material choices with no defaults."),
    ("software", "Human-task control, case state, statistics, rule compilation and authority judgment have different dependencies.", "Retain replaceable libraries."),
    ("operation", "Deadlines, escalation, unknown completion, large studies and expensive consensus methods require bounded behavior.", "Make clocks, budgets, residuals and reconciliation explicit."),
    ("economics", "Assignment overhead, duplicate work, review, measurement and adjudication have distinct costs.", "Expose resource and duplication policies."),
    ("empirical", "OASIS/OMG workflows, CVAT/Label Studio and reliability literature expose complementary seams.", "Generalize laws, not vendor states."),
    ("analytical", "Agreement estimates and consensus algorithms require exact design assumptions and method contracts.", "Use applicability, uncertainty and differential oracles."),
    ("system", "Stale leases, conflicted reviewers, hidden dissent, invalid metrics and arithmetic truth are hazards.", "Fail closed and preserve challenges."),
]
LENS_ROWS = [{"lens_id": f"lens.hwra.{name}", "lens": name, "question": "What does this lens require of human-work, review and adjudication seams?", "finding": finding, "boundary_consequence": consequence, "method_refs": METHODS[name], "status": "applied"} for name, finding, consequence in LENSES]

VERDICTS = [
    {"verdict_id": "verdict.hwra.shared-human-work", "subject_refs": ["library.human_work.task_definition.compiler", "library.human_work.assignment.reducer"], "disposition": "shared_human_work_control", "rationale": "Exact task/assignment mechanics recur, while annotation, quality, stewardship and approval products retain work content and outcome authority.", "status": "candidate_boundary_adjudicated_not_ratified"},
    {"verdict_id": "verdict.hwra.issue-not-case-platform", "subject_refs": ["library.review.issue.lifecycle", "library.cbv.analytical_case_reducer", "library.qor.quality_incident_case_kernel"], "disposition": "exact_review_issue_contract_supersedes_placeholders_without_absorbing_cases", "rationale": "A review issue is an evidence-anchored challenge lifecycle; analytical cases and quality incidents have broader product-specific meaning and remain neighbors.", "status": "candidate_boundary_adjudicated_not_ratified"},
    {"verdict_id": "verdict.hwra.agreement-consensus-adjudication", "subject_refs": ["library.agreement.measurement.evaluator", "library.consensus.rule.compiler", "library.consensus.evaluator", "library.review.adjudication.reducer"], "disposition": "four_distinct_contracts", "rationale": "Statistical similarity, rule definition, rule evaluation and authority-scoped judgment differ in algebra, evidence, authority and failure modes.", "status": "candidate_boundary_adjudicated_not_ratified"},
    {"verdict_id": "verdict.hwra.no-distributed-consensus", "subject_refs": ["library.consensus.rule.compiler", "library.consensus.evaluator"], "disposition": "human_judgment_combination_not_replicated_log_consensus", "rationale": "Paxos/Raft-style agreement concerns replicated machine state under failures; reviewer consensus combines attributed judgments and preserves dissent under domain rules.", "status": "candidate_boundary_adjudicated_not_ratified"},
]

NEGATIVES = [
    ("role_person", "A named role identifies an eligible person.", "Resolve external actor identity and current eligibility evidence."), ("potential_actual", "A potential owner is already the actual owner.", "Require claim or assignment transition."), ("assigned_competent", "Assignment proves competence.", "Bind external competence evidence."), ("manager_authority", "Organizational management implies review or adjudication authority.", "Require exact authority scope."), ("claim_permanent", "Claiming a task creates permanent ownership.", "Bind finite lease and fencing semantics."), ("expired_submit", "A completed result from an expired lease may be accepted silently.", "Classify it as late/stale and retain evidence."), ("delegate_transfer", "Delegation transfers the delegator's entire authority.", "Constrain scope, time and permitted delegatees."), ("deadline_cancel", "A deadline automatically cancels the task.", "Evaluate the declared escalation/state rule."), ("notification_done", "An escalation notification proves reassignment or remediation.", "Reconcile observed assignment state."), ("task_accept", "Task completion means outcome acceptance.", "Require separate review and acceptance."),
    ("issue_comment", "A comment is a review issue.", "Require typed finding, anchor and lifecycle."), ("anchor_latest", "An issue anchor floats to the latest artifact revision.", "Bind exact revision and reanchor explicitly."), ("fix_resolve", "A correction automatically resolves an issue.", "Require verification and resolution decision."), ("resolve_close", "Resolved and closed are identical.", "Preserve closure authority and reopen rules."), ("close_erase", "Closing an issue erases the challenged artifact or dissent.", "Retain append-only evidence and relations."), ("duplicate_delete", "A duplicate issue may be deleted.", "Link it to the canonical issue and retain occurrence."),
    ("percent_universal", "Percent agreement is a universal reliability measure.", "Bind scale, population, design and chance model."), ("kappa_any", "Kappa applies to any number of raters and any scale.", "Evaluate the exact metric's applicability."), ("alpha_default", "Krippendorff alpha removes the need to choose distance and unitization.", "Bind distance, scale and units."), ("icc_name", "ICC is one metric with one meaning.", "Bind model, effects, agreement/consistency and unit."), ("missing_drop", "Missing judgments may always be dropped.", "Declare missingness and resulting estimand."), ("reference_truth", "Agreement with a configured reference proves accuracy.", "Separate reference comparison from truth acceptance."), ("high_accept", "High agreement passes an acceptance threshold automatically.", "Require external threshold and acceptance authority."), ("low_bad", "Low agreement proves individual judgments are wrong.", "Retain ambiguity, design and prevalence explanations."), ("metric_compare", "Scores from different metrics or populations are directly comparable.", "Require a declared comparison relation."),
    ("majority_truth", "Majority vote establishes truth.", "Return a scoped consensus candidate."), ("plurality_majority", "Plurality and majority are interchangeable.", "Bind exact combination rule."), ("weight_hidden", "Worker quality scores may silently become consensus weights.", "Bind weight source, edition and authority."), ("quorum_votes", "The number of submitted judgments proves quorum.", "Apply eligibility, independence and duplicate rules."), ("tie_random", "A tie may be broken randomly by default.", "Declare tie policy and randomness or return unresolved."), ("abstain_no", "Abstention is equivalent to a negative judgment.", "Preserve abstention and missingness."), ("score_probability", "A consensus score is probability of correctness.", "Use only the qualified method's declared semantics."), ("merge_ground", "Merged annotations are ground truth.", "Require review/adjudication and edition acceptance."), ("model_consensus", "A latent-label model adjudicates disagreement.", "Treat it as a selectable consensus method."),
    ("consensus_adjudication", "Consensus automatically binds an adjudicator.", "Treat it as evidence input only."), ("reviewer_adjudicator", "A reviewer is automatically an adjudicator.", "Require independence and authority evidence."), ("metric_precedence", "The largest agreement or confidence score defeats dissent.", "Apply explicit admissibility and precedence."), ("reason_optional", "An adjudication result needs no reason when confidence is high.", "Require scoped reasons and evidence cut."), ("appeal_erase", "Appeal replaces the original judgment.", "Create a linked challenge and later transition."), ("agent_assign", "An agent may assign a plausible competent worker.", "Emit a proposal and require authority/evidence validation."), ("agent_adjudicate", "A model may adjudicate or accept ground truth from consensus.", "Require human/domain authority and typed judgment."), ("one_impl", "One workflow implementation proves portability.", "Require two independent qualified implementations."),
]
NEGATIVE_ROWS = [{"negative_id": f"negative.hwra.{key}", "unsafe_inference": unsafe, "required_behavior": behavior, "status": "active"} for key, unsafe, behavior in NEGATIVES]

COMPILER = []
for library in LIBRARIES:
    stem = library["library_id"].removeprefix("library.")
    req, offer = f"requirement.{stem}.implementation", f"offer.{stem}.reference"
    COMPILER += [{"record_kind": "capability_requirement", "requirement_id": req, "subject_ref": library["library_id"], "required_operations": library["operation_refs"], "required_decisions": library["decision_refs"], "fallback_law": "refuse", "status": "declared"}, {"record_kind": "capability_offer", "offer_id": offer, "subject_ref": library["library_id"], "claimed_operations": library["operation_refs"], "qualified_implementation_count": 0, "portable": False, "selectable": False, "status": "specified_unimplemented"}, {"record_kind": "binding_rule", "binding_rule_id": f"binding.{stem}", "requirement_ref": req, "offer_ref": offer, "structural_match": True, "selection_law": "Structural match never promotes an unqualified or non-portable implementation.", "selectable": False, "status": "declared"}]

FILES = {"sources.jsonl": SOURCES, "bounded-contexts.jsonl": CONTEXTS, "decision-points.jsonl": DECISION_ROWS, "boundary-lens-adjudication.jsonl": LENS_ROWS, "boundary-verdicts.jsonl": VERDICTS, "library-contracts.jsonl": LIBRARIES, "compiler-contracts.jsonl": COMPILER, "negative-twins.jsonl": NEGATIVE_ROWS}


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    digests = {}
    for name, rows in FILES.items():
        payload = render(rows)
        (ROOT / name).write_text(payload, encoding="utf-8")
        digests[name] = {"records": len(rows), "sha256": hashlib.sha256(payload.encode()).hexdigest()}
    manifest = {"manifest_id": "human_work_review_adjudication_v0_1_0", "as_of": AS_OF, "edition": 1, "status": "specified_unimplemented_open_world", "files": digests, "completion_claim": False, "qualified_implementation_count": 0}
    (ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"BUILD PASS hwra: {len(SOURCES)} sources, {len(CONTEXTS)} contexts, {len(DECISION_ROWS)} decisions, {len(LIBRARIES)} libraries, {sum(len(v) for v in OPS.values())} operations, {len(LENS_ROWS)} lenses, {len(NEGATIVE_ROWS)} negative twins")


if __name__ == "__main__":
    main()
