#!/usr/bin/env python3
"""Build claim-bound primary evidence for the Python placement decision."""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent

SOURCES = [
    {
        "source_id": "evidence.arrow.columnar_format",
        "title": "Apache Arrow Columnar Format",
        "publisher": "Apache Arrow",
        "url": "https://arrow.apache.org/docs/format/Columnar.html",
        "source_kind": "official_specification",
        "evidence_role": "architecture",
        "bounded_claim": "A reusable columnar memory and interchange format is a distinct horizontal contract from an application, storage product or analytical method lifecycle.",
        "supports": ["implementation module and interchange contract remain distinct", "universal data representation is separately owned"],
        "does_not_prove": ["the Shannon Python package implements or qualifies Arrow", "a columnar format is a complete data platform"],
    },
    {
        "source_id": "evidence.substrait.plan_specification",
        "title": "Substrait Specification",
        "publisher": "Substrait",
        "url": "https://substrait.io/",
        "source_kind": "official_specification",
        "evidence_role": "architecture",
        "bounded_claim": "Portable compute-plan representation is separable from execution engines, application semantics and provider qualification.",
        "supports": ["application kernel is not a universal query/compiler contract", "plan and engine identities must not collapse"],
        "does_not_prove": ["cross-engine semantic equivalence", "the Python application is a Substrait producer or consumer"],
    },
    {
        "source_id": "evidence.openlineage.object_model",
        "title": "OpenLineage Object Model",
        "publisher": "OpenLineage",
        "url": "https://openlineage.io/docs/spec/object-model/",
        "source_kind": "official_specification",
        "evidence_role": "standard",
        "bounded_claim": "Run, Job and Dataset lineage identities form a separate evidence contract from application findings and source-data authority.",
        "supports": ["execution and provenance evidence deserve explicit identities", "lineage events do not own source truth"],
        "does_not_prove": ["lineage completeness", "application or provider qualification"],
    },
    {
        "source_id": "evidence.w3c.prov_o",
        "title": "PROV-O: The PROV Ontology",
        "publisher": "W3C",
        "url": "https://www.w3.org/TR/prov-o/",
        "source_kind": "standard",
        "evidence_role": "standard",
        "bounded_claim": "Entities, activities and agents provide a provenance vocabulary that remains distinct from domain semantics and authorization.",
        "supports": ["finding evidence and execution provenance require explicit ownership", "provenance is not authority"],
        "does_not_prove": ["truth of a finding", "permission to act"],
    },
    {
        "source_id": "evidence.opentelemetry.signals",
        "title": "OpenTelemetry Signals",
        "publisher": "OpenTelemetry",
        "url": "https://opentelemetry.io/docs/concepts/signals/",
        "source_kind": "official_specification",
        "evidence_role": "architecture",
        "bounded_claim": "Traces, metrics, logs and baggage are operational telemetry signals, not interchangeable analytical results or business facts.",
        "supports": ["runtime telemetry is a separate horizontal concern", "application signals require declared semantics and grain"],
        "does_not_prove": ["analytical validity", "business metric authority"],
    },
    {
        "source_id": "evidence.iceberg.spec",
        "title": "Apache Iceberg Table Specification",
        "publisher": "Apache Iceberg",
        "url": "https://iceberg.apache.org/spec/",
        "source_kind": "official_specification",
        "evidence_role": "architecture",
        "bounded_claim": "A table format owns snapshot, schema and metadata semantics without becoming a query engine, semantic layer or application product.",
        "supports": ["local application persistence is not a universal table product", "snapshot identity needs an explicit contract"],
        "does_not_prove": ["engine interoperability for a concrete occurrence", "the Python application implements Iceberg"],
    },
    {
        "source_id": "evidence.calcite.architecture",
        "title": "Apache Calcite Documentation",
        "publisher": "Apache Calcite",
        "url": "https://calcite.apache.org/docs/",
        "source_kind": "official_documentation",
        "evidence_role": "architecture",
        "bounded_claim": "Query parsing, relational algebra, planning and adapter behavior form reusable engine concerns distinct from an application analysis kernel.",
        "supports": ["application orchestration is not a universal query planner", "planner and adapter seams require explicit contracts"],
        "does_not_prove": ["physical-engine qualification", "semantic equivalence across adapters"],
    },
    {
        "source_id": "evidence.duckdb.documentation",
        "title": "DuckDB Documentation",
        "publisher": "DuckDB",
        "url": "https://duckdb.org/docs/stable/",
        "source_kind": "official_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "An in-process analytical database is an independently operated query/compute implementation, not merely an application query helper.",
        "supports": ["query engine and application query surface should not collapse", "provider implementation requires separate identity"],
        "does_not_prove": ["qualification for Shannon contracts", "universal query semantics"],
    },
    {
        "source_id": "evidence.dbt.semantic_layer",
        "title": "dbt Semantic Layer",
        "publisher": "dbt Labs",
        "url": "https://docs.getdbt.com/docs/use-dbt-semantic-layer/dbt-sl",
        "source_kind": "official_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Governed metric definitions and semantic querying form a product concern separate from application-specific signal scoring.",
        "supports": ["codebase signals are not a universal semantic metric layer", "metric definition and consumption deserve their own lifecycle"],
        "does_not_prove": ["metric correctness", "the Python application implements a semantic layer"],
    },
    {
        "source_id": "evidence.openmetadata.documentation",
        "title": "OpenMetadata Documentation",
        "publisher": "OpenMetadata",
        "url": "https://docs.open-metadata.org/latest/",
        "source_kind": "official_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Metadata discovery, governance, lineage and quality are operated product surfaces distinct from one analytical application.",
        "supports": ["application metadata is not an enterprise catalog", "multiple trust concerns should retain explicit owners"],
        "does_not_prove": ["one sovereign product boundary for all trust concerns", "qualification or semantic authority"],
    },
    {
        "source_id": "evidence.great_expectations.core",
        "title": "Great Expectations Core Introduction",
        "publisher": "Great Expectations",
        "url": "https://docs.greatexpectations.io/docs/core/introduction/",
        "source_kind": "official_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Data validation expectations, validation definitions and checkpoints form an operated quality lifecycle distinct from application tests and diagnostic findings.",
        "supports": ["application regression tests are not enterprise data-quality operations", "quality evidence needs exact populations and runs"],
        "does_not_prove": ["quality of an arbitrary dataset", "Shannon implementation qualification"],
    },
    {
        "source_id": "evidence.apache_beam.model",
        "title": "Apache Beam Basics",
        "publisher": "Apache Beam",
        "url": "https://beam.apache.org/documentation/basics/",
        "source_kind": "official_documentation",
        "evidence_role": "architecture",
        "bounded_claim": "A unified batch/stream programming model and runner separation are horizontal dataflow concerns distinct from the codebase-analysis run lifecycle.",
        "supports": ["application execution control is not a universal dataflow runtime", "logical pipeline and physical runner should remain distinct"],
        "does_not_prove": ["runner conformance", "the Python application is a Beam pipeline"],
    },
    {
        "source_id": "evidence.kafka.design",
        "title": "Apache Kafka Design",
        "publisher": "Apache Kafka",
        "url": "https://kafka.apache.org/documentation/#design",
        "source_kind": "official_documentation",
        "evidence_role": "architecture",
        "bounded_claim": "Partitioned log, replication, producer, consumer and delivery semantics are physical event infrastructure concerns separate from application evidence events.",
        "supports": ["application event records are not an event-log product", "delivery and ordering require occurrence-specific evidence"],
        "does_not_prove": ["exactly-once end-to-end behavior", "a qualified Kafka occurrence"],
    },
    {
        "source_id": "evidence.debezium.architecture",
        "title": "Debezium Architecture",
        "publisher": "Debezium",
        "url": "https://debezium.io/documentation/reference/stable/architecture.html",
        "source_kind": "official_documentation",
        "evidence_role": "architecture",
        "bounded_claim": "Change-data-capture connector architecture is a source-acquisition implementation concern, not source-system authority or an analytical application.",
        "supports": ["connector implementation and source occurrence remain distinct", "Git extraction cannot stand in for universal CDC"],
        "does_not_prove": ["capture completeness for a concrete source", "source semantic authority"],
    },
    {
        "source_id": "evidence.github.codeql",
        "title": "About code scanning with CodeQL",
        "publisher": "GitHub",
        "url": "https://docs.github.com/en/code-security/code-scanning/introduction-to-code-scanning/about-code-scanning-with-codeql",
        "source_kind": "official_product_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "An independently adopted application can build a code database, execute code queries and report code-scanning results as a software-domain lifecycle.",
        "supports": ["codebase intelligence is an application-domain product category", "code observations and findings have a distinct lifecycle"],
        "does_not_prove": ["Shannon product correctness", "semantic authority for all software analysis"],
    },
    {
        "source_id": "evidence.semgrep.documentation",
        "title": "Semgrep Documentation",
        "publisher": "Semgrep",
        "url": "https://semgrep.dev/docs/",
        "source_kind": "official_product_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Rule-based source-code analysis and findings are independently operated software-analysis capabilities.",
        "supports": ["software analysis applications are not merely graph libraries", "rule/method and finding lifecycles are separable"],
        "does_not_prove": ["equivalence to Shannon findings", "universal static-analysis semantics"],
    },
    {
        "source_id": "evidence.sonarqube.documentation",
        "title": "SonarQube Server Documentation",
        "publisher": "Sonar",
        "url": "https://docs.sonarsource.com/sonarqube-server/",
        "source_kind": "official_product_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Code quality and security analysis is operated through projects, analyses, issues and quality controls rather than as an isolated mathematical library.",
        "supports": ["finding and project lifecycles justify an application product boundary", "analysis execution and issue interpretation remain distinct"],
        "does_not_prove": ["correctness of any particular rule", "Shannon readiness or ratification"],
    },
    {
        "source_id": "evidence.qodana.documentation",
        "title": "Qodana Documentation",
        "publisher": "JetBrains",
        "url": "https://www.jetbrains.com/help/qodana/",
        "source_kind": "official_product_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Static code analysis can be packaged as a CI-integrated application with configurations, reports and quality gates.",
        "supports": ["CI adoption is an application seam", "analysis and presentation form a lifecycle beyond algorithms"],
        "does_not_prove": ["horizontal platform status", "independent qualification of Shannon"],
    },
    {
        "source_id": "evidence.snyk_code.documentation",
        "title": "Snyk Code Documentation",
        "publisher": "Snyk",
        "url": "https://docs.snyk.io/scan-with-snyk/snyk-code",
        "source_kind": "official_product_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Source-code scanning, issue identification and developer workflow integration constitute an independently adopted application surface.",
        "supports": ["codebase intelligence is a software-domain application family", "findings require workflow and evidence seams"],
        "does_not_prove": ["shared finding semantics", "Shannon product qualification"],
    },
    {
        "source_id": "evidence.sourcegraph.code_search",
        "title": "Sourcegraph Code Search Documentation",
        "publisher": "Sourcegraph",
        "url": "https://sourcegraph.com/docs/code-search",
        "source_kind": "official_product_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Code indexing, search and navigation are independently adopted software-intelligence application capabilities distinct from enterprise data search.",
        "supports": ["software-domain vocabulary stays in an application pack", "code search does not become universal data search semantics"],
        "does_not_prove": ["diagnostic validity", "the Shannon package implements Sourcegraph protocols"],
    },
    {
        "source_id": "evidence.grimoirelab.documentation",
        "title": "GrimoireLab Documentation",
        "publisher": "CHAOSS",
        "url": "https://chaoss.github.io/grimoirelab/",
        "source_kind": "official_project_documentation",
        "evidence_role": "product_boundary_evidence",
        "bounded_claim": "Software-development analytics can acquire data from development tools, enrich identities and expose analytical views as a coherent application stack.",
        "supports": ["software-development analytics is an application domain", "acquisition, identity, enrichment and presentation are separate concerns"],
        "does_not_prove": ["semantic equivalence with Shannon", "universal enterprise analytics coverage"],
    },
    {
        "source_id": "evidence.dora.four_keys",
        "title": "DORA's software delivery performance metrics",
        "publisher": "DORA",
        "url": "https://dora.dev/guides/dora-metrics-four-keys/",
        "source_kind": "official_research_guidance",
        "evidence_role": "empirical_validation",
        "bounded_claim": "Software-delivery performance metrics have explicit software-domain definitions and measurement concerns rather than universal KPI semantics.",
        "supports": ["software metrics belong to a vertical/domain product or pack", "metric interpretation requires domain evidence"],
        "does_not_prove": ["causality for an individual organization", "correctness of Shannon signals"],
    },
    {
        "source_id": "evidence.sarif.2_1",
        "title": "Static Analysis Results Interchange Format (SARIF) Version 2.1.0",
        "publisher": "OASIS",
        "url": "https://docs.oasis-open.org/sarif/sarif/v2.1.0/sarif-v2.1.0.html",
        "source_kind": "standard",
        "evidence_role": "standard",
        "bounded_claim": "Static-analysis result interchange is a separate contract from analyzer implementation, source authority and finding truth.",
        "supports": ["evidence export needs a typed contract", "application findings can remain portable without making implementations equivalent"],
        "does_not_prove": ["result correctness", "analyzer qualification"],
    },
    {
        "source_id": "evidence.spdx.3",
        "title": "SPDX Specification 3.0",
        "publisher": "SPDX",
        "url": "https://spdx.github.io/spdx-spec/v3.0/",
        "source_kind": "standard",
        "evidence_role": "standard",
        "bounded_claim": "Software supply-chain and bill-of-materials evidence has an independent typed interchange model.",
        "supports": ["build and dependency evidence should be explicit", "application analysis and supply-chain attestations should not collapse"],
        "does_not_prove": ["artifact integrity by itself", "implementation qualification"],
    },
    {
        "source_id": "evidence.cyclonedx.overview",
        "title": "CycloneDX Specification Overview",
        "publisher": "OWASP CycloneDX",
        "url": "https://cyclonedx.org/specification/overview/",
        "source_kind": "standard",
        "evidence_role": "standard",
        "bounded_claim": "Component, service and dependency inventory is a distinct evidence contract used in software supply-chain analysis.",
        "supports": ["reproducible-build qualification needs SBOM evidence", "software analysis may consume but does not own SBOM semantics"],
        "does_not_prove": ["absence of vulnerabilities", "portable analytical implementation"],
    },
    {
        "source_id": "evidence.openapi.3_1_1",
        "title": "OpenAPI Specification 3.1.1",
        "publisher": "OpenAPI Initiative",
        "url": "https://spec.openapis.org/oas/v3.1.1.html",
        "source_kind": "standard",
        "evidence_role": "standard",
        "bounded_claim": "HTTP API description is an interface contract concern distinct from application-domain semantics and implementation qualification.",
        "supports": ["published API shape and product meaning remain separate", "provider interfaces require editioned contracts"],
        "does_not_prove": ["runtime conformance", "semantic correctness"],
    },
    {
        "source_id": "evidence.vega_lite.spec",
        "title": "Vega-Lite Specification",
        "publisher": "Vega-Lite",
        "url": "https://vega.github.io/vega-lite/docs/spec.html",
        "source_kind": "official_specification",
        "evidence_role": "architecture",
        "bounded_claim": "Declarative visual encodings and view composition form a presentation grammar distinct from analytical result meaning and application findings.",
        "supports": ["renderer/dashboard does not own analytical semantics", "visual composition is a separately modeled experience concern"],
        "does_not_prove": ["accessibility or decision fitness of a rendered view", "the Shannon renderer implements Vega-Lite"],
    },
]


def main() -> int:
    rows = []
    for source in SOURCES:
        rows.append(
            {
                **source,
                "last_verified": "2026-08-27",
                "semantic_authority": False,
                "implementation_qualification_claim": False,
                "product_ratification_claim": False,
                "completion_claim": False,
            }
        )
    rows.sort(key=lambda row: row["source_id"])
    (HERE / "shannon-python-placement-evidence.jsonl").write_text(
        "".join(json.dumps(row, sort_keys=True) + "\n" for row in rows),
        encoding="utf-8",
    )
    role_counts = Counter(row["evidence_role"] for row in rows)
    source_kind_counts = Counter(row["source_kind"] for row in rows)
    summary = {
        "report_id": "shannon_python_placement_primary_evidence",
        "source_count": len(rows),
        "evidence_role_counts": dict(sorted(role_counts.items())),
        "source_kind_counts": dict(sorted(source_kind_counts.items())),
        "sources_with_bounded_claim": sum(bool(row["bounded_claim"]) for row in rows),
        "sources_with_explicit_non_proof": sum(bool(row["does_not_prove"]) for row in rows),
        "semantic_authority_claim_count": 0,
        "qualification_claim_count": 0,
        "status": "CLAIM_BOUND_PRIMARY_EVIDENCE_NOT_SEMANTIC_AUTHORITY",
        "completion_claim": False,
    }
    (HERE / "shannon-python-placement-evidence-summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
