"""Explicit research-package routes into the solution-synthesis architecture.

Rules use governed path prefixes as package identities. They never infer ownership from filenames,
record names, vendor names or matching words. Longest-prefix selection is deterministic; equal
specificity is an ambiguity and a missing top-level package is unrouted.
"""

from __future__ import annotations


def rule(
    ident: str, prefix: str, component: str, input_ir: str, output_ir: str,
    frontier: str, phase: str, authority: str, purpose: str,
    invalidation: list[str], dependencies: list[str] | None = None,
) -> dict:
    return {
        "rule_id": f"route-rule.corpus.{ident}", "path_prefix": prefix,
        "component_ref": f"component.synthesis.{component}",
        "input_ir_ref": f"ir.synthesis.{input_ir}", "output_ir_ref": f"ir.synthesis.{output_ir}",
        "frontier_class_ref": f"frontier.synthesis.{frontier}",
        "binding_phase_ref": f"phase.synthesis.{phase}", "authority": authority,
        "purpose": purpose, "invalidation_triggers": invalidation,
        "dependency_rule_refs": [f"route-rule.corpus.{x}" for x in (dependencies or [])],
        "status": "PROPOSED_UNRATIFIED", "completion_claim": False,
    }


RULES = [
    # Historical dispatch and external research inputs remain provenance-bearing open-world inputs.
    rule("dispatch_kit", "research/SAN-GPT-PRO-DISPATCH-KIT-2026-08-13/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "research_program_owner", "Governed research program, prompts, sessions and provenance; never canonical authority by itself.", ["prompt_edition_changed", "session_output_replaced", "input_provenance_changed"]),
    rule("data_analytics_handoff", "research/SAN_DATA_ANALYTICS_GPT_PRO_HANDOFF_2026-08-12", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "research_program_owner", "Historical analytics research handoff and external analysis input.", ["handoff_digest_changed", "external_analysis_superseded"]),
    rule("data_domain_handoff_v2", "research/SAN_DATA_DOMAIN_GPT_PRO_HANDOFF_V2_2026-08-12", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "research_program_owner", "Historical data-domain research handoff V2.", ["handoff_digest_changed", "external_analysis_superseded"]),
    rule("data_domain_handoff_v3", "research/SAN_DATA_DOMAIN_GPT_PRO_HANDOFF_V3_2026-08-12", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "research_program_owner", "Historical data-domain research handoff V3.", ["handoff_digest_changed", "external_analysis_superseded"]),
    rule("data_domain_handoff_v4", "research/SAN_DATA_DOMAIN_RESEARCH_CORPUS_GPT_PRO_HANDOFF_V4_2026-08-12", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "research_program_owner", "Historical corpus research handoff V4.", ["handoff_digest_changed", "external_analysis_superseded"]),
    rule("handoffs", "research/handoffs/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "research_program_owner", "External-agent research inputs and proposed deltas retained with provenance.", ["handoff_input_changed", "output_package_changed", "evidence_source_invalidated"]),

    # Early analytics landscape: discovery inputs, not the current semantic authority.
    rule("analytics_compiler", "research/analytics_landscape/compiler/", "deterministic-compiler-kernel", "semantic-intent-ir", "contract-graph-ir", "mechanically-compilable", "compile", "compiler_architecture_owner", "Early compiler schemas and projections retained as source input and migration evidence.", ["schema_edition_changed", "canonical_compiler_contract_changed"]),
    rule("analytics_composition", "research/analytics_landscape/composition/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "vertical_research_owner", "Early domain-pack and composition research inputs.", ["vertical_vocabulary_changed", "product_boundary_changed"]),
    rule("analytics_domain_engineering", "research/analytics_landscape/domain_engineering/", "authority-adjudication-workbench", "business-intent-ir", "semantic-intent-ir", "authority-or-judgment-required", "authoring", "domain_model_authority", "Domain-engineering research, vocabularies and bounded-context candidates.", ["semantic_owner_changed", "domain_boundary_changed"]),
    rule("analytics_landscape", "research/analytics_landscape/", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "analytics_research_owner", "Legacy analytics taxonomy, companies, experts, innovations and review protocols.", ["taxonomy_changed", "evidence_retracted", "review_cycle_changed"]),

    # Domain-atlas compiler subprograms.
    rule("compiler_canonical_reference", "research/domain_atlas/compiler/canonical_reference_mapper/", "deterministic-compiler-kernel", "semantic-intent-ir", "semantic-intent-ir", "mechanically-compilable", "compile", "canonical_reference_authority", "Directional reference resolution, ambiguity and anti-alias contracts.", ["mapping_edition_changed", "owner_decision_changed", "collision_discovered"]),
    rule("compiler_ir_lowering", "research/domain_atlas/compiler/ir_lowering/", "deterministic-compiler-kernel", "semantic-intent-ir", "contract-graph-ir", "mechanically-compilable", "compile", "compiler_ir_authority", "Typed staged IR and lowering contracts.", ["ir_edition_changed", "lowering_law_changed", "semantic_loss_discovered"]),
    rule("compiler_model_class", "research/domain_atlas/compiler/model_class_adjudication/", "constraint-planner-synthesizer", "semantic-intent-ir", "capability-requirement-ir", "constraint-synthesizable", "compile", "formal_model_authority", "Formal model-class predicates, reformulations and provider requirement projection.", ["feature_fact_changed", "class_predicate_changed", "reformulation_counterexample"]),
    rule("compiler_binder_solver", "research/domain_atlas/compiler/binder_solver/", "constraint-planner-synthesizer", "capability-requirement-ir", "physical-binding-ir", "constraint-synthesizable", "compile", "binding_solver_authority", "Candidate enumeration, hard-constraint solving and binding decisions.", ["requirement_changed", "offer_changed", "constraint_or_objective_changed"]),
    rule("compiler_codegen_build", "research/domain_atlas/compiler/codegen_build/", "deterministic-compiler-kernel", "contract-graph-ir", "deployment-blueprint-ir", "mechanically-compilable", "compile", "artifact_planning_authority", "Target, generation, build, packaging, release and rollback planning contracts; execution remains external.", ["target_edition_changed", "toolchain_changed", "dependency_or_advisory_changed"]),
    rule("compiler_conformance", "research/domain_atlas/compiler/conformance_evaluation/", "assurance-appraisal-system", "contract-graph-ir", "evidence-acceptance-ir", "physical-or-evidence-required", "qualification", "independent_conformance_authority", "Exact-scope oracle, test, qualification, appraisal and evidence contracts.", ["oracle_edition_changed", "receipt_expired", "counterexample_found"]),
    rule("compiler_provider_targets", "research/domain_atlas/compiler/provider_target_registry/", "assurance-appraisal-system", "capability-requirement-ir", "physical-binding-ir", "physical-or-evidence-required", "qualification", "provider_qualification_authority", "Provider, implementation and target occurrences with qualification evidence.", ["provider_version_changed", "region_or_quota_changed", "qualification_expired"]),
    rule("compiler_implementation", "research/domain_atlas/compiler/implementation_architecture/", "deterministic-compiler-kernel", "contract-graph-ir", "physical-binding-ir", "physical-or-evidence-required", "qualification", "implementation_architecture_owner", "Implementation boundaries, ports, targets and removal seams.", ["implementation_edition_changed", "dependency_changed", "target_changed"]),

    # Library registry phases override the broad compiler route.
    rule("library_p6", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/p6_implementation_qualification/", "assurance-appraisal-system", "contract-graph-ir", "physical-binding-ir", "physical-or-evidence-required", "qualification", "implementation_qualification_authority", "P6 implementation identity, build and conformance gates.", ["contract_changed", "implementation_changed", "qualification_receipt_changed"]),
    rule("library_p7", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/p7_offer_binding_qualification/", "assurance-appraisal-system", "physical-binding-ir", "physical-binding-ir", "physical-or-evidence-required", "qualification", "provider_offer_qualification_authority", "P7 provider-offer binding and conformance context.", ["offer_changed", "provider_context_changed", "qualification_expired"]),
    rule("library_p8", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/p8_vertical_acceptance_tensor/", "assurance-appraisal-system", "physical-binding-ir", "evidence-acceptance-ir", "physical-or-evidence-required", "post-runtime", "vertical_acceptance_authority", "P8 unrelated-vertical acceptance gates and evidence.", ["vertical_profile_changed", "implementation_changed", "acceptance_receipt_invalidated"]),
    rule("library_product_coordinates", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/product_coordinate_binding_projection/", "deterministic-compiler-kernel", "product-composition-ir", "physical-binding-ir", "mechanically-compilable", "compile", "product_composition_compiler_authority", "Product-to-library coordinate and assembly closure projection.", ["product_boundary_changed", "library_contract_changed", "coordinate_decision_changed"]),
    rule("library_gap_topology", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/gap_topology/", "authority-adjudication-workbench", "contract-graph-ir", "evidence-acceptance-ir", "authority-or-judgment-required", "change", "closure_program_authority", "Lossless gap quotients, dependency bands and closure programs.", ["gap_atom_changed", "closure_receipt_added", "dependency_changed"]),
    rule("library_semantic_decomposition", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/", "authority-adjudication-workbench", "semantic-intent-ir", "contract-graph-ir", "authority-or-judgment-required", "authoring", "semantic_contract_authority", "Semantic axes, ownership, applicability, exact-contract adjudication and coordinate research.", ["source_authority_changed", "owner_decision_changed", "axis_applicability_changed", "contract_ratified"]),
    rule("compiler_library_registry", "research/domain_atlas/compiler/library_registry/", "deterministic-compiler-kernel", "semantic-intent-ir", "contract-graph-ir", "mechanically-compilable", "compile", "library_registry_authority", "Library contribution, contract generation and compiler route registries.", ["library_identity_changed", "contract_edition_changed", "dependency_changed"]),
    rule("domain_atlas_compiler", "research/domain_atlas/compiler/", "deterministic-compiler-kernel", "semantic-intent-ir", "deployment-blueprint-ir", "mechanically-compilable", "compile", "compiler_program_authority", "Fallback for explicitly governed compiler packages not yet split into a narrower rule.", ["compiler_contract_changed", "registry_changed"]),

    # Domain-atlas knowledge universes and research surfaces.
    rule("atlas_industries", "research/domain_atlas/industries/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "vertical_domain_authorities", "Industry/subindustry vocabulary, needs, sources, cases and solution-pack inputs.", ["industry_taxonomy_changed", "vertical_source_changed", "acceptance_profile_changed"]),
    rule("atlas_ecosystem", "research/domain_atlas/ecosystem/", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "ecosystem_research_owner", "Experts, specialist companies, innovations, evidence graph and change intelligence.", ["source_retracted", "expert_or_company_evidence_changed", "innovation_superseded"]),
    rule("atlas_universes", "research/domain_atlas/universes/", "authority-adjudication-workbench", "semantic-intent-ir", "contract-graph-ir", "authority-or-judgment-required", "authoring", "universe_semantic_authorities", "Sovereign semantic universes, library boundaries, laws and evidence candidates.", ["universe_boundary_changed", "semantic_owner_changed", "source_authority_changed"]),
    rule("atlas_context_map", "research/domain_atlas/context_map/", "authority-adjudication-workbench", "semantic-intent-ir", "product-composition-ir", "authority-or-judgment-required", "authoring", "context_map_authority", "Bounded-context relationships, ACLs and published-language candidates.", ["context_boundary_changed", "relationship_changed", "published_language_changed"]),
    rule("atlas_registry", "research/domain_atlas/registry/", "authority-adjudication-workbench", "semantic-intent-ir", "product-composition-ir", "authority-or-judgment-required", "authoring", "domain_atlas_registry_authority", "Canonical candidate registry and identity graph.", ["candidate_identity_changed", "owner_changed", "edition_changed"]),
    rule("atlas_clusters", "research/domain_atlas/clusters/", "ontology-research-extension", "semantic-intent-ir", "semantic-intent-ir", "open-world-extension-required", "authoring", "research_clustering_owner", "Discovery clusters only; clustering does not confer semantic ownership.", ["cluster_membership_changed", "evidence_changed"]),
    rule("domain_atlas_root", "research/domain_atlas/", "authority-adjudication-workbench", "business-intent-ir", "product-composition-ir", "authority-or-judgment-required", "authoring", "domain_atlas_program_authority", "Domain-atlas metamodel, axes, coverage planes, program and root documentation.", ["metamodel_changed", "axis_taxonomy_changed", "coverage_plane_changed"]),

    # Live research and monitoring is evidence input only.
    rule("luna", "research/luna/", "ontology-research-extension", "business-intent-ir", "semantic-intent-ir", "open-world-extension-required", "post-runtime", "research_monitor_owner", "Change intelligence, source catalog and recurring technical research observations.", ["source_feed_changed", "freshness_expired", "claim_corrected"]),

    # Product ontology: discovery, adjudication, products, assurance and closure.
    rule("product_adjudications", "research/product_ontology/adjudications/", "authority-adjudication-workbench", "semantic-intent-ir", "contract-graph-ir", "authority-or-judgment-required", "authoring", "product_and_contract_authorities", "Product boundary decisions, DDD dossiers, exact library seams, maps, gaps and negative twins.", ["boundary_evidence_changed", "product_owner_decision_changed", "library_contract_changed"]),
    rule("product_composition_pilots", "research/product_ontology/composition_pilots/", "assurance-appraisal-system", "product-composition-ir", "evidence-acceptance-ir", "physical-or-evidence-required", "post-runtime", "vertical_acceptance_authorities", "Structural and executed vertical-composition acceptance pilots.", ["vertical_profile_changed", "binding_changed", "acceptance_receipt_changed"]),
    rule("product_qualification", "research/product_ontology/qualification_program/", "assurance-appraisal-system", "contract-graph-ir", "evidence-acceptance-ir", "physical-or-evidence-required", "qualification", "qualification_program_authority", "Implementation, provider, product and vertical qualification obligations.", ["subject_changed", "evidence_vacancy_changed", "receipt_added_or_invalidated"]),
    rule("product_readiness", "research/product_ontology/dossier_readiness/", "assurance-appraisal-system", "product-composition-ir", "evidence-acceptance-ir", "physical-or-evidence-required", "qualification", "product_readiness_authority", "Lossless product DDD, library, compiler-map and closure readiness projection.", ["product_changed", "dossier_changed", "library_map_changed"]),
    rule("product_global_boundary", "research/product_ontology/global_boundary_research/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "global_product_research_owner", "Global product-boundary evidence, truth applicability and candidate graph.", ["source_changed", "candidate_changed", "boundary_adjudication_changed"]),
    rule("product_upstream_sweep", "research/product_ontology/upstream_demand_surface_sweep/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "upstream_research_owner", "Demand-surface laws, boundary hypotheses, contract seams and vertical deltas.", ["upstream_source_changed", "boundary_hypothesis_changed", "contract_seam_adjudicated"]),
    rule("product_inventory_challenges", "research/product_ontology/inventory_challenges/", "ontology-research-extension", "product-composition-ir", "product-composition-ir", "open-world-extension-required", "authoring", "boundary_falsification_owner", "Adversarial inventory and product-boundary challenge packages.", ["counterexample_added", "boundary_disposition_changed"]),
    rule("product_boundary_methods", "research/product_ontology/boundary_method_ensemble/", "ontology-research-extension", "business-intent-ir", "product-composition-ir", "open-world-extension-required", "authoring", "boundary_method_authority", "Boundary-method ensemble and falsification logic.", ["method_changed", "boundary_test_changed"]),
    rule("product_ddd_doctrine", "research/product_ontology/ddd_seam_doctrine/", "authority-adjudication-workbench", "business-intent-ir", "semantic-intent-ir", "authority-or-judgment-required", "authoring", "domain_modeling_authority", "DDD and seam doctrine used to define products and libraries.", ["ddd_truth_dimension_changed", "seam_law_changed"]),
    rule("product_boundary_migration", "research/product_ontology/boundary_migration_projection/", "deterministic-compiler-kernel", "product-composition-ir", "product-composition-ir", "mechanically-compilable", "change", "product_migration_authority", "Non-retained candidate responsibility migration without compatibility aliases.", ["boundary_decision_changed", "replacement_edge_changed"]),
    rule("product_research_rebase", "research/product_ontology/research_convergence_rebase/", "authority-adjudication-workbench", "product-composition-ir", "evidence-acceptance-ir", "authority-or-judgment-required", "change", "research_convergence_authority", "Rebase external research proposals onto canonical gap quotients without closure claims.", ["gap_topology_changed", "research_disposition_changed"]),
    rule("product_closure", "research/product_ontology/closure_program/", "authority-adjudication-workbench", "contract-graph-ir", "evidence-acceptance-ir", "authority-or-judgment-required", "change", "named_ratification_authorities", "Dependency-ordered ratification and physical/governance closure cockpit.", ["ratification_receipt_added", "gap_atom_changed", "evidence_invalidated"]),
    rule("solution_synthesis_architecture", "research/product_ontology/solution_synthesis_architecture/", "authority-adjudication-workbench", "business-intent-ir", "deployment-blueprint-ir", "authority-or-judgment-required", "authoring", "solution_architecture_authority", "Constitutional architecture for compiler, planner, adjudicator, reconciler, assurance and research extension.", ["architecture_law_changed", "ir_stage_changed", "component_boundary_changed"]),
    rule("product_registry_schema", "research/product_ontology/registry/", "authority-adjudication-workbench", "semantic-intent-ir", "product-composition-ir", "authority-or-judgment-required", "authoring", "product_registry_authority", "Product graph registry identities and relations.", ["registry_identity_changed", "edge_changed"]),
    rule("product_schema", "research/product_ontology/schema/", "deterministic-compiler-kernel", "semantic-intent-ir", "contract-graph-ir", "mechanically-compilable", "compile", "product_schema_authority", "Machine-readable product-graph schema contracts.", ["schema_edition_changed"]),
    rule("product_ontology_root", "research/product_ontology/", "authority-adjudication-workbench", "business-intent-ir", "product-composition-ir", "authority-or-judgment-required", "authoring", "product_ontology_program_authority", "Root product-boundary theory, truth contract, annealing log and validation program.", ["truth_contract_changed", "boundary_theory_changed", "validation_program_changed"]),
]

DECLARED_TOP_LEVEL_PREFIXES = sorted({
    "research/SAN-GPT-PRO-DISPATCH-KIT-2026-08-13/",
    "research/SAN_DATA_ANALYTICS_GPT_PRO_HANDOFF_2026-08-12",
    "research/SAN_DATA_DOMAIN_GPT_PRO_HANDOFF_V2_2026-08-12",
    "research/SAN_DATA_DOMAIN_GPT_PRO_HANDOFF_V3_2026-08-12",
    "research/SAN_DATA_DOMAIN_RESEARCH_CORPUS_GPT_PRO_HANDOFF_V4_2026-08-12",
    "research/analytics_landscape/", "research/domain_atlas/", "research/handoffs/",
    "research/luna/", "research/product_ontology/",
})

IDENTITY_FIELDS = [
    "record_id", "artifact_id", "library_id", "candidate_id", "product_id", "source_id",
    "decision_id", "requirement_id", "offer_id", "binding_map_id", "gap_id", "dossier_id",
    "relation_id", "test_id", "contract_id", "node_id", "edge_id", "id", "kind",
]
