#!/usr/bin/env python3
"""Build exact schema-registry and data-contract governance contracts."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
AS_OF = "2026-08-26"
EDITION = 1


def lines(rows: list[dict]) -> str:
    return "".join(json.dumps(row, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n" for row in rows)


def S(ident: str, title: str, publisher: str, url: str, scope: str, limit: str, kind: str = "official_specification") -> dict:
    return {"source_id": f"source.schema-contract.{ident}", "title": title, "publisher": publisher, "url": url, "source_kind": kind, "claim_scope": scope, "scope_limit": limit}


SOURCES = [
    S("jsonschema.core.2020-12", "JSON Schema Core 2020-12", "JSON Schema Project", "https://json-schema.org/draft/2020-12/json-schema-core", "dialects, vocabularies, schema-resource identity, references and compound documents", "JSON Schema validity is not reader/writer compatibility or business substitutability."),
    S("jsonschema.validation.2020-12", "JSON Schema Validation 2020-12", "JSON Schema Project", "https://json-schema.org/draft/2020-12/json-schema-validation", "assertion and annotation vocabularies", "Instance validation does not establish data-contract attainment or semantic correctness."),
    S("avro.current", "Apache Avro Specification", "Apache Software Foundation", "https://avro.apache.org/docs/current/specification/", "writer/reader schema resolution, parsing canonical form and logical types", "Avro rules apply only to exact Avro editions and do not prove application compatibility."),
    S("protobuf.proto3", "Protocol Buffers Proto3 Language Guide", "Google Protocol Buffers Project", "https://protobuf.dev/programming-guides/proto3/", "wire-safe, wire-compatible and wire-unsafe changes", "Wire safety can still break source code, JSON/text formats or business meaning."),
    S("confluent.registry.api", "Schema Registry API", "Confluent", "https://docs.confluent.io/platform/current/schema-registry/develop/api.html", "observed subject, version, compatibility and reference API behavior", "One vendor API is implementation evidence, not universal registry semantics.", "official_implementation_documentation"),
    S("confluent.evolution", "Schema Evolution and Compatibility", "Confluent", "https://docs.confluent.io/platform/current/schema-registry/fundamentals/schema-evolution.html", "backward, forward, full and transitive compatibility profiles", "Named modes depend on schema format and configured history scope.", "official_implementation_documentation"),
    S("apicurio.registry", "Apicurio Registry Documentation", "Apicurio Project", "https://www.apicur.io/registry/docs/apicurio-registry/3.0.x/getting-started/assembly-intro-to-the-registry.html", "independent registry artifact/group/version/rule implementation", "A second implementation does not constitute qualification or portability.", "official_implementation_documentation"),
    S("odcs.3.1", "Open Data Contract Standard 3.1", "Bitol / LF AI & Data", "https://bitol-io.github.io/open-data-contract-standard/latest/", "contract identity, schema, quality, SLA, team, roles, support and server declarations", "A document standard does not define acceptance authority, breach adjudication or observed attainment."),
    S("odcs.schema", "ODCS 3.1 JSON Schema", "Bitol / LF AI & Data", "https://github.com/bitol-io/open-data-contract-standard/tree/main/schema", "machine validation of ODCS documents", "Schema-valid ODCS is not a mutually accepted or fulfilled contract."),
    S("odps.4.1", "Open Data Product Specification 4.1", "Linux Foundation Open Data Products", "https://opendataproducts.org/v4.1/", "data-product outputs, access, quality, SLA, license, pricing and references", "A product-description standard does not transfer source, schema or contract authority."),
    S("dqv", "Data Quality Vocabulary", "W3C", "https://www.w3.org/TR/vocab-dqv/", "quality measurements, metrics, annotations and certificates", "A declared or observed quality measurement is not automatically a contractual breach."),
    S("openslo", "OpenSLO Specification", "OpenSLO Project", "https://github.com/OpenSLO/OpenSLO", "service, indicator and objective declarations", "An objective declaration is not attainment, SLA acceptance or remedy authority."),
    S("openapi.3.1.1", "OpenAPI Specification 3.1.1", "OpenAPI Initiative", "https://spec.openapis.org/oas/v3.1.1.html", "HTTP API operation and schema contracts", "An API document is one possible data-port binding, not a data contract by itself."),
    S("asyncapi.3", "AsyncAPI Specification 3.0", "AsyncAPI Initiative", "https://www.asyncapi.com/docs/reference/specification/v3.0.0", "asynchronous channel, operation, message and schema contracts", "A channel schema is not consumer acceptance or delivery evidence."),
    S("rfc8594", "RFC 8594: The Sunset HTTP Header Field", "IETF", "https://www.rfc-editor.org/rfc/rfc8594", "machine-readable sunset signaling", "Sunset signaling does not prove consumer migration or safe termination."),
    S("semver2", "Semantic Versioning 2.0.0", "Semantic Versioning Project", "https://semver.org/spec/v2.0.0.html", "declared public-API compatibility versioning", "A version label cannot replace format-specific or contract-specific compatibility evaluation."),
]


SCHEMA = "schema_registry"
CONTRACT = "data_contract"


def context(slug: str, name: str, question: str, outside: list[str]) -> dict:
    return {"context_id": f"context.{slug}", "name": name, "sovereign_question": question, "inside": ["exact identities", "editioned decisions", "typed operations", "laws", "refusals"], "outside": outside + ["provider qualification", "business acceptance outside an explicit authority port"], "owner": f"authority.{slug}", "status": "specified_candidate"}


CONTEXTS = [
    context("schema_registry.subject_identity", "Schema subject identity", "What stable namespace and subject identity groups structural schema editions without becoming a topic, table or artifact?", ["schema parsing", "physical topic/table ownership"]),
    context("schema_registry.artifact_profile", "Schema artifact profile", "How is one exact format/dialect artifact parsed, validated, canonicalized and digested with loss visible?", ["registry state", "business semantics"]),
    context("schema_registry.version_registry", "Schema version registry", "How are immutable subject-scoped schema editions proposed, registered, resolved, deprecated and receipted?", ["compatibility algorithm ownership", "consumer migration"]),
    context("schema_registry.compatibility", "Schema compatibility", "Under an exact format, direction, history cut and feature policy, may designated readers and writers interoperate?", ["business substitutability", "acceptance authority"]),
    context("schema_registry.reference_closure", "Schema reference closure", "Which exact referenced resources and editions form a sealed schema closure?", ["network retrieval implementation", "artifact registration authority"]),
    context("schema_registry.migration_lifecycle", "Schema migration lifecycle", "What consumer-aware change, rollout, sunset and in-flight disposition is required beyond syntactic compatibility?", ["deployment execution", "consumer business acceptance"]),
    context("data_contract.contract_identity", "Data contract identity", "What immutable edition of which governed producer-consumer promise is being drafted, published, resolved or superseded?", ["schema ownership", "party identity authority"]),
    context("data_contract.party_purpose_roles", "Contract parties, purposes and roles", "Which exact parties, purposes, roles, delegations and validity intervals authorize contract actions?", ["enterprise identity proofing", "legal interpretation"]),
    context("data_contract.data_schema_binding", "Contract data and schema bindings", "Which editioned output/input port, dataset identity and schema closure does a contract reference without acquiring their truth?", ["dataset/source truth", "schema compatibility ownership"]),
    context("data_contract.quality_service_obligations", "Contract quality and service obligations", "Which purpose-scoped measurable obligations, windows, evidence requirements and remedies are declared?", ["quality measurement execution", "breach adjudication"]),
    context("data_contract.compatibility_acceptance", "Contract compatibility and acceptance", "What changed, what remains compatible, and which authorized party accepts or rejects the exact edition under stated conditions?", ["schema compatibility ownership", "effect execution beyond acceptance recording"]),
    context("data_contract.change_breach_case", "Contract change and breach cases", "How are proposed changes, possible breaches, evidence, notices, remedies and closure residuals governed?", ["measurement source truth", "remedy execution authority"]),
    context("data_contract.deprecation_exit", "Contract deprecation and exit", "How are notice, consumer census, export, in-flight obligations, termination and retained evidence completed?", ["data deletion authority", "supplier execution"]),
]


DECISIONS: dict[str, list[str]] = {
    "schema_registry.subject_identity": ["namespace_authority", "subject_naming", "alias_policy", "collision_policy", "retirement_policy"],
    "schema_registry.artifact_profile": ["format_edition", "dialect_vocabulary", "canonicalization_profile", "unknown_feature_posture", "loss_policy"],
    "schema_registry.version_registry": ["version_identity", "ordinal_policy", "deduplication_policy", "registration_preconditions", "deprecation_policy"],
    "schema_registry.compatibility": ["relation_direction", "transitivity", "history_scope", "default_presence_semantics", "unknown_feature_posture"],
    "schema_registry.reference_closure": ["reference_identity", "reference_version_policy", "cycle_policy", "resolution_source", "closure_identity"],
    "schema_registry.migration_lifecycle": ["change_classification", "consumer_census", "blast_radius", "rollout_policy", "sunset_and_in_flight_policy"],
    "data_contract.contract_identity": ["identity_scope", "document_profile", "edition_policy", "canonicalization", "supersession_policy"],
    "data_contract.party_purpose_roles": ["party_identity", "purpose_scope", "role_authority", "delegation_policy", "validity_policy"],
    "data_contract.data_schema_binding": ["port_identity", "dataset_identity", "schema_binding", "physical_occurrence_posture", "residual_policy"],
    "data_contract.quality_service_obligations": ["obligation_measure", "threshold_predicate", "service_window", "evidence_requirement", "remedy_posture"],
    "data_contract.compatibility_acceptance": ["compatibility_relation", "acceptance_criteria", "acceptance_authority", "conditional_acceptance", "evidence_policy"],
    "data_contract.change_breach_case": ["change_classification", "breach_materiality", "notice_policy", "remediation_authority", "closure_evidence"],
    "data_contract.deprecation_exit": ["notice_period", "consumer_census", "in_flight_disposition", "exit_completeness", "termination_authority"],
}


DECISION_ROWS = [{"decision_id": f"decision.{context}.{decision}", "owner_context": f"context.{context}", "question": f"What exact {decision.replace('_', ' ')} applies?", "default": None, "default_law": "forbidden", "status": "declared"} for context, values in DECISIONS.items() for decision in values]


def O(context: str, name: str, inputs: list[str], output: str, purity: str = "pure", intent: str | None = None, receipt: str | None = None) -> dict:
    row = {"operation_ref": f"operation.{context}.{name}", "input_types": inputs, "output_type": f"Result<{output},{context.split('.')[-1].title().replace('_', '')}Refusal>", "purity": purity}
    if intent: row["effect_intent_type"] = intent
    if receipt: row["receipt_type"] = receipt
    return row


SPECS = [
    {"id":"library.schema_registry.subject_identity","ctx":"schema_registry.subject_identity","name":"Schema Subject Identity","kind":"semantic_pure","types":["SchemaSubjectId","SubjectNamespaceId","SubjectName","SubjectAlias","SubjectStatus","SubjectEdition","NamespaceAuthorityRef","SubjectRegistration","SubjectResolution","SubjectRetirementPlan","SubjectRefusal"],"ops":[O("schema_registry.subject_identity","validate_subject",["SchemaSubject","SubjectIdentityPolicy"],"SchemaSubjectId"),O("schema_registry.subject_identity","plan_registration",["SchemaSubject","SubjectIdentityPolicy"],"SubjectRegistration"),O("schema_registry.subject_identity","resolve_subject",["SubjectQuery","SubjectSnapshot"],"SubjectResolution"),O("schema_registry.subject_identity","plan_retirement",["SchemaSubjectId","SubjectSnapshot","RetirementPolicy"],"SubjectRetirementPlan")],"laws":["Schema subject is not schema version, artifact, topic, table, dataset or data contract.","Alias is a directional resolution assertion and never identity or authority.","Retirement preserves historical resolution and cannot recycle identity silently.","Provider naming conventions cannot select namespace semantics."],"errors":["NamespaceAuthorityMissing","SubjectCollision","AliasConflict","SubjectUnknown","RetirementBlocked"],"deps":[],"evidence":["source.schema-contract.confluent.registry.api","source.schema-contract.apicurio.registry"]},
    {"id":"library.schema_registry.artifact_profile","ctx":"schema_registry.artifact_profile","name":"Schema Artifact Profile","kind":"semantic_pure","types":["SchemaArtifact","SchemaBytes","SchemaFormat","SchemaDialect","VocabularyProfile","ParsedSchema","SchemaValidationReport","CanonicalSchema","CanonicalizationProfile","SchemaDigest","SchemaLoss","ArtifactProfileRefusal"],"ops":[O("schema_registry.artifact_profile","parse_artifact",["SchemaArtifact","ArtifactProfile"],"ParsedSchema"),O("schema_registry.artifact_profile","validate_artifact",["ParsedSchema","VocabularyProfile"],"SchemaValidationReport"),O("schema_registry.artifact_profile","canonicalize_artifact",["ParsedSchema","CanonicalizationProfile"],"CanonicalSchema"),O("schema_registry.artifact_profile","digest_canonical",["CanonicalSchema","DigestProfile"],"SchemaDigest")],"laws":["Parse success, meta-schema validity, instance validity and compatibility are distinct.","Canonicalization is format/profile scoped and never invents semantic equivalence.","Unknown keywords, annotations and unsupported vocabularies retain their exact posture.","Schema structure is not business meaning or a data contract."],"errors":["FormatUnsupported","DialectUnknown","VocabularyUnsupported","SchemaInvalid","CanonicalizationLossUnauthorized"],"deps":[],"evidence":["source.schema-contract.jsonschema.core.2020-12","source.schema-contract.jsonschema.validation.2020-12","source.schema-contract.avro.current","source.schema-contract.protobuf.proto3"]},
    {"id":"library.schema_registry.version_registry","ctx":"schema_registry.version_registry","name":"Schema Version Registry","kind":"effect_port","types":["SchemaVersionId","VersionOrdinal","SchemaVersion","RegistrationRequest","RegistrationPrecondition","RegistrationIntent","RegistrationReceipt","VersionSnapshot","VersionQuery","DeprecationIntent","DeprecationReceipt","VersionRegistryRefusal"],"ops":[O("schema_registry.version_registry","plan_registration",["RegistrationRequest","VersionSnapshot","RegistrationPolicy"],"RegistrationIntent"),O("schema_registry.version_registry","apply_registration_receipt",["RegistrationIntent","RegistrationReceipt","VersionSnapshot"],"VersionSnapshot"),O("schema_registry.version_registry","resolve_version",["VersionQuery","VersionSnapshot"],"SchemaVersion"),O("schema_registry.version_registry","plan_deprecation",["SchemaVersionId","VersionSnapshot","DeprecationPolicy"],"DeprecationIntent")],"laws":["Version identity is immutable and distinct from ordinal, content digest and latest alias.","Registration intent, provider acceptance, durable registry occurrence and compatibility approval are distinct.","Duplicate-content behavior is an explicit policy and never rewrites edition history.","Deprecation is not deletion, retirement or consumer migration."],"errors":["SubjectUnknown","VersionConflict","DigestConflict","PreconditionFailed","RegistrationCompletionUnknown","IllegalDeprecation"],"deps":["library.schema_registry.subject_identity","library.schema_registry.artifact_profile"],"evidence":["source.schema-contract.confluent.registry.api","source.schema-contract.apicurio.registry"]},
    {"id":"library.schema_registry.compatibility","ctx":"schema_registry.compatibility","name":"Schema Compatibility","kind":"algorithm_pure","types":["CompatibilityRelation","CompatibilityDirection","TransitivityPolicy","ReaderSchemaRef","WriterSchemaRef","ReaderWriterPair","HistoryCut","CompatibilityProfile","CompatibilityFinding","CompatibilityVerdict","CompatibilityResidual","CompatibilityRefusal"],"ops":[O("schema_registry.compatibility","evaluate_pair",["ReaderWriterPair","CompatibilityProfile"],"CompatibilityVerdict"),O("schema_registry.compatibility","evaluate_history",["SchemaVersion","HistoryCut","CompatibilityProfile"],"CompatibilityVerdict"),O("schema_registry.compatibility","explain_incompatibility",["CompatibilityVerdict"],"CompatibilityFindingSet"),O("schema_registry.compatibility","compare_profiles",["CompatibilityProfile","CompatibilityProfile"],"ProfileRelation")],"laws":["Reader/writer compatibility is directional, format-editioned and profile scoped.","Backward, forward, full and transitive labels have no meaning without exact history and format policy.","Wire-safe, source-compatible, value-preserving and business-substitutable are distinct relations.","Unknown or unsupported features produce indeterminate/refusal, never compatible by omission."],"errors":["ModeUnbound","FormatAlgorithmUnavailable","HistoryIncomplete","FeatureUnsupported","CompatibilityIndeterminate"],"deps":["library.schema_registry.artifact_profile","library.schema_registry.version_registry"],"evidence":["source.schema-contract.avro.current","source.schema-contract.protobuf.proto3","source.schema-contract.confluent.evolution"]},
    {"id":"library.schema_registry.reference_closure","ctx":"schema_registry.reference_closure","name":"Schema Reference Closure","kind":"semantic_pure","types":["SchemaReference","SchemaResourceId","ReferenceEdge","ReferenceGraph","ReferenceCycle","ResolutionSource","ResolutionRequest","ResolutionResult","ResolvedSchemaResource","ResolvedClosure","ClosureDigest","ReferenceClosureRefusal"],"ops":[O("schema_registry.reference_closure","enumerate_references",["ParsedSchema","ReferencePolicy"],"ReferenceGraph"),O("schema_registry.reference_closure","plan_resolution",["ReferenceGraph","ResolutionCatalog","ReferencePolicy"],"ResolutionRequestSet"),O("schema_registry.reference_closure","seal_closure",["ReferenceGraph","ResolutionResultSet","ClosurePolicy"],"ResolvedClosure"),O("schema_registry.reference_closure","compare_closures",["ResolvedClosure","ResolvedClosure"],"ClosureDiff")],"laws":["Schema artifact identity and exact resolved reference-closure identity are distinct.","Canonical URI is an identifier and not necessarily a network location.","Floating references, cycles, dynamic scope and unresolved resources are explicit policy facts.","Remote retrieval success does not grant registration or trust authority."],"errors":["ReferenceMissing","ReferenceAmbiguous","CycleForbidden","DynamicScopeUnsupported","ResolutionUnavailable","ClosureChanged"],"deps":["library.schema_registry.artifact_profile"],"evidence":["source.schema-contract.jsonschema.core.2020-12","source.schema-contract.confluent.registry.api","source.schema-contract.avro.current"]},
    {"id":"library.schema_registry.migration_lifecycle","ctx":"schema_registry.migration_lifecycle","name":"Schema Migration Lifecycle","kind":"policy_pure","types":["SchemaChangeSet","ChangeClassification","ConsumerOccurrenceRef","ConsumerCensus","BlastRadius","MigrationStage","MigrationPlan","RolloutGate","SunsetNotice","InFlightDisposition","MigrationOutcome","MigrationRefusal"],"ops":[O("schema_registry.migration_lifecycle","classify_change",["SchemaChangeSet","CompatibilityVerdict","ChangePolicy"],"ChangeClassification"),O("schema_registry.migration_lifecycle","assess_impact",["SchemaChangeSet","ConsumerCensus","ImpactPolicy"],"BlastRadius"),O("schema_registry.migration_lifecycle","plan_migration",["SchemaChangeSet","BlastRadius","MigrationPolicy"],"MigrationPlan"),O("schema_registry.migration_lifecycle","plan_sunset",["MigrationPlan","ConsumerCensus","SunsetPolicy"],"SunsetNotice")],"laws":["Syntactic compatibility is not zero impact, safe rollout or consumer acceptance.","Registration, deployment, migration, activation, sunset and retirement are distinct lifecycle events.","Unknown consumers and in-flight data remain explicit blast-radius residuals.","Rollback is not assumed value-preserving after writers use new representable values."],"errors":["ChangeClassificationUnknown","ConsumerCensusIncomplete","BlastRadiusUnknown","MigrationOrderInvalid","ApprovalMissing","SunsetTooEarly"],"deps":["library.schema_registry.compatibility","library.schema_registry.reference_closure"],"evidence":["source.schema-contract.protobuf.proto3","source.schema-contract.confluent.evolution","source.schema-contract.rfc8594","source.schema-contract.semver2"]},
    {"id":"library.data_contract.contract_identity","ctx":"data_contract.contract_identity","name":"Data Contract Identity","kind":"effect_port","types":["DataContractId","DataContractEdition","DataContractVersion","ContractDocumentProfile","CanonicalContract","ContractDigest","ContractStatus","SupersessionRelation","ContractPublicationIntent","ContractPublicationReceipt","ContractResolution","ContractIdentityRefusal"],"ops":[O("data_contract.contract_identity","validate_contract",["ContractDocument","ContractDocumentProfile"],"CanonicalContract"),O("data_contract.contract_identity","plan_publication",["CanonicalContract","ContractSnapshot","PublicationPolicy"],"ContractPublicationIntent"),O("data_contract.contract_identity","apply_publication_receipt",["ContractPublicationIntent","ContractPublicationReceipt","ContractSnapshot"],"ContractSnapshot"),O("data_contract.contract_identity","resolve_edition",["ContractQuery","ContractSnapshot"],"ContractResolution")],"laws":["Contract document, stable contract identity, immutable edition, version label and registry occurrence are distinct.","Published editions are immutable; correction or supersession creates a new edition.","A schema-valid document is not accepted, attained or legally sufficient.","Supersession never rewrites historical acceptance, breach or usage evidence."],"errors":["ContractIdentityAmbiguous","DocumentProfileUnsupported","EditionConflict","DigestMismatch","PublicationCompletionUnknown","SupersessionInvalid"],"deps":[],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.odcs.schema","source.schema-contract.semver2"]},
    {"id":"library.data_contract.party_purpose_roles","ctx":"data_contract.party_purpose_roles","name":"Data Contract Parties Purpose and Roles","kind":"policy_pure","types":["PartyRef","ProducerPartyRef","ConsumerPartyRef","PurposeId","PurposeEdition","ContractRole","RoleAssignment","AuthorityGrantRef","Delegation","ValidityInterval","AuthorityEvaluation","PartyPurposeRefusal"],"ops":[O("data_contract.party_purpose_roles","bind_party_role",["PartyRef","ContractRole","AuthorityGrantRef","ValidityInterval"],"RoleAssignment"),O("data_contract.party_purpose_roles","bind_purpose",["PurposeDeclaration","PurposePolicy"],"PurposeEdition"),O("data_contract.party_purpose_roles","delegate_role",["RoleAssignment","Delegation","DelegationPolicy"],"RoleAssignment"),O("data_contract.party_purpose_roles","evaluate_authority",["ContractAction","RoleAssignmentSet","AuthorityPolicy"],"AuthorityEvaluation")],"laws":["Producer, consumer, owner, steward, custodian, approver and relying party are distinct roles.","Role label is not authority; every action binds an exact valid grant or delegation.","Purpose is editioned, scoped and not inferred from data access or provider tenancy.","Delegation cannot exceed, outlive or silently transfer the delegator grant."],"errors":["PartyUnresolved","PurposeAmbiguous","RoleConflict","AuthorityMissing","DelegationInvalid","ValidityExpired"],"deps":["library.data_contract.contract_identity"],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.odps.4.1"]},
    {"id":"library.data_contract.data_schema_binding","ctx":"data_contract.data_schema_binding","name":"Data Contract Data and Schema Binding","kind":"semantic_pure","types":["DataPortId","DataPortDirection","DataPortProtocol","DatasetIdentityRef","SchemaClosureRef","PhysicalOccurrenceRef","ContractBinding","BindingEdition","BindingResidual","BindingValidation","BindingDiff","DataSchemaBindingRefusal"],"ops":[O("data_contract.data_schema_binding","bind_data_port",["DataPortDeclaration","PortIdentityPolicy"],"DataPortId"),O("data_contract.data_schema_binding","bind_dataset",["DataPortId","DatasetIdentityRef","BindingPolicy"],"ContractBinding"),O("data_contract.data_schema_binding","bind_schema_closure",["ContractBinding","SchemaClosureRef","BindingPolicy"],"ContractBinding"),O("data_contract.data_schema_binding","validate_binding",["ContractBinding","BindingValidationPolicy"],"BindingValidation")],"laws":["A data contract references but never owns dataset, source, schema or physical-location truth.","Port identity, dataset identity, schema closure and physical occurrence are independent bindings.","A location or provider change does not silently change logical port or dataset identity.","Every cross-model translation retains residual fields and declared information loss."],"errors":["PortIdentityUnresolved","DatasetIdentityAmbiguous","SchemaClosureUnbound","PhysicalOccurrenceUnknown","BindingResidualUnaccepted"],"deps":["library.data_contract.contract_identity","library.schema_registry.reference_closure"],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.odps.4.1","source.schema-contract.openapi.3.1.1","source.schema-contract.asyncapi.3"]},
    {"id":"library.data_contract.quality_service_obligations","ctx":"data_contract.quality_service_obligations","name":"Data Contract Quality and Service Obligations","kind":"semantic_pure","types":["ContractObligationId","ObligationKind","MeasureDefinitionRef","ThresholdPredicate","ServiceWindow","FreshnessObligation","AvailabilityObligation","QualityObligation","SupportObligation","EvidenceRequirement","RemedyPosture","ObligationDeclaration","ObligationRefusal"],"ops":[O("data_contract.quality_service_obligations","declare_quality_obligation",["QualityObligation","ObligationPolicy"],"ObligationDeclaration"),O("data_contract.quality_service_obligations","declare_service_obligation",["ServiceObligation","ObligationPolicy"],"ObligationDeclaration"),O("data_contract.quality_service_obligations","derive_evidence_requirement",["ObligationDeclaration","EvidencePolicy"],"EvidenceRequirement"),O("data_contract.quality_service_obligations","validate_obligation_set",["ObligationDeclarationSet","ObligationPolicy"],"ObligationSetValidation")],"laws":["Declared obligation, observation, evaluated attainment, breach finding and remedy are distinct.","Every quality promise binds purpose, population, grain, measure, threshold, window and evidence requirement.","SLO, SLA, support promise, data defect and contractual remedy are not synonyms.","A missing observation is unknown or refused according to policy, never implicit attainment."],"errors":["MeasureUnbound","PopulationUnknown","ThresholdAmbiguous","WindowMissing","EvidenceRequirementIncomplete","RemedyAuthorityMissing"],"deps":["library.data_contract.data_schema_binding"],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.dqv","source.schema-contract.openslo"]},
    {"id":"library.data_contract.compatibility_acceptance","ctx":"data_contract.compatibility_acceptance","name":"Data Contract Compatibility and Acceptance","kind":"effect_port","types":["ContractDiff","ContractCompatibilityRelation","AcceptanceCriteria","AcceptanceAuthorityRef","AcceptanceCondition","AcceptanceEvaluation","AcceptanceIntent","AcceptanceReceipt","RejectionIntent","RejectionReceipt","AcceptanceResidual","ContractAcceptanceRefusal"],"ops":[O("data_contract.compatibility_acceptance","compare_editions",["CanonicalContract","CanonicalContract","ContractCompatibilityPolicy"],"ContractDiff"),O("data_contract.compatibility_acceptance","evaluate_acceptance",["ContractDiff","AcceptanceCriteria","AcceptanceEvidenceSet"],"AcceptanceEvaluation"),O("data_contract.compatibility_acceptance","plan_acceptance",["AcceptanceEvaluation","AcceptanceAuthorityRef"],"AcceptanceIntent"),O("data_contract.compatibility_acceptance","apply_acceptance_receipt",["AcceptanceIntent","AcceptanceReceipt","AcceptanceSnapshot"],"AcceptanceSnapshot")],"laws":["Schema compatibility, contract compatibility, acceptance eligibility and recorded acceptance are distinct.","Acceptance is party, purpose, edition, evidence and validity scoped.","Conditional acceptance preserves every condition and residual until discharged or expired.","No implementation, model or agent may manufacture acceptance authority."],"errors":["CompatibilityUnknown","CriteriaIncomplete","EvidenceInsufficient","AcceptanceAuthorityMissing","ConditionUnowned","AcceptanceCompletionUnknown"],"deps":["library.data_contract.contract_identity","library.data_contract.party_purpose_roles","library.data_contract.quality_service_obligations"],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.odps.4.1"]},
    {"id":"library.data_contract.change_breach_case","ctx":"data_contract.change_breach_case","name":"Data Contract Change and Breach Case","kind":"effect_port","types":["ContractChangeProposal","ChangeImpact","ObligationObservationRef","PossibleBreachFinding","BreachMateriality","ContractCaseId","ContractCase","NoticeIntent","RemediationPlan","RemedyEffectIntent","CaseClosureIntent","CaseClosureReceipt","ChangeBreachRefusal"],"ops":[O("data_contract.change_breach_case","open_change_case",["ContractChangeProposal","ChangeImpact","CasePolicy"],"ContractCase"),O("data_contract.change_breach_case","record_possible_breach",["ObligationObservationRef","ObligationDeclaration","BreachPolicy"],"PossibleBreachFinding"),O("data_contract.change_breach_case","plan_notice_and_remediation",["ContractCase","BreachMateriality","RemediationPolicy"],"RemediationPlan"),O("data_contract.change_breach_case","plan_case_closure",["ContractCase","ClosureEvidenceSet","ClosurePolicy"],"CaseClosureIntent")],"laws":["Change proposal, accepted edition, possible breach, adjudicated breach and remedy effect are distinct.","An observation outside threshold is evidence for a case, not automatically a contractual verdict.","Notice and remediation plans are effect intents and grant no execution authority.","Closure preserves unresolved findings, residual obligations, appeals and recurrence risk."],"errors":["BlastRadiusUnknown","ObservationScopeMismatch","BreachMaterialityUnknown","NoticeAuthorityMissing","RemedyAuthorityMissing","ClosureUnproved"],"deps":["library.data_contract.compatibility_acceptance","library.data_contract.quality_service_obligations"],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.dqv","source.schema-contract.openslo"]},
    {"id":"library.data_contract.deprecation_exit","ctx":"data_contract.deprecation_exit","name":"Data Contract Deprecation and Exit","kind":"effect_port","types":["DeprecationNotice","NoticePeriod","ConsumerOccurrenceRef","ConsumerCensus","ContractExportPackage","InFlightObligation","InFlightDisposition","TerminationEligibility","TerminationIntent","TerminationReceipt","ResidualObligation","ExitCompletion","ContractExitRefusal"],"ops":[O("data_contract.deprecation_exit","plan_deprecation",["DataContractEdition","DeprecationPolicy"],"DeprecationNotice"),O("data_contract.deprecation_exit","evaluate_consumer_census",["ConsumerCensus","CensusPolicy"],"CensusEvaluation"),O("data_contract.deprecation_exit","plan_exit",["DataContractEdition","ConsumerCensus","ExitPolicy"],"ContractExportPackage"),O("data_contract.deprecation_exit","plan_termination",["ContractExportPackage","InFlightDispositionSet","TerminationPolicy"],"TerminationIntent")],"laws":["Deprecation, sunset, supersession, termination, deletion and completed exit are distinct.","Deleting a registry record is not export, consumer migration, obligation disposition or evidence retention.","Every known consumer and in-flight obligation receives exactly one explicit disposition.","Termination eligibility does not authorize termination or prove downstream deletion."],"errors":["ConsumerCensusIncomplete","NoticePeriodUnsatisfied","ExportPackageIncomplete","InFlightDispositionMissing","ResidualObligationUnowned","TerminationAuthorityMissing"],"deps":["library.data_contract.change_breach_case","library.data_contract.contract_identity"],"evidence":["source.schema-contract.odcs.3.1","source.schema-contract.odps.4.1","source.schema-contract.rfc8594"]},
]


def materialize(spec: dict) -> dict:
    ctx = spec["ctx"]
    effect = "pure_effect_intents" if spec["kind"] == "effect_port" else "pure_no_io"
    return {"library_id":spec["id"],"name":spec["name"],"library_kind":spec["kind"],"semantic_owner_context":f"context.{ctx}","status":"specified","candidate_responsibility":spec["name"].lower(),"effect_boundary":effect,"public_types":spec["types"],"public_traits":[spec["name"].replace(" ","")+"Algebra"],"operation_refs":[op["operation_ref"] for op in spec["ops"]],"operations":spec["ops"],"decision_refs":[f"decision.{ctx}.{d}" for d in DECISIONS[ctx]],"configuration_contracts":[spec["name"].replace(" ","")+"Policy"],"laws":spec["laws"],"invariants":["published editions are immutable","all authority and evidence are exact-subject, edition, purpose, scope and time bound","unknown, absent, refused, failed and completion-unknown remain distinct"],"error_contracts":spec["errors"]+["UnsupportedEdition","InvalidConfiguration","ResourceBudgetExceeded"],"dependencies":spec["deps"],"evidence_refs":spec["evidence"],"oracles":["canonical positive fixtures","negative twins","property laws","state-machine model tests","malformed and boundary corpus","edition migration corpus","two independent differential implementations"],"gaps":["No implementation is qualified; two independent implementations and executed conformance remain required."],"must_not_own":["source or dataset truth","business semantics outside the contract","provider qualification","legal interpretation","unauthorized external effects"],"qualification_required":False}


LIBRARIES = [materialize(spec) for spec in SPECS]


NEGATIVES = [
    ("subject_topic", "A schema subject is the broker topic or table.", "Keep registry grouping identity separate from physical resources."),
    ("parse_compatible", "A schema parses and validates, therefore it is compatible.", "Run exact format, direction, history and feature policy."),
    ("compatible_substitutable", "Wire compatibility proves source, application and business substitutability.", "Retain each compatibility relation separately."),
    ("latest_identity", "The latest alias is an immutable schema identity.", "Resolve an exact version and closure."),
    ("reference_location", "A canonical schema URI is necessarily a retrievable location.", "Use a declared resolution source and sealed closure."),
    ("compatible_safe_rollout", "A compatible schema change has zero migration impact.", "Require consumer census, blast radius and rollout plan."),
    ("contract_valid_accepted", "An ODCS-valid document is an accepted contract.", "Require explicit party authority, criteria, evidence and receipt."),
    ("contract_owns_dataset", "A data contract owns dataset and source truth.", "Reference exact external identities through governed bindings."),
    ("declared_attained", "A declared quality or service obligation is attained.", "Bind and evaluate an exact observation cut separately."),
    ("threshold_breach", "A threshold violation automatically proves contractual breach.", "Open an evidence-bearing case under materiality and authority rules."),
    ("acceptance_compatibility", "Compatibility automatically records consumer acceptance.", "Emit a separately authorized acceptance intent and receipt."),
    ("deprecation_exit", "Deprecation or deletion completes supplier exit.", "Disposition consumers, data, schemas, obligations and evidence."),
    ("agent_approval", "A model or agent may accept a contract, waive a breach or authorize termination.", "Refuse and require the named authority."),
]


NEGATIVE_ROWS = [{"negative_id":f"negative.schema-contract.{slug}","unsafe_inference":unsafe,"required_behavior":behavior,"status":"active"} for slug,unsafe,behavior in NEGATIVES]


COMPILER_ROWS = []
for lib in LIBRARIES:
    stem = lib["library_id"].removeprefix("library.")
    COMPILER_ROWS += [
        {"record_kind":"capability_requirement","requirement_id":f"requirement.{stem}.implementation","subject_ref":lib["library_id"],"required_operations":lib["operation_refs"],"required_decisions":lib["decision_refs"],"fallback_law":"refuse","status":"declared"},
        {"record_kind":"capability_offer","offer_id":f"offer.{stem}.reference","subject_ref":lib["library_id"],"claimed_operations":lib["operation_refs"],"qualified_implementation_count":0,"portable":False,"selectable":False,"status":"specified_unimplemented"},
        {"record_kind":"binding_rule","binding_rule_id":f"binding.{stem}","requirement_ref":f"requirement.{stem}.implementation","offer_ref":f"offer.{stem}.reference","structural_match":True,"selection_law":"Structural match never promotes an unqualified or non-portable implementation.","selectable":False,"status":"declared"},
    ]


FILES = {"sources.jsonl":SOURCES,"bounded-contexts.jsonl":CONTEXTS,"decision-points.jsonl":DECISION_ROWS,"library-contracts.jsonl":LIBRARIES,"compiler-contracts.jsonl":COMPILER_ROWS,"negative-twins.jsonl":NEGATIVE_ROWS}


def main() -> None:
    digests = {}
    for name, rows in FILES.items():
        payload = lines(rows); (ROOT / name).write_text(payload, encoding="utf-8")
        digests[name] = {"records":len(rows),"sha256":hashlib.sha256(payload.encode()).hexdigest()}
    manifest = {"manifest_id":"schema_data_contract_governance_v0_1_0","as_of":AS_OF,"edition":EDITION,"status":"specified_unimplemented_open_world","files":digests,"completion_claim":False,"qualified_implementation_count":0}
    (ROOT / "manifest.json").write_text(json.dumps(manifest,indent=2,sort_keys=True)+"\n",encoding="utf-8")
    print(f"BUILD PASS schema/data-contract governance: {len(SOURCES)} sources, {len(CONTEXTS)} contexts, {len(DECISION_ROWS)} decisions, {len(LIBRARIES)} exact libraries, {len(COMPILER_ROWS)} compiler contracts")


if __name__ == "__main__": main()
