"""Vertical pressure tests, adversarial non-collapse tests and saturation evidence."""

VERTICAL_CASES = [{'vertical_case_id': 'vertical.presentation_sota.banking',
  'industry': 'banking',
  'required_intent_refs': ['intent.presentation_sota.headline_status',
                           'intent.presentation_sota.progress_to_target',
                           'intent.presentation_sota.compare_categories',
                           'intent.presentation_sota.rank_entities'],
  'specialist_ref': 'specialist.presentation_sota.process_intelligence',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.capital_markets',
  'industry': 'capital_markets',
  'required_intent_refs': ['intent.presentation_sota.compare_two_states',
                           'intent.presentation_sota.variance_to_baseline',
                           'intent.presentation_sota.variance_to_plan',
                           'intent.presentation_sota.contribution_to_change'],
  'specialist_ref': 'specialist.presentation_sota.product_journey',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.insurance',
  'industry': 'insurance',
  'required_intent_refs': ['intent.presentation_sota.composition_now',
                           'intent.presentation_sota.hierarchy_size',
                           'intent.presentation_sota.trend_over_time',
                           'intent.presentation_sota.compare_time_series'],
  'specialist_ref': 'specialist.presentation_sota.observability_investigation',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.supply_chain',
  'industry': 'supply_chain',
  'required_intent_refs': ['intent.presentation_sota.composition_over_time',
                           'intent.presentation_sota.seasonality',
                           'intent.presentation_sota.change_points',
                           'intent.presentation_sota.before_after'],
  'specialist_ref': 'specialist.presentation_sota.planning',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.manufacturing',
  'industry': 'manufacturing',
  'required_intent_refs': ['intent.presentation_sota.cumulative_progress',
                           'intent.presentation_sota.event_timeline',
                           'intent.presentation_sota.state_changes',
                           'intent.presentation_sota.time_of_day_pattern'],
  'specialist_ref': 'specialist.presentation_sota.finance_market',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.process_industries',
  'industry': 'process_industries',
  'required_intent_refs': ['intent.presentation_sota.distribution',
                           'intent.presentation_sota.compare_distributions',
                           'intent.presentation_sota.outliers',
                           'intent.presentation_sota.tail_risk'],
  'specialist_ref': 'specialist.presentation_sota.project_controls',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.construction',
  'industry': 'construction',
  'required_intent_refs': ['intent.presentation_sota.percentile_position',
                           'intent.presentation_sota.spread_and_center',
                           'intent.presentation_sota.multimodality',
                           'intent.presentation_sota.skewness'],
  'specialist_ref': 'specialist.presentation_sota.geospatial',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.retail',
  'industry': 'retail',
  'required_intent_refs': ['intent.presentation_sota.sampling_variability',
                           'intent.presentation_sota.uncertainty_estimate',
                           'intent.presentation_sota.relationship',
                           'intent.presentation_sota.multivariate_relationship'],
  'specialist_ref': 'specialist.presentation_sota.graph_knowledge',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.cpg',
  'industry': 'cpg',
  'required_intent_refs': ['intent.presentation_sota.correlation_structure',
                           'intent.presentation_sota.regression_fit',
                           'intent.presentation_sota.residual_diagnostics',
                           'intent.presentation_sota.interaction_effect'],
  'specialist_ref': 'specialist.presentation_sota.industrial_signal',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.healthcare',
  'industry': 'healthcare',
  'required_intent_refs': ['intent.presentation_sota.cluster_structure',
                           'intent.presentation_sota.dimension_reduction',
                           'intent.presentation_sota.pairwise_comparison',
                           'intent.presentation_sota.tradeoff_frontier'],
  'specialist_ref': 'specialist.presentation_sota.scientific_field',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.pharma',
  'industry': 'pharma',
  'required_intent_refs': ['intent.presentation_sota.forecast',
                           'intent.presentation_sota.forecast_compare',
                           'intent.presentation_sota.scenario_compare',
                           'intent.presentation_sota.what_if'],
  'specialist_ref': 'specialist.presentation_sota.digital_twin',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.telecom',
  'industry': 'telecom',
  'required_intent_refs': ['intent.presentation_sota.optimization_tradeoff',
                           'intent.presentation_sota.recommended_action',
                           'intent.presentation_sota.decision_alternatives',
                           'intent.presentation_sota.sensitivity'],
  'specialist_ref': 'specialist.presentation_sota.storytelling',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.energy',
  'industry': 'energy',
  'required_intent_refs': ['intent.presentation_sota.constraint_binding',
                           'intent.presentation_sota.risk_reward',
                           'intent.presentation_sota.known_funnel',
                           'intent.presentation_sota.unknown_paths'],
  'specialist_ref': 'specialist.presentation_sota.formal_reporting',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.utilities',
  'industry': 'utilities',
  'required_intent_refs': ['intent.presentation_sota.retention',
                           'intent.presentation_sota.stickiness',
                           'intent.presentation_sota.segment_overlap',
                           'intent.presentation_sota.lifecycle_stage'],
  'specialist_ref': 'specialist.presentation_sota.computational_document',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.logistics',
  'industry': 'logistics',
  'required_intent_refs': ['intent.presentation_sota.journey_dropoff',
                           'intent.presentation_sota.conversion_latency',
                           'intent.presentation_sota.cohort_compare',
                           'intent.presentation_sota.impact_analysis'],
  'specialist_ref': 'specialist.presentation_sota.embedded_analytics',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.transport',
  'industry': 'transport',
  'required_intent_refs': ['intent.presentation_sota.process_discovery',
                           'intent.presentation_sota.process_variants',
                           'intent.presentation_sota.process_conformance',
                           'intent.presentation_sota.process_bottleneck'],
  'specialist_ref': 'specialist.presentation_sota.self_service_visual_discovery',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.government',
  'industry': 'government',
  'required_intent_refs': ['intent.presentation_sota.throughput_duration',
                           'intent.presentation_sota.rework',
                           'intent.presentation_sota.handoff_delay',
                           'intent.presentation_sota.case_deviation'],
  'specialist_ref': 'specialist.presentation_sota.decision_support',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.cybersecurity',
  'industry': 'cybersecurity',
  'required_intent_refs': ['intent.presentation_sota.object_centric_flow',
                           'intent.presentation_sota.process_change_compare',
                           'intent.presentation_sota.root_cause_contrast',
                           'intent.presentation_sota.anomaly_over_time'],
  'specialist_ref': 'specialist.presentation_sota.security_investigation',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.sre_observability',
  'industry': 'sre_observability',
  'required_intent_refs': ['intent.presentation_sota.live_monitoring',
                           'intent.presentation_sota.service_topology',
                           'intent.presentation_sota.latency_trace',
                           'intent.presentation_sota.code_profile'],
  'specialist_ref': 'specialist.presentation_sota.network_operations',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.sales',
  'industry': 'sales',
  'required_intent_refs': ['intent.presentation_sota.log_inspection',
                           'intent.presentation_sota.slo_health',
                           'intent.presentation_sota.error_budget',
                           'intent.presentation_sota.dependency_failure'],
  'specialist_ref': 'specialist.presentation_sota.construction_bim',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.marketing',
  'industry': 'marketing',
  'required_intent_refs': ['intent.presentation_sota.geographic_distribution',
                           'intent.presentation_sota.location_magnitude',
                           'intent.presentation_sota.spatial_flow',
                           'intent.presentation_sota.spatial_field'],
  'specialist_ref': 'specialist.presentation_sota.medical_imaging',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.product_analytics',
  'industry': 'product_analytics',
  'required_intent_refs': ['intent.presentation_sota.route_deviation',
                           'intent.presentation_sota.network_structure',
                           'intent.presentation_sota.network_dependency',
                           'intent.presentation_sota.ego_context'],
  'specialist_ref': 'specialist.presentation_sota.process_intelligence',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.finance_fp_and_a',
  'industry': 'finance_fp_and_a',
  'required_intent_refs': ['intent.presentation_sota.community_structure',
                           'intent.presentation_sota.graph_path',
                           'intent.presentation_sota.signal_trend',
                           'intent.presentation_sota.signal_relationship'],
  'specialist_ref': 'specialist.presentation_sota.product_journey',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.hr',
  'industry': 'hr',
  'required_intent_refs': ['intent.presentation_sota.condition_intervals',
                           'intent.presentation_sota.frequency_content',
                           'intent.presentation_sota.process_control',
                           'intent.presentation_sota.scientific_scalar_field'],
  'specialist_ref': 'specialist.presentation_sota.observability_investigation',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.scientific_research',
  'industry': 'scientific_research',
  'required_intent_refs': ['intent.presentation_sota.scientific_vector_field',
                           'intent.presentation_sota.3d_structure',
                           'intent.presentation_sota.volume_inspection',
                           'intent.presentation_sota.simulation_field_compare'],
  'specialist_ref': 'specialist.presentation_sota.planning',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.engineering',
  'industry': 'engineering',
  'required_intent_refs': ['intent.presentation_sota.project_schedule',
                           'intent.presentation_sota.resource_capacity',
                           'intent.presentation_sota.earned_value_status',
                           'intent.presentation_sota.milestone_risk'],
  'specialist_ref': 'specialist.presentation_sota.finance_market',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.digital_twins',
  'industry': 'digital_twins',
  'required_intent_refs': ['intent.presentation_sota.schedule_variance',
                           'intent.presentation_sota.market_price_action',
                           'intent.presentation_sota.yield_term_structure',
                           'intent.presentation_sota.portfolio_drawdown'],
  'specialist_ref': 'specialist.presentation_sota.project_controls',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.education',
  'industry': 'education',
  'required_intent_refs': ['intent.presentation_sota.market_depth',
                           'intent.presentation_sota.portfolio_contribution',
                           'intent.presentation_sota.incident_sequence',
                           'intent.presentation_sota.entity_risk_context'],
  'specialist_ref': 'specialist.presentation_sota.geospatial',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.media',
  'industry': 'media',
  'required_intent_refs': ['intent.presentation_sota.attack_technique_coverage',
                           'intent.presentation_sota.security_posture',
                           'intent.presentation_sota.detection_concentration',
                           'intent.presentation_sota.network_path_health'],
  'specialist_ref': 'specialist.presentation_sota.graph_knowledge',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.public_safety',
  'industry': 'public_safety',
  'required_intent_refs': ['intent.presentation_sota.hop_degradation',
                           'intent.presentation_sota.routing_change',
                           'intent.presentation_sota.outage_scope',
                           'intent.presentation_sota.traffic_hotspot'],
  'specialist_ref': 'specialist.presentation_sota.industrial_signal',
  'acceptance_classes': ['semantic_preservation',
                         'interaction_authority',
                         'accessibility_equivalence',
                         'uncertainty_missingness',
                         'provenance',
                         'resource_budget'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.banking.adversarial_1',
  'industry': 'banking',
  'required_intent_refs': ['intent.presentation_sota.geographic_distribution',
                           'intent.presentation_sota.project_schedule'],
  'specialist_ref': 'specialist.presentation_sota.digital_twin',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.capital_markets.adversarial_2',
  'industry': 'capital_markets',
  'required_intent_refs': ['intent.presentation_sota.location_magnitude', 'intent.presentation_sota.resource_capacity'],
  'specialist_ref': 'specialist.presentation_sota.storytelling',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.insurance.adversarial_3',
  'industry': 'insurance',
  'required_intent_refs': ['intent.presentation_sota.spatial_flow', 'intent.presentation_sota.earned_value_status'],
  'specialist_ref': 'specialist.presentation_sota.formal_reporting',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.supply_chain.adversarial_4',
  'industry': 'supply_chain',
  'required_intent_refs': ['intent.presentation_sota.spatial_field', 'intent.presentation_sota.milestone_risk'],
  'specialist_ref': 'specialist.presentation_sota.computational_document',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.manufacturing.adversarial_5',
  'industry': 'manufacturing',
  'required_intent_refs': ['intent.presentation_sota.route_deviation', 'intent.presentation_sota.schedule_variance'],
  'specialist_ref': 'specialist.presentation_sota.embedded_analytics',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.process_industries.adversarial_6',
  'industry': 'process_industries',
  'required_intent_refs': ['intent.presentation_sota.network_structure',
                           'intent.presentation_sota.market_price_action'],
  'specialist_ref': 'specialist.presentation_sota.self_service_visual_discovery',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.construction.adversarial_7',
  'industry': 'construction',
  'required_intent_refs': ['intent.presentation_sota.network_dependency',
                           'intent.presentation_sota.yield_term_structure'],
  'specialist_ref': 'specialist.presentation_sota.decision_support',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.retail.adversarial_8',
  'industry': 'retail',
  'required_intent_refs': ['intent.presentation_sota.ego_context', 'intent.presentation_sota.portfolio_drawdown'],
  'specialist_ref': 'specialist.presentation_sota.security_investigation',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.cpg.adversarial_9',
  'industry': 'cpg',
  'required_intent_refs': ['intent.presentation_sota.community_structure', 'intent.presentation_sota.market_depth'],
  'specialist_ref': 'specialist.presentation_sota.network_operations',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.healthcare.adversarial_10',
  'industry': 'healthcare',
  'required_intent_refs': ['intent.presentation_sota.graph_path', 'intent.presentation_sota.portfolio_contribution'],
  'specialist_ref': 'specialist.presentation_sota.construction_bim',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.pharma.adversarial_11',
  'industry': 'pharma',
  'required_intent_refs': ['intent.presentation_sota.signal_trend', 'intent.presentation_sota.incident_sequence'],
  'specialist_ref': 'specialist.presentation_sota.medical_imaging',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False},
 {'vertical_case_id': 'vertical.presentation_sota.telecom.adversarial_12',
  'industry': 'telecom',
  'required_intent_refs': ['intent.presentation_sota.signal_relationship',
                           'intent.presentation_sota.entity_risk_context'],
  'specialist_ref': 'specialist.presentation_sota.process_intelligence',
  'acceptance_classes': ['negative_twin', 'cross_target_equivalence', 'stale_data', 'unauthorized_interaction'],
  'executed': False,
  'completion_claim': False}]

NEGATIVE_TESTS = [{'test_id': 'negative.presentation_sota.001',
  'left': 'metric_definition',
  'right': 'query_result',
  'law': 'metric_definition != query_result',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.002',
  'left': 'query_result',
  'right': 'visual_encoding',
  'law': 'query_result != visual_encoding',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.003',
  'left': 'visual_encoding',
  'right': 'rendered_pixels',
  'law': 'visual_encoding != rendered_pixels',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.004',
  'left': 'visualization',
  'right': 'dashboard',
  'law': 'visualization != dashboard',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.005',
  'left': 'dashboard',
  'right': 'report_snapshot',
  'law': 'dashboard != report_snapshot',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.006',
  'left': 'report_snapshot',
  'right': 'export_artifact',
  'law': 'report_snapshot != export_artifact',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.007',
  'left': 'dashboard',
  'right': 'alert_occurrence',
  'law': 'dashboard != alert_occurrence',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.008',
  'left': 'alert_occurrence',
  'right': 'notification_delivery',
  'law': 'alert_occurrence != notification_delivery',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.009',
  'left': 'notification_delivery',
  'right': 'human_acknowledgment',
  'law': 'notification_delivery != human_acknowledgment',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.010',
  'left': 'presentation_selection',
  'right': 'business_decision',
  'law': 'presentation_selection != business_decision',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.011',
  'left': 'presentation_filter',
  'right': 'source_entitlement',
  'law': 'presentation_filter != source_entitlement',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.012',
  'left': 'analytical_drill',
  'right': 'domain_workflow_navigation',
  'law': 'analytical_drill != domain_workflow_navigation',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.013',
  'left': 'presentation_annotation',
  'right': 'authoritative_evidence',
  'law': 'presentation_annotation != authoritative_evidence',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.014',
  'left': 'analytical_recommendation',
  'right': 'approval',
  'law': 'analytical_recommendation != approval',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.015',
  'left': 'approval',
  'right': 'operational_effect',
  'law': 'approval != operational_effect',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.016',
  'left': 'live_view',
  'right': 'historical_snapshot',
  'law': 'live_view != historical_snapshot',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.017',
  'left': 'uncertainty_value',
  'right': 'uncertainty_encoding',
  'law': 'uncertainty_value != uncertainty_encoding',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.018',
  'left': 'missing_value',
  'right': 'zero',
  'law': 'missing_value != zero',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.019',
  'left': 'chart_recommendation',
  'right': 'valid_statistical_inference',
  'law': 'chart_recommendation != valid_statistical_inference',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.020',
  'left': 'embed_token',
  'right': 'host_business_authorization',
  'law': 'embed_token != host_business_authorization',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.021',
  'left': 'accessible_equivalent',
  'right': 'optional_alt_text',
  'law': 'accessible_equivalent != optional_alt_text',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.022',
  'left': 'map_image',
  'right': 'spatial_feature',
  'law': 'map_image != spatial_feature',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.023',
  'left': 'map_style',
  'right': 'spatial_data',
  'law': 'map_style != spatial_data',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.024',
  'left': 'tile',
  'right': 'source_resource',
  'law': 'tile != source_resource',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.025',
  'left': 'graph_layout',
  'right': 'graph_identity',
  'law': 'graph_layout != graph_identity',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.026',
  'left': 'notebook_output',
  'right': 'reproducible_result',
  'law': 'notebook_output != reproducible_result',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.027',
  'left': 'spreadsheet_cell_value',
  'right': 'accepted_business_fact',
  'law': 'spreadsheet_cell_value != accepted_business_fact',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.028',
  'left': 'narrative_claim',
  'right': 'validated_evidence',
  'law': 'narrative_claim != validated_evidence',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.029',
  'left': 'view_telemetry',
  'right': 'user_intent',
  'law': 'view_telemetry != user_intent',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.030',
  'left': 'pixel_similarity',
  'right': 'semantic_equivalence',
  'law': 'pixel_similarity != semantic_equivalence',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.031',
  'left': 'process_map',
  'right': 'sankey',
  'law': 'process_map != sankey',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.032',
  'left': 'trace_waterfall',
  'right': 'gantt',
  'law': 'trace_waterfall != gantt',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.033',
  'left': 'cohort_matrix',
  'right': 'generic_heatmap',
  'law': 'cohort_matrix != generic_heatmap',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.034',
  'left': 'network_path',
  'right': 'generic_graph',
  'law': 'network_path != generic_graph',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.035',
  'left': 'medical_measurement_annotation',
  'right': 'clinical_diagnosis',
  'law': 'medical_measurement_annotation != clinical_diagnosis',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.036',
  'left': 'bim_geometry',
  'right': 'physical_asset',
  'law': 'bim_geometry != physical_asset',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.037',
  'left': 'scenario',
  'right': 'probability_distribution',
  'law': 'scenario != probability_distribution',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.038',
  'left': 'confidence_interval',
  'right': 'prediction_interval',
  'law': 'confidence_interval != prediction_interval',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.039',
  'left': 'imputed_value',
  'right': 'observed_value',
  'law': 'imputed_value != observed_value',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.040',
  'left': 'suppressed_value',
  'right': 'missing_value',
  'law': 'suppressed_value != missing_value',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.041',
  'left': 'provisional_value',
  'right': 'final_value',
  'law': 'provisional_value != final_value',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.042',
  'left': 'revised_value',
  'right': 'restated_value',
  'law': 'revised_value != restated_value',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.043',
  'left': 'source_pixels',
  'right': 'display_transform',
  'law': 'source_pixels != display_transform',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.044',
  'left': 'measurement_overlay',
  'right': 'source_observation',
  'law': 'measurement_overlay != source_observation',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.045',
  'left': 'security_detection',
  'right': 'adjudicated_incident',
  'law': 'security_detection != adjudicated_incident',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.046',
  'left': 'incident_presentation',
  'right': 'containment_authority',
  'law': 'incident_presentation != containment_authority',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.047',
  'left': 'network_hop',
  'right': 'service_identity',
  'law': 'network_hop != service_identity',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.048',
  'left': 'routing_path',
  'right': 'business_route',
  'law': 'routing_path != business_route',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.049',
  'left': 'model_revision',
  'right': 'construction_progress_fact',
  'law': 'model_revision != construction_progress_fact',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.050',
  'left': 'planning_grid_edit',
  'right': 'approved_plan',
  'law': 'planning_grid_edit != approved_plan',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.051',
  'left': 'what_if_result',
  'right': 'committed_action',
  'law': 'what_if_result != committed_action',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.052',
  'left': 'renderer_receipt',
  'right': 'semantic_truth',
  'law': 'renderer_receipt != semantic_truth',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.053',
  'left': 'export_delivery_receipt',
  'right': 'recipient_comprehension',
  'law': 'export_delivery_receipt != recipient_comprehension',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.054',
  'left': 'bookmark',
  'right': 'source_snapshot',
  'law': 'bookmark != source_snapshot',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.055',
  'left': 'selection',
  'right': 'filter',
  'law': 'selection != filter',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.056',
  'left': 'filter',
  'right': 'authorization',
  'law': 'filter != authorization',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.057',
  'left': 'annotation',
  'right': 'evidence',
  'law': 'annotation != evidence',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.058',
  'left': 'recommendation',
  'right': 'effect',
  'law': 'recommendation != effect',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.059',
  'left': 'forecast',
  'right': 'actual',
  'law': 'forecast != actual',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.060',
  'left': 'monitoring_dashboard',
  'right': 'incident',
  'law': 'monitoring_dashboard != incident',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.061',
  'left': 'alert',
  'right': 'case',
  'law': 'alert != case',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.062',
  'left': 'map_view',
  'right': 'geospatial_dataset',
  'law': 'map_view != geospatial_dataset',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.063',
  'left': 'graph_view',
  'right': 'graph_analytics',
  'law': 'graph_view != graph_analytics',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.064',
  'left': 'volume_render',
  'right': 'medical_diagnosis',
  'law': 'volume_render != medical_diagnosis',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.065',
  'left': '3d_scene',
  'right': 'digital_twin_identity',
  'law': '3d_scene != digital_twin_identity',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.066',
  'left': 'theme',
  'right': 'semantic_encoding',
  'law': 'theme != semantic_encoding',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.067',
  'left': 'responsive_layout',
  'right': 'semantic_deletion',
  'law': 'responsive_layout != semantic_deletion',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.068',
  'left': 'offline_cache',
  'right': 'source_finality',
  'law': 'offline_cache != source_finality',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.069',
  'left': 'natural_language_answer',
  'right': 'evidence',
  'law': 'natural_language_answer != evidence',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False},
 {'test_id': 'negative.presentation_sota.070',
  'left': 'llm_proposal',
  'right': 'compiler_admission',
  'law': 'llm_proposal != compiler_admission',
  'expected': 'DISTINCTION_PRESERVED_OR_TYPED_REFUSAL',
  'completion_claim': False}]

SATURATION_TRIALS = [{'trial_id': 'saturation.presentation_sota.01',
  'sample_family': 'self_service_bi',
  'sampled_products': 18,
  'new_root_families': 7,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.02',
  'sample_family': 'observability',
  'sampled_products': 7,
  'new_root_families': 5,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.03',
  'sample_family': 'process_intelligence',
  'sampled_products': 4,
  'new_root_families': 4,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.04',
  'sample_family': 'planning_finance_project',
  'sampled_products': 5,
  'new_root_families': 4,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.05',
  'sample_family': 'geo_graph_signal',
  'sampled_products': 7,
  'new_root_families': 5,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.06',
  'sample_family': 'story_computational_3d',
  'sampled_products': 7,
  'new_root_families': 3,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.07',
  'sample_family': 'supply_chain_control',
  'sampled_products': 3,
  'new_root_families': 0,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.08',
  'sample_family': 'security_investigation',
  'sampled_products': 3,
  'new_root_families': 1,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.09',
  'sample_family': 'network_operations',
  'sampled_products': 3,
  'new_root_families': 1,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.10',
  'sample_family': 'medical_imaging',
  'sampled_products': 3,
  'new_root_families': 1,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.11',
  'sample_family': 'construction_bim',
  'sampled_products': 3,
  'new_root_families': 1,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False},
 {'trial_id': 'saturation.presentation_sota.12',
  'sample_family': 'late_cross_vertical_redundancy',
  'sampled_products': 6,
  'new_root_families': 0,
  'criterion': 'Continue until unrelated late samples add no new root intent, lifecycle, interaction or specialist '
               'semantic.',
  'completion_claim': False}]
