"""Typed result, visual-pattern and specialist-experience vocabulary."""

RESULT_KINDS = [{'result_kind_id': 'result-kind.presentation_sota.scalar',
  'family': 'general',
  'name': 'scalar',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.categorical_series',
  'family': 'general',
  'name': 'categorical_series',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.ordered_series',
  'family': 'general',
  'name': 'ordered_series',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.time_series',
  'family': 'time',
  'name': 'time_series',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.multidimensional_cube',
  'family': 'table',
  'name': 'multidimensional_cube',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.distribution',
  'family': 'statistical',
  'name': 'distribution',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.statistical_estimate',
  'family': 'statistical',
  'name': 'statistical_estimate',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.forecast',
  'family': 'forecast',
  'name': 'forecast',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.forecast_distribution',
  'family': 'forecast',
  'name': 'forecast_distribution',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.anomaly_change',
  'family': 'statistical',
  'name': 'anomaly_change',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.causal_effect',
  'family': 'statistical',
  'name': 'causal_effect',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.optimization_solution',
  'family': 'decision',
  'name': 'optimization_solution',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.simulation_ensemble',
  'family': 'decision',
  'name': 'simulation_ensemble',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.scenario_set',
  'family': 'decision',
  'name': 'scenario_set',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.recommendation_set',
  'family': 'decision',
  'name': 'recommendation_set',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.process_model',
  'family': 'process',
  'name': 'process_model',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.process_variant_set',
  'family': 'process',
  'name': 'process_variant_set',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.conformance_result',
  'family': 'process',
  'name': 'conformance_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.case_trace_set',
  'family': 'process',
  'name': 'case_trace_set',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.object_centric_process_result',
  'family': 'process',
  'name': 'object_centric_process_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.graph_network',
  'family': 'graph',
  'name': 'graph_network',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.graph_path_result',
  'family': 'graph',
  'name': 'graph_path_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.community_result',
  'family': 'graph',
  'name': 'community_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.geospatial_feature',
  'family': 'geo',
  'name': 'geospatial_feature',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.raster_coverage',
  'family': 'geo',
  'name': 'raster_coverage',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.trajectory',
  'family': 'geo',
  'name': 'trajectory',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.spatial_field',
  'family': 'geo',
  'name': 'spatial_field',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.signal_window',
  'family': 'signal',
  'name': 'signal_window',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.signal_spectrum',
  'family': 'signal',
  'name': 'signal_spectrum',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.control_chart_result',
  'family': 'signal',
  'name': 'control_chart_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.trace_tree',
  'family': 'observability',
  'name': 'trace_tree',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.log_event_set',
  'family': 'observability',
  'name': 'log_event_set',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.service_topology_result',
  'family': 'observability',
  'name': 'service_topology_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.slo_result',
  'family': 'observability',
  'name': 'slo_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.project_schedule_result',
  'family': 'project',
  'name': 'project_schedule_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.earned_value_result',
  'family': 'project',
  'name': 'earned_value_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.market_ohlc_result',
  'family': 'finance',
  'name': 'market_ohlc_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.yield_curve_result',
  'family': 'finance',
  'name': 'yield_curve_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.portfolio_risk_result',
  'family': 'finance',
  'name': 'portfolio_risk_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.medical_image_series',
  'family': 'medical',
  'name': 'medical_image_series',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.segmentation_result',
  'family': 'medical',
  'name': 'segmentation_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.registered_volume_result',
  'family': 'medical',
  'name': 'registered_volume_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.network_path_result',
  'family': 'network',
  'name': 'network_path_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.bgp_route_result',
  'family': 'network',
  'name': 'bgp_route_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.security_incident_result',
  'family': 'security',
  'name': 'security_incident_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.entity_investigation_result',
  'family': 'security',
  'name': 'entity_investigation_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.bim_model_result',
  'family': 'bim',
  'name': 'bim_model_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.construction_issue_result',
  'family': 'bim',
  'name': 'construction_issue_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.scientific_mesh_volume',
  'family': 'volume',
  'name': 'scientific_mesh_volume',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False},
 {'result_kind_id': 'result-kind.presentation_sota.vector_field_result',
  'family': 'volume',
  'name': 'vector_field_result',
  'preservation': ['identity',
                   'grain',
                   'type',
                   'unit',
                   'time',
                   'uncertainty',
                   'missingness',
                   'provenance',
                   'authority'],
  'completion_claim': False}]

VISUAL_PATTERNS = [{'visual_pattern_id': 'visual-pattern.presentation_sota.bar',
  'family': 'comparison_ranking',
  'name': 'bar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.grouped_bar',
  'family': 'comparison_ranking',
  'name': 'grouped_bar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.stacked_bar',
  'family': 'comparison_ranking',
  'name': 'stacked_bar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.normalized_stacked_bar',
  'family': 'comparison_ranking',
  'name': 'normalized_stacked_bar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.dot_plot',
  'family': 'comparison_ranking',
  'name': 'dot_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.lollipop',
  'family': 'comparison_ranking',
  'name': 'lollipop',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.range_plot',
  'family': 'comparison_ranking',
  'name': 'range_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.slopegraph',
  'family': 'comparison_ranking',
  'name': 'slopegraph',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.pareto',
  'family': 'comparison_ranking',
  'name': 'pareto',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.small_multiples',
  'family': 'comparison_ranking',
  'name': 'small_multiples',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.bullet_graph',
  'family': 'comparison_ranking',
  'name': 'bullet_graph',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.bump_chart',
  'family': 'comparison_ranking',
  'name': 'bump_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.donut',
  'family': 'composition_hierarchy',
  'name': 'donut',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.treemap',
  'family': 'composition_hierarchy',
  'name': 'treemap',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.sunburst',
  'family': 'composition_hierarchy',
  'name': 'sunburst',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.icicle',
  'family': 'composition_hierarchy',
  'name': 'icicle',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.waffle',
  'family': 'composition_hierarchy',
  'name': 'waffle',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.packed_circles',
  'family': 'composition_hierarchy',
  'name': 'packed_circles',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.tree',
  'family': 'composition_hierarchy',
  'name': 'tree',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.mosaic_plot',
  'family': 'composition_hierarchy',
  'name': 'mosaic_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.marimekko',
  'family': 'composition_hierarchy',
  'name': 'marimekko',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.histogram',
  'family': 'distribution_uncertainty',
  'name': 'histogram',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.density',
  'family': 'distribution_uncertainty',
  'name': 'density',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ecdf',
  'family': 'distribution_uncertainty',
  'name': 'ecdf',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.boxplot',
  'family': 'distribution_uncertainty',
  'name': 'boxplot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.violin',
  'family': 'distribution_uncertainty',
  'name': 'violin',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.strip',
  'family': 'distribution_uncertainty',
  'name': 'strip',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.beeswarm',
  'family': 'distribution_uncertainty',
  'name': 'beeswarm',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ridgeline',
  'family': 'distribution_uncertainty',
  'name': 'ridgeline',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.error_bar',
  'family': 'distribution_uncertainty',
  'name': 'error_bar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.interval_band',
  'family': 'distribution_uncertainty',
  'name': 'interval_band',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.fan_chart',
  'family': 'distribution_uncertainty',
  'name': 'fan_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ensemble_spaghetti',
  'family': 'distribution_uncertainty',
  'name': 'ensemble_spaghetti',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.quantile_plot',
  'family': 'distribution_uncertainty',
  'name': 'quantile_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.confidence_ellipse',
  'family': 'distribution_uncertainty',
  'name': 'confidence_ellipse',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.prediction_band',
  'family': 'distribution_uncertainty',
  'name': 'prediction_band',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.candlestick',
  'family': 'finance_project',
  'name': 'candlestick',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ohlc',
  'family': 'finance_project',
  'name': 'ohlc',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.yield_curve',
  'family': 'finance_project',
  'name': 'yield_curve',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.drawdown',
  'family': 'finance_project',
  'name': 'drawdown',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.budget_variance',
  'family': 'finance_project',
  'name': 'budget_variance',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.gantt',
  'family': 'finance_project',
  'name': 'gantt',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.resource_histogram',
  'family': 'finance_project',
  'name': 'resource_histogram',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.s_curve',
  'family': 'finance_project',
  'name': 's_curve',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.milestone_timeline',
  'family': 'finance_project',
  'name': 'milestone_timeline',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.volume_profile',
  'family': 'finance_project',
  'name': 'volume_profile',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.depth_chart',
  'family': 'finance_project',
  'name': 'depth_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.waterfall_bridge',
  'family': 'finance_project',
  'name': 'waterfall_bridge',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.sankey',
  'family': 'flow_sequence',
  'name': 'sankey',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.alluvial',
  'family': 'flow_sequence',
  'name': 'alluvial',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.funnel',
  'family': 'flow_sequence',
  'name': 'funnel',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.journey_path',
  'family': 'flow_sequence',
  'name': 'journey_path',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.event_sequence',
  'family': 'flow_sequence',
  'name': 'event_sequence',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.chord',
  'family': 'flow_sequence',
  'name': 'chord',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.parallel_sets',
  'family': 'flow_sequence',
  'name': 'parallel_sets',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.sequence_ribbon',
  'family': 'flow_sequence',
  'name': 'sequence_ribbon',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.choropleth',
  'family': 'geospatial',
  'name': 'choropleth',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.proportional_symbol_map',
  'family': 'geospatial',
  'name': 'proportional_symbol_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.dot_density_map',
  'family': 'geospatial',
  'name': 'dot_density_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.spatial_heatmap',
  'family': 'geospatial',
  'name': 'spatial_heatmap',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.hex_grid_map',
  'family': 'geospatial',
  'name': 'hex_grid_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.flow_map',
  'family': 'geospatial',
  'name': 'flow_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.route_trajectory',
  'family': 'geospatial',
  'name': 'route_trajectory',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.isoline',
  'family': 'geospatial',
  'name': 'isoline',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.raster_map',
  'family': 'geospatial',
  'name': 'raster_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.extruded_3d_map',
  'family': 'geospatial',
  'name': 'extruded_3d_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.cartogram',
  'family': 'geospatial',
  'name': 'cartogram',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.voronoi_map',
  'family': 'geospatial',
  'name': 'voronoi_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.tile_map',
  'family': 'geospatial',
  'name': 'tile_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.space_time_cube',
  'family': 'geospatial',
  'name': 'space_time_cube',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.node_link',
  'family': 'graph_knowledge',
  'name': 'node_link',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.force_graph',
  'family': 'graph_knowledge',
  'name': 'force_graph',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.hierarchical_network',
  'family': 'graph_knowledge',
  'name': 'hierarchical_network',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.adjacency_matrix',
  'family': 'graph_knowledge',
  'name': 'adjacency_matrix',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ego_graph',
  'family': 'graph_knowledge',
  'name': 'ego_graph',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.dependency_wheel',
  'family': 'graph_knowledge',
  'name': 'dependency_wheel',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.arc_diagram',
  'family': 'graph_knowledge',
  'name': 'arc_diagram',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.matrix_reordering',
  'family': 'graph_knowledge',
  'name': 'matrix_reordering',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.community_map',
  'family': 'graph_knowledge',
  'name': 'community_map',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.signal_trend',
  'family': 'industrial_scientific',
  'name': 'signal_trend',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.xy_signal',
  'family': 'industrial_scientific',
  'name': 'xy_signal',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.capsule_lane',
  'family': 'industrial_scientific',
  'name': 'capsule_lane',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.spectrogram',
  'family': 'industrial_scientific',
  'name': 'spectrogram',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.waveform',
  'family': 'industrial_scientific',
  'name': 'waveform',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.spectrum',
  'family': 'industrial_scientific',
  'name': 'spectrum',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.contour_field',
  'family': 'industrial_scientific',
  'name': 'contour_field',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.vector_field',
  'family': 'industrial_scientific',
  'name': 'vector_field',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.streamlines',
  'family': 'industrial_scientific',
  'name': 'streamlines',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.surface_3d',
  'family': 'industrial_scientific',
  'name': 'surface_3d',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.mesh_3d',
  'family': 'industrial_scientific',
  'name': 'mesh_3d',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.volume_render',
  'family': 'industrial_scientific',
  'name': 'volume_render',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.isosurface',
  'family': 'industrial_scientific',
  'name': 'isosurface',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.point_cloud',
  'family': 'industrial_scientific',
  'name': 'point_cloud',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.phase_plot',
  'family': 'industrial_scientific',
  'name': 'phase_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.waterfall_spectrum',
  'family': 'industrial_scientific',
  'name': 'waterfall_spectrum',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.polar_signal',
  'family': 'industrial_scientific',
  'name': 'polar_signal',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ternary_field',
  'family': 'industrial_scientific',
  'name': 'ternary_field',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.annotated_visual',
  'family': 'narrative_artifact',
  'name': 'annotated_visual',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.story_sequence',
  'family': 'narrative_artifact',
  'name': 'story_sequence',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.scrollytelling',
  'family': 'narrative_artifact',
  'name': 'scrollytelling',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.dashboard',
  'family': 'narrative_artifact',
  'name': 'dashboard',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.scorecard',
  'family': 'narrative_artifact',
  'name': 'scorecard',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.wallboard',
  'family': 'narrative_artifact',
  'name': 'wallboard',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.paginated_report',
  'family': 'narrative_artifact',
  'name': 'paginated_report',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.notebook_output',
  'family': 'narrative_artifact',
  'name': 'notebook_output',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.saved_3d_view',
  'family': 'narrative_artifact',
  'name': 'saved_3d_view',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.data_story',
  'family': 'narrative_artifact',
  'name': 'data_story',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.briefing_board',
  'family': 'narrative_artifact',
  'name': 'briefing_board',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.state_timeline',
  'family': 'observability',
  'name': 'state_timeline',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.status_history',
  'family': 'observability',
  'name': 'status_history',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.logs_view',
  'family': 'observability',
  'name': 'logs_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.trace_waterfall',
  'family': 'observability',
  'name': 'trace_waterfall',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.flame_graph',
  'family': 'observability',
  'name': 'flame_graph',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.service_topology',
  'family': 'observability',
  'name': 'service_topology',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.hostmap',
  'family': 'observability',
  'name': 'hostmap',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.slo_panel',
  'family': 'observability',
  'name': 'slo_panel',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.bubbleup_contrast',
  'family': 'observability',
  'name': 'bubbleup_contrast',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.span_map',
  'family': 'observability',
  'name': 'span_map',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.dependency_latency_map',
  'family': 'observability',
  'name': 'dependency_latency_map',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.error_budget_burn',
  'family': 'observability',
  'name': 'error_budget_burn',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.process_map',
  'family': 'process_intelligence',
  'name': 'process_map',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.process_variant_explorer',
  'family': 'process_intelligence',
  'name': 'process_variant_explorer',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.conformance_overlay',
  'family': 'process_intelligence',
  'name': 'conformance_overlay',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.throughput_explorer',
  'family': 'process_intelligence',
  'name': 'throughput_explorer',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.process_animation',
  'family': 'process_intelligence',
  'name': 'process_animation',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.activity_frequency',
  'family': 'process_intelligence',
  'name': 'activity_frequency',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.case_explorer',
  'family': 'process_intelligence',
  'name': 'case_explorer',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.rework_loop_view',
  'family': 'process_intelligence',
  'name': 'rework_loop_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.object_centric_process_map',
  'family': 'process_intelligence',
  'name': 'object_centric_process_map',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.transition_duration_overlay',
  'family': 'process_intelligence',
  'name': 'transition_duration_overlay',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.retention_cohort',
  'family': 'product_behavior',
  'name': 'retention_cohort',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.lifecycle_matrix',
  'family': 'product_behavior',
  'name': 'lifecycle_matrix',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.segment_overlap',
  'family': 'product_behavior',
  'name': 'segment_overlap',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.path_sunburst',
  'family': 'product_behavior',
  'name': 'path_sunburst',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.impact_analysis',
  'family': 'product_behavior',
  'name': 'impact_analysis',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.stickiness_curve',
  'family': 'product_behavior',
  'name': 'stickiness_curve',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.funnel_steps',
  'family': 'product_behavior',
  'name': 'funnel_steps',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.journey_sankey',
  'family': 'product_behavior',
  'name': 'journey_sankey',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.cohort_curve',
  'family': 'product_behavior',
  'name': 'cohort_curve',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.scatter',
  'family': 'relationship_multivariate',
  'name': 'scatter',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.bubble',
  'family': 'relationship_multivariate',
  'name': 'bubble',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.hexbin',
  'family': 'relationship_multivariate',
  'name': 'hexbin',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.density_contour',
  'family': 'relationship_multivariate',
  'name': 'density_contour',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.regression_plot',
  'family': 'relationship_multivariate',
  'name': 'regression_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.correlation_matrix',
  'family': 'relationship_multivariate',
  'name': 'correlation_matrix',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.scatterplot_matrix',
  'family': 'relationship_multivariate',
  'name': 'scatterplot_matrix',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.parallel_coordinates',
  'family': 'relationship_multivariate',
  'name': 'parallel_coordinates',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.heatmap',
  'family': 'relationship_multivariate',
  'name': 'heatmap',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.ternary',
  'family': 'relationship_multivariate',
  'name': 'ternary',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.polar',
  'family': 'relationship_multivariate',
  'name': 'polar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.radar',
  'family': 'relationship_multivariate',
  'name': 'radar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.pairwise_slope',
  'family': 'relationship_multivariate',
  'name': 'pairwise_slope',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.residual_plot',
  'family': 'relationship_multivariate',
  'name': 'residual_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.single_value',
  'family': 'summary_status',
  'name': 'single_value',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.kpi_with_delta',
  'family': 'summary_status',
  'name': 'kpi_with_delta',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.sparkline_kpi',
  'family': 'summary_status',
  'name': 'sparkline_kpi',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.bullet_chart',
  'family': 'summary_status',
  'name': 'bullet_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.progress_bar',
  'family': 'summary_status',
  'name': 'progress_bar',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.gauge',
  'family': 'summary_status',
  'name': 'gauge',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.traffic_light',
  'family': 'summary_status',
  'name': 'traffic_light',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.status_badge',
  'family': 'summary_status',
  'name': 'status_badge',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.threshold_band',
  'family': 'summary_status',
  'name': 'threshold_band',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.table',
  'family': 'tabular_grid',
  'name': 'table',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.matrix',
  'family': 'tabular_grid',
  'name': 'matrix',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.pivot',
  'family': 'tabular_grid',
  'name': 'pivot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.conditional_table',
  'family': 'tabular_grid',
  'name': 'conditional_table',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.table_sparklines',
  'family': 'tabular_grid',
  'name': 'table_sparklines',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.planning_grid',
  'family': 'tabular_grid',
  'name': 'planning_grid',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.crosstab',
  'family': 'tabular_grid',
  'name': 'crosstab',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.tree_table',
  'family': 'tabular_grid',
  'name': 'tree_table',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.editable_grid',
  'family': 'tabular_grid',
  'name': 'editable_grid',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.variance_grid',
  'family': 'tabular_grid',
  'name': 'variance_grid',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.line',
  'family': 'time_change',
  'name': 'line',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.multi_line',
  'family': 'time_change',
  'name': 'multi_line',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.step_line',
  'family': 'time_change',
  'name': 'step_line',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.area',
  'family': 'time_change',
  'name': 'area',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.stacked_area',
  'family': 'time_change',
  'name': 'stacked_area',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.streamgraph',
  'family': 'time_change',
  'name': 'streamgraph',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.horizon',
  'family': 'time_change',
  'name': 'horizon',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.calendar_heatmap',
  'family': 'time_change',
  'name': 'calendar_heatmap',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.waterfall',
  'family': 'time_change',
  'name': 'waterfall',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.index_chart',
  'family': 'time_change',
  'name': 'index_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.control_chart',
  'family': 'time_change',
  'name': 'control_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.run_chart',
  'family': 'time_change',
  'name': 'run_chart',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.event_strip',
  'family': 'time_change',
  'name': 'event_strip',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.cycle_plot',
  'family': 'time_change',
  'name': 'cycle_plot',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.seasonal_subseries',
  'family': 'time_change',
  'name': 'seasonal_subseries',
  'semantic_level': 'generic_recipe',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.incident_timeline',
  'family': 'security_investigation',
  'name': 'incident_timeline',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.entity_investigation_graph',
  'family': 'security_investigation',
  'name': 'entity_investigation_graph',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.attack_technique_matrix',
  'family': 'security_investigation',
  'name': 'attack_technique_matrix',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.risk_card_grid',
  'family': 'security_investigation',
  'name': 'risk_card_grid',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.detection_heatmap',
  'family': 'security_investigation',
  'name': 'detection_heatmap',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.investigation_workbook',
  'family': 'security_investigation',
  'name': 'investigation_workbook',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.path_hop_view',
  'family': 'network_operations',
  'name': 'path_hop_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.directional_path_health',
  'family': 'network_operations',
  'name': 'directional_path_health',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.bgp_route_view',
  'family': 'network_operations',
  'name': 'bgp_route_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.outage_swimlane',
  'family': 'network_operations',
  'name': 'outage_swimlane',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.network_topology_health',
  'family': 'network_operations',
  'name': 'network_topology_health',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.transport_slice_health',
  'family': 'network_operations',
  'name': 'transport_slice_health',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.traffic_matrix',
  'family': 'network_operations',
  'name': 'traffic_matrix',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.mpr_view',
  'family': 'medical_imaging',
  'name': 'mpr_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.mip_projection',
  'family': 'medical_imaging',
  'name': 'mip_projection',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.cpr_projection',
  'family': 'medical_imaging',
  'name': 'cpr_projection',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.cine_view',
  'family': 'medical_imaging',
  'name': 'cine_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.segmentation_overlay',
  'family': 'medical_imaging',
  'name': 'segmentation_overlay',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.measurement_overlay',
  'family': 'medical_imaging',
  'name': 'measurement_overlay',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.registered_volume_compare',
  'family': 'medical_imaging',
  'name': 'registered_volume_compare',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.window_level_view',
  'family': 'medical_imaging',
  'name': 'window_level_view',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.model_revision_compare',
  'family': 'construction_bim',
  'name': 'model_revision_compare',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.spatial_issue_overlay',
  'family': 'construction_bim',
  'name': 'spatial_issue_overlay',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.model_progress_3d',
  'family': 'construction_bim',
  'name': 'model_progress_3d',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.reality_capture_overlay',
  'family': 'construction_bim',
  'name': 'reality_capture_overlay',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.schedule_geometry_link',
  'family': 'construction_bim',
  'name': 'schedule_geometry_link',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False},
 {'visual_pattern_id': 'visual-pattern.presentation_sota.construction_risk_grid',
  'family': 'construction_bim',
  'name': 'construction_risk_grid',
  'semantic_level': 'typed_specialist',
  'provider_neutral': True,
  'completion_claim': False}]

SPECIALISTS = [{'specialist_id': 'specialist.presentation_sota.process_intelligence',
  'name': 'process_intelligence',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.product_journey',
  'name': 'product_journey',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.observability_investigation',
  'name': 'observability_investigation',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.planning',
  'name': 'planning',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.finance_market',
  'name': 'finance_market',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.project_controls',
  'name': 'project_controls',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.geospatial',
  'name': 'geospatial',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.graph_knowledge',
  'name': 'graph_knowledge',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.industrial_signal',
  'name': 'industrial_signal',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.scientific_field',
  'name': 'scientific_field',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.digital_twin',
  'name': 'digital_twin',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.storytelling',
  'name': 'storytelling',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.formal_reporting',
  'name': 'formal_reporting',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.computational_document',
  'name': 'computational_document',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.embedded_analytics',
  'name': 'embedded_analytics',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.self_service_visual_discovery',
  'name': 'self_service_visual_discovery',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.decision_support',
  'name': 'decision_support',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.security_investigation',
  'name': 'security_investigation',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.network_operations',
  'name': 'network_operations',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.construction_bim',
  'name': 'construction_bim',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False},
 {'specialist_id': 'specialist.presentation_sota.medical_imaging',
  'name': 'medical_imaging',
  'dispatch_key': 'typed_result_and_intent_profile_only',
  'provider_name_dispatch_forbidden': True,
  'completion_claim': False}]
