"""Interaction algebra and candidate semantic/library seams."""

INTERACTIONS = [{'interaction_id': 'interaction.presentation_sota.hover',
  'name': 'hover',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.select',
  'name': 'select',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.multi_select',
  'name': 'multi_select',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.brush',
  'name': 'brush',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.lasso',
  'name': 'lasso',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.highlight',
  'name': 'highlight',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.filter',
  'name': 'filter',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.cross_filter',
  'name': 'cross_filter',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.sort',
  'name': 'sort',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.search',
  'name': 'search',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.zoom',
  'name': 'zoom',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.pan',
  'name': 'pan',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.drill_down',
  'name': 'drill_down',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.drill_up',
  'name': 'drill_up',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.drill_through',
  'name': 'drill_through',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.graph_expand',
  'name': 'graph_expand',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.graph_collapse',
  'name': 'graph_collapse',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.pivot',
  'name': 'pivot',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.expand_hierarchy',
  'name': 'expand_hierarchy',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.collapse_hierarchy',
  'name': 'collapse_hierarchy',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.facet',
  'name': 'facet',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.toggle_series',
  'name': 'toggle_series',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.change_measure',
  'name': 'change_measure',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.change_dimension',
  'name': 'change_dimension',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.change_time_range',
  'name': 'change_time_range',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.scrub_time',
  'name': 'scrub_time',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.replay',
  'name': 'replay',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.compare',
  'name': 'compare',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.bookmark',
  'name': 'bookmark',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.share_view_state',
  'name': 'share_view_state',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.annotate',
  'name': 'annotate',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.comment',
  'name': 'comment',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.export',
  'name': 'export',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.print',
  'name': 'print',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.subscribe',
  'name': 'subscribe',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.acknowledge_attention',
  'name': 'acknowledge_attention',
  'class': 'effect_intent_only',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.assign_attention',
  'name': 'assign_attention',
  'class': 'effect_intent_only',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.scenario_edit',
  'name': 'scenario_edit',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.writeback_proposal',
  'name': 'writeback_proposal',
  'class': 'effect_intent_only',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.approve_recommendation_intent',
  'name': 'approve_recommendation_intent',
  'class': 'effect_intent_only',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.override_recommendation_intent',
  'name': 'override_recommendation_intent',
  'class': 'effect_intent_only',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.external_action_intent',
  'name': 'external_action_intent',
  'class': 'effect_intent_only',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.window_level',
  'name': 'window_level',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.medical_measurement',
  'name': 'medical_measurement',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.rotate_3d',
  'name': 'rotate_3d',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.section_3d',
  'name': 'section_3d',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.recenter_3d',
  'name': 'recenter_3d',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.path_probe',
  'name': 'path_probe',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.process_case_open',
  'name': 'process_case_open',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False},
 {'interaction_id': 'interaction.presentation_sota.trace_span_open',
  'name': 'trace_span_open',
  'class': 'presentation_state',
  'business_effect_authority': False,
  'law': 'Presentation interaction may change declared view/session state or emit a typed intent; it cannot mint '
         'business authority.',
  'completion_claim': False}]

LIBRARY_SEAMS = [{'library_candidate_id': 'library-candidate.presentation_sota.presentation_intent',
  'name': 'presentation_intent',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.result_presentation_binding',
  'name': 'result_presentation_binding',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.presentation_ir',
  'name': 'presentation_ir',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.statistical_visual_grammar',
  'name': 'statistical_visual_grammar',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.visual_recipe_catalog',
  'name': 'visual_recipe_catalog',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.visual_fitness_constraints',
  'name': 'visual_fitness_constraints',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.presentation_planner',
  'name': 'presentation_planner',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.composition_layout',
  'name': 'composition_layout',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.responsive_layout',
  'name': 'responsive_layout',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.interaction_state',
  'name': 'interaction_state',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.selection_algebra',
  'name': 'selection_algebra',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.drill_navigation',
  'name': 'drill_navigation',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.view_state_bookmark',
  'name': 'view_state_bookmark',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.table_grid_model',
  'name': 'table_grid_model',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.dashboard_runtime',
  'name': 'dashboard_runtime',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.story_narrative',
  'name': 'story_narrative',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.report_definition',
  'name': 'report_definition',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.report_run',
  'name': 'report_run',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.pagination_layout',
  'name': 'pagination_layout',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.publication_lifecycle',
  'name': 'publication_lifecycle',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.report_snapshot',
  'name': 'report_snapshot',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.export_plan',
  'name': 'export_plan',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.export_encoder',
  'name': 'export_encoder',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.export_delivery',
  'name': 'export_delivery',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.embedded_bridge',
  'name': 'embedded_bridge',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.embed_entitlement_projection',
  'name': 'embed_entitlement_projection',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.accessibility_semantics',
  'name': 'accessibility_semantics',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.accessible_task_equivalent',
  'name': 'accessible_task_equivalent',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.localization_format',
  'name': 'localization_format',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.uncertainty_encoding',
  'name': 'uncertainty_encoding',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.missingness_encoding',
  'name': 'missingness_encoding',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.provenance_disclosure',
  'name': 'provenance_disclosure',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.annotation_collaboration',
  'name': 'annotation_collaboration',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.specialized_experience_registry',
  'name': 'specialized_experience_registry',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.renderer_adapter',
  'name': 'renderer_adapter',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.semantic_equivalence_oracle',
  'name': 'semantic_equivalence_oracle',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.visual_regression_oracle',
  'name': 'visual_regression_oracle',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.presentation_resource_budget',
  'name': 'presentation_resource_budget',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.presentation_usage_evidence',
  'name': 'presentation_usage_evidence',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.process_view_profile',
  'name': 'process_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.journey_view_profile',
  'name': 'journey_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.observability_view_profile',
  'name': 'observability_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.geospatial_view_profile',
  'name': 'geospatial_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.graph_view_profile',
  'name': 'graph_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.signal_view_profile',
  'name': 'signal_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.scientific_scene_profile',
  'name': 'scientific_scene_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.planning_interaction_profile',
  'name': 'planning_interaction_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.finance_market_view_profile',
  'name': 'finance_market_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.project_control_view_profile',
  'name': 'project_control_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.digital_twin_scene_profile',
  'name': 'digital_twin_scene_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.security_investigation_profile',
  'name': 'security_investigation_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.network_operations_profile',
  'name': 'network_operations_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.medical_imaging_profile',
  'name': 'medical_imaging_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.construction_bim_profile',
  'name': 'construction_bim_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.decision_explanation_profile',
  'name': 'decision_explanation_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.evidence_overlay_profile',
  'name': 'evidence_overlay_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.alert_attention_projection',
  'name': 'alert_attention_projection',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.freshness_encoding',
  'name': 'freshness_encoding',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.data_quality_encoding',
  'name': 'data_quality_encoding',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.theme_tokens',
  'name': 'theme_tokens',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.print_rendition_profile',
  'name': 'print_rendition_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.offline_view_profile',
  'name': 'offline_view_profile',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False},
 {'library_candidate_id': 'library-candidate.presentation_sota.presentation_telemetry_contract',
  'name': 'presentation_telemetry_contract',
  'status': 'CANDIDATE_UNRATIFIED',
  'required_surface': ['types',
                       'operations',
                       'decisions',
                       'invariants',
                       'refusals',
                       'time',
                       'resources',
                       'oracles',
                       'compatibility',
                       'evidence'],
  'implementation_qualification': 'NOT_ATTEMPTED',
  'completion_claim': False}]
