"""Question/job intents and provider-neutral candidate visual routes."""

INTENTS = [{'intent_id': 'intent.presentation_sota.headline_status',
  'family': 'status_compare',
  'question_job': 'headline status',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.single_value',
                            'visual-pattern.presentation_sota.kpi_with_delta',
                            'visual-pattern.presentation_sota.traffic_light'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.progress_to_target',
  'family': 'status_compare',
  'question_job': 'progress to target',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bullet_chart',
                            'visual-pattern.presentation_sota.progress_bar',
                            'visual-pattern.presentation_sota.kpi_with_delta'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.compare_categories',
  'family': 'status_compare',
  'question_job': 'compare categories',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.dot_plot',
                            'visual-pattern.presentation_sota.small_multiples'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.rank_entities',
  'family': 'status_compare',
  'question_job': 'rank entities',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.lollipop',
                            'visual-pattern.presentation_sota.pareto',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.compare_two_states',
  'family': 'status_compare',
  'question_job': 'compare two states',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.dot_plot',
                            'visual-pattern.presentation_sota.small_multiples'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.variance_to_baseline',
  'family': 'status_compare',
  'question_job': 'variance to baseline',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.variance_to_plan',
  'family': 'status_compare',
  'question_job': 'variance to plan',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.contribution_to_change',
  'family': 'status_compare',
  'question_job': 'contribution to change',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.composition_now',
  'family': 'status_compare',
  'question_job': 'composition now',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.hierarchy_size',
  'family': 'status_compare',
  'question_job': 'hierarchy size',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.trend_over_time',
  'family': 'time',
  'question_job': 'trend over time',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.line',
                            'visual-pattern.presentation_sota.run_chart',
                            'visual-pattern.presentation_sota.sparkline_kpi'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.compare_time_series',
  'family': 'time',
  'question_job': 'compare time series',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.dot_plot',
                            'visual-pattern.presentation_sota.small_multiples'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.composition_over_time',
  'family': 'time',
  'question_job': 'composition over time',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.seasonality',
  'family': 'time',
  'question_job': 'seasonality',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.change_points',
  'family': 'time',
  'question_job': 'change points',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.before_after',
  'family': 'time',
  'question_job': 'before after',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.cumulative_progress',
  'family': 'time',
  'question_job': 'cumulative progress',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.event_timeline',
  'family': 'time',
  'question_job': 'event timeline',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.state_changes',
  'family': 'time',
  'question_job': 'state changes',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.time_of_day_pattern',
  'family': 'time',
  'question_job': 'time of day pattern',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.distribution',
  'family': 'distribution',
  'question_job': 'distribution',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.histogram',
                            'visual-pattern.presentation_sota.ecdf',
                            'visual-pattern.presentation_sota.boxplot',
                            'visual-pattern.presentation_sota.density'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.compare_distributions',
  'family': 'distribution',
  'question_job': 'compare distributions',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.histogram',
                            'visual-pattern.presentation_sota.ecdf',
                            'visual-pattern.presentation_sota.boxplot',
                            'visual-pattern.presentation_sota.density'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.outliers',
  'family': 'distribution',
  'question_job': 'outliers',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.boxplot',
                            'visual-pattern.presentation_sota.scatter',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.tail_risk',
  'family': 'distribution',
  'question_job': 'tail risk',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.percentile_position',
  'family': 'distribution',
  'question_job': 'percentile position',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.spread_and_center',
  'family': 'distribution',
  'question_job': 'spread and center',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.multimodality',
  'family': 'distribution',
  'question_job': 'multimodality',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.skewness',
  'family': 'distribution',
  'question_job': 'skewness',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.sampling_variability',
  'family': 'distribution',
  'question_job': 'sampling variability',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.uncertainty_estimate',
  'family': 'distribution',
  'question_job': 'uncertainty estimate',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.error_bar',
                            'visual-pattern.presentation_sota.interval_band',
                            'visual-pattern.presentation_sota.quantile_plot'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.relationship',
  'family': 'relationship',
  'question_job': 'relationship',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.multivariate_relationship',
  'family': 'relationship',
  'question_job': 'multivariate relationship',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.correlation_structure',
  'family': 'relationship',
  'question_job': 'correlation structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.regression_fit',
  'family': 'relationship',
  'question_job': 'regression fit',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.residual_diagnostics',
  'family': 'relationship',
  'question_job': 'residual diagnostics',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.interaction_effect',
  'family': 'relationship',
  'question_job': 'interaction effect',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.cluster_structure',
  'family': 'relationship',
  'question_job': 'cluster structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.dimension_reduction',
  'family': 'relationship',
  'question_job': 'dimension reduction',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.pairwise_comparison',
  'family': 'relationship',
  'question_job': 'pairwise comparison',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.tradeoff_frontier',
  'family': 'relationship',
  'question_job': 'tradeoff frontier',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.forecast',
  'family': 'forecast_decision',
  'question_job': 'forecast',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.line',
                            'visual-pattern.presentation_sota.fan_chart',
                            'visual-pattern.presentation_sota.interval_band'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.forecast_compare',
  'family': 'forecast_decision',
  'question_job': 'forecast compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.line',
                            'visual-pattern.presentation_sota.fan_chart',
                            'visual-pattern.presentation_sota.interval_band'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.scenario_compare',
  'family': 'forecast_decision',
  'question_job': 'scenario compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.ensemble_spaghetti',
                            'visual-pattern.presentation_sota.fan_chart',
                            'visual-pattern.presentation_sota.small_multiples',
                            'visual-pattern.presentation_sota.planning_grid'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.what_if',
  'family': 'forecast_decision',
  'question_job': 'what if',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.optimization_tradeoff',
  'family': 'forecast_decision',
  'question_job': 'optimization tradeoff',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.scatter',
                            'visual-pattern.presentation_sota.parallel_coordinates',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.recommended_action',
  'family': 'forecast_decision',
  'question_job': 'recommended action',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.decision_alternatives',
  'family': 'forecast_decision',
  'question_job': 'decision alternatives',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.sensitivity',
  'family': 'forecast_decision',
  'question_job': 'sensitivity',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.constraint_binding',
  'family': 'forecast_decision',
  'question_job': 'constraint binding',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.risk_reward',
  'family': 'forecast_decision',
  'question_job': 'risk reward',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.known_funnel',
  'family': 'journey',
  'question_job': 'known funnel',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.funnel',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.unknown_paths',
  'family': 'journey',
  'question_job': 'unknown paths',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.retention',
  'family': 'journey',
  'question_job': 'retention',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.retention_cohort',
                            'visual-pattern.presentation_sota.heatmap',
                            'visual-pattern.presentation_sota.cohort_curve'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.stickiness',
  'family': 'journey',
  'question_job': 'stickiness',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.segment_overlap',
  'family': 'journey',
  'question_job': 'segment overlap',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.lifecycle_stage',
  'family': 'journey',
  'question_job': 'lifecycle stage',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.journey_dropoff',
  'family': 'journey',
  'question_job': 'journey dropoff',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.journey_path',
                            'visual-pattern.presentation_sota.journey_sankey',
                            'visual-pattern.presentation_sota.path_sunburst'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.conversion_latency',
  'family': 'journey',
  'question_job': 'conversion latency',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.cohort_compare',
  'family': 'journey',
  'question_job': 'cohort compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.dot_plot',
                            'visual-pattern.presentation_sota.small_multiples'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.impact_analysis',
  'family': 'journey',
  'question_job': 'impact analysis',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.process_discovery',
  'family': 'process',
  'question_job': 'process discovery',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.process_map',
                            'visual-pattern.presentation_sota.process_variant_explorer',
                            'visual-pattern.presentation_sota.conformance_overlay',
                            'visual-pattern.presentation_sota.throughput_explorer',
                            'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.process_variants',
  'family': 'process',
  'question_job': 'process variants',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.process_map',
                            'visual-pattern.presentation_sota.process_variant_explorer',
                            'visual-pattern.presentation_sota.conformance_overlay',
                            'visual-pattern.presentation_sota.throughput_explorer',
                            'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.process_conformance',
  'family': 'process',
  'question_job': 'process conformance',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.process_map',
                            'visual-pattern.presentation_sota.process_variant_explorer',
                            'visual-pattern.presentation_sota.conformance_overlay',
                            'visual-pattern.presentation_sota.throughput_explorer',
                            'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.process_bottleneck',
  'family': 'process',
  'question_job': 'process bottleneck',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.process_map',
                            'visual-pattern.presentation_sota.process_variant_explorer',
                            'visual-pattern.presentation_sota.conformance_overlay',
                            'visual-pattern.presentation_sota.throughput_explorer',
                            'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.throughput_duration',
  'family': 'process',
  'question_job': 'throughput duration',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.rework',
  'family': 'process',
  'question_job': 'rework',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.handoff_delay',
  'family': 'process',
  'question_job': 'handoff delay',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.case_deviation',
  'family': 'process',
  'question_job': 'case deviation',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.object_centric_flow',
  'family': 'process',
  'question_job': 'object centric flow',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.process_change_compare',
  'family': 'process',
  'question_job': 'process change compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.process_map',
                            'visual-pattern.presentation_sota.process_variant_explorer',
                            'visual-pattern.presentation_sota.conformance_overlay',
                            'visual-pattern.presentation_sota.throughput_explorer',
                            'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.root_cause_contrast',
  'family': 'observability',
  'question_job': 'root cause contrast',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.anomaly_over_time',
  'family': 'observability',
  'question_job': 'anomaly over time',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.live_monitoring',
  'family': 'observability',
  'question_job': 'live monitoring',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.service_topology',
  'family': 'observability',
  'question_job': 'service topology',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.logs_view', 'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.latency_trace',
  'family': 'observability',
  'question_job': 'latency trace',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.trace_waterfall',
                            'visual-pattern.presentation_sota.service_topology',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.code_profile',
  'family': 'observability',
  'question_job': 'code profile',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.flame_graph', 'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.log_inspection',
  'family': 'observability',
  'question_job': 'log inspection',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.logs_view', 'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.slo_health',
  'family': 'observability',
  'question_job': 'slo health',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.slo_panel',
                            'visual-pattern.presentation_sota.line',
                            'visual-pattern.presentation_sota.kpi_with_delta'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.error_budget',
  'family': 'observability',
  'question_job': 'error budget',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.dependency_failure',
  'family': 'observability',
  'question_job': 'dependency failure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.geographic_distribution',
  'family': 'geo_graph',
  'question_job': 'geographic distribution',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.choropleth',
                            'visual-pattern.presentation_sota.hex_grid_map',
                            'visual-pattern.presentation_sota.proportional_symbol_map'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.location_magnitude',
  'family': 'geo_graph',
  'question_job': 'location magnitude',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.spatial_flow',
  'family': 'geo_graph',
  'question_job': 'spatial flow',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.spatial_heatmap',
                            'visual-pattern.presentation_sota.flow_map',
                            'visual-pattern.presentation_sota.raster_map'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.spatial_field',
  'family': 'geo_graph',
  'question_job': 'spatial field',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.spatial_heatmap',
                            'visual-pattern.presentation_sota.flow_map',
                            'visual-pattern.presentation_sota.raster_map'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.route_deviation',
  'family': 'geo_graph',
  'question_job': 'route deviation',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.network_structure',
  'family': 'geo_graph',
  'question_job': 'network structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.path_hop_view',
                            'visual-pattern.presentation_sota.network_topology_health',
                            'visual-pattern.presentation_sota.traffic_matrix'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.network_dependency',
  'family': 'geo_graph',
  'question_job': 'network dependency',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.path_hop_view',
                            'visual-pattern.presentation_sota.network_topology_health',
                            'visual-pattern.presentation_sota.traffic_matrix'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.ego_context',
  'family': 'geo_graph',
  'question_job': 'ego context',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.community_structure',
  'family': 'geo_graph',
  'question_job': 'community structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.graph_path',
  'family': 'geo_graph',
  'question_job': 'graph path',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.node_link',
                            'visual-pattern.presentation_sota.adjacency_matrix',
                            'visual-pattern.presentation_sota.force_graph'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.signal_trend',
  'family': 'signal_science',
  'question_job': 'signal trend',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.signal_trend',
                            'visual-pattern.presentation_sota.xy_signal',
                            'visual-pattern.presentation_sota.spectrogram'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.signal_relationship',
  'family': 'signal_science',
  'question_job': 'signal relationship',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.signal_trend',
                            'visual-pattern.presentation_sota.xy_signal',
                            'visual-pattern.presentation_sota.spectrogram'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.condition_intervals',
  'family': 'signal_science',
  'question_job': 'condition intervals',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.frequency_content',
  'family': 'signal_science',
  'question_job': 'frequency content',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.spectrum',
                            'visual-pattern.presentation_sota.spectrogram',
                            'visual-pattern.presentation_sota.waveform'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.process_control',
  'family': 'signal_science',
  'question_job': 'process control',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.process_map',
                            'visual-pattern.presentation_sota.process_variant_explorer',
                            'visual-pattern.presentation_sota.conformance_overlay',
                            'visual-pattern.presentation_sota.throughput_explorer',
                            'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.scientific_scalar_field',
  'family': 'signal_science',
  'question_job': 'scientific scalar field',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.contour_field',
                            'visual-pattern.presentation_sota.surface_3d',
                            'visual-pattern.presentation_sota.volume_render'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.scientific_vector_field',
  'family': 'signal_science',
  'question_job': 'scientific vector field',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.contour_field',
                            'visual-pattern.presentation_sota.surface_3d',
                            'visual-pattern.presentation_sota.volume_render'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.3d_structure',
  'family': 'signal_science',
  'question_job': '3d structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.volume_inspection',
  'family': 'signal_science',
  'question_job': 'volume inspection',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.volume_render',
                            'visual-pattern.presentation_sota.isosurface',
                            'visual-pattern.presentation_sota.mpr_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.simulation_field_compare',
  'family': 'signal_science',
  'question_job': 'simulation field compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.dot_plot',
                            'visual-pattern.presentation_sota.small_multiples'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.project_schedule',
  'family': 'project_finance',
  'question_job': 'project schedule',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.gantt',
                            'visual-pattern.presentation_sota.milestone_timeline',
                            'visual-pattern.presentation_sota.resource_histogram'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.resource_capacity',
  'family': 'project_finance',
  'question_job': 'resource capacity',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.resource_histogram',
                            'visual-pattern.presentation_sota.gantt',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.earned_value_status',
  'family': 'project_finance',
  'question_job': 'earned value status',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.single_value',
                            'visual-pattern.presentation_sota.kpi_with_delta',
                            'visual-pattern.presentation_sota.traffic_light'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.milestone_risk',
  'family': 'project_finance',
  'question_job': 'milestone risk',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.schedule_variance',
  'family': 'project_finance',
  'question_job': 'schedule variance',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.market_price_action',
  'family': 'project_finance',
  'question_job': 'market price action',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.candlestick',
                            'visual-pattern.presentation_sota.line',
                            'visual-pattern.presentation_sota.volume_profile'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.yield_term_structure',
  'family': 'project_finance',
  'question_job': 'yield term structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.yield_curve', 'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.portfolio_drawdown',
  'family': 'project_finance',
  'question_job': 'portfolio drawdown',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.drawdown',
                            'visual-pattern.presentation_sota.waterfall',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.market_depth',
  'family': 'project_finance',
  'question_job': 'market depth',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.candlestick',
                            'visual-pattern.presentation_sota.line',
                            'visual-pattern.presentation_sota.volume_profile'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.portfolio_contribution',
  'family': 'project_finance',
  'question_job': 'portfolio contribution',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.drawdown',
                            'visual-pattern.presentation_sota.waterfall',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.incident_sequence',
  'family': 'security_network',
  'question_job': 'incident sequence',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.incident_timeline',
                            'visual-pattern.presentation_sota.entity_investigation_graph',
                            'visual-pattern.presentation_sota.risk_card_grid'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.entity_risk_context',
  'family': 'security_network',
  'question_job': 'entity risk context',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.attack_technique_coverage',
  'family': 'security_network',
  'question_job': 'attack technique coverage',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.attack_technique_matrix',
                            'visual-pattern.presentation_sota.risk_card_grid'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.security_posture',
  'family': 'security_network',
  'question_job': 'security posture',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.risk_card_grid',
                            'visual-pattern.presentation_sota.attack_technique_matrix',
                            'visual-pattern.presentation_sota.incident_timeline'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.detection_concentration',
  'family': 'security_network',
  'question_job': 'detection concentration',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.detection_heatmap',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.network_path_health',
  'family': 'security_network',
  'question_job': 'network path health',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.path_hop_view',
                            'visual-pattern.presentation_sota.network_topology_health',
                            'visual-pattern.presentation_sota.traffic_matrix'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.hop_degradation',
  'family': 'security_network',
  'question_job': 'hop degradation',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.path_hop_view',
                            'visual-pattern.presentation_sota.directional_path_health',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.routing_change',
  'family': 'security_network',
  'question_job': 'routing change',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bgp_route_view',
                            'visual-pattern.presentation_sota.path_hop_view',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.outage_scope',
  'family': 'security_network',
  'question_job': 'outage scope',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.traffic_hotspot',
  'family': 'security_network',
  'question_job': 'traffic hotspot',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.multi_planar_anatomy',
  'family': 'medical_bim',
  'question_job': 'multi planar anatomy',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.mpr_view',
                            'visual-pattern.presentation_sota.window_level_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.maximum_intensity_structure',
  'family': 'medical_bim',
  'question_job': 'maximum intensity structure',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.mip_projection',
                            'visual-pattern.presentation_sota.mpr_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.curved_structure_follow',
  'family': 'medical_bim',
  'question_job': 'curved structure follow',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.cpr_projection',
                            'visual-pattern.presentation_sota.mpr_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.cine_motion',
  'family': 'medical_bim',
  'question_job': 'cine motion',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.cine_view', 'visual-pattern.presentation_sota.mpr_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.segmentation_review',
  'family': 'medical_bim',
  'question_job': 'segmentation review',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.segmentation_overlay',
                            'visual-pattern.presentation_sota.mpr_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.measurement_compare',
  'family': 'medical_bim',
  'question_job': 'measurement compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.measurement_overlay',
                            'visual-pattern.presentation_sota.table'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.registered_series_compare',
  'family': 'medical_bim',
  'question_job': 'registered series compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.registered_volume_compare',
                            'visual-pattern.presentation_sota.mpr_view'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.model_revision_change',
  'family': 'medical_bim',
  'question_job': 'model revision change',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.model_revision_compare',
                            'visual-pattern.presentation_sota.spatial_issue_overlay'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.spatial_issue_context',
  'family': 'medical_bim',
  'question_job': 'spatial issue context',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.spatial_issue_overlay',
                            'visual-pattern.presentation_sota.model_progress_3d'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.construction_progress_context',
  'family': 'medical_bim',
  'question_job': 'construction progress context',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.model_progress_3d',
                            'visual-pattern.presentation_sota.spatial_issue_overlay',
                            'visual-pattern.presentation_sota.construction_risk_grid'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.record_inspection',
  'family': 'artifact_evidence',
  'question_job': 'record inspection',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table', 'visual-pattern.presentation_sota.case_explorer'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.slice_and_dice',
  'family': 'artifact_evidence',
  'question_job': 'slice and dice',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.pivot',
                            'visual-pattern.presentation_sota.matrix',
                            'visual-pattern.presentation_sota.heatmap'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.narrative_explanation',
  'family': 'artifact_evidence',
  'question_job': 'narrative explanation',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.story_sequence',
                            'visual-pattern.presentation_sota.annotated_visual',
                            'visual-pattern.presentation_sota.scrollytelling'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.formal_publication',
  'family': 'artifact_evidence',
  'question_job': 'formal publication',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.paginated_report',
                            'visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.annotated_visual'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.evidence_provenance',
  'family': 'artifact_evidence',
  'question_job': 'evidence provenance',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.node_link',
                            'visual-pattern.presentation_sota.annotated_visual'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.natural_language_question',
  'family': 'artifact_evidence',
  'question_job': 'natural language question',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.accessible_equivalent',
  'family': 'artifact_evidence',
  'question_job': 'accessible equivalent',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.snapshot_compare',
  'family': 'artifact_evidence',
  'question_job': 'snapshot compare',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.dot_plot',
                            'visual-pattern.presentation_sota.small_multiples'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.export_fidelity',
  'family': 'artifact_evidence',
  'question_job': 'export fidelity',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.table',
                            'visual-pattern.presentation_sota.bar',
                            'visual-pattern.presentation_sota.line'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False},
 {'intent_id': 'intent.presentation_sota.freshness_status',
  'family': 'artifact_evidence',
  'question_job': 'freshness status',
  'candidate_visual_refs': ['visual-pattern.presentation_sota.single_value',
                            'visual-pattern.presentation_sota.kpi_with_delta',
                            'visual-pattern.presentation_sota.traffic_light'],
  'hard_law': 'Candidate visuals are admissible only after exact typed-result, authority, uncertainty, missingness, '
              'accessibility and resource constraints pass.',
  'completion_claim': False}]
