"""Official/primary evidence for the SOTA presentation semantics extension."""

SOURCES = [{'source_id': 'evidence.presentation_sota.product.celonis',
  'source_class': 'official_product_documentation',
  'title': 'Celonis Process Intelligence',
  'publisher': 'Celonis',
  'uri': 'https://docs.celonis.com/en/process-explorer.html',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: process_map, variant_explorer, '
                   'throughput_explorer, process_animation, process_filters, root_cause_handoff.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.uipath_process_mining',
  'source_class': 'official_product_documentation',
  'title': 'UiPath Process Mining',
  'publisher': 'UiPath',
  'uri': 'https://docs.uipath.com/process-mining/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: process_graph, variant_control, '
                   'kpi_bar, cross_analysis_table, process_heatmap.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.signavio_process_intelligence',
  'source_class': 'official_product_documentation',
  'title': 'SAP Signavio Process Intelligence',
  'publisher': 'SAP',
  'uri': 'https://help.sap.com/docs/signavio-process-intelligence',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: process_discovery, '
                   'process_conformance, variant_explorer, process_funnel, activity_list, live_insights.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.apromore',
  'source_class': 'official_product_documentation',
  'title': 'Apromore',
  'publisher': 'Apromore',
  'uri': 'https://documentation.apromore.org/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: process_map, variant_inspector, '
                   'frequency_duration_cost_overlays, bpmn_view, root_cause_analysis, saved_process_view.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.power_bi',
  'source_class': 'official_product_documentation',
  'title': 'Microsoft Power BI',
  'publisher': 'Microsoft',
  'uri': 'https://learn.microsoft.com/en-us/power-bi/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: interactive_report, dashboard, '
                   'paginated_report, matrix, decomposition_tree, key_influencers, map, bookmark.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.tableau',
  'source_class': 'official_product_documentation',
  'title': 'Salesforce Tableau',
  'publisher': 'Salesforce',
  'uri': 'https://help.tableau.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: worksheet, dashboard, story, '
                   'show_me_recommendation, small_multiples, maps, highlight_table, box_plot.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.qlik',
  'source_class': 'official_product_documentation',
  'title': 'Qlik Cloud Analytics',
  'publisher': 'Qlik',
  'uri': 'https://help.qlik.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: associative_exploration, kpi, '
                   'geospatial_breakdown, pareto, control_chart, forecast, anomaly.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.looker',
  'source_class': 'official_product_documentation',
  'title': 'Google Cloud Looker',
  'publisher': 'Google',
  'uri': 'https://cloud.google.com/looker/docs',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: explore, dashboard, '
                   'single_value, boxplot, waterfall, funnel, timeline, map.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.thoughtspot',
  'source_class': 'official_product_documentation',
  'title': 'ThoughtSpot',
  'publisher': 'ThoughtSpot',
  'uri': 'https://docs.thoughtspot.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: liveboard, '
                   'natural_language_analysis, automatic_chart_selection, visual_explorer, watchlist, custom_charts.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.sigma',
  'source_class': 'official_product_documentation',
  'title': 'Sigma Computing',
  'publisher': 'Sigma',
  'uri': 'https://help.sigmacomputing.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: workbook, table, pivot, '
                   'dashboard_layout, chart, input_table, app_ui, report_export.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.oracle_analytics',
  'source_class': 'official_product_documentation',
  'title': 'Oracle Analytics',
  'publisher': 'Oracle',
  'uri': 'https://docs.oracle.com/en/middleware/bi/analytics-server/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: auto_visualization, '
                   'network_graph, maps, grid, narrative, gauge, dashboard_controls.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.sap_analytics_cloud',
  'source_class': 'official_product_documentation',
  'title': 'SAP Analytics Cloud',
  'publisher': 'SAP',
  'uri': 'https://help.sap.com/docs/SAP_ANALYTICS_CLOUD',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: story, analytic_application, '
                   'variance_chart, waterfall, time_series, geo_layers, planning_table, in_cell_chart.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.cognos',
  'source_class': 'official_product_documentation',
  'title': 'IBM Cognos Analytics',
  'publisher': 'IBM',
  'uri': 'https://www.ibm.com/docs/en/cognos-analytics',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: dashboard, story, '
                   'auto_visualization, map, table, chart, plot.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.spotfire',
  'source_class': 'official_product_documentation',
  'title': 'Spotfire',
  'publisher': 'Spotfire',
  'uri': 'https://docs.tibco.com/products/tibco-spotfire',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: marking, linked_visualizations, '
                   'data_functions, statistical_tools, maps, custom_mods.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.strategy_one',
  'source_class': 'official_product_documentation',
  'title': 'Strategy One',
  'publisher': 'Strategy',
  'uri': 'https://www2.microstrategy.com/producthelp/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: grid, heatmap, dual_axis, '
                   'network, histogram, boxplot, waterfall, sankey.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.sisense',
  'source_class': 'official_product_documentation',
  'title': 'Sisense',
  'publisher': 'Sisense',
  'uri': 'https://docs.sisense.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: widget, dashboard, pivot, '
                   'scatter, kpi, map, recommended_widget.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.domo',
  'source_class': 'official_product_documentation',
  'title': 'Domo',
  'publisher': 'Domo',
  'uri': 'https://domo-support.domo.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: card, dashboard, '
                   'chart_compatibility_picker, maps, sparklines, running_total, funnel.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.metabase',
  'source_class': 'official_product_documentation',
  'title': 'Metabase',
  'publisher': 'Metabase',
  'uri': 'https://www.metabase.com/docs/latest/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: question, dashboard, auto_chart, '
                   'pivot, sankey, waterfall, funnel, map.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.superset',
  'source_class': 'official_product_documentation',
  'title': 'Apache Superset',
  'publisher': 'Apache',
  'uri': 'https://superset.apache.org/docs/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: explore, dashboard, '
                   'plugin_visualization, geospatial, sql_lab.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.palantir_foundry',
  'source_class': 'official_product_documentation',
  'title': 'Palantir Foundry',
  'publisher': 'Palantir',
  'uri': 'https://www.palantir.com/docs/foundry/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: object_chart, '
                   'time_series_analysis, dashboard, dependency_graph, operational_app_embedding, '
                   'parameterized_analysis.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.dataiku',
  'source_class': 'official_product_documentation',
  'title': 'Dataiku DSS',
  'publisher': 'Dataiku',
  'uri': 'https://doc.dataiku.com/dss/latest/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: dataset_chart, '
                   'visual_analysis_chart, dashboard_insight, model_report, map, scatter, animated_chart, subcharts.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.mode',
  'source_class': 'official_product_documentation',
  'title': 'Mode Analytics',
  'publisher': 'Mode',
  'uri': 'https://mode.com/help/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: sql_report, quick_chart, '
                   'python_r_visual, custom_javascript_visual, report_filter.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.rill',
  'source_class': 'official_product_documentation',
  'title': 'Rill',
  'publisher': 'Rill',
  'uri': 'https://docs.rilldata.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: explore_dashboard, '
                   'dimension_leaderboard, time_dimension_detail, pivot, multiple_measures.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.grafana',
  'source_class': 'official_product_documentation',
  'title': 'Grafana',
  'publisher': 'Grafana',
  'uri': 'https://grafana.com/docs/grafana/latest/visualizations/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: time_series, state_timeline, '
                   'status_history, logs, traces, flame_graph, node_graph, geomap.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.datadog',
  'source_class': 'official_product_documentation',
  'title': 'Datadog',
  'publisher': 'Datadog',
  'uri': 'https://docs.datadoghq.com/dashboards/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: timeseries, distribution, '
                   'heatmap, top_list, flame_graph, topology_map, hostmap, slo.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.dynatrace',
  'source_class': 'official_product_documentation',
  'title': 'Dynatrace',
  'publisher': 'Dynatrace',
  'uri': 'https://docs.dynatrace.com/docs/analyze-explore-automate/dashboards-and-notebooks',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: band_chart, honeycomb, '
                   'choropleth, connection_map, record_list, davis_view, dashboard_document.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.new_relic',
  'source_class': 'official_product_documentation',
  'title': 'New Relic',
  'publisher': 'New',
  'uri': 'https://docs.newrelic.com/docs/query-your-data/explore-query-data/dashboards/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: area, bar, billboard, gauge, '
                   'heatmap, histogram, line, table.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.kibana',
  'source_class': 'official_product_documentation',
  'title': 'Elastic Kibana Lens',
  'publisher': 'Elastic',
  'uri': 'https://www.elastic.co/guide/en/kibana/current/lens.html',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: lens, xy_layer, partition_chart, '
                   'metric, table, maps, vega_custom, annotations.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.splunk',
  'source_class': 'official_product_documentation',
  'title': 'Splunk Dashboard Studio',
  'publisher': 'Splunk',
  'uri': 'https://docs.splunk.com/Documentation/Splunk/latest/DashStudio/IntroFrame',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: event_viewer, time_series, '
                   'bubble, choropleth, sankey, timeline, custom_visualization.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.honeycomb',
  'source_class': 'official_product_documentation',
  'title': 'Honeycomb',
  'publisher': 'Honeycomb',
  'uri': 'https://docs.honeycomb.io/analyze/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: heatmap, bubbleup, '
                   'correlation_views, trace_view, events_view, query_assistant.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.amplitude',
  'source_class': 'official_product_documentation',
  'title': 'Amplitude Analytics',
  'publisher': 'Amplitude',
  'uri': 'https://amplitude.com/docs/analytics',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: event_segmentation, funnel, '
                   'retention, journeys, engagement_matrix, personas, impact_analysis, stickiness.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.ga4',
  'source_class': 'official_product_documentation',
  'title': 'Google Analytics 4 Explorations',
  'publisher': 'Google',
  'uri': 'https://support.google.com/analytics/answer/7579450',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: funnel_exploration, path_tree, '
                   'cohort_exploration, segment_overlap, free_form.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.anaplan',
  'source_class': 'official_product_documentation',
  'title': 'Anaplan UX',
  'publisher': 'Anaplan',
  'uri': 'https://help.anaplan.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: worksheet, board, report, '
                   'editable_grid, kpi_card, field_input, scenario.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.workday_adaptive',
  'source_class': 'official_product_documentation',
  'title': 'Workday Adaptive Planning',
  'publisher': 'Workday',
  'uri': 'https://doc.workday.com/adaptive-planning/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: dashboard, sheet, matrix_report, '
                   'report_book, scenario, prediction_vs_plan.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.primavera_p6',
  'source_class': 'official_product_documentation',
  'title': 'Oracle Primavera P6',
  'publisher': 'Oracle',
  'uri': 'https://docs.oracle.com/cd/F74771_01/client_help/en_US/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: gantt, resource_usage_histogram, '
                   'resource_usage_spreadsheet, time_phased_curve, s_curve.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.bloomberg',
  'source_class': 'official_product_documentation',
  'title': 'Bloomberg Terminal/BQuant',
  'publisher': 'Bloomberg',
  'uri': 'https://www.bloomberg.com/professional/product/bloomberg-terminal/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: market_monitor, '
                   'instrument_chart, candlestick, yield_curve, scenario_analysis, portfolio_report, heatmap, map.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.arcgis_dashboards',
  'source_class': 'official_product_documentation',
  'title': 'Esri ArcGIS Dashboards',
  'publisher': 'Esri',
  'uri': 'https://doc.arcgis.com/en/dashboards/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: map, serial_chart, pie, '
                   'indicator, gauge, list, table, details.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.carto',
  'source_class': 'official_product_documentation',
  'title': 'CARTO Builder',
  'publisher': 'CARTO',
  'uri': 'https://docs.carto.com/carto-user-manual/builder',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: map, formula_widget, '
                   'category_widget, histogram_widget, range_widget, time_series_widget, table_widget.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.mapbox',
  'source_class': 'official_product_documentation',
  'title': 'Mapbox Studio/GL',
  'publisher': 'Mapbox',
  'uri': 'https://docs.mapbox.com/mapbox-gl-js/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: choropleth, data_driven_circle, '
                   'data_driven_line, 3d_extrusion, heatmap, symbol_map.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.neo4j_bloom',
  'source_class': 'official_product_documentation',
  'title': 'Neo4j Bloom',
  'publisher': 'Neo4j',
  'uri': 'https://neo4j.com/docs/bloom-user-guide/current/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: graph_scene, perspective, '
                   'relationship_filter, business_view, custom_search_phrase.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.seeq',
  'source_class': 'official_product_documentation',
  'title': 'Seeq Workbench',
  'publisher': 'Seeq',
  'uri': 'https://support.seeq.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: trend_view, xy_plot, '
                   'tables_charts, treemap, summary_report, capsule_intervals.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.aveva_pi_vision',
  'source_class': 'official_product_documentation',
  'title': 'AVEVA PI Vision',
  'publisher': 'AVEVA',
  'uri': 'https://docs.aveva.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: realtime_display, trend, gauge, '
                   'color_coded_symbol, asset_collection, ad_hoc_analysis, visual_alarm.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.flourish',
  'source_class': 'official_product_documentation',
  'title': 'Flourish',
  'publisher': 'Flourish',
  'uri': 'https://help.flourish.studio/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: visualization_templates, story, '
                   'scrollytelling, animation, responsive_chart, survey_view, hierarchy_graph.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.datawrapper',
  'source_class': 'official_product_documentation',
  'title': 'Datawrapper',
  'publisher': 'Datawrapper',
  'uri': 'https://academy.datawrapper.de/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: accessible_chart, choropleth, '
                   'symbol_map, locator_map, table_heatmap, small_chart_in_table, annotation.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.observable_plot',
  'source_class': 'official_product_documentation',
  'title': 'Observable Plot',
  'publisher': 'Observable',
  'uri': 'https://observablehq.com/plot/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: mark_grammar, layered_marks, '
                   'transforms, facets, geo, raster, vector, tree.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.plotly_dash',
  'source_class': 'official_product_documentation',
  'title': 'Plotly/Dash',
  'publisher': 'Plotly/Dash',
  'uri': 'https://plotly.com/python/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: 3d_surface, volume, isosurface, '
                   'streamtube, ternary, polar, parallel_coordinates, sankey.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.hex',
  'source_class': 'official_product_documentation',
  'title': 'Hex',
  'publisher': 'Hex',
  'uri': 'https://learn.hex.tech/docs',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: chart_cell, notebook, '
                   'app_builder, input_control, filtered_dataframe_output.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.streamlit',
  'source_class': 'official_product_documentation',
  'title': 'Streamlit',
  'publisher': 'Streamlit',
  'uri': 'https://docs.streamlit.io/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: native_chart, vega_lite, plotly, '
                   'pydeck, graphviz, mermaid, interactive_input.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.jupyter',
  'source_class': 'official_product_documentation',
  'title': 'Project Jupyter',
  'publisher': 'Project',
  'uri': 'https://jupyter.org/documentation',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: notebook, mime_output, '
                   'interactive_widget, rich_display, code_narrative.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.autodesk_tandem',
  'source_class': 'official_product_documentation',
  'title': 'Autodesk Tandem',
  'publisher': 'Autodesk',
  'uri': 'https://help.autodesk.com/view/TANDEM/ENU/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: 3d_twin_view, saved_view, '
                   'asset_inventory, color_coding, clustering, section_plane.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.o9',
  'source_class': 'official_product_documentation',
  'title': 'o9 Digital Brain / Control Tower',
  'publisher': 'o9',
  'uri': 'https://o9solutions.com/solutions/supply-chain/control-tower/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: control_tower, scenario_compare, '
                   'exception_view, network_visibility, root_cause, decision_support.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.kinaxis_maestro',
  'source_class': 'official_product_documentation',
  'title': 'Kinaxis Maestro',
  'publisher': 'Kinaxis',
  'uri': 'https://www.kinaxis.com/en/solutions/supply-chain-orchestration',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: concurrent_planning, '
                   'control_tower, scenario, exception_management, root_cause, network_view.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.blue_yonder',
  'source_class': 'official_product_documentation',
  'title': 'Blue Yonder Supply Chain Command Center',
  'publisher': 'Blue',
  'uri': 'https://blueyonder.com/solutions/supply-chain-command-center',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: command_center, '
                   'network_visibility, exception_view, scenario, decision_support.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.microsoft_sentinel',
  'source_class': 'official_product_documentation',
  'title': 'Microsoft Sentinel',
  'publisher': 'Microsoft',
  'uri': 'https://learn.microsoft.com/en-us/azure/sentinel/monitor-your-data',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: workbook, incident_timeline, '
                   'entity_investigation, attack_technique_matrix, hunting_results.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.crowdstrike_ngsiem',
  'source_class': 'official_product_documentation',
  'title': 'CrowdStrike Next-Gen SIEM',
  'publisher': 'CrowdStrike',
  'uri': 'https://www.crowdstrike.com/en-us/platform/next-gen-siem/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: incident_graph, entity_context, '
                   'timeline, detection_dashboard, hunting_results.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.thousandeyes',
  'source_class': 'official_product_documentation',
  'title': 'Cisco ThousandEyes',
  'publisher': 'Cisco',
  'uri': 'https://docs.thousandeyes.com/product-documentation/internet-and-wan-monitoring/viewing-test-data/path-visualization',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: path_visualization, hop_by_hop, '
                   'loss_latency, outage_map, network_topology.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.kentik',
  'source_class': 'official_product_documentation',
  'title': 'Kentik',
  'publisher': 'Kentik',
  'uri': 'https://kb.kentik.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: network_explorer, flow_map, '
                   'path_view, traffic_matrix, capacity_view.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.nokia_ava',
  'source_class': 'official_product_documentation',
  'title': 'Nokia AVA',
  'publisher': 'Nokia',
  'uri': 'https://www.nokia.com/networks/analytics-and-ai/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: network_health, slice_health, '
                   'topology, anomaly_view, service_assurance.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.ohif',
  'source_class': 'official_product_documentation',
  'title': 'OHIF Viewer',
  'publisher': 'OHIF',
  'uri': 'https://docs.ohif.org/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: mpr, measurement_overlay, '
                   'segmentation_overlay, cine, registered_series_compare.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.three_d_slicer',
  'source_class': 'official_product_documentation',
  'title': '3D Slicer',
  'publisher': '3D',
  'uri': 'https://slicer.readthedocs.io/en/latest/user_guide/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: mpr, mip, volume_rendering, '
                   'segmentation, measurement, registered_volume_compare.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.syngo_via',
  'source_class': 'official_product_documentation',
  'title': 'Siemens syngo.via',
  'publisher': 'Siemens',
  'uri': 'https://www.siemens-healthineers.com/digital-health-solutions/syngo-via',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: mpr, mip, '
                   'curved_planar_reformation, cine, segmentation, measurement.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.autodesk_construction_cloud',
  'source_class': 'official_product_documentation',
  'title': 'Autodesk Construction Cloud',
  'publisher': 'Autodesk',
  'uri': 'https://help.autodesk.com/view/BUILD/ENU/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: model_viewer, issue_overlay, '
                   'model_coordination, progress_context, analytics_dashboard.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.bentley_itwin',
  'source_class': 'official_product_documentation',
  'title': 'Bentley iTwin',
  'publisher': 'Bentley',
  'uri': 'https://developer.bentley.com/apis/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: 3d_model_view, '
                   'change_visualization, issue_context, asset_context, reality_data_overlay.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.procore_analytics',
  'source_class': 'official_product_documentation',
  'title': 'Procore Analytics',
  'publisher': 'Procore',
  'uri': 'https://support.procore.com/products/online/user-guide/company-level/analytics',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: construction_dashboard, '
                   'schedule_view, cost_view, risk_view, reporting.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.nvidia_omniverse',
  'source_class': 'official_product_documentation',
  'title': 'NVIDIA Omniverse',
  'publisher': 'NVIDIA',
  'uri': 'https://docs.omniverse.nvidia.com/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: usd_scene, real_time_3d, '
                   'simulation_overlay, sensor_overlay, collaboration.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.tradingview',
  'source_class': 'official_product_documentation',
  'title': 'TradingView',
  'publisher': 'TradingView',
  'uri': 'https://www.tradingview.com/support/solutions/43000502000-chart-types/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: candlestick, line, area, '
                   'heikin_ashi, renko, kagi, point_and_figure, volume_profile.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.opensearch_dashboards',
  'source_class': 'official_product_documentation',
  'title': 'OpenSearch Dashboards',
  'publisher': 'OpenSearch',
  'uri': 'https://docs.opensearch.org/latest/dashboards/',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: dashboard, time_series, metric, '
                   'table, maps, vega, logs.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.product.splunk_enterprise_security',
  'source_class': 'official_product_documentation',
  'title': 'Splunk Enterprise Security',
  'publisher': 'Splunk',
  'uri': 'https://docs.splunk.com/Documentation/ES/latest/User/Investigations',
  'bounded_claim': 'Official product evidence for observed presentation capabilities: investigation, risk_analysis, '
                   'notable_events, incident_review, security_posture_dashboard.',
  'authority_limit': 'Provider documentation is adoption evidence only; it does not define Shannon Insight semantic '
                     'ownership or qualification.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.vegalite',
  'source_class': 'standard_or_primary_research',
  'title': 'Vega-Lite Documentation',
  'publisher': 'Vega Project',
  'uri': 'https://vega.github.io/vega-lite/docs/',
  'bounded_claim': 'Declarative marks, encodings, composition and interaction.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.wcag22',
  'source_class': 'standard_or_primary_research',
  'title': 'Web Content Accessibility Guidelines 2.2',
  'publisher': 'W3C',
  'uri': 'https://www.w3.org/TR/WCAG22/',
  'bounded_claim': 'Normative accessibility requirements for perceivable and operable content.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.graphics_aria',
  'source_class': 'standard_or_primary_research',
  'title': 'WAI-ARIA Graphics Module',
  'publisher': 'W3C',
  'uri': 'https://www.w3.org/TR/graphics-aria/',
  'bounded_claim': 'Structured graphics roles for accessibility APIs.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.prov_dm',
  'source_class': 'standard_or_primary_research',
  'title': 'PROV-DM',
  'publisher': 'W3C',
  'uri': 'https://www.w3.org/TR/prov-dm/',
  'bounded_claim': 'Provenance model for entities, activities, agents and derivations.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.ogc_maps',
  'source_class': 'standard_or_primary_research',
  'title': 'OGC API Maps',
  'publisher': 'OGC',
  'uri': 'https://ogcapi.ogc.org/maps/overview.html',
  'bounded_claim': 'Map portrayal separated from underlying spatial resources.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.ogc_tiles',
  'source_class': 'standard_or_primary_research',
  'title': 'OGC API Tiles',
  'publisher': 'OGC',
  'uri': 'https://ogcapi.ogc.org/tiles/overview.html',
  'bounded_claim': 'Tile delivery and matrix semantics.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.dicom',
  'source_class': 'standard_or_primary_research',
  'title': 'DICOM Standard',
  'publisher': 'NEMA',
  'uri': 'https://www.dicomstandard.org/current',
  'bounded_claim': 'Medical image objects, series, geometry and display-related standards.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.opentelemetry_trace',
  'source_class': 'standard_or_primary_research',
  'title': 'OpenTelemetry Traces',
  'publisher': 'OpenTelemetry',
  'uri': 'https://opentelemetry.io/docs/concepts/signals/traces/',
  'bounded_claim': 'Trace/span identity, parentage and timing semantics.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.cloudevents',
  'source_class': 'standard_or_primary_research',
  'title': 'CloudEvents 1.0',
  'publisher': 'CNCF',
  'uri': 'https://github.com/cloudevents/spec/blob/v1.0.2/cloudevents/spec.md',
  'bounded_claim': 'Event envelope identity and source/type/time metadata.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.xbrl',
  'source_class': 'standard_or_primary_research',
  'title': 'XBRL Specifications',
  'publisher': 'XBRL International',
  'uri': 'https://specifications.xbrl.org/specifications.html',
  'bounded_claim': 'Facts, contexts, units, taxonomies and presentation relationships.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.openformula',
  'source_class': 'standard_or_primary_research',
  'title': 'OpenFormula',
  'publisher': 'OASIS',
  'uri': 'https://docs.oasis-open.org/office/OpenDocument/v1.4/os/part4-formula/OpenDocument-v1.4-os-part4-formula.html',
  'bounded_claim': 'Spreadsheet formula syntax and evaluation semantics.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.nbformat',
  'source_class': 'standard_or_primary_research',
  'title': 'Jupyter Notebook Format',
  'publisher': 'Project Jupyter',
  'uri': 'https://nbformat.readthedocs.io/en/latest/format_description.html',
  'bounded_claim': 'Versioned notebook document cells and rich outputs.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.munzner_nested',
  'source_class': 'standard_or_primary_research',
  'title': 'A Nested Model for Visualization Design and Validation',
  'publisher': 'IEEE TVCG',
  'uri': 'https://doi.org/10.1109/TVCG.2009.111',
  'bounded_claim': 'Separates domain problem, abstraction, encoding/interaction and algorithm validation.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.olli',
  'source_class': 'standard_or_primary_research',
  'title': 'Olli: An Extensible Visualization Library for Screen Reader Accessibility',
  'publisher': 'MIT/IEEE VIS',
  'uri': 'https://vis.csail.mit.edu/pubs/olli/',
  'bounded_claim': 'Structured accessible alternatives for visualization.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.draco',
  'source_class': 'standard_or_primary_research',
  'title': 'Draco: Representing and Learning Visualization Design',
  'publisher': 'UW Interactive Data Lab',
  'uri': 'https://idl.cs.washington.edu/papers/draco/',
  'bounded_claim': 'Constraint-based visualization design and recommendation.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.voyager',
  'source_class': 'standard_or_primary_research',
  'title': 'Voyager: Exploratory Analysis via Faceted Browsing',
  'publisher': 'UW Interactive Data Lab',
  'uri': 'https://idl.cs.washington.edu/papers/voyager/',
  'bounded_claim': 'Visualization recommendation for exploratory analysis.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.graphscape',
  'source_class': 'standard_or_primary_research',
  'title': 'GraphScape',
  'publisher': 'UW Interactive Data Lab',
  'uri': 'https://idl.cs.washington.edu/papers/graphscape/',
  'bounded_claim': 'Graphical transitions and visualization sequence reasoning.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.cldr',
  'source_class': 'standard_or_primary_research',
  'title': 'Unicode CLDR',
  'publisher': 'Unicode Consortium',
  'uri': 'https://cldr.unicode.org/',
  'bounded_claim': 'Locale-sensitive formatting data.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.svg2',
  'source_class': 'standard_or_primary_research',
  'title': 'Scalable Vector Graphics 2',
  'publisher': 'W3C',
  'uri': 'https://www.w3.org/TR/SVG2/',
  'bounded_claim': 'Structured vector rendering carrier.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False},
 {'source_id': 'evidence.presentation_sota.standard.pdfua',
  'source_class': 'standard_or_primary_research',
  'title': 'PDF/UA',
  'publisher': 'PDF Association',
  'uri': 'https://pdfa.org/resource/pdfua-in-a-nutshell/',
  'bounded_claim': 'Accessible tagged PDF principles.',
  'authority_limit': 'Source informs a bounded semantic or validation law; it does not ratify a Shannon Insight '
                     'product or provider.',
  'retrieved_at': '2026-08-27',
  'completion_claim': False}]
