#!/usr/bin/env python3
"""Build an interaction-positioned semantic-role ontology and lossless all-member rebase."""
from __future__ import annotations
import json, sys
from pathlib import Path
from typing import Any

HERE=Path(__file__).resolve().parent; SEM=HERE.parent; AS_OF="2026-08-27"
PRECLASSIFICATIONS=SEM/"applicability_matrices/member-preclassifications.jsonl"
sys.path.insert(0,str(SEM))
from structural_coordinate_package import build_package, render_outputs  # noqa: E402

SOURCES=[
 {"source_id":"source.semantic-role.rust-traits","title":"Traits — The Rust Reference","publisher":"Rust Project","url":"https://doc.rust-lang.org/reference/items/traits.html","bounded_implication":"A trait declares an abstract interface of associated functions, types and constants that concrete types may implement.","authority_limit":"A trait signature or default method does not establish domain meaning, purity, effects, ownership, laws, total outcomes or qualification."},
 {"source_id":"source.semantic-role.wit","title":"WIT Reference — WebAssembly Component Model","publisher":"Bytecode Alliance / WebAssembly","url":"https://component-model.bytecodealliance.org/design/wit.html","bounded_implication":"Worlds distinguish required imports from provided exports, while interfaces and resources form typed component boundaries.","authority_limit":"WIT describes component contracts and direction, not business semantics, implementation fitness, authority or end-to-end behavior."},
 {"source_id":"source.semantic-role.prov-o","title":"PROV-O: The PROV Ontology","publisher":"W3C","url":"https://www.w3.org/TR/prov-o/","bounded_implication":"Qualified associations attach an agent role and optional plan to one activity; role is positioned in a relation rather than intrinsic to the agent.","authority_limit":"Provenance roles do not establish application authority, contractual duties, semantic ownership or implementation qualification."},
 {"source_id":"source.semantic-role.hexagonal","title":"Hexagonal Architecture — original 2005 article","publisher":"Alistair Cockburn","url":"https://alistair.cockburn.us/hexagonal-architecture","bounded_implication":"Ports express application interactions while technology-specific adapters translate external devices or systems at the boundary.","authority_limit":"The pattern does not choose SAN port granularity, domain semantics, provider quality, failure contracts or compiler bindings."},
 {"source_id":"source.semantic-role.reactive-streams","title":"Reactive Streams Specification for the JVM","publisher":"Reactive Streams","url":"https://github.com/reactive-streams/reactive-streams-jvm","bounded_implication":"Publisher, Subscriber, Subscription and Processor have distinct interaction roles; a Processor simultaneously obeys subscriber and publisher contracts.","authority_limit":"These roles govern asynchronous stream exchange, not domain ownership, transformation semantics, event truth or arbitrary execution."},
 {"source_id":"source.semantic-role.kubernetes-controller","title":"Kubernetes Controllers","publisher":"Kubernetes","url":"https://kubernetes.io/docs/concepts/architecture/controller/","bounded_implication":"A controller observes current state and makes or requests changes to move it toward desired state; it need not perform effects itself.","authority_limit":"Controller mechanics do not establish desired-state authority, domain acceptance, general workflow ownership or exact reconciliation semantics."},
 {"source_id":"source.semantic-role.otel","title":"OpenTelemetry Specification Overview","publisher":"OpenTelemetry / CNCF","url":"https://opentelemetry.io/docs/specs/otel/overview/","bounded_implication":"APIs, SDKs, instrumentation, processors, exporters and propagators occupy different telemetry roles and package boundaries.","authority_limit":"Instrumentation and export do not constitute business behavior, source-of-truth ownership, semantic evidence sufficiency or acceptance."},
 {"source_id":"source.semantic-role.odrl","title":"ODRL Information Model 2.2","publisher":"W3C","url":"https://www.w3.org/TR/odrl-model/","bounded_implication":"Parties occupy scoped functional roles such as assigner and assignee within policies and rules.","authority_limit":"A role token does not itself prove party identity, delegation, effective authority, fulfillment or enforcement."},
 {"source_id":"source.semantic-role.cloudevents","title":"CloudEvents Specification","publisher":"CNCF","url":"https://github.com/cloudevents/spec/blob/main/cloudevents/spec.md","bounded_implication":"Event producers, consumers, intermediaries, context attributes and data can be distinguished at an event boundary.","authority_limit":"Producing or consuming an envelope does not establish semantic ownership, occurrence truth, processing authority or accepted effects."},
 {"source_id":"source.semantic-role.substrait","title":"Substrait Specification","publisher":"Substrait Project","url":"https://substrait.io/","bounded_implication":"A portable plan separates producers of relational plans, extension declarations and consuming execution engines.","authority_limit":"Plan production does not imply execution, optimizer correctness, connector fitness, effect authority or semantic equivalence."},
]

ROLE_ARCHETYPES=[
 ("carrier_or_value_type","Carries a value under an owned semantic contract."),("identifier_or_reference_type","Names or resolves another subject."),
 ("predicate_or_specification","States a pure condition or reusable specification."),("pure_transformation","Maps inputs to outputs without external effects under declared laws."),
 ("algebra_or_calculus","Defines operators, operands, results and laws."),("parser_or_interpreter","Turns a surface language into a structured meaning candidate."),
 ("validator_or_conformance_checker","Evaluates a subject against an explicit contract or profile."),("canonicalizer_or_normalizer","Selects a scoped representative under one equivalence relation."),
 ("comparator_or_reconciler","Compares positions and produces differences or convergence actions."),("planner","Produces a prospective plan from intent and constraints."),
 ("compiler_or_lowerer","Transforms one declared language/IR into another while preserving obligations."),("optimizer","Selects an equivalent or authorized-bounded alternative under objectives."),
 ("policy_evaluator","Evaluates applicable rules without itself performing the governed effect."),("decision_service","Renders a scoped decision or judgment from inputs and authority."),
 ("required_port","Capability/interface the component requires from its environment."),("provided_port","Capability/interface the component exposes to its environment."),
 ("inbound_adapter","Translates an external driver into a provided port."),("outbound_adapter","Translates a required port into a provider protocol."),
 ("anti_corruption_layer","Protects owned meaning by translating a foreign model at a boundary."),("provider_or_implementation","Concrete implementation offered for a required contract."),
 ("runtime_or_executor","Performs a plan, command or operation with total outcomes."),("scheduler_or_dispatcher","Selects when and where admitted work runs."),
 ("controller_or_reconciler","Observes divergence and requests actions toward desired state."),("coordinator_or_process_manager","Coordinates participants across a long-running process."),
 ("repository","Loads and saves aggregate roots while preserving aggregate semantics."),("ledger_or_journal","Retains append/history/evidence facts under ordering and correction rules."),
 ("cache_index_or_materialization","Derived acceleration structure with explicit invalidation and authority limits."),("source_reader_or_publisher","Provides values, records or signals under a source contract."),
 ("sink_writer_or_subscriber","Consumes and possibly effects values under a sink contract."),("processor","Occupies both consumer and producer roles under two directional contracts."),
 ("query_or_projection","Answers or projects from owned sources without becoming source of truth."),("registry_catalog_or_resolver","Registers metadata or resolves references under scoped authority."),
 ("factory_or_builder","Creates valid semantic subjects under construction invariants."),("allocator_or_admission_controller","Grants or refuses bounded resource assignments."),
 ("authorizer_or_enforcer","Checks or enforces authority at an exact action/effect boundary."),("effect_handler","Attempts an authorized external world change."),
 ("migration_upcaster_or_backfill","Transforms historical/editioned state with explicit compatibility and residuals."),("codec_or_representation_adapter","Maps logical subjects to/from carriers with declared loss."),
 ("oracle_or_verifier","Produces scoped evidence about conformance or properties."),("instrumentation_or_evidence_emitter","Observes execution and emits telemetry/evidence without owning behavior."),
 ("claimant_or_proposer","Advances a claim, intent or proposed action."),("reviewer_approver_or_acceptor","Reviews, approves or accepts within an authority scope."),
 ("semantic_owner","Owns meaning and its evolution inside a bounded context."),("implementation_owner_or_operator","Owns implementation or operations, distinct from semantic ownership."),
 ("producer_input_or_caller_position","Supplies an input/request in one interaction."),("consumer_output_or_callee_position","Receives an output/request in one interaction."),
]

KERNELS=["bind_role","unbind_role","qualify_role_relation","require_port","provide_port","match_import_to_export","adapt_inbound","adapt_outbound","translate_foreign_model","register_provider_offer","qualify_provider","select_provider","replace_provider","fail_over_provider","delegate_role","revoke_delegation","separate_semantic_and_implementation_owner","parse_or_interpret","validate_or_conform","canonicalize_or_normalize","compare_or_reconcile","derive_or_transform","plan","compile_or_lower","optimize","evaluate_policy","render_decision","authorize","enforce","read_or_publish","consume_or_write","process_bidirectionally","persist_or_retrieve","append_to_ledger","project_or_query","cache_or_materialize","invalidate_derived_state","schedule_or_dispatch","execute","observe_and_reconcile","coordinate_process","compensate","allocate_or_admit","release_allocation","handle_effect","accept_or_reject_effect","migrate_or_upcast","encode_or_decode","emit_instrumentation","evaluate_with_oracle","issue_evidence_receipt","compose_roles","check_role_compatibility","refuse_role_punning"]

def archetypes():
 return [{"record_kind":"semantic_role_archetype","archetype_id":f"archetype.semantic-role.{n}.v1","meaning":m,"applicability":"UNRESOLVED_PER_INTERACTION_AND_USE_SITE","completion_claim":False} for n,m in ROLE_ARCHETYPES]
def kernels():
 return [{"record_kind":"semantic_role_operation_kernel","kernel_id":f"kernel.semantic-role.{n.replace('_','-')}.v1","operation":n,"required_input":"EXACT_SUBJECT_KIND_ROLE_CONTRACT_OPERATION_AND_COUNTERPARTY","required_output":"TYPED_ROLE_BINDING_OR_REFUSAL_WITH_RESIDUALS","effect_classification":"MUST_BE_DECLARED_PER_BINDING","completion_claim":False} for n in KERNELS]

ONTOLOGY={"ontology_id":"ontology.semantic-axis.semantic-role-coordinate.v1","edition":1,"as_of":AS_OF,"axis":"semantic_role","domain_question":"For this exact subject in this exact interaction, what role does it occupy relative to which operation, counterparty, port, authority, effect and responsibility boundary?","coordinate_key":["bounded_context_ref","semantic_subject_ref","semantic_object_kind_ref","role_ref","contract_or_operation_ref","counterparty_ref","direction_and_position_ref","edition_ref","use_site_ref"],"required_coordinate_fields":["intrinsic_subject_kind_versus_contextual_role","role_contract_and_operation_position","required_versus_provided_direction","input_output_control_and_effect_position","counterparty_and_interaction_scope","semantic_owner_implementation_owner_provider_and_operator","port_adapter_acl_provider_and_runtime_seams","pure_effectful_and_determinism_class","authority_delegation_and_separation_of_duties","state_source_of_truth_and_mutation_responsibility","resource_budget_and_admission_responsibility","failure_cancellation_recovery_and_compensation_responsibility","time_lifecycle_multiplicity_and_exclusivity","composition_laws_and_role_imports","representation_translation_and_loss","sync_async_stream_backpressure_and_completion","evidence_oracle_telemetry_and_acceptance_responsibility","compatibility_qualification_and_conformance"],"non_collapse_laws":["subject_kind_is_not_interaction_role","trait_or_interface_is_not_semantic_contract","port_is_not_adapter_provider_or_runtime","adapter_is_not_semantic_owner","provider_is_not_implementation_or_semantic_owner","planner_or_compiler_output_is_not_execution","predicate_is_not_policy_decision_authorization_or_enforcement","pure_transform_is_not_migration_or_external_effect","repository_is_not_aggregate_ledger_or_source_of_truth_by_default","projection_cache_and_index_are_not_source_of_truth","oracle_is_not_implementation_and_telemetry_is_not_business_behavior","controller_is_not_controlled_resource_or_effect_handler","producer_is_not_source_authority_and_consumer_is_not acceptor","one_subject_may_hold_multiple_explicit_roles_but_authority_does_not_transfer_implicitly","default_trait_method_is_not_universal_domain_default"],"compiler_refusals":["REFUSE_UNBOUND_ROLE_OR_COUNTERPARTY","REFUSE_KIND_ROLE_PUNNING","REFUSE_REQUIRED_PROVIDED_DIRECTION_AMBIGUITY","REFUSE_PORT_ADAPTER_PROVIDER_COLLAPSE","REFUSE_PLANNER_EXECUTOR_OR_OBSERVER_EFFECT_COLLAPSE","REFUSE_SEMANTIC_OWNER_PROVIDER_COLLAPSE","REFUSE_UNBOUND_AUTHORITY_EFFECT_FAILURE_OR_EVIDENCE_RESPONSIBILITY"],"status":"STRUCTURAL_COORDINATE_ONTOLOGY_DECISIONS_OPEN","completion_claim":False}

def route(f): return "LEXICAL_DISCOVERY_PROJECTION_ONLY_ROLE_RESEARCH_REQUIRED" if f else "NO_MEMBER_INTERACTION_ROLE_EVIDENCE_VACANCY"
def build():
 return build_package(axis="semantic_role",preclassifications_path=PRECLASSIFICATIONS,docket_prefix="docket.semantic-role-coordinate",docket_record_kind="semantic_role_structural_rebase_docket",cluster_prefix="cluster.semantic-role-coordinate-rebase",cluster_record_kind="semantic_role_member_research_cluster",member_record_kind="semantic_role_member_research_route",member_route_prefix="route.semantic-role-coordinate",extension_record_kind="semantic_role_exact_contract_extension_candidate",extension_prefix="extension.semantic-role-coordinate",route_for_facets=route,cluster_next_evidence=["authoritative per-operation role and counterparty inventory","required/provided port adapter provider runtime and ownership seams","authority effect resource failure and evidence responsibilities","negative twins and role conformance oracles"],member_open_fields={"required_interaction_role_inventory":"NOT_YET_SUPPLIED","required_port_adapter_provider_and_owner_profile":"NOT_YET_SUPPLIED","required_authority_effect_failure_and_evidence_responsibilities":"NOT_YET_SUPPLIED"},extension_record_kinds=["interaction_role_inventory","required_provided_port_contract","adapter_acl_and_provider_binding","role_authority_effect_and_failure_profile","role_conformance_oracle"],ontology=ONTOLOGY,sources=SOURCES,archetypes=archetypes(),kernels=kernels(),summary_base={"program_id":"program.semantic-role-coordinate-ontology-and-rebase.v1","as_of":AS_OF,"axis":"semantic_role","semantic_role_archetypes":len(ROLE_ARCHETYPES),"semantic_role_operation_kernels":len(KERNELS),"interaction_role_inventories_supplied":0,"semantic_role_coordinate_profiles_supplied":0},lexical_summary_key="routes_with_lexical_discovery_projection",vacancy_summary_key="routes_with_no_member_role_evidence")
def outputs(): return render_outputs(built=build(),ontology_filename="semantic-role-coordinate-ontology.json",archetypes_filename="semantic-role-archetypes.jsonl",kernels_filename="semantic-role-operation-kernels.jsonl",members_filename="member-semantic-role-routes.jsonl",manifest_id="manifest.semantic-role-coordinate-ontology-and-rebase.v1",as_of=AS_OF)
def main():
 for n,t in outputs().items(): (HERE/n).write_text(t)
 s=build()["summary"]; print(f"BUILD PASS semantic-role coordinate ontology: {s['semantic_role_archetypes']} roles, {s['semantic_role_operation_kernels']} kernels, {s['research_clusters']} clusters and {s['target_member_routes']} exact routes; decisions remain zero"); return 0
if __name__=="__main__": raise SystemExit(main())
