#!/usr/bin/env python3
"""Build the Phase-5 semantic role/composition/resources/evidence constitution candidate."""

from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any

HERE=Path(__file__).resolve().parent
AS_OF="2026-08-26"

def canonical(value:Any)->str:return json.dumps(value,ensure_ascii=False,sort_keys=True,separators=(",",":"))

def build()->dict[str,Any]:
    sources=[
        {"source_id":"source.semantic-phase5.rust.traits","publisher":"Rust project","source_kind":"language_reference","title":"The Rust Reference — Traits","url":"https://doc.rust-lang.org/reference/items/traits.html","claim_scope":"abstract interfaces, implementations, associated functions/types/constants and bounds","authority_limit":"Rust traits encode type-level interface obligations; they do not by themselves express domain laws, effects, total failures, resource bounds or conformance evidence."},
        {"source_id":"source.semantic-phase5.wasm.wit","publisher":"WebAssembly Component Model project","source_kind":"design_specification","title":"WebAssembly Interface Types (WIT)","url":"https://github.com/WebAssembly/component-model/blob/main/design/mvp/WIT.md","claim_scope":"typed imports/exports, resources, worlds and cross-language component interfaces","authority_limit":"WIT describes component interfaces and bindings, not business semantics, algebraic laws, provider quality or end-to-end behavior."},
        {"source_id":"source.semantic-phase5.crdt","publisher":"INRIA / authors","source_kind":"research_paper","title":"Conflict-free Replicated Data Types","url":"https://perso.lip6.fr/Marc.Shapiro/papers/2011/CRDTs_SSS-2011.pdf","claim_scope":"convergence conditions for state- and operation-based replicated data types","authority_limit":"The paper proves convergence under explicit assumptions; it does not make arbitrary merges semantically valid or establish application invariants, authorization or loss acceptance."},
        {"source_id":"source.semantic-phase5.reactive-streams","publisher":"Reactive Streams project","source_kind":"specification_and_tck","title":"Reactive Streams JVM Specification 1.0.4","url":"https://github.com/reactive-streams/reactive-streams-jvm","claim_scope":"asynchronous sequenced stream exchange with non-blocking backpressure and a TCK","authority_limit":"Covers mediation between stream components; it does not define transformations, business ordering, durability, exactly-once effects or all runtime resource policies."},
        {"source_id":"source.semantic-phase5.ietf.problem-details","publisher":"IETF","source_kind":"internet_standard","title":"RFC 9457 Problem Details for HTTP APIs","url":"https://www.rfc-editor.org/rfc/rfc9457.html","claim_scope":"machine-readable HTTP problem type and occurrence details","authority_limit":"Defines an HTTP representation for interface problems, not an internal exception model, retry policy, root cause, compensation result or universal domain refusal catalog."},
        {"source_id":"source.semantic-phase5.tla","publisher":"Leslie Lamport / Microsoft Research","source_kind":"primary_specification_text","title":"Specifying and Verifying Systems With TLA+","url":"https://lamport.org/pubs/spec-and-verifying.pdf","claim_scope":"state-machine specifications using initial states, next-state relation, safety and liveness properties","authority_limit":"A model proves only encoded properties within its abstraction and assumptions; it does not prove implementation refinement, environment behavior or product fitness without further evidence."},
        {"source_id":"source.semantic-phase5.w3c.prov","publisher":"W3C","source_kind":"recommendation","title":"PROV-O: The PROV Ontology","url":"https://www.w3.org/TR/prov-o/","claim_scope":"interchange of provenance about entities, activities, agents, generation, use and derivation","authority_limit":"Provenance records origins and relations; it does not establish truth, authorization, causal sufficiency, integrity or acceptance."},
        {"source_id":"source.semantic-phase5.w3c.conformance","publisher":"W3C","source_kind":"working_group_note","title":"A Method for Writing Testable Conformance Requirements","url":"https://www.w3.org/TR/test-methodology/","claim_scope":"testable normative requirements and derivation of implementation-independent tests","authority_limit":"Methodological guidance cannot make an underspecified requirement testable or prove completeness of a test suite or implementation."},
        {"source_id":"source.semantic-phase5.quickcheck","publisher":"Koen Claessen and John Hughes","source_kind":"research_paper","title":"QuickCheck: A Lightweight Tool for Random Testing of Haskell Programs","url":"https://www.cs.tufts.edu/~nr/cs257/archive/john-hughes/quick.pdf","claim_scope":"executable properties, generated test data and shrinking counterexamples","authority_limit":"Random testing finds counterexamples under generators and seeds; passing tests is not a universal proof and properties can reproduce specification mistakes."},
        {"source_id":"source.semantic-phase5.opentelemetry","publisher":"OpenTelemetry project","source_kind":"specification","title":"OpenTelemetry Specification","url":"https://opentelemetry.io/docs/specs/otel/overview/","claim_scope":"traces, metrics, logs, context, resources, propagation and telemetry pipelines","authority_limit":"Telemetry is sampled and pipeline-dependent observation; it does not by itself prove causality, completeness, business outcome, conformance or absence of failure."},
    ]
    constitution={
        "record_kind":"semantic_axis_phase_constitution_candidate","constitution_id":"constitution.semantic-axis.phase5.behavior-resources-proof.v1","edition":1,"as_of":AS_OF,"status":"EVIDENCE_BACKED_CANDIDATE_PENDING_OWNER_RATIFICATION","completion_claim":False,
        "sovereign_question":"What exact role and law does each library own, how may it compose, under which finite resources and total failure semantics, and what edition-bound evidence is sufficient to trust an implementation for a declared profile?",
        "negative_mission":"Do not infer laws from type signatures, composability from plug compatibility, reliability from retries, success from absence of exceptions, conformance from examples, truth from provenance, or proof from telemetry or AI-generated tests.",
        "modules":[
            {"module_id":"module.semantic-axis.semantic-role.v1","axis":"semantic_role",
             "role_kinds":["carrier/value type","pure predicate/specification","pure transformation","algebra/calculus","policy/decision","planner/compiler","port/SPI","adapter/ACL","runtime/executor","ledger/repository","oracle/verifier","projection/query","coordination/process manager","instrumentation/evidence emitter"],
             "operation_coordinates":["owned verb","input semantic types","output/total outcome types","preconditions","postconditions","invariants/laws","purity/effect class","determinism","partiality/refusals","time/order semantics","authority phase","resource contract","concurrency/thread/cancellation contract","evidence emitted","edition/compatibility profile"],
             "non_collapse_laws":["a type signature is not a semantic contract","carrier type is not entity aggregate repository or DTO","predicate is not policy decision or authorization","pure transformation is not migration or external effect","planner/compiler output is intent not execution","port is not adapter provider or runtime","adapter is not semantic owner","repository is not aggregate or event ledger","oracle is not implementation","projection is not source of truth","instrumentation is not business behavior","default trait method is not a universal domain default","async syntax does not establish cancellation backpressure or thread safety","genericity is not domain generality","one role may import another but cannot silently absorb its authority","every public operation has total typed outcomes rather than hidden panics or string errors"],
             "required_outcomes":["satisfied","produced","not_applicable","indeterminate","refused","unsupported","resource_exhausted","cancelled","failed_with_typed_cause"]},
            {"module_id":"module.semantic-axis.composition-algebra.v1","axis":"composition_algebra",
             "composition_coordinates":["operator and notation","operand roles/types","result role/type","closure","identity/zero","associativity","commutativity","idempotence","distributivity/absorption","monotonicity","order/precedence","conflict semantics","partiality/domain","loss/residual","termination/fixed point","incrementality","parallelization/reordering permission","proof obligations"],
             "composition_forms":["sequential/pipe","product/parallel","choice/fallback","join/meet/merge","overlay/override","fold/reduce","graph/workflow","feedback/fixed_point","adapter/refinement","policy combining"],
             "non_collapse_laws":["syntactic nesting is not semantic composition","shared carrier is not closed composition","merge join union overlay override and reconciliation are distinct","associativity commutativity and idempotence are never assumed","identity zero bottom top empty missing and unknown remain distinct","fallback is not catch-all error suppression","parallel execution requires proved independence order and resource bounds","reordering requires an explicit law for the declared profile","fixed-point iteration requires order termination and widening/convergence conditions","monotonicity in one order does not imply monotonicity in another","CRDT convergence does not establish application invariant preservation","conflict-free does not mean conflict absent","lossy composition exposes residual information","policy combining is not boolean folding","adapter composition multiplies preservation obligations","optimization may use only ratified laws and must preserve refusals/effects/evidence"],
             "required_outcomes":["composed","composed_with_residual","conflict","non_convergent","law_unproved","type_mismatch","order_unsafe","unsupported","refused"]},
            {"module_id":"module.semantic-axis.resources-failure.v1","axis":"resources_and_failure",
             "resource_coordinates":["resource kind/unit","demand interval/burst","offer/capability edition","reservation/admission","quota and authority scope","precharge/budget","placement/topology/locality","isolation/contention","latency/deadline","throughput/concurrency","memory/storage/network/compute","energy/carbon/cost","backpressure/overload","usage accounting","release/reclamation evidence"],
             "failure_coordinates":["failure type/code","phase and operation","subject/attempt occurrence","transient/permanent/indeterminate","retry safety and budget","partial/unknown completion","cancellation observation","fault vs refusal vs resource exhaustion","provider vs adapter vs domain source","blast radius/failure domain","degraded mode","reconciliation/compensation","operator action","evidence and redaction","residual owner"],
             "non_collapse_laws":["capacity offer is not reservation allocation or observed availability","quota is not budget reservation precharge or usage","deadline timeout cancellation and termination are distinct","backpressure is not unbounded buffering or silent dropping","retry is a new attempt and consumes budget","transient labels do not prove retry safety","failure exception refusal rejection and defect remain distinct","provider error is translated at the ACL and does not become a domain error by string mapping","partial failure and unknown completion are total outcomes","cancellation request does not prove work stopped","compensation is not rollback and can fail","degraded mode requires separate authority and acceptance","availability is scoped by time topology and failure assumptions","observed latency is not an SLO guarantee","resource reclamation needs evidence where leaks matter","overload policies preserve fairness authority and safety constraints"],
             "required_outcomes":["admitted","queued","backpressured","degraded","completed","partially_completed","resource_exhausted","deadline_exceeded","cancelled","failed","unknown_completion","refused"]},
            {"module_id":"module.semantic-axis.evidence-conformance.v1","axis":"evidence_and_conformance",
             "evidence_coordinates":["claim","claim type/strength","subject and exact edition","profile/requirements","evidence artifact identity","producer/issuer","method/oracle","input corpus/generator/model","environment/configuration","coverage and exclusions","result/counterexample","time/freshness","integrity/provenance","independence/conflicts/defeaters","accepting authority and residual"],
             "oracle_classes":["type/static check","example/boundary test","property-based test","metamorphic/differential test","model/state-machine check","fuzz/mutation test","conformance/TCK","trace/runtime invariant","formal proof/refinement","independent implementation/appraisal","production acceptance observation"],
             "non_collapse_laws":["claim is not evidence and evidence is not acceptance","provenance is not truth or integrity","integrity is not correctness","test pass is scoped to edition profile inputs environment and oracle","examples do not establish universal laws","property-based testing is not exhaustive proof","shrinking a counterexample does not identify root cause","model checking proves the model within explored bounds not its implementation","formal proof is relative to assumptions specification and refinement","telemetry absence is not absence of failure","coverage percentage is not behavioral completeness","a TCK proves only encoded conformance requirements","self-attestation is not independent appraisal","two implementations can share the same specification error","AI or agents may generate hypotheses/tests but cannot be evidence authority or accept residual risk","evidence expires when relied-upon meaning code dependency provider configuration or environment changes","negative/adversarial twins are required for dangerous boundary claims","every verdict preserves unresolved defeaters and the residual owner"],
             "required_outcomes":["conforms_for_profile","conforms_with_exceptions","counterexample_found","nonconformant","inconclusive","oracle_invalid","evidence_stale","coverage_insufficient","conflicting_evidence","acceptance_required","refused"]},
        ],
        "cross_module_laws":["A library's semantic role selects its lawful composition operators, resource contract, refusal surface and minimum oracle classes.","Compiler optimizations may use only explicit algebraic laws whose evidence covers the exact editions and semantic profile.","Every effectful composition aggregates finite budgets, cancellation, partiality, evidence and failure domains instead of erasing them.","Conformance is claim×subject-edition×profile×evidence×verdict; no global conformant flag exists.","Provider qualification requires contract conformance and operational acceptance; neither substitutes for the other.","Agents and learned components remain optional bounded providers behind the same deterministic contracts, refusals, budgets and evidence gates."],
        "imported_foundation_refs":["library.csp.intent.constraint-algebra","library.csp.authority.policy-algebra","library.method_kernels.result_algebra","library.lpe.prov-statement-algebra","library.lpe.evidence-evaluation","library.lpe.evidence-bundle","library.cp.conformance_oracle","library.qck.kernel-conformance","library.runtime-resource.resource-quantity","library.runtime-resource.demand-offer-compatibility","library.runtime-resource.admission","library.runtime-resource.quota-ledger","library.runtime-resource.budget-precharge","library.runtime-resource.backpressure","library.runtime-resource.deadline-cancellation","library.runtime-resource.resource-topology","library.runtime-resource.runtime-receipts","library.runtime-resource.conformance-oracles"],
        "prohibited_new_facades":["universal_service","universal_pipeline","universal_merge","universal_retry","universal_error","universal_resource","universal_evidence","universal_conformance_boolean","universal_observability_proof"],
        "ratification_gate":"Named semantic, algebra, runtime/resource, assurance and every affected family owner accept roles, laws, budgets, total failures, oracle sufficiency and evidence expiry; implementations remain unqualified until profile-specific conformance and acceptance pass.",
    }
    claims=[
        {"claim_id":"claim.phase5.rust-trait-interface","source_ref":"source.semantic-phase5.rust.traits","bounded_claim":"Rust traits define abstract interfaces through functions, types and constants implemented for concrete types; associated declarations form the type-level contract available to generic code.","supports_module_refs":["module.semantic-axis.semantic-role.v1"],"authority_limit":sources[0]["authority_limit"]},
        {"claim_id":"claim.phase5.wit-typed-ports","source_ref":"source.semantic-phase5.wasm.wit","bounded_claim":"WIT expresses typed imports, exports, resources and worlds that can serve as language-neutral component port boundaries.","supports_module_refs":["module.semantic-axis.semantic-role.v1","module.semantic-axis.composition-algebra.v1"],"authority_limit":sources[1]["authority_limit"]},
        {"claim_id":"claim.phase5.crdt-law-bounds","source_ref":"source.semantic-phase5.crdt","bounded_claim":"CRDT convergence follows only for defined state- or operation-based designs satisfying their stated algebraic and delivery assumptions.","supports_module_refs":["module.semantic-axis.composition-algebra.v1"],"authority_limit":sources[2]["authority_limit"]},
        {"claim_id":"claim.phase5.reactive-backpressure","source_ref":"source.semantic-phase5.reactive-streams","bounded_claim":"Reactive Streams specifies asynchronous sequenced exchange with mandatory non-blocking backpressure and supplies a TCK for encoded interoperability rules.","supports_module_refs":["module.semantic-axis.resources-failure.v1","module.semantic-axis.evidence-conformance.v1"],"authority_limit":sources[3]["authority_limit"]},
        {"claim_id":"claim.phase5.problem-occurrence","source_ref":"source.semantic-phase5.ietf.problem-details","bounded_claim":"RFC 9457 distinguishes a reusable machine-readable problem type from a URI-identifiable problem occurrence at an HTTP boundary.","supports_module_refs":["module.semantic-axis.resources-failure.v1"],"authority_limit":sources[4]["authority_limit"]},
        {"claim_id":"claim.phase5.tla-model-scope","source_ref":"source.semantic-phase5.tla","bounded_claim":"TLA+ specifications separate initial states, next-state behavior, safety and liveness, making system assumptions and properties explicit at the model level.","supports_module_refs":["module.semantic-axis.composition-algebra.v1","module.semantic-axis.evidence-conformance.v1"],"authority_limit":sources[5]["authority_limit"]},
        {"claim_id":"claim.phase5.provenance-bound","source_ref":"source.semantic-phase5.w3c.prov","bounded_claim":"PROV-O represents provenance relations among entities, activities and agents and can be specialized for domain interchange.","supports_module_refs":["module.semantic-axis.evidence-conformance.v1"],"authority_limit":sources[6]["authority_limit"]},
        {"claim_id":"claim.phase5.testable-requirement","source_ref":"source.semantic-phase5.w3c.conformance","bounded_claim":"Testable conformance begins with precise normative requirements whose subjects, conditions and required behavior can be mapped to implementation-independent tests.","supports_module_refs":["module.semantic-axis.evidence-conformance.v1"],"authority_limit":sources[7]["authority_limit"]},
        {"claim_id":"claim.phase5.property-counterexamples","source_ref":"source.semantic-phase5.quickcheck","bounded_claim":"QuickCheck turns executable properties and generators into reproducible randomized tests and shrinks failures toward smaller counterexamples.","supports_module_refs":["module.semantic-axis.evidence-conformance.v1"],"authority_limit":sources[8]["authority_limit"]},
        {"claim_id":"claim.phase5.telemetry-observation","source_ref":"source.semantic-phase5.opentelemetry","bounded_claim":"OpenTelemetry defines distinct trace, metric and log signals with shared context/resource conventions and pluggable processing/export pipelines.","supports_module_refs":["module.semantic-axis.resources-failure.v1","module.semantic-axis.evidence-conformance.v1"],"authority_limit":sources[9]["authority_limit"]},
    ]
    projection={
        "record_kind":"semantic_axis_compiler_projection_candidate","projection_id":"projection.compiler.semantic-axis.phase5.v1","edition":1,"status":"STRUCTURAL_PROJECTION_NOT_IR_AUTHORITY",
        "required_ir_roles":["SemanticRoleRef","OperationContractRef","InputTypeRef","OutcomeTypeRef","LawSetRef","EffectClassRef","DeterminismProfileRef","PortRef","AdapterRef","CompositionOperatorRef","CompositionProofRef","ResidualRef","ResourceDemandRef","ResourceOfferRef","AdmissionDecisionRef","ReservationRef","BudgetRef","DeadlineRef","BackpressureProfileRef","CancellationProfileRef","FailureRef","FailureDomainRef","DegradedModeRef","ReconciliationRef","EvidenceClaimRef","EvidenceArtifactRef","OracleRef","CoverageRef","CounterexampleRef","DefeaterRef","ConformanceVerdictRef","AcceptanceRef"],
        "binding_sequence":["bind exact semantic role and total operation contracts","select only composition operators whose laws cover exact profiles","propagate residuals effects authority and refusals through the composition","aggregate resource demand topology budgets deadlines cancellation and failure domains","admit or refuse before effects when precharge is required","execute with bounded backpressure and total failure observations","reconcile partial or unknown completion","collect edition-bound evidence without promoting telemetry to truth","run required oracle classes including negative twins","issue scoped conformance verdict and separate production acceptance"],
        "required_proofs":["role and public operation completeness","algebraic law profile","composition preservation","resource dimensional consistency","finite budget and admission","backpressure/cancellation/overload behavior","total failure and unknown completion","oracle-to-requirement traceability","coverage/exclusion disclosure","counterexample retention","evidence provenance/integrity/freshness","independent conformance and acceptance where required"],
        "refusal_roles":["semantic_role_unbound","operation_outcome_incomplete","law_unproved","composition_type_mismatch","composition_loss_unreported","nontermination_risk","reorder_unsafe","resource_dimension_mismatch","offer_stale","admission_denied","budget_unfunded","deadline_infeasible","backpressure_unsupported","cancellation_unsupported","failure_untyped","unknown_completion_unreconciled","degraded_authority_missing","claim_unbound","oracle_missing","coverage_insufficient","counterexample_open","evidence_stale","defeater_unresolved","conformance_inconclusive","acceptance_missing"],
        "generation_prohibition":"Do not generate implementations, compositions, retries, optimizations, resource admissions or conformance verdicts from trait signatures, connector fit, provider claims, examples, telemetry, model output or AI-generated tests alone.",
    }
    summary={"program_id":"program.semantic-axis.phase5.behavior-resources-proof.v1","edition":1,"as_of":AS_OF,"status":"ACTIVE_PENDING_OWNER_RATIFICATION","completion_claim":False,"modules":4,"primary_sources":len(sources),"bounded_primary_evidence_claims":len(claims),"semantic_role_kinds":14,"composition_coordinates":18,"resource_coordinates":15,"failure_coordinates":15,"evidence_coordinates":15,"oracle_classes":11,"canonical_exact_gaps_closed":0,"remaining_gate":constitution["ratification_gate"]}
    return {"sources":sources,"constitution":constitution,"claims":claims,"projection":projection,"summary":summary}

def outputs()->dict[str,str]:
    b=build();files={"sources.jsonl":"".join(canonical(x)+"\n" for x in b["sources"]),"constitution.json":json.dumps(b["constitution"],ensure_ascii=False,sort_keys=True,indent=2)+"\n","evidence-claims.jsonl":"".join(canonical(x)+"\n" for x in b["claims"]),"compiler-projection.json":json.dumps(b["projection"],ensure_ascii=False,sort_keys=True,indent=2)+"\n","summary.json":json.dumps(b["summary"],ensure_ascii=False,sort_keys=True,indent=2)+"\n"};manifest={n:{"sha256":hashlib.sha256(t.encode()).hexdigest(),"bytes":len(t.encode())} for n,t in files.items()};files["manifest.json"]=json.dumps({"manifest_id":"manifest.semantic-axis.phase5.v1","as_of":AS_OF,"files":manifest},sort_keys=True,indent=2)+"\n";return files

def main()->int:
    p=argparse.ArgumentParser();p.add_argument("--check",action="store_true");a=p.parse_args();stale=[]
    for n,t in outputs().items():
        q=HERE/n
        if a.check:
            if not q.is_file() or q.read_text()!=t:stale.append(n)
        else:q.write_text(t)
    if stale:print("STALE "+", ".join(stale));return 1
    s=build()["summary"];print(f"{'CHECK' if a.check else 'BUILD'} PASS Phase 5 semantic constitution: {s['modules']} modules, {s['primary_sources']} sources, {s['bounded_primary_evidence_claims']} claims, zero canonical gaps closed");return 0

if __name__=="__main__":raise SystemExit(main())
