#!/usr/bin/env python3
"""Build analytical-workspace and interactive-selection semantic contracts."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent
AS_OF = "2026-08-26"


def render(rows: list[dict]) -> str:
    return "\n".join(json.dumps(r, sort_keys=True, separators=(",", ":"), ensure_ascii=False) for r in rows) + "\n"


def src(key: str, title: str, authority: str, url: str, supports: str, limit: str) -> dict:
    return {"source_id": f"source.aws.{key}", "title": title, "authority": authority, "url": url,
            "retrieved": AS_OF, "source_kind": "primary_or_official", "supports": supports,
            "does_not_prove": limit}


SOURCES = [
    src("openrefine.facets", "Facets", "OpenRefine", "https://openrefine.org/docs/manual/facets", "facets are views over variation; filters narrow rows; combined facets recompute counts; blank, error, numeric and temporal cases remain visible", "OpenRefine UI behavior is not a universal predicate language."),
    src("openrefine.running", "Running, history and operation reuse", "OpenRefine", "https://openrefine.org/docs/manual/running/", "projects, immutable input, current state, history cursor and reusable operations are distinct", "A local project lifecycle does not define collaboration or release authority."),
    src("openrefine.expressions", "Expressions", "OpenRefine", "https://openrefine.org/docs/manual/expressions/", "filter expressions require a named language, variables, functions, types and error behavior", "One expression language is not the canonical selection algebra."),
    src("openrefine.export", "Exporting", "OpenRefine", "https://openrefine.org/docs/manual/exporting", "project export, data export and operation export are different artifacts", "Export does not prove portability or source mutation authority."),
    src("openrefine.architecture", "Architecture before version 4", "OpenRefine", "https://openrefine.org/docs/technical-reference/architecture-before-4", "project metadata, column model, row data, history and processes are separate implementation objects", "Implementation structure does not establish the shared semantic boundary."),
    src("vegalite.selection", "Selection parameters", "Vega-Lite", "https://vega.github.io/vega-lite/docs/selection.html", "point and interval selection, field/encoding projection, event, clear and union/intersection/global resolution are explicit", "Visualization selection does not authorize transformation or export."),
    src("vegalite.parameter", "Parameters", "Vega-Lite", "https://vega.github.io/vega-lite/docs/parameter.html", "variables and selections are named reactive parameters with explicit binding and expression use", "Reactive parameter state is not durable analytical-work identity."),
    src("vega.events", "Event streams", "Vega", "https://vega.github.io/vega/docs/event-streams/", "input events, filters, source, consume, throttle, debounce and sequencing are distinguishable", "UI events do not themselves carry semantic authority."),
    src("vega.signals", "Signals", "Vega", "https://vega.github.io/vega/docs/signals/", "reactive state updates and propagation order are explicit", "Signal update order is not a universal collaboration model."),
    src("vega.filter", "Filter transform", "Vega", "https://vega.github.io/vega/docs/transforms/filter/", "a predicate derives a filtered stream from an input stream", "A derived view is not a mutation of its source."),
    src("vega.crossfilter", "Crossfilter transform", "Vega", "https://vega.github.io/vega/docs/transforms/crossfilter/", "multiple field queries can maintain an incremental filter mask", "A mask representation is not stable domain identity."),
    src("vega.resolvefilter", "ResolveFilter transform", "Vega", "https://vega.github.io/vega/docs/transforms/resolvefilter/", "a consumer may resolve a shared filter while explicitly ignoring selected dimensions", "Ignoring a dimension is not a safe implicit facet default."),
    src("vega.aggregate", "Aggregate transform", "Vega", "https://vega.github.io/vega/docs/transforms/aggregate/", "group counts distinguish valid, missing, distinct and empty groups and declare cross/drop behavior", "Aggregation defaults are not universal faceting semantics."),
    src("crossfilter", "Crossfilter", "Crossfilter project", "https://github.com/crossfilter/crossfilter", "coordinated multidimensional filtering uses indexed dimensions and incremental reductions", "A JavaScript implementation does not qualify this contract."),
    src("ogc.cql2", "Common Query Language CQL2 1.0", "Open Geospatial Consortium", "https://docs.ogc.org/is/21-065r2/21-065r2.html", "editioned text and JSON filter encodings have logical, comparison, spatial, temporal, array, function and conformance classes", "CQL2 does not define workspace or UI selection lifecycle."),
    src("ogc.cql2.schemas", "CQL2 1.0 schemas", "Open Geospatial Consortium", "https://schemas.opengis.net/cql2/1.0/", "machine-readable schemas can bind an exact filter-language edition", "Schema validity does not establish field typing or authorization."),
    src("sql.foundation", "ISO/IEC 9075 SQL overview", "ISO", "https://www.iso.org/standard/76583.html", "relational predicates and queries are editioned language concerns", "The ISO overview does not supply executable conformance evidence here."),
    src("postgres.comparison", "Comparison functions and operators", "PostgreSQL", "https://www.postgresql.org/docs/current/functions-comparison.html", "NULL-aware predicates and three-valued results require explicit treatment", "PostgreSQL behavior is not silently the universal policy."),
    src("jupyter.workspaces", "JupyterLab workspaces", "JupyterLab", "https://jupyterlab.readthedocs.io/en/stable/user/workspaces.html", "a UI workspace has an identity, layout/state document, import, export, clone, rename, reset and delete lifecycle", "A UI layout workspace is not the analytical-work aggregate."),
    src("jupyter.rest", "Jupyter Server REST API", "Jupyter Server", "https://jupyter-server.readthedocs.io/en/stable/developers/rest-api.html", "contents, kernels, sessions and terminals use separate identities and lifecycle APIs", "A server session is not a governed analysis project."),
    src("jupyter.kernels", "Jupyter kernels", "Project Jupyter", "https://docs.jupyter.org/en/stable/projects/kernels.html", "execution kernels are runtime processes with replaceable language implementations", "Kernel lifetime must not define analytical-work lifetime."),
    src("superset.filters", "Dashboard native filters", "Apache Superset", "https://superset.apache.org/user-docs/using-superset/creating-your-first-dashboard/", "dashboard filters declare target data source, field, default value and scope", "Dashboard filter configuration is not source mutation authority."),
    src("jsonpatch", "JSON Patch", "IETF", "https://www.rfc-editor.org/rfc/rfc6902", "ordered structural edits and test preconditions have explicit failure behavior", "A structural patch is not automatically a semantic workspace command."),
    src("prov", "PROV-O", "W3C", "https://www.w3.org/TR/prov-o/", "entities, activities, plans, revisions, derivations, generations and invalidations remain distinct", "Provenance alone does not define analytical-work invariants."),
]

CONTEXTS = [
    {"context_id": "context.analytical_workspace.definition", "name": "Analytical Workspace Definition", "sovereign_question": "Which immutable references and policies define one governed analytical work aggregate without absorbing its data, recipe, runtime or view state?", "inside": ["workspace family and edition", "purpose and owner refs", "admitted data-cut refs", "active recipe refs", "semantic resource refs", "view-state refs", "review refs", "canonical digest"], "outside": ["tenant membership", "source data", "recipe semantics", "kernel processes", "UI layout", "review issuance", "output publication"], "owner": "authority.analytical_workspace.definition", "status": "specified_candidate"},
    {"context_id": "context.analytical_workspace.lifecycle", "name": "Analytical Workspace Lifecycle", "sovereign_question": "Which commands may move one analytical workspace through draft, active, review, accepted, archived, superseded and withdrawn states while preserving referenced evidence?", "inside": ["workspace state", "commands", "transition validation", "revision", "optimistic version", "checkpoint refs", "archive and exit plan"], "outside": ["issuing review or acceptance", "repository I/O", "runtime process control", "recipe edit semantics", "data mutation"], "owner": "authority.analytical_workspace.lifecycle", "status": "specified_candidate"},
    {"context_id": "context.selection.predicate", "name": "Selection Predicate", "sovereign_question": "What exact typed, finite, editioned predicate over one schema and population can classify occurrences as included, excluded or unknown?", "inside": ["predicate AST", "language edition", "field binding", "operators", "null/error logic", "type checking", "normal form", "digest", "explanation"], "outside": ["UI gestures", "query execution", "permissions", "data mutation", "business acceptance"], "owner": "authority.selection.predicate", "status": "specified_candidate"},
    {"context_id": "context.selection.state", "name": "Interactive Selection State", "sovereign_question": "How do attributed point, interval, include, exclude, combine, clear and reset actions deterministically evolve reversible selection state?", "inside": ["selection identity", "scope", "named clauses", "point and interval values", "resolution algebra", "event-to-action mapping", "revision", "clear/reset", "serialization"], "outside": ["facet aggregation", "UI rendering", "workspace storage", "data mutation", "effect authority"], "owner": "authority.selection.state", "status": "specified_candidate"},
    {"context_id": "context.selection.faceting", "name": "Facet Evaluation", "sovereign_question": "Which evidence-scoped buckets and counts are derived for one population and selection state under exact missing, error, binning, self-filter and resource policies?", "inside": ["facet definition", "bucket identity", "binning", "missing/error groups", "self-filter policy", "count mode", "coverage", "staleness", "result digest"], "outside": ["predicate language ownership", "selection mutation", "physical query planning", "visual encoding", "source correction"], "owner": "authority.selection.faceting", "status": "specified_candidate"},
]

DECISIONS = {
    "definition": ["workspace_family_identity", "workspace_edition_identity", "purpose_ref", "owner_and_collaborator_refs", "tenant_workspace_ref", "admitted_data_cut_refs", "active_recipe_ref", "semantic_resource_refs", "selection_state_refs", "view_state_refs", "runtime_session_refs", "review_ref", "output_refs", "clock_and_validity", "retention_and_exit", "canonicalization", "definition_digest"],
    "lifecycle": ["workspace_identity", "initial_state", "command_identity", "actor_and_authority_ref", "expected_version", "transition_table", "activation_preconditions", "review_preconditions", "acceptance_evidence_ref", "archive_semantics", "supersession", "withdrawal", "checkpoint_policy", "inflight_runtime_disposition", "concurrent_command_precedence", "idempotency_scope", "event_identity", "history_retention", "exit_bundle", "lifecycle_digest"],
    "predicate": ["language_edition", "schema_edition", "population_ref", "field_resolution", "literal_types", "operator_set", "function_set", "logical_algebra", "null_unknown_error_logic", "comparison_and_collation", "case_and_accent", "numeric_semantics", "temporal_semantics", "spatial_semantics", "array_semantics", "parameter_binding", "normalization", "constant_folding", "complexity_budget", "canonical_digest", "explanation_scope"],
    "state": ["selection_identity", "population_and_schema_ref", "selection_scope", "clause_identity", "point_or_interval", "include_or_exclude", "open_closed_bounds", "multi_value_semantics", "global_union_intersection", "cross_view_resolution", "event_to_action_mapping", "initial_state", "empty_selection_semantics", "clear_semantics", "reset_semantics", "undo_and_redo", "concurrency_precedence", "serialization_edition", "stale_field_behavior", "revision_digest"],
    "facet": ["facet_identity", "population_and_schema_ref", "field_or_expression", "facet_kind", "bucket_identity", "binning_policy", "ordering", "limit_and_other_bucket", "missing_null_blank_groups", "error_group", "self_filter_policy", "other_selection_scope", "count_measure", "distinct_identity", "weight_semantics", "zero_count_retention", "coverage_and_truncation", "incremental_equivalence", "staleness_invalidation", "resource_budget", "result_digest"],
}
OWNER_CONTEXT = {"definition": CONTEXTS[0]["context_id"], "lifecycle": CONTEXTS[1]["context_id"], "predicate": CONTEXTS[2]["context_id"], "state": CONTEXTS[3]["context_id"], "facet": CONTEXTS[4]["context_id"]}
DECISION_ROWS = [{"decision_id": f"decision.aws.{owner}.{name}", "owner_context": OWNER_CONTEXT[owner], "question": f"What exact {name.replace('_', ' ')} applies?", "default": None, "default_law": "forbidden", "binding_phase": "intent_or_compile_time", "status": "declared"} for owner, names in DECISIONS.items() for name in names]


def op(owner: str, name: str, inputs: list[str], output: str) -> dict:
    return {"operation_ref": f"operation.aws.{owner}.{name}", "input_types": inputs, "output_type": f"Result<{output},AnalyticalWorkspaceSelectionRefusal>", "purity": "pure"}


OPS = {
    "definition": [op("definition", "validate_workspace_declaration", ["AnalyticalWorkspaceDeclaration", "WorkspaceDefinitionPolicy"], "ValidatedWorkspaceDeclaration"), op("definition", "resolve_workspace_reference_closure", ["ValidatedWorkspaceDeclaration", "WorkspaceArtifactCut"], "WorkspaceReferenceClosure"), op("definition", "classify_workspace_reference_roles", ["WorkspaceReferenceClosure", "ReferenceRolePolicy"], "ClassifiedWorkspaceReferences"), op("definition", "compile_workspace_definition", ["ValidatedWorkspaceDeclaration", "ClassifiedWorkspaceReferences"], "AnalyticalWorkspaceDefinition"), op("definition", "compare_workspace_definitions", ["AnalyticalWorkspaceDefinition", "AnalyticalWorkspaceDefinition"], "WorkspaceSemanticDiff"), op("definition", "compile_workspace_exit_bundle", ["AnalyticalWorkspaceDefinition", "WorkspaceLifecycleRevision", "ExitPolicy"], "WorkspaceExitBundle"), op("definition", "explain_workspace_definition", ["AnalyticalWorkspaceDefinition", "ExplanationScope", "ResourceBudget"], "WorkspaceDefinitionExplanation")],
    "lifecycle": [op("lifecycle", "validate_workspace_command", ["WorkspaceLifecycleRevision", "WorkspaceCommand", "WorkspaceLifecyclePolicy"], "ValidatedWorkspaceCommand"), op("lifecycle", "evaluate_workspace_transition", ["ValidatedWorkspaceCommand", "WorkspaceEvidenceCut"], "WorkspaceTransitionDecision"), op("lifecycle", "apply_workspace_transition", ["WorkspaceLifecycleRevision", "WorkspaceTransitionDecision"], "WorkspaceLifecycleTransition"), op("lifecycle", "reconcile_concurrent_workspace_commands", ["WorkspaceLifecycleRevision", "WorkspaceCommandSet", "ConcurrencyPolicy"], "WorkspaceCommandResolution"), op("lifecycle", "plan_workspace_supersession", ["WorkspaceLifecycleRevision", "AnalyticalWorkspaceDefinition", "SupersessionPolicy"], "WorkspaceSupersessionPlan"), op("lifecycle", "validate_workspace_checkpoint", ["WorkspaceCheckpoint", "AnalyticalWorkspaceDefinition", "CheckpointPolicy"], "ValidatedWorkspaceCheckpoint"), op("lifecycle", "explain_workspace_lifecycle", ["WorkspaceLifecycleRevision", "ExplanationScope", "ResourceBudget"], "WorkspaceLifecycleExplanation")],
    "predicate": [op("predicate", "parse_predicate", ["PredicateRepresentation", "PredicateLanguageEdition", "ParseBudget"], "PredicateSyntaxTree"), op("predicate", "bind_predicate_fields", ["PredicateSyntaxTree", "SchemaEdition", "FieldBindingPolicy"], "FieldBoundPredicate"), op("predicate", "typecheck_predicate", ["FieldBoundPredicate", "PredicateTypePolicy"], "TypedPredicate"), op("predicate", "normalize_predicate", ["TypedPredicate", "PredicateNormalizationPolicy"], "NormalizedPredicate"), op("predicate", "evaluate_predicate", ["NormalizedPredicate", "Occurrence", "PredicateEvaluationPolicy"], "PredicateTruthValue"), op("predicate", "compare_predicates", ["NormalizedPredicate", "NormalizedPredicate", "PredicateEquivalencePolicy"], "PredicateComparison"), op("predicate", "explain_predicate", ["NormalizedPredicate", "ExplanationScope", "ResourceBudget"], "PredicateExplanation")],
    "state": [op("state", "map_interaction_to_selection_action", ["InteractionOccurrence", "InteractionMappingPolicy"], "SelectionAction"), op("state", "validate_selection_action", ["SelectionRevision", "SelectionAction", "SelectionPolicy"], "ValidatedSelectionAction"), op("state", "reduce_selection_action", ["SelectionRevision", "ValidatedSelectionAction"], "SelectionTransition"), op("state", "compile_selection_predicate", ["SelectionRevision", "SelectionResolutionPolicy"], "SelectionPredicateDeclaration"), op("state", "clear_selection", ["SelectionRevision", "SelectionClearPolicy"], "SelectionTransition"), op("state", "reset_selection", ["SelectionRevision", "InitialSelectionState", "SelectionResetPolicy"], "SelectionTransition"), op("state", "compare_selection_revisions", ["SelectionRevision", "SelectionRevision"], "SelectionSemanticDiff"), op("state", "serialize_selection_state", ["SelectionRevision", "SelectionSerializationEdition"], "SerializedSelectionState"), op("state", "explain_selection_state", ["SelectionRevision", "ExplanationScope", "ResourceBudget"], "SelectionExplanation")],
    "facet": [op("facet", "validate_facet_definition", ["FacetDefinition", "SchemaEdition", "FacetPolicy"], "ValidatedFacetDefinition"), op("facet", "compile_facet_evaluation_plan", ["ValidatedFacetDefinition", "SelectionRevision", "FacetEvaluationPolicy"], "FacetEvaluationPlan"), op("facet", "evaluate_facet", ["FacetEvaluationPlan", "PopulationCut", "FacetEvaluationBudget"], "FacetResult"), op("facet", "merge_facet_partials", ["FacetPartialSet", "FacetMergePolicy"], "FacetResult"), op("facet", "evaluate_incremental_facet_delta", ["FacetResult", "PopulationDelta", "SelectionTransition", "IncrementalFacetPolicy"], "FacetResult"), op("facet", "classify_facet_staleness", ["FacetResult", "PopulationCut", "SelectionRevision", "StalenessPolicy"], "FacetStaleness"), op("facet", "compare_facet_results", ["FacetResult", "FacetResult", "FacetEquivalencePolicy"], "FacetComparison"), op("facet", "explain_facet_result", ["FacetResult", "ExplanationScope", "ResourceBudget"], "FacetExplanation")],
}

SHARED_LAWS = [
    "Tenant collaboration workspace, analytical workspace, UI-layout workspace, runtime session, data cut, recipe edition, selection revision and published output are distinct identities.",
    "Creating or opening a workspace grants no data access, review authority, execution authority or publication authority.",
    "A view selection is not a source mutation and becomes transformation or export scope only through an explicit command binding its exact revision.",
    "Predicate syntax validity, field binding, type validity, evaluability, selection application and business acceptance are distinct.",
    "Missing, null, blank, invalid, error, unknown, excluded and absent are never silently collapsed.",
    "A UI event is evidence input to a declared interaction mapping, not a semantic selection action by itself.",
    "Clear, reset, undo, delete and archive are different commands with different residual history.",
    "Facet definition, selection state, evaluation plan, result, count and visual encoding are distinct artifacts.",
    "Every predicate, selection and facet result binds exact language, schema, population, policy, time and resource cuts.",
    "Models or agents may propose attributed predicates or facets but cannot invent missing semantics, grant access, mutate data, approve work or accept results.",
]

TYPES = {
    "definition": ["AnalyticalWorkspaceId", "AnalyticalWorkspaceEdition", "AnalyticalWorkspaceDeclaration", "AnalyticalWorkspaceDefinition", "WorkspacePurposeRef", "WorkspaceReference", "WorkspaceReferenceRole", "WorkspaceReferenceClosure", "WorkspaceExitBundle", "WorkspaceSemanticDiff", "WorkspaceDefinitionRefusal"],
    "lifecycle": ["WorkspaceLifecycleState", "WorkspaceLifecycleRevision", "WorkspaceCommand", "WorkspaceEvent", "WorkspaceTransitionDecision", "WorkspaceLifecycleTransition", "WorkspaceCheckpoint", "WorkspaceSupersessionPlan", "WorkspaceLifecycleRefusal"],
    "predicate": ["PredicateLanguageEdition", "PredicateRepresentation", "PredicateSyntaxTree", "FieldBoundPredicate", "TypedPredicate", "NormalizedPredicate", "PredicateTruthValue", "PredicateComparison", "PredicateRefusal"],
    "state": ["SelectionId", "SelectionRevision", "SelectionScope", "SelectionClause", "SelectionAction", "PointSelection", "IntervalSelection", "SelectionResolution", "SelectionTransition", "SerializedSelectionState", "SelectionRefusal"],
    "facet": ["FacetId", "FacetDefinition", "FacetKind", "FacetBucket", "FacetEvaluationPlan", "FacetPartial", "FacetResult", "FacetCoverage", "FacetStaleness", "FacetComparison", "FacetRefusal"],
}


def lib(owner: str, ident: str, name: str, kind: str, responsibility: str, deps: list[str], laws: list[str], refusals: list[str], exclusions: list[str], oracles: list[str]) -> dict:
    return {"library_id": ident, "name": name, "library_kind": kind, "semantic_owner_context": OWNER_CONTEXT[owner], "status": "specified", "candidate_responsibility": responsibility, "effect_boundary": "pure_no_io", "public_types": TYPES[owner], "public_traits": ["".join(x.title() for x in ident.split(".")[1:]) + "Algebra"], "operation_refs": [x["operation_ref"] for x in OPS[owner]], "operations": OPS[owner], "decision_refs": [x["decision_id"] for x in DECISION_ROWS if f".{owner}." in x["decision_id"]], "configuration_contracts": [f"{owner.title()}Policy"], "laws": SHARED_LAWS + laws, "invariants": ["all material decisions are explicit and no-default", "all semantic operations are deterministic for exact inputs and perform no ambient I/O", "all identities, revisions, populations, policies and evidence cuts are digest-bound", "optional model or agent proposals never issue semantic or effect authority"], "error_contracts": refusals + ["UnsupportedEdition", "InvalidConfiguration", "ResourceBudgetExceeded"], "dependencies": deps, "evidence_refs": [x["source_id"] for x in SOURCES], "oracles": oracles + ["two independent implementations and cross-provider differential results"], "gaps": ["No implementation is qualified; exact-scope state, predicate, faceting and collision conformance remains required."], "must_not_own": exclusions, "qualification_required": False}


LIBRARIES = [
    lib("definition", "library.analytical_workspace.definition.compiler", "Analytical Workspace Definition Compiler", "semantic_pure", "compile one immutable analytical-work definition from explicit purpose, data-cut, recipe, semantic-resource, selection, view, runtime, review and output references without absorbing their ownership", [], ["References retain their external identity, edition, authority and lifecycle.", "A runtime or view-state reference may expire without changing the workspace definition unless a named command revises it."], ["WorkspaceIdentityMissing", "PurposeUnbound", "DataCutUnbound", "RecipeRefUnbound", "ReferenceRoleAmbiguous", "ReferenceClosureIncomplete", "WorkspaceDigestMismatch"], ["tenant membership", "source data", "recipe semantics", "kernel lifecycle", "UI layout", "review issuance", "output publication"], ["reference-role collision corpus", "canonical digest properties", "workspace export/import round trips"]),
    lib("lifecycle", "library.analytical_workspace.lifecycle.reducer", "Analytical Workspace Lifecycle Reducer", "state_pure", "validate and reduce versioned workspace commands across draft, active, review, accepted, archived, superseded and withdrawn states while retaining checkpoints and evidence references", ["library.analytical_workspace.definition.compiler"], ["Lifecycle transitions validate externally issued evidence but never issue review or acceptance authority.", "Archive retains governed identity and history; delete or physical purge is a separate authorized effect."], ["WorkspaceDefinitionUnbound", "TransitionInvalid", "ExpectedVersionMismatch", "AuthorityEvidenceMissing", "ReviewEvidenceMissing", "AcceptanceEvidenceMissing", "CheckpointInvalid", "ConcurrentCommandConflict", "InflightDispositionMissing", "ExitBundleIncomplete"], ["repository I/O", "review or acceptance issuance", "runtime process control", "recipe editing", "physical deletion"], ["total state-machine model", "concurrency and idempotency decision tables", "archive/supersession/withdrawal negative twins"]),
    lib("predicate", "library.selection.predicate.compiler", "Typed Selection Predicate Compiler", "semantic_pure", "parse, field-bind, typecheck, normalize, evaluate, compare and explain one finite predicate under an exact language/schema/null/numeric/temporal/spatial policy", [], ["A normalized predicate preserves declared truth behavior and information loss.", "Logical equivalence is claimed only under the exact schema, function, null and comparison policy."], ["PredicateSyntaxInvalid", "FieldUnbound", "FieldAmbiguous", "OperatorUnsupported", "FunctionUnsupported", "TypeMismatch", "NullLogicUnbound", "CollationUnbound", "EvaluationUnknown", "PredicateBudgetExceeded", "EquivalenceInconclusive"], ["UI interaction", "physical query planning", "data access", "data mutation", "business truth"], ["parser and malformed corpus", "three-valued truth tables", "normalization metamorphic properties", "CQL2 and declared-language fixtures"]),
    lib("state", "library.selection.state.reducer", "Interactive Selection-State Reducer", "state_pure", "map attributed interactions into typed selection actions and deterministically reduce point, interval, include, exclude, union, intersection, clear, reset and serialization behavior", ["library.selection.predicate.compiler"], ["Selection state is reversible view state and confers no mutation or access authority.", "Empty selection, select-all and select-none remain distinct unless the policy explicitly identifies them."], ["InteractionUnmapped", "SelectionScopeUnbound", "SelectionFieldStale", "SelectionValueInvalid", "IntervalInvalid", "ResolutionUnbound", "InitialStateMissing", "ClearPolicyMissing", "ResetStateMissing", "SelectionVersionConflict", "SerializationLoss"], ["UI rendering", "facet aggregation", "workspace persistence", "query execution", "mutation scope"], ["total selection state model", "clear/reset/undo negative twins", "union/intersection algebra properties", "serialization round trips"]),
    lib("facet", "library.selection.facet.evaluator", "Selection Facet Evaluator", "algorithm_pure", "derive evidence-scoped buckets and counts for one exact population and selection revision with explicit missing/error/binning/self-filter/coverage/resource policies", ["library.selection.predicate.compiler", "library.selection.state.reducer"], ["A facet count is meaningful only with its exact population, selection and self-filter policy.", "Incremental evaluation must equal full recomputation under the declared equivalence relation or return an explicit residual."], ["FacetFieldUnbound", "FacetKindUnsupported", "BinningPolicyMissing", "BucketIdentityAmbiguous", "SelfFilterPolicyMissing", "CountMeasureUnbound", "DistinctIdentityMissing", "FacetCoverageIncomplete", "FacetResultStale", "IncrementalEquivalenceFailed", "FacetBudgetExceeded"], ["predicate language", "selection mutation", "physical query execution", "visual encoding", "source correction"], ["self-filter and coordinated-view fixtures", "missing/error/zero-bucket corpus", "partition/merge properties", "incremental versus full differential tests"]),
]

METHODS = {"value": ["method.business.jtbd", "method.business.capability_map"], "semantic": ["method.domain.ddd", "method.domain.terminology", "method.information.conceptual_data"], "behavior": ["method.domain.eventstorming", "method.work.statecharts", "method.work.dmn"], "authority": ["method.trust.threat_model", "method.systems.stpa"], "consistency": ["method.domain.ddd", "method.formal.alloy", "method.formal.design_by_contract"], "variability": ["method.variability.foda", "method.variability.decision_model"], "software": ["method.architecture.coupling", "method.architecture.hexagonal", "method.variability.algebraic_api"], "operation": ["method.operations.resilience", "method.operations.capacity", "method.operations.sre"], "economics": ["method.operations.finops", "method.business.product_split_merge"], "empirical": ["method.evidence.systematic_review", "method.evidence.repository_mining", "method.evidence.red_team"], "analytical": ["method.analytics.or", "method.formal.property_testing", "method.formal.theorem_proving"], "system": ["method.systems.stpa", "method.trust.fmea_fta", "method.strategy.systems_thinking"]}
LENSES = [
    ("value", "An analytical project is an adoptable work aggregate; selection and faceting are reusable mechanics.", "Keep product work local and share exact mechanics."),
    ("semantic", "Tenant workspace, analytical work, runtime session, view state, predicate, selection and facet result have distinct identities.", "Use five contexts and five libraries."),
    ("behavior", "Workspace and selection evolve through total reducers; predicates and facets compile/evaluate purely.", "Separate state evolution from effects."),
    ("authority", "Membership, data access, review, acceptance, mutation and publication have separate issuers.", "References never mint external authority."),
    ("consistency", "Workspace, selection and facet revisions bind immutable external references and optimistic versions.", "Reject stale or conflicting commands."),
    ("variability", "Predicate languages, null logic, resolution, self-filter, bins and counts vary independently.", "Expose each as a no-default decision."),
    ("software", "Workspace definition/lifecycle, predicate compilation, state reduction and facet evaluation change independently.", "Make five replaceable libraries."),
    ("operation", "Large populations require finite budgets, truncation, incremental updates and staleness checks.", "Return coverage and explicit residuals."),
    ("economics", "State storage, predicate evaluation and facet recomputation consume separate resources.", "Bind cost and resource budgets."),
    ("empirical", "OpenRefine, Vega, CQL2, Jupyter and Crossfilter expose complementary seams and collisions.", "Generalize laws, not provider defaults."),
    ("analytical", "Counts and predicate truth depend on exact populations, missing-value semantics and equivalence relations.", "Require differential and algebraic oracles."),
    ("system", "Stale fields, hidden filters, ambiguous empty state and mutation-from-view are hazards.", "Fail closed and preserve evidence."),
]
LENS_ROWS = [{"lens_id": f"lens.aws.{name}", "lens": name, "question": "What does this lens require of analytical workspace and selection seams?", "finding": finding, "boundary_consequence": consequence, "method_refs": METHODS[name], "status": "applied"} for name, finding, consequence in LENSES]

VERDICTS = [
    {"verdict_id": "verdict.aws.workspace-collision", "subject_refs": ["library.analytical_workspace.definition.compiler", "library.analytical_workspace.lifecycle.reducer"], "disposition": "new_shared_analytical_work_aggregate", "rationale": "Collaboration workspace owns namespace and membership; Jupyter UI workspace owns layout; runtime session owns processes. None owns the governed analytical work definition and lifecycle.", "status": "candidate_boundary_adjudicated_not_ratified"},
    {"verdict_id": "verdict.aws.interaction-reducer-supersession", "subject_refs": ["library.selection.state.reducer", "library.cbv.interaction_reducer"], "disposition": "exact_contract_supersedes_coarse_placeholder", "rationale": "The prior CBV interaction reducer is candidate/unadjudicated and lacks exact selection identity, resolution, clear/reset, null, stale-field and serialization laws. Generic UI gesture mapping remains an adapter outside selection semantics.", "status": "candidate_boundary_adjudicated_not_ratified"},
    {"verdict_id": "verdict.aws.facet-split", "subject_refs": ["library.selection.predicate.compiler", "library.selection.state.reducer", "library.selection.facet.evaluator"], "disposition": "three_composable_libraries", "rationale": "Language/type semantics, reversible state transitions and population aggregation have different laws, dependencies, cost and replacement cadence.", "status": "candidate_boundary_adjudicated_not_ratified"},
]

NEGATIVES = [
    ("tenant_project", "Tenant workspace membership defines the analytical project.", "Reference collaboration identity without absorbing it."), ("ui_project", "A saved UI layout is the analytical work aggregate.", "Keep layout/view state as an external reference."), ("kernel_project", "A live kernel or server session is the analytical project.", "Bind replaceable runtime-session references."), ("open_grant", "Opening a workspace grants data access.", "Require external access authorization."), ("project_data", "A workspace owns or copies source truth by reference.", "Preserve exact external data-cut identity."), ("project_recipe", "The workspace owns recipe step semantics.", "Reference governed recipe editions."), ("accept_state", "Moving to accepted state issues acceptance authority.", "Validate externally issued acceptance evidence."), ("archive_delete", "Archiving a workspace physically deletes it.", "Treat purge as a separate authorized effect."), ("latest_ref", "Workspace references silently float to latest editions.", "Bind exact editions or explicit compatibility policy."), ("checkpoint_truth", "A checkpoint is a complete authoritative workspace state.", "Validate scope, version and omissions."),
    ("syntax_typed", "A parsed predicate is type-valid.", "Bind fields and typecheck."), ("typed_authorized", "A typed predicate is authorized to query the data.", "Keep access authorization external."), ("sql_universal", "All providers share one SQL null and comparison behavior.", "Bind an exact predicate policy and edition."), ("null_false", "NULL, unknown and error may be treated as false.", "Preserve declared truth states."), ("string_field", "A field name string uniquely resolves a field.", "Bind stable schema identity and path semantics."), ("normal_equal", "Matching normalized syntax proves logical equivalence.", "Evaluate equivalence under exact semantics."), ("function_safe", "A registered predicate function is deterministic and safe.", "Bind function contract, effects and budgets."), ("predicate_mutate", "A predicate authorizes mutation of matching rows.", "Require an explicit mutation command and exact selection revision."),
    ("event_action", "A click or brush event is already a semantic selection action.", "Map events through an editioned interaction policy."), ("empty_all", "An empty selection means select all.", "Declare empty-state semantics."), ("empty_none", "An empty selection means select none.", "Declare empty-state semantics."), ("clear_reset", "Clear and reset are interchangeable.", "Preserve initial-state and history differences."), ("point_interval", "A point selection is a zero-width interval.", "Keep kinds and bound semantics explicit."), ("union_default", "Selections across views combine by union.", "Require global/union/intersection resolution."), ("exclude_not", "Exclude is always equivalent to logical NOT.", "Bind scope, unknown logic and population."), ("stale_keep", "A selection remains valid after schema replacement.", "Rebind or refuse stale fields."), ("serialize_complete", "Serialized UI state is a complete durable selection.", "Bind serialization edition and loss report."),
    ("facet_filter", "A facet is merely a filter predicate.", "Separate definition, selection and evaluated counts."), ("count_global", "Facet counts always use the full population.", "Bind current selection and self-filter policy."), ("self_ignore", "A facet always ignores its own selection.", "Expose self-filter as a decision."), ("missing_zero", "Missing and zero-valued buckets are identical.", "Preserve missing, zero and empty groups."), ("blank_null", "Blank, null and invalid values form one bucket.", "Declare separate grouping policy."), ("top_complete", "Top-N facet output proves no other values exist.", "Return truncation and coverage."), ("distinct_row", "Distinct count always means row count.", "Bind counted identity and weighting."), ("incremental_equal", "Incremental facet updates equal full recomputation by construction.", "Test equivalence or emit residual."), ("facet_fresh", "A cached facet remains valid after data or selection change.", "Bind digests and classify staleness."), ("facet_visual", "Bucket ordering and visual encoding define semantic order.", "Keep presentation outside facet meaning."),
    ("agent_predicate", "A model may fill an omitted predicate or null policy from context.", "Emit an attributed proposal and refuse compilation."), ("agent_accept", "A model may approve a workspace or authorize selection-based effects.", "Require typed external authority."), ("one_impl", "One passing implementation proves portability.", "Require two independent qualified implementations."),
]
NEGATIVE_ROWS = [{"negative_id": f"negative.aws.{key}", "unsafe_inference": unsafe, "required_behavior": behavior, "status": "active"} for key, unsafe, behavior in NEGATIVES]

COMPILER = []
for library in LIBRARIES:
    stem = library["library_id"].removeprefix("library.")
    req, offer = f"requirement.{stem}.implementation", f"offer.{stem}.reference"
    COMPILER += [{"record_kind": "capability_requirement", "requirement_id": req, "subject_ref": library["library_id"], "required_operations": library["operation_refs"], "required_decisions": library["decision_refs"], "fallback_law": "refuse", "status": "declared"}, {"record_kind": "capability_offer", "offer_id": offer, "subject_ref": library["library_id"], "claimed_operations": library["operation_refs"], "qualified_implementation_count": 0, "portable": False, "selectable": False, "status": "specified_unimplemented"}, {"record_kind": "binding_rule", "binding_rule_id": f"binding.{stem}", "requirement_ref": req, "offer_ref": offer, "structural_match": True, "selection_law": "Structural match never promotes an unqualified or non-portable implementation.", "selectable": False, "status": "declared"}]

FILES = {"sources.jsonl": SOURCES, "bounded-contexts.jsonl": CONTEXTS, "decision-points.jsonl": DECISION_ROWS, "boundary-lens-adjudication.jsonl": LENS_ROWS, "boundary-verdicts.jsonl": VERDICTS, "library-contracts.jsonl": LIBRARIES, "compiler-contracts.jsonl": COMPILER, "negative-twins.jsonl": NEGATIVE_ROWS}


def main() -> None:
    ROOT.mkdir(parents=True, exist_ok=True)
    digests = {}
    for name, rows in FILES.items():
        payload = render(rows)
        (ROOT / name).write_text(payload, encoding="utf-8")
        digests[name] = {"records": len(rows), "sha256": hashlib.sha256(payload.encode()).hexdigest()}
    manifest = {"manifest_id": "analytical_workspace_selection_v0_1_0", "as_of": AS_OF, "edition": 1, "status": "specified_unimplemented_open_world", "files": digests, "completion_claim": False, "qualified_implementation_count": 0}
    (ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"BUILD PASS aws: {len(SOURCES)} sources, {len(CONTEXTS)} contexts, {len(DECISION_ROWS)} decisions, {len(LIBRARIES)} libraries, {sum(len(v) for v in OPS.values())} operations, {len(LENS_ROWS)} lenses, {len(NEGATIVE_ROWS)} negative twins")


if __name__ == "__main__":
    main()
