#!/usr/bin/env python3
"""Build exact business-glossary and ontology/knowledge-model contracts."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent
AS_OF = "2026-08-26"
EDITION = 1


def lines(rows: list[dict]) -> str:
    return "".join(json.dumps(row, sort_keys=True, separators=(",", ":"), ensure_ascii=False) + "\n" for row in rows)


def S(ident: str, title: str, publisher: str, url: str, scope: str, limit: str, kind: str = "official_specification") -> dict:
    return {"source_id": f"source.semantic-vocabulary.{ident}", "title": title, "publisher": publisher, "url": url, "source_kind": kind, "claim_scope": scope, "scope_limit": limit}


SOURCES = [
    S("iso.704.2022", "ISO 704:2022 Terminology Work — Principles and Methods", "ISO", "https://www.iso.org/standard/79077.html", "relationships among objects, concepts, definitions and designations", "The public catalog abstract supports boundary claims, not paywalled clause-level conformance."),
    S("iso.1087.2019", "ISO 1087:2019 Terminology Work and Terminology Science — Vocabulary", "ISO", "https://www.iso.org/standard/62330.html", "basic terminology-work vocabulary", "The public catalog abstract does not expose the complete normative vocabulary."),
    S("iso.30042.2019", "ISO 30042:2019 TermBase eXchange", "ISO", "https://www.iso.org/standard/62510.html", "concept-oriented terminology-resource metamodel and exchange dialects", "TBX interchange does not confer semantic approval or universal equivalence."),
    S("rfc.5646", "RFC 5646: Tags for Identifying Languages", "IETF", "https://www.rfc-editor.org/rfc/rfc5646", "language, script, region, variant and private-use tag syntax and registry semantics", "A language tag does not identify a concept, locale policy or translation quality."),
    S("unicode.tr35", "Unicode Locale Data Markup Language", "Unicode Consortium", "https://unicode.org/reports/tr35/", "locale identifiers, canonicalization, display names and language matching", "Localized display-name fallback is not terminological equivalence or business approval."),
    S("w3c.skos", "SKOS Simple Knowledge Organization System Reference", "W3C", "https://www.w3.org/TR/skos-reference/", "concept schemes, labels, notation, semantic relations and mapping properties", "SKOS concept-scheme relations are not OWL entailments or universal identity."),
    S("w3c.ontolex", "Lexicon Model for Ontologies: Community Report", "W3C Ontology-Lexica Community Group", "https://www.w3.org/2016/05/ontolex/", "lexical entries, forms, senses and references", "This is a Community Group report, not a W3C Recommendation.", "official_community_report"),
    S("w3c.rdf11.concepts", "RDF 1.1 Concepts and Abstract Syntax", "W3C", "https://www.w3.org/TR/rdf11-concepts/", "RDF terms, graphs, datasets, named graphs, literals and blank nodes", "RDF graph structure does not establish ontology consistency or real-world truth."),
    S("w3c.rdf11.semantics", "RDF 1.1 Semantics", "W3C", "https://www.w3.org/TR/rdf11-mt/", "RDF interpretations, entailment and semantic conditions", "RDF entailment must not be confused with OWL Direct Semantics or closed-world validation."),
    S("w3c.owl2.syntax", "OWL 2 Structural Specification and Functional-Style Syntax", "W3C", "https://www.w3.org/TR/owl2-syntax/", "ontology/version IRIs, documents, imports, annotations, entities, axioms and profiles", "Structural validity and profile membership do not prove consistency or truth."),
    S("w3c.owl2.direct", "OWL 2 Direct Semantics", "W3C", "https://www.w3.org/TR/owl2-direct-semantics/", "satisfaction, consistency and entailment under Direct Semantics", "A formal entailment is scoped to an exact ontology closure and interpretation regime."),
    S("w3c.owl2.profiles", "OWL 2 Profiles", "W3C", "https://www.w3.org/TR/owl2-profiles/", "EL, QL and RL syntactic profiles and computational properties", "Profile membership does not guarantee a particular provider's performance or completeness."),
    S("w3c.owl2.conformance", "OWL 2 Conformance", "W3C", "https://www.w3.org/TR/owl2-conformance/", "document, parser, reasoner and entailment-checker conformance", "Implementation conformance does not transfer semantic or domain authority."),
    S("w3c.shacl", "Shapes Constraint Language", "W3C", "https://www.w3.org/TR/shacl/", "immutable data/shape graph validation, focus nodes, results and conformance reports", "SHACL conformance is not ontology consistency, completeness or real-world truth."),
    S("w3c.rdf-canon", "RDF Dataset Canonicalization", "W3C", "https://www.w3.org/TR/rdf-canon/", "canonical labeling and serialization of RDF datasets", "Canonicalization proves representation-level isomorphism under a profile, not semantic equivalence."),
    S("w3c.sparql11", "SPARQL 1.1 Query Language", "W3C", "https://www.w3.org/TR/sparql11-query/", "dataset cuts, named graphs, graph patterns and query result forms", "A query result is cut- and entailment-regime-bound and does not prove source completeness."),
    S("w3c.prov-o", "PROV-O: The PROV Ontology", "W3C", "https://www.w3.org/TR/prov-o/", "entity, activity, agent, attribution, derivation and bundle provenance", "Provenance does not by itself prove assertion correctness or authority."),
]


def context(slug: str, name: str, question: str, outside: list[str]) -> dict:
    return {"context_id": f"context.{slug}", "name": name, "sovereign_question": question, "inside": ["exact identities", "editioned decisions", "typed operations", "laws", "refusals"], "outside": outside + ["provider qualification", "ambient persistence", "unauthorized effects"], "owner": f"authority.{slug}", "status": "specified_candidate"}


CONTEXTS = [
    context("business_glossary.term_identity", "Terminological concept and designation identity", "Within an exact business scope, which concept is denoted by which language- and script-bound designation without making text the concept?", ["ontology entity identity", "definition approval", "runtime schema fields"]),
    context("business_glossary.definition_scope", "Scoped definition editions", "Which immutable definition edition, scope, authority, characteristics and usage guidance govern one terminological concept?", ["formal logical axioms", "examples as exhaustive meaning"]),
    context("business_glossary.lexical_relations", "Lexical relations and resolution", "Under what language, scope, direction and strength are designations synonymous, homonymous, abbreviated, transliterated or translated?", ["concept identity by lexical similarity", "ontology equivalence"]),
    context("business_glossary.taxonomy_binding", "Taxonomy and concept-scheme binding", "Within which exact scheme edition are concepts placed under which typed hierarchical or associative relations?", ["OWL subsumption entailment", "part-whole by broader-label assumption"]),
    context("business_glossary.stewardship_lifecycle", "Glossary stewardship lifecycle", "How are proposals reviewed, authorized, published, challenged, deprecated and superseded with maker-checker evidence?", ["semantic approval by stewardship assignment", "automatic downstream mutation"]),
    context("ontology_model.identity_import_closure", "Ontology identity and import closure", "Which ontology and exact edition are identified, and which retrieved document results seal its complete import closure?", ["network retrieval hidden inside semantics", "axiom validity or consistency"]),
    context("ontology_model.axiom_profile", "Axiom and logic profile", "Which declarations, logical axioms and annotations form an edition, and does its axiom closure satisfy the selected structural profile?", ["reasoning results", "real-world observation"]),
    context("ontology_model.reasoning_entailment", "Reasoning, consistency and entailment", "Under which exact formal semantics, ontology closure and finite budget is consistency or entailment established, refuted or left inconclusive?", ["domain truth", "closed-world validation", "decision authority"]),
    context("ontology_model.shape_validation", "Graph-shape validation", "For exact immutable data and shape graph cuts, targets and entailment options, what SHACL validation report results?", ["ontology consistency", "source correctness", "data mutation"]),
    context("ontology_model.ontology_mapping", "Ontology mapping governance", "Between exact source and target ontology editions, what typed mapping assertion, direction, evidence and approval status exist?", ["source ontology editing", "same-label equivalence"]),
    context("ontology_model.knowledge_graph_release", "Knowledge-graph release", "Which source-attributed assertion partitions form an immutable canonicalized graph release and query cut without becoming source truth?", ["ontology axiom ownership", "source-fact authority", "query-engine operation"]),
]


DECISIONS: dict[str, list[str]] = {
    "business_glossary.term_identity": ["business_scope", "concept_identity_authority", "language_script", "preferred_designation", "identity_lifecycle"],
    "business_glossary.definition_scope": ["definition_authority", "scope_grain", "characteristic_selection", "normative_posture", "conflict_precedence"],
    "business_glossary.lexical_relations": ["relation_kind", "directionality", "language_pair", "equivalence_strength", "ambiguity_and_loss"],
    "business_glossary.taxonomy_binding": ["scheme_identity", "relation_vocabulary", "polyhierarchy", "cycle_posture", "placement_authority"],
    "business_glossary.stewardship_lifecycle": ["steward_authority", "maker_checker", "review_evidence", "challenge_appeal", "deprecation_successor"],
    "ontology_model.identity_import_closure": ["ontology_iri", "version_iri", "document_resolution", "import_version", "cycle_and_conflict"],
    "ontology_model.axiom_profile": ["logic_profile", "entity_declaration", "annotation_posture", "unsupported_axiom", "axiom_provenance"],
    "ontology_model.reasoning_entailment": ["formal_semantics", "entailment_regime", "open_closed_world", "unique_name_posture", "resource_bound"],
    "ontology_model.shape_validation": ["shacl_edition", "target_selection", "entailment_option", "severity_posture", "recursion_and_extension"],
    "ontology_model.ontology_mapping": ["mapping_relation", "directionality", "source_target_scope", "evidence_threshold", "approval_and_retraction"],
    "ontology_model.knowledge_graph_release": ["dataset_identity", "assertion_identity", "partition_policy", "canonicalization_digest", "release_and_query_cut"],
}


DECISION_ROWS = [{"decision_id": f"decision.{ctx}.{decision}", "owner_context": f"context.{ctx}", "question": f"What exact {decision.replace('_', ' ')} applies?", "default": None, "default_law": "forbidden", "status": "declared"} for ctx, values in DECISIONS.items() for decision in values]


def O(ctx: str, name: str, inputs: list[str], output: str) -> dict:
    return {"operation_ref": f"operation.{ctx}.{name}", "input_types": inputs, "output_type": f"Result<{output},{ctx.split('.')[-1].title().replace('_', '')}Refusal>", "purity": "pure"}


SPECS = [
    {"id":"library.business_glossary.term_identity","ctx":"business_glossary.term_identity","name":"Terminological Concept and Designation Identity","kind":"effect_port","types":["TerminologicalConceptId","BusinessScopeRef","DesignationId","Designation","LexicalForm","LanguageTag","ScriptTag","DesignationStatus","PreferenceStatus","ConceptRegistrationIntent","DesignationAdditionIntent","IdentityReceipt","DesignationResolution","TermIdentityRefusal"],"ops":[O("business_glossary.term_identity","validate_designation",["Designation","LanguageTag","ScriptTag","DesignationPolicy"],"ValidatedDesignation"),O("business_glossary.term_identity","plan_concept_registration",["ConceptProposal","BusinessScopeRef","ConceptIdentityAuthorityRef"],"ConceptRegistrationIntent"),O("business_glossary.term_identity","plan_designation_addition",["TerminologicalConceptId","ValidatedDesignation","PreferencePolicy"],"DesignationAdditionIntent"),O("business_glossary.term_identity","resolve_designation",["LexicalForm","LanguageTag","BusinessScopeRef","GlossaryEdition"],"DesignationResolution")],"laws":["Object, terminological concept, designation, lexical form, term entry and definition are distinct.","The same character sequence does not prove the same concept; one designation may denote different concepts in different scopes.","Concept identity survives preferred-label, language, spelling and display changes unless an authorized identity event says otherwise.","Language tag, script tag, locale and business scope are separate bindings."],"errors":["BusinessScopeMissing","ConceptAuthorityMissing","LanguageTagInvalid","DesignationCollision","PreferredDesignationConflict","IdentityCompletionUnknown"],"deps":[],"evidence":["source.semantic-vocabulary.iso.704.2022","source.semantic-vocabulary.iso.30042.2019","source.semantic-vocabulary.rfc.5646","source.semantic-vocabulary.w3c.ontolex"]},
    {"id":"library.business_glossary.definition_scope","ctx":"business_glossary.definition_scope","name":"Scoped Definition Edition","kind":"effect_port","types":["DefinitionId","DefinitionEdition","TerminologicalConceptId","BusinessScopeRef","CharacteristicSet","DefiningStatement","UsageGuidance","Example","Counterexample","NormativePosture","DefinitionPublicationIntent","DefinitionReceipt","DefinitionDiff","DefinitionRefusal"],"ops":[O("business_glossary.definition_scope","validate_definition",["DefinitionDraft","CharacteristicSet","DefinitionPolicy"],"DefinitionValidation"),O("business_glossary.definition_scope","compare_definitions",["DefinitionEdition","DefinitionEdition","ComparisonPolicy"],"DefinitionDiff"),O("business_glossary.definition_scope","plan_publication",["DefinitionDraft","DefinitionAuthorityRef","PublicationPolicy"],"DefinitionPublicationIntent"),O("business_glossary.definition_scope","plan_supersession",["DefinitionEdition","DefinitionDraft","SupersessionPolicy"],"DefinitionSupersessionIntent")],"laws":["A definition defines a concept in a scope; it is not a description of a word, label or database field.","Definition edition, usage guidance, example, counterexample and formal axiom are distinct artifacts.","Examples and observed instances never establish an exhaustive definition by enumeration.","Publication authority, domain acceptance and logical consistency are separate verdicts."],"errors":["ConceptUnbound","DefinitionAuthorityMissing","ScopeMissing","CharacteristicConflict","CircularDefinitionUnaccepted","PublicationCompletionUnknown"],"deps":["library.business_glossary.term_identity"],"evidence":["source.semantic-vocabulary.iso.704.2022","source.semantic-vocabulary.iso.1087.2019","source.semantic-vocabulary.iso.30042.2019"]},
    {"id":"library.business_glossary.lexical_relations","ctx":"business_glossary.lexical_relations","name":"Lexical Relations and Resolution","kind":"semantic_pure","types":["DesignationRef","LexicalRelation","SynonymAssertion","HomonymGroup","AbbreviationAssertion","TransliterationAssertion","TranslationAssertion","LanguagePair","RelationDirection","RelationStrength","AmbiguitySet","TranslationResidual","LexicalResolution","LexicalRelationRefusal"],"ops":[O("business_glossary.lexical_relations","evaluate_synonymy",["DesignationRef","DesignationRef","LexicalRelationPolicy"],"SynonymAssertion"),O("business_glossary.lexical_relations","resolve_homonym",["LexicalForm","LanguageTag","BusinessContext","GlossaryEdition"],"LexicalResolution"),O("business_glossary.lexical_relations","expand_abbreviation",["DesignationRef","BusinessContext","GlossaryEdition"],"LexicalResolution"),O("business_glossary.lexical_relations","translate_designation",["DesignationRef","LanguagePair","TranslationPolicy"],"TranslationAssertion")],"laws":["Synonymy, identity, abbreviation, homonymy, translation, transliteration and lexical similarity are different relations.","Synonymy is concept-, language-, scope- and edition-bound and does not merge designation identity.","Translation direction and loss are explicit; a target designation may narrow, broaden or fail to preserve the source concept.","Ambiguous lexical resolution returns candidates and residuals rather than selecting by frequency or model confidence."],"errors":["DesignationUnresolved","RelationScopeMissing","HomonymAmbiguous","AbbreviationContextMissing","LanguagePairUnsupported","TranslationLossUnaccepted"],"deps":["library.business_glossary.term_identity"],"evidence":["source.semantic-vocabulary.w3c.ontolex","source.semantic-vocabulary.rfc.5646","source.semantic-vocabulary.unicode.tr35","source.semantic-vocabulary.iso.30042.2019"]},
    {"id":"library.business_glossary.taxonomy_binding","ctx":"business_glossary.taxonomy_binding","name":"Taxonomy and Concept Scheme Binding","kind":"effect_port","types":["ConceptSchemeId","ConceptSchemeEdition","TerminologicalConceptId","SchemeMembership","TaxonomyRelation","BroaderRelation","NarrowerRelation","RelatedRelation","Notation","PlacementProposal","SchemeValidation","SchemePublicationIntent","SchemeReceipt","TaxonomyRefusal"],"ops":[O("business_glossary.taxonomy_binding","validate_scheme",["ConceptSchemeEdition","TaxonomyPolicy"],"SchemeValidation"),O("business_glossary.taxonomy_binding","evaluate_placement",["PlacementProposal","ConceptSchemeEdition","PlacementPolicy"],"PlacementEvaluation"),O("business_glossary.taxonomy_binding","compare_editions",["ConceptSchemeEdition","ConceptSchemeEdition"],"ConceptSchemeDiff"),O("business_glossary.taxonomy_binding","plan_publication",["ConceptSchemeEdition","PlacementAuthorityRef","PublicationPolicy"],"SchemePublicationIntent")],"laws":["Concept-scheme placement is not OWL class subsumption, set inclusion, instance typing or real-world containment.","Broader-generic, broader-partitive, broader-instantial and untyped broader relations cannot be silently collapsed.","Polyhierarchy and cycles require declared relation-specific policies; visual tree shape is not semantic proof.","Notation is a scheme-scoped representation and not concept identity or a universally stable code."],"errors":["SchemeIdentityMissing","RelationKindAmbiguous","PlacementAuthorityMissing","CycleForbidden","PolyhierarchyForbidden","PublicationCompletionUnknown"],"deps":["library.business_glossary.term_identity"],"evidence":["source.semantic-vocabulary.w3c.skos","source.semantic-vocabulary.iso.704.2022"]},
    {"id":"library.business_glossary.stewardship_lifecycle","ctx":"business_glossary.stewardship_lifecycle","name":"Glossary Stewardship Lifecycle","kind":"effect_port","types":["GlossaryChangeCaseId","GlossaryChangeProposal","TermStewardRef","SemanticApprovalAuthorityRef","ReviewAssignmentIntent","ReviewEvidenceSet","ReviewDecision","Challenge","Appeal","DeprecationNotice","SuccessorRelation","PublicationIntent","PublicationReceipt","GlossaryLifecycleRefusal"],"ops":[O("business_glossary.stewardship_lifecycle","plan_review_assignment",["GlossaryChangeProposal","TermStewardRef","AssignmentPolicy"],"ReviewAssignmentIntent"),O("business_glossary.stewardship_lifecycle","evaluate_review",["GlossaryChangeProposal","ReviewEvidenceSet","MakerCheckerPolicy"],"ReviewEligibility"),O("business_glossary.stewardship_lifecycle","plan_publication",["ReviewEligibility","SemanticApprovalAuthorityRef"],"PublicationIntent"),O("business_glossary.stewardship_lifecycle","plan_deprecation",["GlossaryEditionRef","SuccessorRelationSet","DeprecationPolicy"],"DeprecationNotice")],"laws":["Stewardship assignment, review work, semantic approval, publication and downstream adoption are distinct occurrences.","A steward is not approval authority unless an exact valid delegation grants that decision right.","Maker-checker, challenge, appeal and dissent evidence survive publication and deprecation.","Deprecation preserves identity, prior usage, notices and possibly plural or absent successors."],"errors":["StewardUnassigned","ApprovalAuthorityMissing","MakerCheckerViolated","ReviewEvidenceInsufficient","AppealUnresolved","SuccessorAmbiguous"],"deps":["library.business_glossary.definition_scope","library.business_glossary.lexical_relations","library.business_glossary.taxonomy_binding"],"evidence":["source.semantic-vocabulary.iso.704.2022","source.semantic-vocabulary.iso.30042.2019","source.semantic-vocabulary.w3c.skos"]},
    {"id":"library.ontology_model.identity_import_closure","ctx":"ontology_model.identity_import_closure","name":"Ontology Identity and Import Closure","kind":"effect_port","types":["OntologyIri","VersionIri","OntologyEdition","OntologyDocumentRef","ImportDeclaration","ImportResolutionPlan","ImportRetrievalResult","ImportGraph","ImportConflict","ResolvedImportClosure","ClosureDigest","OntologyRegistrationIntent","OntologyReceipt","ImportClosureRefusal"],"ops":[O("ontology_model.identity_import_closure","validate_identity",["OntologyDocument","OntologyIdentityPolicy"],"OntologyEdition"),O("ontology_model.identity_import_closure","plan_import_resolution",["OntologyEdition","ImportCatalogCut","ResolutionPolicy"],"ImportResolutionPlan"),O("ontology_model.identity_import_closure","seal_import_closure",["OntologyEdition","ImportRetrievalResultSet","ImportPolicy"],"ResolvedImportClosure"),O("ontology_model.identity_import_closure","plan_registration",["ResolvedImportClosure","OntologyAuthorityRef"],"OntologyRegistrationIntent")],"laws":["Ontology IRI, version IRI, ontology edition, document location, serialization and registry occurrence are distinct.","Import resolution plans network or catalog retrieval explicitly; missing or redirected imports never silently disappear.","Every reasoning or validation request binds one sealed import closure rather than ambient latest documents.","Import closure, axiom closure, structural validity, consistency and compatibility are distinct results."],"errors":["OntologyIriInvalid","VersionIriAmbiguous","ImportUnresolved","ImportEditionConflict","ImportCycleForbidden","RegistrationCompletionUnknown"],"deps":[],"evidence":["source.semantic-vocabulary.w3c.owl2.syntax","source.semantic-vocabulary.w3c.rdf11.concepts"]},
    {"id":"library.ontology_model.axiom_profile","ctx":"ontology_model.axiom_profile","name":"Ontology Axiom and Logic Profile","kind":"semantic_pure","types":["OntologyEntityDeclaration","EntityKind","LogicalAxiom","AnnotationAssertion","AxiomId","AxiomProvenance","AxiomClosure","LogicProfile","ProfileFeature","ProfileValidation","UnsupportedConstruct","OntologyRevision","AxiomDiff","AxiomProfileRefusal"],"ops":[O("ontology_model.axiom_profile","declare_entity",["EntityIri","EntityKind","DeclarationPolicy"],"OntologyEntityDeclaration"),O("ontology_model.axiom_profile","validate_axiom",["LogicalAxiom","LogicProfile","AxiomPolicy"],"AxiomValidation"),O("ontology_model.axiom_profile","validate_profile",["AxiomClosure","LogicProfile","ResourceBudget"],"ProfileValidation"),O("ontology_model.axiom_profile","derive_revision",["OntologyEdition","AxiomChangeSet","RevisionPolicy"],"OntologyRevision")],"laws":["Entity declaration, logical axiom, annotation assertion, lexical label and source observation are distinct.","Annotation values do not affect OWL logical semantics unless a separately selected regime says otherwise.","Profile membership is a structural result, not consistency, completeness, tractability on a given input or domain truth.","Retraction or correction produces a new ontology edition and preserves prior axiom provenance."],"errors":["EntityKindConflict","AxiomUnsupported","ProfileViolation","AxiomProvenanceMissing","ResourceBudgetExceeded","RevisionInvalid"],"deps":["library.ontology_model.identity_import_closure"],"evidence":["source.semantic-vocabulary.w3c.owl2.syntax","source.semantic-vocabulary.w3c.owl2.profiles","source.semantic-vocabulary.w3c.owl2.conformance"]},
    {"id":"library.ontology_model.reasoning_entailment","ctx":"ontology_model.reasoning_entailment","name":"Ontology Reasoning and Entailment","kind":"algorithm_pure","types":["FormalSemantics","EntailmentRegime","OntologyInterpretationProfile","ConsistencyRequest","ConsistencyResult","EntailmentRequest","EntailmentResult","EntailmentStatus","InferenceTrace","JustificationSet","CounterModelRef","ReasoningBudget","ReasoningCompleteness","ReasoningRefusal"],"ops":[O("ontology_model.reasoning_entailment","check_consistency",["ResolvedImportClosure","AxiomClosure","ReasoningProfile","ReasoningBudget"],"ConsistencyResult"),O("ontology_model.reasoning_entailment","evaluate_entailment",["AxiomClosure","EntailmentRequest","ReasoningProfile","ReasoningBudget"],"EntailmentResult"),O("ontology_model.reasoning_entailment","explain_entailment",["EntailmentResult","ExplanationPolicy","ReasoningBudget"],"InferenceTrace"),O("ontology_model.reasoning_entailment","compare_regimes",["EntailmentRequest","EntailmentRegimeSet","ReasoningBudget"],"RegimeComparison")],"laws":["Asserted, entailed, inferred, assumed, observed and proposed statements retain different provenance and status.","Consistency and entailment are relative to exact axioms, import closure, formal semantics, datatype map and regime.","Open-world unknown, false, inconsistent, unsupported, timed out and resource-exhausted are distinct outcomes.","Reasoner identity cannot change the selected formal semantics, and a model or agent explanation cannot manufacture entailment."],"errors":["FormalSemanticsUnbound","RegimeUnsupported","OntologyInconsistent","DatatypeMapUnsupported","ReasoningIncomplete","ResourceBudgetExceeded"],"deps":["library.ontology_model.axiom_profile"],"evidence":["source.semantic-vocabulary.w3c.owl2.direct","source.semantic-vocabulary.w3c.owl2.conformance","source.semantic-vocabulary.w3c.rdf11.semantics"]},
    {"id":"library.ontology_model.shape_validation","ctx":"ontology_model.shape_validation","name":"Graph Shape Validation","kind":"algorithm_pure","types":["DataGraphCut","ShapesGraphCut","ShapeId","TargetSelection","FocusNode","EntailmentOption","ConstraintComponent","ResultSeverity","ValidationResult","ValidationReport","ConformanceStatus","ValidationBudget","ValidationCompleteness","ShapeValidationRefusal"],"ops":[O("ontology_model.shape_validation","validate_shapes_graph",["ShapesGraphCut","ShapeProfile","ValidationBudget"],"ShapesGraphValidation"),O("ontology_model.shape_validation","select_focus_nodes",["DataGraphCut","ShapesGraphCut","TargetPolicy"],"FocusNodeSet"),O("ontology_model.shape_validation","validate_data_graph",["DataGraphCut","ShapesGraphCut","FocusNodeSet","ValidationProfile","ValidationBudget"],"ValidationReport"),O("ontology_model.shape_validation","explain_result",["ValidationResult","DataGraphCut","ShapesGraphCut"],"ValidationExplanation")],"laws":["SHACL validation consumes immutable data and shape graph cuts and never repairs or mutates them.","Shape conformance, shapes-graph well-formedness, ontology consistency, data completeness and real-world truth are distinct.","Each result binds focus node, severity, source shape and constraint component under one exact validation profile.","Warning, information, violation, failure, incomplete and resource-exhausted follow declared policy and cannot silently collapse."],"errors":["ShapesGraphInvalid","TargetScopeUnknown","EntailmentOptionUnsupported","RecursionUnsupported","ValidationIncomplete","ResourceBudgetExceeded"],"deps":["library.ontology_model.axiom_profile"],"evidence":["source.semantic-vocabulary.w3c.shacl","source.semantic-vocabulary.w3c.rdf11.concepts"]},
    {"id":"library.ontology_model.ontology_mapping","ctx":"ontology_model.ontology_mapping","name":"Ontology Mapping Governance","kind":"effect_port","types":["OntologyMappingId","OntologyMappingEdition","SourceOntologyEditionRef","TargetOntologyEditionRef","MappingRelation","MappingDirection","MappingScope","MappingAssertion","MappingEvidenceSet","MappingValidation","MappingApprovalIntent","MappingApprovalReceipt","MappingRetractionIntent","OntologyMappingRefusal"],"ops":[O("ontology_model.ontology_mapping","validate_mapping",["MappingAssertion","SourceTargetClosurePair","MappingPolicy"],"MappingValidation"),O("ontology_model.ontology_mapping","evaluate_mapping_evidence",["MappingAssertion","MappingEvidenceSet","EvidencePolicy"],"MappingEligibility"),O("ontology_model.ontology_mapping","plan_approval",["MappingEligibility","MappingAuthorityRef"],"MappingApprovalIntent"),O("ontology_model.ontology_mapping","plan_retraction",["OntologyMappingEdition","RetractionEvidenceSet","RetractionPolicy"],"MappingRetractionIntent")],"laws":["Same label, close match, exact match, class equivalence, property equivalence and transformation are distinct assertions.","Every mapping binds exact source and target ontology editions, direction, scope, relation and evidence.","Mapping approval cannot modify either source ontology or manufacture reverse, transitive or global equivalence.","Retraction preserves prior usage, provenance, dependent mappings and blast-radius evidence."],"errors":["SourceOntologyUnbound","TargetOntologyUnbound","MappingRelationAmbiguous","EvidenceInsufficient","MappingAuthorityMissing","RetractionBlastRadiusUnknown"],"deps":["library.ontology_model.identity_import_closure","library.ontology_model.axiom_profile"],"evidence":["source.semantic-vocabulary.w3c.skos","source.semantic-vocabulary.w3c.owl2.syntax","source.semantic-vocabulary.w3c.prov-o"]},
    {"id":"library.ontology_model.knowledge_graph_release","ctx":"ontology_model.knowledge_graph_release","name":"Knowledge Graph Release","kind":"effect_port","types":["KnowledgeDatasetId","GraphReleaseId","GraphReleaseEdition","NamedGraphPartition","GraphAssertionId","SourceAssertionRef","AssertionProvenance","DatasetCut","CanonicalizationProfile","CanonicalDataset","DatasetDigest","GraphReleaseIntent","GraphReleaseReceipt","GraphQueryCut","GraphReleaseRefusal"],"ops":[O("ontology_model.knowledge_graph_release","validate_assertion_envelope",["GraphAssertionEnvelope","AssertionPolicy"],"ValidatedGraphAssertion"),O("ontology_model.knowledge_graph_release","assemble_release",["ValidatedGraphAssertionSet","PartitionPolicy","DatasetCut"],"GraphReleaseEdition"),O("ontology_model.knowledge_graph_release","canonicalize_release",["GraphReleaseEdition","CanonicalizationProfile","ResourceBudget"],"CanonicalDataset"),O("ontology_model.knowledge_graph_release","plan_publication",["CanonicalDataset","GraphReleaseAuthorityRef","PublicationPolicy"],"GraphReleaseIntent")],"laws":["A knowledge graph release stores source-attributed assertions; it does not own source facts, ontology axioms or real-world truth.","Assertion identity, RDF term identity, graph name, named-graph partition, dataset identity and release identity are distinct.","Canonicalization and digest establish representation-level identity under an exact profile, not semantic equivalence or truth.","A query result binds an immutable graph release, dataset selection, entailment regime and query edition; empty result is not source absence."],"errors":["AssertionProvenanceMissing","DatasetCutIncomplete","PartitionLeak","CanonicalizationTooComplex","PublicationAuthorityMissing","PublicationCompletionUnknown"],"deps":["library.ontology_model.identity_import_closure","library.ontology_model.ontology_mapping"],"evidence":["source.semantic-vocabulary.w3c.rdf11.concepts","source.semantic-vocabulary.w3c.rdf-canon","source.semantic-vocabulary.w3c.sparql11","source.semantic-vocabulary.w3c.prov-o"]},
]


def materialize(spec: dict) -> dict:
    ctx = spec["ctx"]
    return {"library_id": spec["id"], "name": spec["name"], "library_kind": spec["kind"], "semantic_owner_context": f"context.{ctx}", "status": "specified", "candidate_responsibility": spec["name"].lower(), "effect_boundary": "pure_effect_intents" if spec["kind"] == "effect_port" else "pure_no_io", "public_types": spec["types"], "public_traits": [spec["name"].replace(" ", "") + "Algebra"], "operation_refs": [op["operation_ref"] for op in spec["ops"]], "operations": spec["ops"], "decision_refs": [f"decision.{ctx}.{decision}" for decision in DECISIONS[ctx]], "configuration_contracts": [spec["name"].replace(" ", "") + "Policy"], "laws": spec["laws"], "invariants": ["published editions and effect receipts are immutable", "all identities, semantics, authority, evidence, graph cuts and results are exact-scope, edition and time bound", "unknown, absent, false, refused, inconsistent, indeterminate, incomplete and completion-unknown remain distinct"], "error_contracts": spec["errors"] + ["UnsupportedEdition", "InvalidConfiguration", "ResourceBudgetExceeded"], "dependencies": spec["deps"], "evidence_refs": spec["evidence"], "oracles": ["canonical positive fixtures", "negative twins", "property and metamorphic laws", "state-machine model tests", "malformed and boundary corpus", "edition migration corpus", "two independent differential implementations"], "gaps": ["No implementation is qualified; two independent implementations and executed conformance remain required."], "must_not_own": ["source or real-world truth", "neighboring schema or metric semantics", "provider qualification", "legal interpretation", "unauthorized external effects"], "qualification_required": False}


LIBRARIES = [materialize(spec) for spec in SPECS]


NEGATIVES = [
    ("label_concept", "The same label proves the same concept.", "Resolve concept and designation under exact business scope, language and edition."),
    ("definition_word", "A definition defines a word or database field.", "Bind the definition to one terminological concept and business scope."),
    ("examples_complete", "Observed examples completely define the concept.", "Keep examples, counterexamples, characteristics and defining statement distinct."),
    ("translation_equivalence", "Translation automatically preserves concept identity.", "Publish direction, scope, strength and residual information loss."),
    ("taxonomy_subsumption", "A taxonomy broader edge proves OWL subsumption.", "Keep concept-scheme placement separate from formal axioms and entailment."),
    ("steward_approver", "The assigned steward automatically has semantic approval authority.", "Require an exact current delegation and maker-checker evidence."),
    ("iri_location", "Ontology IRI or version IRI is necessarily its retrievable document location.", "Use an explicit resolution plan and sealed import closure."),
    ("missing_import", "An unavailable import may be ignored.", "Refuse or retain an explicit incomplete closure according to declared policy."),
    ("profile_consistent", "OWL profile membership proves ontology consistency.", "Run consistency under the selected formal semantics and exact axiom closure."),
    ("entailed_asserted", "An entailed statement was explicitly asserted or observed.", "Retain derivation status and inference trace separately."),
    ("unknown_false", "Open-world unknown means false.", "Return the exact formal outcome without closed-world substitution."),
    ("shape_truth", "SHACL conformance proves ontology consistency, data completeness or real-world truth.", "Report only cut-bound graph-shape conformance."),
    ("canonical_semantic", "Equal canonical RDF serialization proves semantic equivalence or truth.", "Claim only profile-bound representation isomorphism and digest identity."),
    ("graph_owns_source", "A knowledge graph assertion becomes source truth when released.", "Preserve source assertion reference, provenance and authority."),
    ("mapping_equivalence", "Same label or close match proves OWL equivalence.", "Require an exact typed mapping relation and evidence."),
    ("agent_semantic_authority", "A model or agent may approve a definition, axiom, mapping, entailment or graph release.", "Require deterministic checks and the named human or institutional authority."),
]


NEGATIVE_ROWS = [{"negative_id": f"negative.semantic-vocabulary.{slug}", "unsafe_inference": unsafe, "required_behavior": behavior, "status": "active"} for slug, unsafe, behavior in NEGATIVES]


COMPILER_ROWS = []
for lib in LIBRARIES:
    stem = lib["library_id"].removeprefix("library.")
    COMPILER_ROWS += [
        {"record_kind": "capability_requirement", "requirement_id": f"requirement.{stem}.implementation", "subject_ref": lib["library_id"], "required_operations": lib["operation_refs"], "required_decisions": lib["decision_refs"], "fallback_law": "refuse", "status": "declared"},
        {"record_kind": "capability_offer", "offer_id": f"offer.{stem}.reference", "subject_ref": lib["library_id"], "claimed_operations": lib["operation_refs"], "qualified_implementation_count": 0, "portable": False, "selectable": False, "status": "specified_unimplemented"},
        {"record_kind": "binding_rule", "binding_rule_id": f"binding.{stem}", "requirement_ref": f"requirement.{stem}.implementation", "offer_ref": f"offer.{stem}.reference", "structural_match": True, "selection_law": "Structural match never promotes an unqualified or non-portable implementation.", "selectable": False, "status": "declared"},
    ]


FILES = {"sources.jsonl": SOURCES, "bounded-contexts.jsonl": CONTEXTS, "decision-points.jsonl": DECISION_ROWS, "library-contracts.jsonl": LIBRARIES, "compiler-contracts.jsonl": COMPILER_ROWS, "negative-twins.jsonl": NEGATIVE_ROWS}


def main() -> None:
    digests = {}
    for name, rows in FILES.items():
        payload = lines(rows)
        (ROOT / name).write_text(payload, encoding="utf-8")
        digests[name] = {"records": len(rows), "sha256": hashlib.sha256(payload.encode()).hexdigest()}
    manifest = {"manifest_id": "semantic_vocabulary_ontology_governance_v0_1_0", "as_of": AS_OF, "edition": EDITION, "status": "specified_unimplemented_open_world", "files": digests, "completion_claim": False, "qualified_implementation_count": 0}
    (ROOT / "manifest.json").write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"BUILD PASS semantic vocabulary/ontology: {len(SOURCES)} sources, {len(CONTEXTS)} contexts, {len(DECISION_ROWS)} decisions, {len(LIBRARIES)} exact libraries, {len(COMPILER_ROWS)} compiler contracts")


if __name__ == "__main__":
    main()
