#!/usr/bin/env python3
"""Validate structure, references, coverage floors, and deterministic serialization."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import sys
from collections import Counter
from pathlib import Path
from urllib.parse import urlparse


HERE = Path(__file__).resolve().parent
sys.dont_write_bytecode = True
SURFACES = {
    "source_occurrences", "types_shapes", "pipelines", "persistence",
    "runtime", "governance", "lineage", "consumption",
}
MINIMUMS = {
    "sources": 45,
    "bounded-context-candidates": 35,
    "innovations": 20,
}


def validate_manifest() -> None:
    manifest = json.loads((HERE / "manifest.json").read_text())
    if manifest["completion_claim"] is not False:
        fail("manifest completion claim must remain false")
    for name, claim in manifest["files"].items():
        data = (HERE / name).read_bytes()
        if len(data) != claim["bytes"] or hashlib.sha256(data).hexdigest() != claim["sha256"]:
            fail(f"manifest mismatch: {name}")


def fail(message: str) -> None:
    raise AssertionError(message)


def load_module():
    spec = importlib.util.spec_from_file_location("spt_build_corpus", HERE / "build_corpus.py")
    if spec is None or spec.loader is None:
        fail("cannot load build_corpus.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def load_jsonl(path: Path) -> list[dict]:
    records = []
    with path.open(encoding="utf-8") as handle:
        for number, line in enumerate(handle, 1):
            if not line.strip():
                fail(f"{path.name}:{number}: blank lines are not canonical JSONL")
            try:
                record = json.loads(line)
            except json.JSONDecodeError as exc:
                fail(f"{path.name}:{number}: invalid JSON: {exc}")
            if json.dumps(record, sort_keys=True) + "\n" != line:
                fail(f"{path.name}:{number}: non-canonical serialization")
            records.append(record)
    return records


def validate_schema_shape(schema: dict, record: dict, path: str) -> None:
    """Minimal in-repo validator for the schema subset emitted by the generator."""
    if schema.get("type") != "object" or not isinstance(record, dict):
        fail(f"{path}: expected object")
    for field in schema["required"]:
        if field not in record:
            fail(f"{path}: missing schema-required field {field}")
    for field, rules in schema.get("properties", {}).items():
        if field not in record or not rules:
            continue
        value = record[field]
        expected = rules.get("type")
        if expected == "string" and not isinstance(value, str):
            fail(f"{path}.{field}: expected string")
        if expected == "integer" and not isinstance(value, int):
            fail(f"{path}.{field}: expected integer")
        if expected == "array" and not isinstance(value, list):
            fail(f"{path}.{field}: expected array")
        if expected == "object" and not isinstance(value, dict):
            fail(f"{path}.{field}: expected object")
        if "enum" in rules and value not in rules["enum"]:
            fail(f"{path}.{field}: value outside enum")
        if expected == "object":
            for required in rules.get("required", []):
                if required not in value:
                    fail(f"{path}.{field}: missing {required}")


def main() -> int:
    validate_manifest()
    build = load_module()
    registries: dict[str, list[dict]] = {}
    ids: dict[str, set[str]] = {}

    # Every generated byte must be reproducible from the checked-in generator data.
    for name, (identifier, expected_records) in build.REGISTRIES.items():
        path = HERE / f"{name}.jsonl"
        actual = load_jsonl(path)
        expected_text = "".join(json.dumps(record, sort_keys=True) + "\n" for record in expected_records)
        if path.read_text(encoding="utf-8") != expected_text:
            fail(f"{path.name}: differs from deterministic generator output")
        schema = json.loads((HERE / "schemas" / f"{name}.schema.json").read_text(encoding="utf-8"))
        expected_schema = build.registry_schema(name, identifier, build.REQUIRED_BY_REGISTRY[name])
        if schema != expected_schema:
            fail(f"schemas/{name}.schema.json: differs from deterministic generator output")
        registries[name] = actual
        found = [record[identifier] for record in actual]
        if len(found) != len(set(found)):
            duplicates = [item for item, count in Counter(found).items() if count > 1]
            fail(f"{name}: duplicate IDs {duplicates}")
        ids[name] = set(found)
        for index, record in enumerate(actual, 1):
            validate_schema_shape(schema, record, f"{name}:{index}")
            allowed_status = "open_candidate_gap" if name == "gaps" else "sourced_candidate"
            if record["status"] != allowed_status:
                fail(f"{name}:{index}: non-candidate status {record['status']}")

    for name, minimum in MINIMUMS.items():
        if len(registries[name]) < minimum:
            fail(f"{name}: {len(registries[name])} < required {minimum}")

    combined = sum(len(registries[name]) for name in ("capabilities", "operations", "threat-abuse-cases", "decisions"))
    if combined < 140:
        fail(f"combined capability/operation/threat/decision candidates: {combined} < 140")

    source_ids = ids["sources"]
    context_ids = ids["bounded-context-candidates"]
    capability_ids = ids["capabilities"]
    operation_ids = ids["operations"]
    requirement_ids = ids["compiler-requirements"]
    asset_ids = ids["assets-trust-boundaries"]

    # Source records are primary, original research, or primary law; no aggregators or vendor blogs.
    allowed_primary_kinds = {
        "authority_framework", "authority_guidance", "primary_standard", "community_specification",
        "candidate_recommendation", "open_source_specification", "official_documentation",
        "privacy_authority_guidance", "primary_law", "peer_reviewed_original_research",
        "official_method_documentation",
    }
    for record in registries["sources"]:
        parsed = urlparse(record["url"])
        if parsed.scheme != "https" or not parsed.netloc:
            fail(f"{record['source_id']}: source URL must be absolute HTTPS")
        if record["source_kind"] not in allowed_primary_kinds:
            fail(f"{record['source_id']}: source kind is not an allowed primary-authority class")
        if not record["occurrences"]:
            fail(f"{record['source_id']}: no source occurrences")
    source_mix = {
        "nist": sum(record["source_id"].startswith("src.nist.") for record in registries["sources"]),
        "w3c": sum(record["source_id"].startswith("src.w3c.") for record in registries["sources"]),
        "ietf": sum(record["source_id"].startswith("src.ietf.") for record in registries["sources"]),
        "oasis": sum(record["source_id"].startswith("src.oasis.") for record in registries["sources"]),
        "oss": sum(record["source_kind"] in {"open_source_specification", "official_documentation"} for record in registries["sources"]),
        "privacy_authority_or_law": sum(record["source_kind"] in {"privacy_authority_guidance", "primary_law"} for record in registries["sources"]),
        "peer_reviewed_original_research": sum(record["source_kind"] == "peer_reviewed_original_research" for record in registries["sources"]),
    }
    source_mix_floors = {"nist": 10, "w3c": 5, "ietf": 10, "oasis": 3, "oss": 8, "privacy_authority_or_law": 4, "peer_reviewed_original_research": 8}
    for family, minimum in source_mix_floors.items():
        if source_mix[family] < minimum:
            fail(f"source mix {family}: {source_mix[family]} < {minimum}")

    for name, records in registries.items():
        if name == "sources":
            continue
        for record in records:
            record_id = next(value for key, value in record.items() if key.endswith("_id"))
            refs = record.get("evidence_source_ids", [])
            if not refs or not set(refs) <= source_ids:
                fail(f"{record_id}: missing or unknown evidence source reference")
            mapping = record.get("cross_platform_map")
            if not isinstance(mapping, dict) or set(mapping) != SURFACES:
                fail(f"{record_id}: cross-platform map does not have exactly eight required surfaces")
            if any(not isinstance(mapping[surface], list) or not mapping[surface] for surface in SURFACES):
                fail(f"{record_id}: cross-platform surface empty or ill-typed")
            if set(mapping["source_occurrences"]) & source_ids:
                fail(f"{record_id}: platform source occurrences are conflated with bibliography IDs")
            if not any(item.startswith("source_boundary:") for item in mapping["source_occurrences"]):
                fail(f"{record_id}: cross-map lacks a source-system boundary occurrence")

    cited_sources = {
        source_id
        for name, records in registries.items() if name != "sources"
        for record in records
        for source_id in record.get("evidence_source_ids", [])
    }
    if cited_sources != source_ids:
        fail(f"bibliography contains uncited sources: {sorted(source_ids - cited_sources)}")

    for record in registries["assets-trust-boundaries"]:
        if record["authority_owner"] not in context_ids:
            fail(f"{record['asset_id']}: unknown authority owner")
    for name in ("threat-abuse-cases", "capabilities", "operations", "decisions", "compiler-requirements"):
        for record in registries[name]:
            if record["owner_context"] not in context_ids:
                fail(f"{next(value for key, value in record.items() if key.endswith('_id'))}: unknown owner context")
    for record in registries["threat-abuse-cases"]:
        if not set(record["asset_refs"]) <= asset_ids:
            fail(f"{record['threat_id']}: unknown asset reference")
    for record in registries["compiler-requirements"]:
        if record["capability_ref"] not in capability_ids:
            fail(f"{record['requirement_id']}: unknown capability reference")
    for record in registries["capability-offers"]:
        if not set(record["declared_capabilities"]) <= capability_ids:
            fail(f"{record['offer_id']}: unknown declared capability")
        if record["qualification_state"] != "unqualified_template" or record["provider_binding"] is not None:
            fail(f"{record['offer_id']}: seed offer must remain unqualified and provider-neutral")
    for record in registries["compiler-mappings"]:
        if record["context_ref"] not in context_ids:
            fail(f"{record['mapping_id']}: unknown context")
        if not set(record["required_capabilities"]) <= capability_ids:
            fail(f"{record['mapping_id']}: unknown capability")
        if not set(record["candidate_operations"]) <= operation_ids:
            fail(f"{record['mapping_id']}: unknown operation")
        if not set(record["requirement_refs"]) <= requirement_ids:
            fail(f"{record['mapping_id']}: unknown requirement")

    years = [record["year"] for record in registries["innovations"]]
    if not all(2021 <= year <= 2026 for year in years):
        fail("innovations: year outside requested 2021-2026 window")
    if len(set(years)) < 5:
        fail("innovations: insufficient temporal coverage")

    # Guard the core method boundary.  Mentions in README completeness notes are intentionally not scanned.
    forbidden = ("large_language_model", "prompt_engineering", "retrieval_augmented_generation", "agent_memory")
    for name, records in registries.items():
        searchable = json.dumps(records, sort_keys=True).lower().replace("-", "_").replace(" ", "_")
        hit = next((term for term in forbidden if term in searchable), None)
        if hit:
            fail(f"{name}: forbidden core method dependency {hit}")

    report = json.loads((HERE / "coverage-report.json").read_text(encoding="utf-8"))
    actual_counts = {name: len(records) for name, records in registries.items()}
    if report["counts"] != actual_counts or report["combined_capability_operation_threat_decision_candidates"] != combined:
        fail("coverage-report.json: stale counts")
    if report["cited_source_count"] != len(cited_sources):
        fail("coverage-report.json: stale cited-source count")
    if report["completion_claim"] is not False:
        fail("coverage-report.json: completion claim must remain false")

    print("VALID security/privacy/trust corpus")
    print("counts=" + json.dumps(actual_counts, sort_keys=True))
    print(f"combined_capability_operation_threat_decision_candidates={combined}")
    print(f"primary_sources={len(registries['sources'])}")
    print(f"cited_sources={len(cited_sources)}")
    print("source_mix=" + json.dumps(source_mix, sort_keys=True))
    print(f"bounded_contexts={len(registries['bounded-context-candidates'])}")
    print(f"recent_innovations={len(registries['innovations'])}")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except AssertionError as exc:
        print(f"INVALID: {exc}", file=sys.stderr)
        raise SystemExit(1)
