#!/usr/bin/env python3
"""Full product-specific DDD for collaboration, privacy, resolution and assurance."""

from __future__ import annotations

from typing import Any


DDD_FIELDS = {
    "domain_vision_statement", "subdomain_classification", "bounded_context_boundary",
    "ubiquitous_language_policy", "context_map", "anti_corruption_layers", "published_language",
    "value_objects", "entities", "aggregates", "aggregate_roots", "aggregate_invariants",
    "commands", "domain_events", "refusal_failure_catalog", "domain_services",
    "application_services", "repositories", "factories", "specifications", "state_machine",
    "policies_and_reactions", "sagas_and_process_managers", "read_models_and_projections",
    "integration_event_policy", "concurrency_and_idempotency", "time_model",
    "event_storming_swimlanes", "nonfunctional_laws",
}

AUTOMATION = {
    "default": "DETERMINISTIC_CORE_ONLY",
    "postures": ["PROHIBITED", "OPTIONAL", "REQUIRED_BY_INTENT", "UNDETERMINED"],
    "law": "Predictive models may implement an explicitly selected scoring or risk method and models or agents may propose drafts, evidence candidates, triage or explanations; typed contracts, deterministic policy, qualified methods, named authorities and effect gates decide every authoritative transition.",
    "removal_law": "Removing every optional model or agent extension preserves deterministic collaboration policy and release, rights/retention case control, rules-based entity resolution, assurance appraisal, evidence, refusal and effect contracts; explicitly selected predictive methods may instead become capability_unavailable.",
    "hard_work_law": "Automation never replaces vocabulary, bounded contexts, authority, invariants, evidence acquisition, qualification, numerical or policy evaluation, human judgment where required, effects, receipts or relying-party acceptance.",
}


def _result(ident: str, product: str, truth: dict[str, Any], ddd: dict[str, Any]) -> dict[str, Any]:
    assert set(ddd) == DDD_FIELDS
    return {"dossier_id": ident, "product_ref": product, "status": "candidate_not_ratified", "product_truth": truth, "strategic_and_tactical_ddd": ddd}


def _collaboration() -> dict[str, Any]:
    product = "product.controlled_data_collaboration"
    truth = {
        "sovereign_question": "How can mutually bounded parties admit governed contributions, execute only jointly approved analyses under declared privacy and runtime guarantees, release only authorized outputs, and exit with complete evidence?",
        "users": ["collaboration_owner", "data_contributor", "analysis_requestor", "participant_authority", "output_reviewer", "privacy_reviewer", "runtime_operator"],
        "harmed_parties": ["data_subject", "contributor", "nonparticipating_party", "confidentiality_owner", "decision_subject"],
        "jobs": ["negotiate an editioned collaboration contract", "admit participants and contributions", "approve exact analyses", "select and qualify privacy/secure-compute mechanisms", "execute against admitted cuts", "appraise and release outputs", "revoke suspend close export and verify exit"],
        "measurable_outcomes": ["contract_and_authority_closure", "admitted_input_coverage", "approved_analysis_exact_match", "privacy_budget_and_risk_compliance", "output_release_refusal_correctness", "receipt_completeness", "revocation_propagation", "verified_exit"],
        "negative_mission": "Does not own source truth, participant identity, purpose or legal authority, general warehouse/query semantics, analytical method meaning, TEE/MPC identity, or permission to release merely because computation succeeded.",
    }
    ddd = {
        "domain_vision_statement": "Own the governed multi-party contract from participant and contribution admission through approved computation, output release and evidenced exit.",
        "subdomain_classification": {"core": ["collaboration_contract", "participant_and_contribution_admission", "approved_analysis_policy", "output_release_authority", "collaboration_receipts"], "supporting": ["privacy_budget", "disclosure_risk_appraisal", "secure_compute_binding", "attestation_appraisal", "revocation_and_exit"], "generic_or_imported": ["identity_and_delegation", "data_use_policy", "schema_and_data_contracts", "query_and_runtime", "deidentification_and_privacy_methods", "TEE_MPC_cryptography", "lineage_and_evidence"]},
        "bounded_context_boundary": {"inside": ["collaboration and participant terms", "contribution contracts and admitted cuts", "approved analysis editions and parameters", "combined policy evaluation", "privacy budget and release-risk state", "secure-compute requirements", "execution and release receipts", "suspension revocation and exit"], "outside": ["source record truth", "participant identity proof", "legal interpretation", "general analytical method semantics", "physical compute", "master data", "recipient business decisions"]},
        "ubiquitous_language_policy": {"terms": {"CollaborationContract": "editioned participants purposes inputs analyses outputs duties term and exit", "ParticipantAdmission": "role and authority decision for one party occurrence", "Contribution": "source-owner-bound data cut and obligations", "ApprovedAnalysis": "exact code query parameters parties and release profile", "ExecutionOccurrence": "one runtime attempt under one approved analysis", "OutputCandidate": "computed result not yet releasable", "OutputRelease": "separate authorized disclosure effect"}, "homonym_rules": ["clean room is an architecture pattern not semantic owner", "TEE is not collaboration", "query success is not release", "masking is not anonymity", "attestation is not relying authorization"]},
        "context_map": [{"neighbor_ref": "neighbor.identity_authority", "relationship": "conformist_with_acl", "translation": "import principal role delegation and revocation"}, {"neighbor_ref": "neighbor.data_use_policy", "relationship": "customer_supplier", "translation": "import purpose permission prohibition and duty semantics"}, {"neighbor_ref": "neighbor.source_truth", "relationship": "customer_supplier", "translation": "bind immutable contribution cuts and corrections"}, {"neighbor_ref": "neighbor.analytical_method", "relationship": "customer_supplier", "translation": "bind exact method contracts without transferring release authority"}, {"neighbor_ref": "neighbor.query_compute", "relationship": "effect_port", "translation": "submit approved work and consume attested receipts"}],
        "anti_corruption_layers": ["acl.participant_identity", "acl.data_use_policy", "acl.source_contribution", "acl.analysis_language", "acl.secure_compute_provider", "acl.attestation", "acl.output_projection"],
        "published_language": ["CollaborationId", "CollaborationEdition", "ParticipantRef", "ParticipantAuthorityReceipt", "ContributionContract", "AdmittedDataCut", "ApprovedAnalysisEdition", "AnalysisPolicyDecision", "PrivacyBudgetReservation", "SecureRuntimeRequirement", "ExecutionReceipt", "OutputCandidate", "ReleaseRiskAssessment", "OutputReleaseDecision", "OutputReleaseReceipt", "CollaborationExitManifest"],
        "value_objects": ["CollaborationId", "ContractEdition", "ParticipantRef", "RoleRef", "AuthorityRef", "PurposeRef", "ContributionId", "DataCutRef", "SchemaEditionRef", "AnalysisDigest", "ParameterBinding", "PrivacyUnit", "BudgetAmount", "RuntimeProfileRef", "AudienceRef", "EvidenceRef"],
        "entities": ["Collaboration", "ParticipantAdmission", "Contribution", "ApprovedAnalysis", "PrivacyBudgetLedger", "ExecutionOccurrence", "OutputReviewCase", "OutputRelease", "CollaborationExitCase"],
        "aggregates": [{"root": "Collaboration", "members": ["contract_editions", "participants", "purposes", "term", "allowed_analyses", "output_policy", "exit_policy", "state"], "consistency": "one active edition closes all parties purposes duties and precedence"}, {"root": "ExecutionOccurrence", "members": ["approved_analysis_ref", "admitted_inputs", "policy_decision", "budget_reservation", "runtime_binding", "receipts", "output_candidates"], "consistency": "every effect binds exact contract analysis input runtime and authority editions"}, {"root": "OutputReviewCase", "members": ["candidate", "recipient", "projection", "risk_assessment", "participant_obligations", "decision", "release_receipt"], "consistency": "release requires a fresh explicit decision and never follows from execution success"}],
        "aggregate_roots": ["Collaboration", "ExecutionOccurrence", "OutputReviewCase"],
        "aggregate_invariants": ["every participant role authority delegation and revocation is explicit", "every contribution retains source owner cut identity schema time and use obligations", "analysis approval binds exact code query parameters participants and output profile", "applicable participant restrictions compose without silent weakening", "privacy accounting uses explicit unit adjacency mechanism and composition", "secure compute mechanism never authorizes an analysis or release", "execution and output release have distinct receipts", "revocation and exit obligations propagate to dependent future effects"],
        "commands": ["declare_collaboration", "propose_contract_edition", "admit_participant", "revoke_participant", "admit_contribution", "withdraw_contribution", "approve_analysis", "reserve_privacy_budget", "bind_secure_runtime", "request_execution", "record_execution_receipt", "open_output_review", "appraise_release_risk", "approve_output_release", "release_output", "suspend_collaboration", "close_collaboration", "verify_collaboration_exit"],
        "domain_events": ["collaboration_declared", "contract_edition_proposed", "participant_admitted", "participant_revoked", "contribution_admitted", "contribution_withdrawn", "analysis_approved", "privacy_budget_reserved", "secure_runtime_bound", "execution_requested", "execution_receipt_recorded", "output_review_opened", "release_risk_appraised", "output_release_approved", "output_released", "collaboration_suspended", "collaboration_closed", "collaboration_exit_verified"],
        "refusal_failure_catalog": ["collaboration_contract_incomplete", "participant_authority_unresolved", "purpose_incompatible", "contribution_contract_incompatible", "source_cut_stale", "analysis_not_jointly_approved", "policy_indeterminate", "privacy_budget_unavailable", "release_risk_unbounded", "secure_runtime_unqualified", "attestation_unacceptable", "execution_outcome_unknown", "output_release_refused", "recipient_unauthorized", "revocation_not_propagated", "exit_evidence_incomplete"],
        "domain_services": ["CollaborationContractService", "ParticipantAdmissionService", "ContributionAdmissionService", "AnalysisPolicyCompositionService", "PrivacyBudgetService", "SecureRuntimeBindingService", "OutputRiskAppraisalService", "OutputReleaseService", "CollaborationExitService"],
        "application_services": ["OpenCollaborationUseCase", "JoinCollaborationUseCase", "ContributeDataUseCase", "ApproveAnalysisUseCase", "ExecuteApprovedAnalysisUseCase", "ReviewReleaseOutputUseCase", "SuspendCollaborationUseCase", "ExitCollaborationUseCase"],
        "repositories": ["CollaborationRepository", "ParticipantAdmissionRepository", "ContributionRepository", "ApprovedAnalysisRepository", "PrivacyBudgetLedgerRepository", "ExecutionOccurrenceRepository", "OutputReviewCaseRepository", "ExitCaseRepository"],
        "factories": ["CollaborationFactory", "ParticipantAdmissionFactory", "ContributionFactory", "ApprovedAnalysisFactory", "ExecutionOccurrenceFactory", "OutputReviewCaseFactory", "ExitManifestFactory"],
        "specifications": ["CollaborationContractClosureSpecification", "ParticipantAuthoritySpecification", "ContributionCompatibilitySpecification", "AnalysisExactnessSpecification", "RestrictivePolicyCompositionSpecification", "PrivacyBudgetAvailabilitySpecification", "SecureRuntimeQualificationSpecification", "OutputReleaseSpecification", "CollaborationExitCompletenessSpecification"],
        "state_machine": {"Collaboration": ["draft", "negotiating", "participants_admitted", "contributions_admitted", "enabled", "suspended", "closing", "closed", "exit_pending"], "ExecutionOccurrence": ["planned", "policy_pending", "budget_pending", "runtime_pending", "running", "succeeded", "failed", "cancelled", "unknown"], "OutputReviewCase": ["candidate", "risk_review", "participant_review", "approved", "refused", "released", "recalled"], "law": "more restrictive authority dominates, output approval and release are separate, and unknown runtime outcomes are reconciled"},
        "policies_and_reactions": ["when participant authority is revoked invalidate future analyses and release decisions", "when a contribution changes create a new cut and invalidate dependent approvals", "when privacy budget is consumed update atomically before another effect", "when execution succeeds open output review rather than release", "when a release risk counterexample appears block release", "when collaboration closes require export revocation and residual-obligation evidence"],
        "sagas_and_process_managers": ["CollaborationNegotiationProcess", "ParticipantOnboardingProcess", "ContributionAdmissionProcess", "ApprovedAnalysisExecutionProcess", "PrivacyBudgetProcess", "OutputReviewReleaseProcess", "RevocationPropagationProcess", "CollaborationExitProcess"],
        "read_models_and_projections": ["CollaborationContractView", "ParticipantAuthorityView", "ContributionInventoryView", "ApprovedAnalysisMatrix", "PrivacyBudgetView", "ExecutionAndAttestationView", "OutputReviewQueue", "ReleaseLedgerView", "ExitReadinessView"],
        "integration_event_policy": "Only editioned collaboration, admission, contribution, approved-analysis, policy, budget, execution, output-review, release and exit contracts cross the boundary; raw participant secrets, provider DTOs and unreleased outputs do not.",
        "concurrency_and_idempotency": ["contract editions use optimistic concurrency", "participant and contribution admissions are idempotent by authority and cut digest", "execution idempotency binds contract analysis input budget and runtime editions", "privacy budget reservations serialize per ledger", "output release is single-winner per candidate recipient projection", "unknown effect completion is reconciled before retry"],
        "time_model": ["contract participant contribution purpose and authority validity are independent", "data-cut time differs from execution and release time", "privacy budget accounting windows are explicit", "attestation and policy evidence expire independently", "revocation effective time dominates cached approvals", "exit retains residual obligations until discharged"],
        "event_storming_swimlanes": ["collaboration_owner", "data_contributor", "analysis_requestor", "participant_authority", "data_use_policy", "privacy_accountant", "secure_runtime", "output_reviewer", "release_authority", "exit_reviewer"],
        "nonfunctional_laws": ["fail-closed multi-party authority", "deterministic policy composition for frozen inputs", "finite data query output privacy and runtime budgets", "no raw input or unreleased output leakage", "provider-neutral secure-compute ports", "complete input-analysis-runtime-output-release evidence", "cooperative cancellation with explicit unknown", "optional model or agent removal preserves the deterministic collaboration core"],
    }
    return _result("ddd.cpra.controlled_data_collaboration", product, truth, ddd)


def _privacy() -> dict[str, Any]:
    product = "product.privacy_rights_retention"
    truth = {
        "sovereign_question": "How can an organization receive, scope, adjudicate, plan, execute, verify, appeal and recall privacy-rights and records-disposition cases across heterogeneous systems under imported authority, retention schedules and holds?",
        "users": ["privacy_operations_team", "records_manager", "requestor", "data_subject", "case_reviewer", "system_owner", "appeal_authority"],
        "harmed_parties": ["data_subject", "third_party_data_subject", "records_owner", "litigation_or_hold_owner", "system_owner", "recipient"],
        "jobs": ["receive and authenticate requests", "resolve subject and record scope", "bind competent authority and deadlines", "calculate retention and hold precedence", "plan cross-system access correction portability restriction or deletion", "execute and verify effects", "disclose evidence", "appeal recall and close cases"],
        "measurable_outcomes": ["verified_subject_scope_coverage", "deadline_compliance", "hold_conflict_detection", "target_effect_coverage", "verified_vs_acknowledged_effect_ratio", "appeal_and_recall_traceability", "residual_copy_visibility"],
        "negative_mission": "Does not interpret law, establish real-world identity, own source records, override holds, claim provider acknowledgement as erasure, delete immutable evidence, or make rights/retention one blind timer.",
    }
    ddd = {
        "domain_vision_statement": "Own evidence-bearing rights and disposition cases from request through scoped, authorized, target-specific effects, appeal and recall.",
        "subdomain_classification": {"core": ["rights_and_disposition_case", "subject_and_record_scope", "authority_and_precedence_binding", "effect_plan_and_verification", "appeal_recall_and_evidence"], "supporting": ["retention_calculus", "hold_management", "disclosure_package", "downstream_impact", "deadline_and_calendar"], "generic_or_imported": ["identity_proof", "legal_interpretation", "records_schedules", "source_inventory", "deletion_and_mutation_adapters", "backup_and_archive", "lineage_and_evidence"]},
        "bounded_context_boundary": {"inside": ["case identity and lifecycle", "requestor subject and record scope", "authority policy and precedence references", "retention due calculations", "holds exceptions appeals", "effect plan attempts receipts and verification", "disclosure evidence recall and closure"], "outside": ["legal advice", "source-system record truth", "identity proof issuance", "backup mechanics", "provider deletion semantics", "court or regulator decisions"]},
        "ubiquitous_language_policy": {"terms": {"Requestor": "principal making or representing a request", "DataSubject": "person or subject whose records are scoped", "RightsCase": "governed request and adjudication lifecycle", "RetentionSchedule": "imported authority trigger duration cutoff and action edition", "Hold": "higher-precedence prohibition on disposition for a scope and interval", "EffectPlan": "target-specific intended actions", "EffectReceipt": "observed provider outcome", "VerifiedDisposition": "separately appraised effect evidence"}, "homonym_rules": ["requestor is not subject", "approval is not effect", "deletion request is not verified erasure", "retention due is not permission to delete", "backup expiry is not source erasure", "case closure is not universal deletion"]},
        "context_map": [{"neighbor_ref": "neighbor.legal_records_authority", "relationship": "customer_supplier_acl", "translation": "import applicability schedules exceptions holds and appeal decisions"}, {"neighbor_ref": "neighbor.identity_authority", "relationship": "conformist_with_acl", "translation": "consume requestor subject delegation and revocation evidence"}, {"neighbor_ref": "neighbor.source_truth", "relationship": "customer_supplier", "translation": "discover target records and submit authorized mutations"}, {"neighbor_ref": "neighbor.backup_archive", "relationship": "customer_supplier_acl", "translation": "coordinate future restoration gates and preservation obligations"}, {"neighbor_ref": "product.lineage_provenance", "relationship": "customer_supplier", "translation": "discover downstream copies disclosures and impact"}],
        "anti_corruption_layers": ["acl.legal_authority", "acl.identity_and_delegation", "acl.source_inventory", "acl.retention_schedule", "acl.effect_provider", "acl.backup_archive", "acl.lineage_impact"],
        "published_language": ["RightsCaseId", "RequestorRef", "SubjectRef", "SubjectScope", "RecordScope", "AuthorityDecisionRef", "RetentionScheduleRef", "DispositionDue", "HoldRef", "EffectPlanEdition", "TargetEffectIntent", "EffectAttempt", "DispositionReceipt", "DisclosurePackage", "Appeal", "RecallNotice", "CaseEvidenceBundle"],
        "value_objects": ["CaseId", "RequestType", "RequestorRef", "SubjectRef", "DelegationRef", "RecordLocator", "PurposeRef", "JurisdictionProfileRef", "ScheduleEditionRef", "TriggerRef", "BusinessCalendarRef", "HoldId", "TargetRef", "EffectKind", "EvidenceRef", "Deadline"],
        "entities": ["RightsCase", "SubjectScopeAssessment", "RetentionAssessment", "Hold", "EffectPlan", "EffectAttempt", "DisclosurePackage", "AppealCase", "RecallCase"],
        "aggregates": [{"root": "RightsCase", "members": ["request", "identity_evidence", "scope", "authority", "deadline", "plan", "evidence", "outcome", "appeal"], "consistency": "one transition records exact evidence authority and refusal precedence"}, {"root": "EffectPlan", "members": ["targets", "actions", "dependencies", "compensations", "hold_checks", "attempts", "receipts"], "consistency": "approval plan attempt acknowledgement and verified effect stay distinct"}, {"root": "Hold", "members": ["authority", "scope", "priority", "validity", "release"], "consistency": "no applicable active hold is bypassed by retention or rights automation"}],
        "aggregate_roots": ["RightsCase", "EffectPlan", "Hold"],
        "aggregate_invariants": ["requestor identity subject identity and record scope are distinct", "competent authority and policy editions are imported and attributable", "retention due binds schedule trigger time basis calendar and edition", "active hold and higher-authority prohibitions dominate effect plans", "approval plan attempt acknowledgement verified effect and closure are distinct", "every target effect has exact occurrence and verification evidence", "access and portability packages include only authorized projections", "correction retraction recall restriction and deletion remain distinct", "appeal never rewrites prior history"],
        "commands": ["receive_case", "verify_requestor", "resolve_subject_scope", "discover_record_scope", "bind_case_authority", "calculate_disposition_due", "place_hold", "release_hold", "compile_effect_plan", "approve_effect_plan", "execute_target_effect", "record_effect_receipt", "verify_disposition", "construct_disclosure_package", "fulfil_case", "refuse_case", "appeal_case", "recall_disposition", "close_case"],
        "domain_events": ["case_received", "requestor_verified", "subject_scope_resolved", "record_scope_discovered", "case_authority_bound", "disposition_due_calculated", "hold_placed", "hold_released", "effect_plan_compiled", "effect_plan_approved", "target_effect_executed", "effect_receipt_recorded", "disposition_verified", "disclosure_package_constructed", "case_fulfilled", "case_refused", "case_appealed", "disposition_recalled", "case_closed"],
        "refusal_failure_catalog": ["requestor_unverified", "delegation_invalid", "subject_scope_ambiguous", "record_scope_incomplete", "authority_unbound", "deadline_semantics_unknown", "retention_trigger_unknown", "calendar_unsupported", "active_hold_conflict", "effect_plan_incomplete", "effect_provider_unqualified", "target_effect_unsupported", "provider_outcome_unknown", "disposition_receipt_incomplete", "disclosure_projection_unsafe", "appeal_authority_missing", "recall_scope_unknown"],
        "domain_services": ["SubjectScopeResolutionService", "RecordScopeDiscoveryService", "AuthorityBindingService", "RetentionCalculusService", "HoldPrecedenceService", "EffectPlanningService", "DispositionVerificationService", "DisclosurePackagingService", "RecallImpactService"],
        "application_services": ["ReceiveRightsCaseUseCase", "ScopeRightsCaseUseCase", "AdjudicateRightsCaseUseCase", "ExecuteDispositionUseCase", "ProvideAccessOrPortabilityUseCase", "AppealCaseUseCase", "RecallDispositionUseCase", "CloseCaseUseCase"],
        "repositories": ["RightsCaseRepository", "SubjectScopeAssessmentRepository", "RetentionAssessmentRepository", "HoldRepository", "EffectPlanRepository", "EffectAttemptRepository", "AppealCaseRepository", "RecallCaseRepository"],
        "factories": ["RightsCaseFactory", "SubjectScopeFactory", "RetentionAssessmentFactory", "HoldFactory", "EffectPlanFactory", "DispositionReceiptFactory", "DisclosurePackageFactory"],
        "specifications": ["RequestorEvidenceSpecification", "SubjectScopeCompletenessSpecification", "AuthorityApplicabilitySpecification", "RetentionDueSpecification", "HoldPrecedenceSpecification", "EffectPlanClosureSpecification", "TargetProviderQualificationSpecification", "DispositionEvidenceSpecification", "DisclosureMinimizationSpecification", "CaseClosureSpecification"],
        "state_machine": {"RightsCase": ["received", "identity_pending", "scoped", "authority_review", "planned", "executing", "evidence_review", "fulfilled", "refused", "appealed", "recalled", "closed"], "EffectAttempt": ["planned", "authorized", "submitted", "acknowledged", "verified", "failed", "cancelled", "unknown", "compensating"], "Hold": ["proposed", "active", "challenged", "released", "expired", "superseded"], "law": "higher-authority prohibitions dominate and unknown target outcomes remain unknown until reconciled"},
        "policies_and_reactions": ["when identity or authority evidence expires pause the case", "when scope expands repeat authority and hold evaluation", "when a hold becomes active stop uncommitted effects and gate restoration", "when a provider only acknowledges an effect retain verification_pending", "when new downstream lineage appears extend recall impact", "when an appeal succeeds supersede outcome without editing history"],
        "sagas_and_process_managers": ["RightsCaseProcess", "SubjectAndRecordScopeProcess", "CrossSystemEffectProcess", "HoldPropagationProcess", "DisclosurePackageProcess", "AppealProcess", "DispositionRecallProcess", "CaseClosureProcess"],
        "read_models_and_projections": ["CaseQueueView", "DeadlineAndSlaView", "SubjectRecordScopeView", "AuthorityAndHoldView", "EffectPlanProgressView", "VerifiedDispositionCoverageView", "ResidualCopyView", "AppealAndRecallHistoryView", "CaseEvidenceView"],
        "integration_event_policy": "Only minimized editioned case scope authority schedule hold effect disclosure evidence appeal and recall contracts cross the boundary; identity secrets, raw source records, provider DTOs and legal work product do not.",
        "concurrency_and_idempotency": ["case transitions use optimistic edition", "target effects use case plan target and action idempotency scopes", "holds serialize by governed scope and authority precedence", "provider unknown outcomes reconcile before retry", "receipts append and never overwrite", "closure is single-winner and can later be appealed or recalled through new cases"],
        "time_model": ["request receipt validity deadline and completion times differ", "identity authority schedule and hold validity are bitemporal", "retention trigger occurrence cutoff and due times are explicit", "provider effect occurrence acknowledgement and verification times differ", "appeal and recall time never rewrite historical evidence", "backup restoration gates may outlive case closure"],
        "event_storming_swimlanes": ["requestor", "privacy_operations", "identity_authority", "legal_records_authority", "records_manager", "source_system_owner", "effect_provider", "backup_archive_owner", "evidence_reviewer", "appeal_authority"],
        "nonfunctional_laws": ["fail-closed authority hold and disclosure precedence", "deterministic time and retention calculation for frozen editions", "finite target case retry deadline and evidence budgets", "non-enumerating identity and record-scope refusals", "provider-neutral effect ports", "complete target-specific effect and residual evidence", "recoverable appeal and recall", "optional model or agent removal preserves deterministic case control"],
    }
    return _result("ddd.cpra.privacy_rights_retention", product, truth, ddd)


def _resolution() -> dict[str, Any]:
    product = "product.entity_resolution"
    truth = {
        "sovereign_question": "Which source-record occurrences may refer to the same scoped entity, under which normalization, candidate, feature, method, threshold, review and clustering evidence, and how can every link, split and downstream proposal be challenged and reversed?",
        "users": ["data_steward", "resolution_engineer", "domain_owner", "clerical_reviewer", "master_data_owner", "quality_reviewer", "downstream_consumer"],
        "harmed_parties": ["misidentified_person", "merged_organization", "excluded_entity", "source_owner", "decision_subject", "downstream_system_owner"],
        "jobs": ["declare entity population and namespaces", "normalize comparison features with loss accounting", "generate candidate pairs", "apply rules probabilistic or predictive scoring", "bind thresholds and review policy", "decide links and form clusters", "propose merges and splits", "evaluate population quality and reverse decisions"],
        "measurable_outcomes": ["candidate_generation_recall", "pair_precision_recall_and_calibration", "clerical_review_burden", "cluster_overmerge_and_undermerge", "subgroup_harm", "decision_explainability", "reversal_and_downstream_impact_coverage"],
        "negative_mission": "Does not establish metaphysical or legal identity, own source/master truth, treat a score as a link, let transitive closure invent equivalence, mutate golden records, or make predictive ML mandatory.",
    }
    ddd = {
        "domain_vision_statement": "Own evidence-bearing, population-scoped record linkage and entity clustering decisions while leaving source and master mutation to their authorities.",
        "subdomain_classification": {"core": ["entity_and_namespace_scope", "candidate_and_comparison_contract", "link_decision_policy", "cluster_and_merge_split_ledger", "resolution_evidence_and_evaluation"], "supporting": ["normalization", "clerical_review", "threshold calibration", "drift and subgroup evaluation", "downstream impact"], "generic_or_imported": ["source ingestion", "identity authority", "rules_probabilistic_and_predictive_methods", "master_data", "human workflow", "lineage_and_evidence"]},
        "bounded_context_boundary": {"inside": ["entity kind population and namespace declarations", "source record occurrences", "normalization profiles", "candidate pairs", "comparison features and scores", "threshold and review policy", "link decisions", "cluster editions", "merge split and reversal proposals", "evaluation evidence"], "outside": ["source record mutation", "legal identity proof", "golden record field authority", "generic model training runtime", "business decision using a resolved entity"]},
        "ubiquitous_language_policy": {"terms": {"RecordOccurrence": "source namespace edition and time bound record reference", "CandidatePair": "pair selected for comparison, not a match", "ComparisonFeature": "method-edition-bound evidence about a pair", "MatchScore": "rule probability or predictive result under assumptions", "LinkDecision": "authorized match nonmatch or review fact", "EntityCluster": "versioned grouping under one clustering policy", "MergeProposal": "request to a master authority, not an effect"}, "homonym_rules": ["same carrier value is not same identifier across namespaces", "score is not decision", "link is not entity identity", "pair links are not automatically transitive", "cluster is not golden record", "merge proposal is not merge effect"]},
        "context_map": [{"neighbor_ref": "neighbor.source_truth", "relationship": "customer_supplier_acl", "translation": "bind source identities occurrences corrections and field evidence"}, {"neighbor_ref": "neighbor.analytical_method", "relationship": "customer_supplier", "translation": "bind rules probabilistic or predictive method contracts"}, {"neighbor_ref": "neighbor.master_data", "relationship": "customer_supplier_acl", "translation": "submit merge split survivorship proposals and consume authoritative outcomes"}, {"neighbor_ref": "neighbor.identity_authority", "relationship": "customer_supplier", "translation": "consume authoritative identity claims where available"}, {"neighbor_ref": "product.lineage_provenance", "relationship": "customer_supplier", "translation": "trace downstream uses and reversals"}],
        "anti_corruption_layers": ["acl.source_namespace", "acl.normalization_provider", "acl.scoring_method", "acl.review_workflow", "acl.master_authority", "acl.downstream_lineage"],
        "published_language": ["EntityScope", "SourceNamespace", "RecordOccurrenceRef", "NormalizationProfile", "CandidatePairId", "ComparisonFeatureSet", "ScoringMethodProfile", "MatchScore", "ThresholdPolicyEdition", "LinkDecision", "ReviewCase", "ClusterEdition", "MergeSplitProposal", "ResolutionEvidenceBundle", "PopulationEvaluation"],
        "value_objects": ["EntityKind", "PopulationRef", "NamespaceRef", "RecordOccurrenceId", "SourceCutRef", "NormalizationProfileRef", "CandidatePairId", "FeatureRef", "MethodEditionRef", "Score", "Uncertainty", "Threshold", "ReviewerRef", "ClusterId", "EvidenceRef"],
        "entities": ["ResolutionProject", "RecordOccurrence", "CandidatePair", "PairAssessment", "LinkDecision", "ClericalReviewCase", "EntityCluster", "MergeSplitProposal", "PopulationEvaluation"],
        "aggregates": [{"root": "ResolutionProject", "members": ["entity_scope", "source_cuts", "normalization", "candidate_policy", "method", "thresholds", "review_policy", "cluster_policy"], "consistency": "one project edition closes the population and every method/policy dependency"}, {"root": "PairAssessment", "members": ["pair", "source_evidence", "features", "score", "threshold_policy", "review", "decision"], "consistency": "score and authorized decision remain separately attributable"}, {"root": "EntityCluster", "members": ["cluster_edition", "members", "supporting_links", "conflicts", "merge_split_history"], "consistency": "every membership change is supported, challengeable and reversible"}],
        "aggregate_roots": ["ResolutionProject", "PairAssessment", "EntityCluster"],
        "aggregate_invariants": ["entity scope namespace population and source cut are explicit", "normalization is versioned and accounts for loss", "blocked-out pairs are unexamined not nonmatches", "features retain source values missingness and method edition", "rules probabilistic and predictive methods share a typed score contract but retain assumptions", "score prediction review and link decision are distinct", "thresholds bind population error cost authority and validity", "pair link cluster membership and master identity are distinct", "source and master mutation require external authority", "reversal propagates impact without deleting historical decisions"],
        "commands": ["open_resolution_project", "bind_source_namespace", "bind_source_cut", "normalize_features", "generate_candidates", "compare_record_pair", "score_pair", "bind_threshold_policy", "request_clerical_review", "record_review", "decide_link", "form_cluster", "propose_merge_split", "submit_master_proposal", "reverse_decision", "evaluate_population", "retire_resolution_project"],
        "domain_events": ["resolution_project_opened", "source_namespace_bound", "source_cut_bound", "features_normalized", "candidates_generated", "record_pair_compared", "pair_scored", "threshold_policy_bound", "clerical_review_requested", "review_recorded", "link_decided", "cluster_formed", "merge_split_proposed", "master_proposal_submitted", "decision_reversed", "population_evaluated", "resolution_project_retired"],
        "refusal_failure_catalog": ["entity_scope_ambiguous", "source_namespace_ambiguous", "source_cut_stale", "normalization_profile_missing", "semantic_loss_unknown", "candidate_recall_unmeasured", "feature_semantics_incompatible", "method_unqualified_for_population", "score_uncalibrated", "threshold_authority_missing", "review_conflict", "cluster_inconsistent", "merge_authority_missing", "master_change_refused", "evaluation_insufficient", "reversal_scope_unknown"],
        "domain_services": ["NamespaceResolutionService", "NormalizationService", "CandidateGenerationService", "ComparisonFeatureService", "MatchScoringService", "ThresholdDecisionService", "ClericalReviewService", "ClusterFormationService", "MergeSplitProposalService", "PopulationEvaluationService"],
        "application_services": ["ConfigureResolutionUseCase", "RunCandidateGenerationUseCase", "ScorePairsUseCase", "ReviewUncertainPairsUseCase", "DecideLinksUseCase", "BuildClustersUseCase", "ProposeMasterChangesUseCase", "ReverseResolutionUseCase", "EvaluateResolutionUseCase"],
        "repositories": ["ResolutionProjectRepository", "RecordOccurrenceRepository", "CandidatePairRepository", "PairAssessmentRepository", "LinkDecisionRepository", "ClericalReviewCaseRepository", "EntityClusterRepository", "MergeSplitProposalRepository", "PopulationEvaluationRepository"],
        "factories": ["ResolutionProjectFactory", "RecordOccurrenceFactory", "CandidatePairFactory", "PairAssessmentFactory", "LinkDecisionFactory", "EntityClusterFactory", "MergeSplitProposalFactory"],
        "specifications": ["EntityScopeClosureSpecification", "NamespaceResolutionSpecification", "NormalizationLossSpecification", "CandidateGenerationCoverageSpecification", "FeatureCompatibilitySpecification", "MethodPopulationQualificationSpecification", "ThresholdAuthoritySpecification", "LinkDecisionSpecification", "ClusterConsistencySpecification", "MasterProposalSpecification", "PopulationEvaluationSpecification"],
        "state_machine": {"ResolutionProject": ["configured", "profiled", "candidates_generated", "scoring", "review_pending", "links_decided", "clustered", "evaluated", "suspended", "retired"], "PairAssessment": ["candidate", "features_ready", "scored", "review_pending", "match", "nonmatch", "uncertain", "reversed"], "MergeSplitProposal": ["draft", "authority_pending", "submitted", "accepted", "rejected", "executed", "reversed", "unknown"], "law": "source/master effects are external, decisions are append-only, and reversal creates new evidence-bearing state"},
        "policies_and_reactions": ["when a source cut or normalization profile changes invalidate dependent assessments", "when population drift exceeds policy suspend quality claims", "when score falls in review band open clerical review", "when a link changes recompute only affected cluster closure", "when a master proposal is refused preserve resolution evidence without mutating truth", "when a decision reverses propagate exact downstream impact"],
        "sagas_and_process_managers": ["ResolutionRunProcess", "CandidateAndScoringProcess", "ClericalReviewProcess", "ClusterFormationProcess", "MasterProposalProcess", "DecisionReversalProcess", "PopulationReevaluationProcess"],
        "read_models_and_projections": ["ResolutionConfigurationView", "CandidateCoverageView", "PairEvidenceView", "ScoreAndThresholdView", "ClericalReviewQueue", "ClusterGraphView", "MergeSplitLedgerView", "PopulationQualityView", "DriftAndSubgroupView", "DownstreamImpactView"],
        "integration_event_policy": "Only editioned scope namespace occurrence candidate feature score decision cluster proposal evaluation and reversal contracts cross the boundary; raw provider model objects, source records and master mutations do not.",
        "concurrency_and_idempotency": ["project configuration uses immutable editions", "pair identity is canonical under scoped record occurrences", "scoring binds feature and method digests", "link decisions use optimistic pair edition", "cluster updates use affected-graph compare-and-swap", "master proposals use idempotency keys", "reversal never deletes the original decision"],
        "time_model": ["source occurrence validity and recording times differ", "population source cut method threshold and review-policy validity are independent", "link and cluster decisions have effective and recording times", "quality evidence expires under drift", "master outcomes and downstream propagation occur later than resolution decisions", "historical evaluations retain original cuts"],
        "event_storming_swimlanes": ["resolution_engineer", "source_owner", "method_provider", "data_steward", "clerical_reviewer", "cluster_service", "master_data_owner", "quality_reviewer", "downstream_consumer"],
        "nonfunctional_laws": ["deterministic candidate feature and rule execution for frozen inputs", "finite pair memory review and method budgets", "declared numerical tolerance randomness and uncertainty", "population and subgroup scoped quality evidence", "provider and model isolation behind typed method ports", "complete pair-to-cluster-to-proposal trace", "reversible decisions and impact propagation", "optional model or agent removal preserves deterministic rules review cluster and authority paths"],
    }
    return _result("ddd.cpra.entity_resolution", product, truth, ddd)


def _assurance() -> dict[str, Any]:
    product = "product.assurance_case_appraisal"
    truth = {
        "sovereign_question": "How can a relying party obtain a scoped, criteria-edition-bound, evidence-linked, independently challengeable and time-bounded appraisal of a precise claim without confusing tests, attestations, signatures, approvals or automation with truth?",
        "users": ["claim_owner", "assurance_case_author", "appraiser", "independence_reviewer", "evidence_custodian", "challenger", "relying_authority"],
        "harmed_parties": ["relying_party", "claim_subject", "affected_person", "evidence_source", "public_or_customer", "conflicted_appraiser"],
        "jobs": ["define claim scope and criteria", "plan appraisal and evidence populations", "appoint competent non-conflicted appraisers", "admit and preserve evidence", "perform tests inspections and analysis", "record findings defeaters and challenges", "issue disclose supersede withdraw and reappraise bounded verdicts"],
        "measurable_outcomes": ["claim_criteria_scope_closure", "planned_vs_performed_work_coverage", "evidence_relevance_integrity_freshness_and_custody", "conflict_and_independence_resolution", "defeater_disposition", "verdict_limitation_visibility", "reappraisal_and_withdrawal_latency"],
        "negative_mission": "Does not guarantee truth, grant accreditation, infer independence from software or brand, treat test pass or signature as acceptance, suppress contrary evidence, or make the relying decision.",
    }
    ddd = {
        "domain_vision_statement": "Own a challengeable claim-argument-evidence appraisal lifecycle culminating only in a scoped bounded verdict and its evidence.",
        "subdomain_classification": {"core": ["claim_argument_graph", "criteria_and_appraisal_plan", "evidence_admission_and_evaluation", "findings_defeaters_and_challenge", "bounded_verdict_lifecycle"], "supporting": ["appraiser_competence_and_conflict", "evidence_custody", "executable_oracles", "attestation_and_signature_verification", "disclosure"], "generic_or_imported": ["identity_and_credentials", "accreditation", "domain_criteria", "test_execution", "cryptography", "records_preservation", "relying_decision"]},
        "bounded_context_boundary": {"inside": ["claim scope and argument graph", "criteria applicability and edition", "appraisal plan and performed work", "appraiser mandate competence independence and conflict evidence", "evidence admission custody evaluation", "findings defeaters challenges", "bounded verdict attestation signature disclosure supersession withdrawal"], "outside": ["domain truth", "criteria authorship", "accreditation authority", "raw test/runtime implementation", "issuer identity authority", "relying-party acceptance or business action"]},
        "ubiquitous_language_policy": {"terms": {"Claim": "precise proposition with subject scope criteria and time", "Argument": "structured support and rebuttal relations", "EvidenceItem": "identified occurrence admitted under explicit quality dimensions", "Appraisal": "planned evaluation occurrence by named appraiser", "Finding": "supported observation against criteria", "Defeater": "material reason support may not hold", "BoundedVerdict": "scope time evidence limitations and residual-bound conclusion", "Attestation": "authenticated statement, not independent appraisal"}, "homonym_rules": ["evidence is not truth", "test pass is not verdict", "signature is not authority or truth", "approval is not issuance", "independence is occurrence evidence not product identity", "verdict is not relying decision"]},
        "context_map": [{"neighbor_ref": "neighbor.relying_authority", "relationship": "customer_supplier", "translation": "receive reliance purpose and publish bounded verdict without deciding reliance"}, {"neighbor_ref": "neighbor.identity_authority", "relationship": "customer_supplier_acl", "translation": "verify appraiser issuer subject and mandate claims"}, {"neighbor_ref": "neighbor.analytical_method", "relationship": "customer_supplier", "translation": "bind exact test statistical inspection and evaluation methods"}, {"neighbor_ref": "product.lineage_provenance", "relationship": "customer_supplier", "translation": "bind evidence provenance custody and impact"}, {"neighbor_ref": "component.provider_qualification", "relationship": "peer", "translation": "exchange scoped qualification evidence without circular self-qualification"}],
        "anti_corruption_layers": ["acl.domain_criteria", "acl.identity_and_credential", "acl.test_and_oracle", "acl.attestation", "acl.signature_verification", "acl.accreditation", "acl.relying_decision"],
        "published_language": ["AssuranceCaseId", "ClaimId", "ClaimEdition", "ArgumentNode", "CriteriaProfile", "AppraisalPlan", "AppraiserAppointment", "ConflictDeclaration", "EvidenceItem", "CustodyEvent", "EvidenceEvaluation", "Finding", "Defeater", "Challenge", "BoundedVerdict", "AttestationRef", "SignatureEnvelope", "DisclosureProjection", "VerdictStatus"],
        "value_objects": ["ClaimId", "SubjectRef", "ScopeRef", "CriteriaEditionRef", "ReliancePurposeRef", "AppraiserRef", "MandateRef", "CompetenceEvidenceRef", "ConflictRef", "EvidenceId", "Digest", "CustodyRef", "FindingId", "DefeaterId", "VerdictId", "ValidityWindow"],
        "entities": ["AssuranceCase", "Claim", "ArgumentGraph", "AppraisalPlan", "AppraiserAppointment", "EvidenceItem", "Finding", "Defeater", "ChallengeCase", "BoundedVerdict"],
        "aggregates": [{"root": "AssuranceCase", "members": ["claim", "criteria", "argument", "plan", "appraisers", "evidence", "findings", "defeaters", "challenges", "verdicts"], "consistency": "one case edition closes subject scope criteria reliance purpose and authority"}, {"root": "AppraisalPlan", "members": ["methods", "population", "sampling", "environment", "schedule", "independence", "performed_work", "deviations"], "consistency": "performed work and deviations remain comparable to the approved plan"}, {"root": "BoundedVerdict", "members": ["claim_ref", "criteria_ref", "result", "support", "defeaters", "limitations", "residuals", "validity", "signature", "status"], "consistency": "verdict never exceeds appraised evidence and historical editions are immutable"}],
        "aggregate_roots": ["AssuranceCase", "AppraisalPlan", "BoundedVerdict"],
        "aggregate_invariants": ["claim identity includes subject scope criteria edition reliance purpose and time", "argument evidence finding defeater appraisal verdict and relying decision remain distinct", "evidence quality dimensions never collapse to one score", "custody and integrity do not prove truth", "appraiser competence mandate independence and conflict are evidenced per occurrence", "blocking defeaters cannot be silently offset", "absence of findings is not evidence of conformance", "automated manual and mixed appraisal modes are explicit", "verdict retains limitations residual gaps and expiry", "signature validity does not prove mandate or claim truth"],
        "commands": ["open_assurance_case", "define_claim", "bind_criteria", "construct_argument", "appoint_appraiser", "declare_conflict", "approve_appraisal_plan", "admit_evidence", "record_custody_event", "perform_appraisal", "execute_conformance_oracle", "record_finding", "raise_defeater", "open_challenge", "answer_challenge", "issue_bounded_verdict", "seal_verdict", "disclose_verdict", "supersede_verdict", "withdraw_verdict", "request_reappraisal"],
        "domain_events": ["assurance_case_opened", "claim_defined", "criteria_bound", "argument_constructed", "appraiser_appointed", "conflict_declared", "appraisal_plan_approved", "evidence_admitted", "custody_event_recorded", "appraisal_performed", "conformance_oracle_executed", "finding_recorded", "defeater_raised", "challenge_opened", "challenge_answered", "bounded_verdict_issued", "verdict_sealed", "verdict_disclosed", "verdict_superseded", "verdict_withdrawn", "reappraisal_requested"],
        "refusal_failure_catalog": ["claim_ambiguous", "subject_or_scope_unbound", "criteria_unbound_or_inapplicable", "reliance_purpose_missing", "appraisal_plan_incomplete", "appraiser_competence_unproved", "mandate_missing", "independence_conflict_unresolved", "evidence_inadmissible", "evidence_custody_broken", "population_or_sampling_undefined", "oracle_inapplicable", "finding_basis_missing", "material_defeater_unresolved", "challenge_unanswered", "scope_exceeded", "signature_invalid", "disclosure_refused", "verdict_expired"],
        "domain_services": ["ClaimScopeService", "CriteriaApplicabilityService", "ArgumentEvaluationService", "AppraiserQualificationService", "EvidenceAdmissionService", "EvidenceEvaluationService", "AppraisalExecutionService", "DefeaterResolutionService", "BoundedVerdictService", "VerdictLifecycleService"],
        "application_services": ["AuthorAssuranceCaseUseCase", "PlanAppraisalUseCase", "AppointAppraiserUseCase", "CollectAndAdmitEvidenceUseCase", "PerformAppraisalUseCase", "ChallengeFindingUseCase", "IssueVerdictUseCase", "DiscloseVerdictUseCase", "ReappraiseOrWithdrawUseCase"],
        "repositories": ["AssuranceCaseRepository", "ArgumentGraphRepository", "AppraisalPlanRepository", "AppraiserAppointmentRepository", "EvidenceItemRepository", "FindingRepository", "ChallengeCaseRepository", "BoundedVerdictRepository"],
        "factories": ["AssuranceCaseFactory", "ClaimFactory", "ArgumentGraphFactory", "AppraisalPlanFactory", "EvidenceItemFactory", "FindingFactory", "DefeaterFactory", "BoundedVerdictFactory"],
        "specifications": ["ClaimClosureSpecification", "CriteriaApplicabilitySpecification", "AppraisalPlanCompletenessSpecification", "AppraiserCompetenceAndIndependenceSpecification", "EvidenceAdmissibilitySpecification", "CustodyIntegritySpecification", "PerformedWorkSpecification", "DefeaterDispositionSpecification", "BoundedVerdictSpecification", "DisclosureSpecification"],
        "state_machine": {"AssuranceCase": ["proposed", "scoped", "planned", "evidence_collecting", "appraising", "draft_findings", "challenge_open", "final", "superseded", "withdrawn"], "EvidenceItem": ["proposed", "admission_pending", "admitted", "rejected", "stale", "recalled", "superseded"], "BoundedVerdict": ["draft", "review_pending", "issued", "sealed", "disclosed", "expired", "challenged", "superseded", "withdrawn"], "law": "contrary evidence and material defeaters block issuance according to explicit precedence and history is append-only"},
        "policies_and_reactions": ["when criteria or subject edition changes invalidate dependent verdict scope", "when evidence expires or is recalled re-evaluate affected claims", "when conflict evidence appears suspend the appraiser occurrence", "when a material defeater is raised block final issuance", "when a verdict expires remove active reliance projection", "when new automation proposes evidence treat it as an unadmitted candidate"],
        "sagas_and_process_managers": ["AssuranceCaseProcess", "AppraiserAppointmentProcess", "EvidenceCollectionAndCustodyProcess", "LongRunningAppraisalProcess", "ChallengeAndDefeaterProcess", "VerdictIssuanceProcess", "VerdictDisclosureProcess", "ReappraisalWithdrawalProcess"],
        "read_models_and_projections": ["ClaimArgumentGraphView", "CriteriaApplicabilityView", "AppraisalPlanVsPerformedView", "AppraiserConflictView", "EvidenceQualityAndCustodyView", "FindingsAndDefeatersView", "ChallengeQueue", "BoundedVerdictView", "VerdictValidityAndRelianceView"],
        "integration_event_policy": "Only editioned claim criteria plan appointment evidence finding defeater challenge verdict status attestation and disclosure contracts cross the boundary; raw secrets, provider-internal tests and relying-party decisions do not.",
        "concurrency_and_idempotency": ["case and plan edits use optimistic editions", "evidence identity binds subject occurrence source and digest", "custody events append monotonically", "oracle runs use exact subject profile environment and attempt identity", "verdict issuance is single-winner per case edition", "signature and disclosure retries reconcile unknown outcomes", "supersession and withdrawal never overwrite prior verdicts"],
        "time_model": ["claim criteria evidence appointment and mandate validity are independent", "evidence occurrence acquisition admission and evaluation times differ", "appraisal plan and performed work times are explicit", "verdict issue validity expiry challenge supersession and withdrawal times differ", "reappraisal never rewrites historical evidence or verdicts"],
        "event_storming_swimlanes": ["claim_owner", "assurance_case_author", "criteria_owner", "appraiser", "independence_reviewer", "evidence_custodian", "oracle_provider", "challenger", "verdict_issuer", "relying_authority"],
        "nonfunctional_laws": ["deterministic evidence and criteria evaluation for frozen inputs", "finite evidence test appraisal and disclosure budgets", "tamper-evident append-only custody and verdict history", "provider-neutral oracle and attestation ports", "independent review without self-qualification cycles", "complete claim-to-verdict trace including contrary evidence", "minimized audience-scoped disclosure", "optional model or agent removal preserves deterministic assurance and appraisal"],
    }
    return _result("ddd.cpra.assurance_case_appraisal", product, truth, ddd)


def enrich_product_ddd(source: dict[str, Any]) -> dict[str, Any]:
    dossiers = [_collaboration(), _privacy(), _resolution(), _assurance()]
    truths = {row["product_ref"]: row["product_truth"] for row in dossiers}
    for row in source["artifacts"]:
        truth = truths.get(row.get("artifact_id"))
        if truth:
            row.update({
                "users": truth["users"],
                "harmed_parties": truth["harmed_parties"],
                "jobs": truth["jobs"],
                "outcomes": truth["measurable_outcomes"],
                "automation_modality": AUTOMATION,
            })
    source["ddd_dossiers"] = dossiers
    source["non_collapse_laws"].extend([
        "participant admission != contribution admission != analysis approval != execution success != output release",
        "requestor != data subject != subject scope != record scope != effect target",
        "record occurrence != candidate pair != feature evidence != score != link decision != cluster != master identity",
        "claim != argument != evidence != finding != defeater != appraisal != verdict != relying decision",
    ])
    source["negative_tests"].extend([
        {"test_id": "negative.cpra.collaboration_release_success", "prohibited_claim": "Successful approved computation authorizes output release.", "expected_result": "open a separate scoped output review and authority gate"},
        {"test_id": "negative.cpra.privacy_ack_erasure", "prohibited_claim": "A provider acknowledgement proves verified erasure.", "expected_result": "retain verification pending and exact residual scope"},
        {"test_id": "negative.cpra.resolution_cluster_truth", "prohibited_claim": "A computed entity cluster is authoritative real-world or master identity.", "expected_result": "retain resolution evidence and submit a master proposal"},
        {"test_id": "negative.cpra.assurance_signature_truth", "prohibited_claim": "A valid signature proves appraiser mandate independence or claim truth.", "expected_result": "verify each property separately and preserve bounded verdict limits"},
    ])
    return source

