#!/usr/bin/env python3
"""Authored source model for the governed corpus build protocol.

This is build-system metadata, not domain authority.  A package contract says how
an artifact is reproduced and checked; it does not ratify the artifact's meaning.
"""
from __future__ import annotations

PROTOCOL_VERSION = "1.0.0-candidate"

PACKAGE_KINDS = {
    "authored_source": "Human-authored evidence or policy; validation is allowed but automatic regeneration is not.",
    "deterministic_projection": "Outputs are a pure deterministic projection of declared inputs.",
    "fixed_point_projection": "Projection observes a broad corpus and must be rerun after upstream writes until stable.",
    "aggregate_validator": "Read-only validator over other packages; it owns no generated semantic records.",
    "execution_campaign": "Runs implementations or systems and emits occurrence-bound evidence receipts.",
    "historical_snapshot": "Immutable evidence from an earlier campaign; never silently rebuilt against live inputs.",
}

AUTHORITY_CLASSES = {
    "structural_metadata",
    "research_candidate",
    "proposed_unratified",
    "execution_evidence_not_qualification",
    "historical_evidence",
}

REBUILD_POLICIES = {
    "on_declared_input_change",
    "repository_fixed_point",
    "validate_only",
    "manual_evidence_occurrence",
    "immutable_never_rebuild",
}

WRITE_POLICIES = {
    "package_root_only",
    "declared_output_paths_only",
    "read_only",
}

# The first executable slice is deliberately small and high-fanout.  Other
# discovered packages are inventoried as migration candidates rather than being
# guessed into an unsafe order.
CONTRACTS = [
    {
        "package_id": "package.solution_synthesis_architecture",
        "root": "research/product_ontology/solution_synthesis_architecture",
        "package_kind": "deterministic_projection",
        "authority_class": "structural_metadata",
        "dependency_refs": [],
        "build_commands": [["python3", "research/product_ontology/solution_synthesis_architecture/build_corpus.py"]],
        "validate_commands": [["python3", "research/product_ontology/solution_synthesis_architecture/validate.py"]],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": True,
        "input_selectors": ["research/product_ontology/solution_synthesis_architecture/source_model.py"],
        "uncontracted_input_surfaces": [],
        "fixed_point_group": None,
        "negative_claims": ["does_not_ratify_products", "does_not_select_providers", "compiler_is_not_universal_judgment"],
    },
    {
        "package_id": "package.library_registry",
        "root": "research/domain_atlas/compiler/library_registry",
        "package_kind": "deterministic_projection",
        "authority_class": "research_candidate",
        "dependency_refs": [],
        "build_commands": [["python3", "research/domain_atlas/compiler/library_registry/generate_registry.py"]],
        "validate_commands": [["python3", "research/domain_atlas/compiler/library_registry/validate_registry.py"]],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/domain_atlas/universes/**", "research/domain_atlas/compiler/provider_target_registry/**"],
        "uncontracted_input_surfaces": ["universe package contracts", "provider-target package contract"],
        "fixed_point_group": None,
        "negative_claims": ["registry_entry_is_not_ratified_contract", "provider_reference_is_not_qualified_offer"],
    },
    {
        "package_id": "package.contract_generation",
        "root": "research/domain_atlas/compiler/library_registry/contract_generation",
        "package_kind": "deterministic_projection",
        "authority_class": "proposed_unratified",
        "dependency_refs": ["package.library_registry"],
        "build_commands": [["python3", "research/domain_atlas/compiler/library_registry/contract_generation/build_program.py"]],
        "validate_commands": [["python3", "research/domain_atlas/compiler/library_registry/contract_generation/validate.py"]],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/domain_atlas/compiler/library_registry/*.jsonl", "research/domain_atlas/universes/**"],
        "uncontracted_input_surfaces": ["universe package contracts"],
        "fixed_point_group": None,
        "negative_claims": ["generated_contract_is_not_ratified", "generated_api_is_not_implementation"],
    },
    {
        "package_id": "package.semantic_decomposition",
        "root": "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition",
        "package_kind": "deterministic_projection",
        "authority_class": "proposed_unratified",
        "dependency_refs": ["package.contract_generation"],
        "build_commands": [["python3", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/build_semantic_decomposition.py"]],
        "validate_commands": [["python3", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/validate.py"]],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/domain_atlas/compiler/library_registry/contract_generation/*.{json,jsonl}"],
        "uncontracted_input_surfaces": ["nested semantic evidence and coordinate package contracts"],
        "fixed_point_group": None,
        "negative_claims": ["axis_coverage_is_not_axis_decision", "route_is_not_evidence"],
    },
    {
        "package_id": "package.gap_topology",
        "root": "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/gap_topology",
        "package_kind": "deterministic_projection",
        "authority_class": "structural_metadata",
        "dependency_refs": ["package.semantic_decomposition"],
        "build_commands": [["python3", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/gap_topology/build_gap_topology.py"]],
        "validate_commands": [["python3", "research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/gap_topology/validate.py"]],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/**"],
        "uncontracted_input_surfaces": ["coordinate, evidence-campaign and adjudication package contracts"],
        "fixed_point_group": None,
        "negative_claims": ["gap_accounting_is_not_gap_closure"],
    },
    {
        "package_id": "package.research_convergence_rebase",
        "root": "research/product_ontology/research_convergence_rebase",
        "package_kind": "deterministic_projection",
        "authority_class": "proposed_unratified",
        "dependency_refs": ["package.gap_topology"],
        "build_commands": [["python3", "research/product_ontology/research_convergence_rebase/build_rebase.py"]],
        "validate_commands": [["python3", "research/product_ontology/research_convergence_rebase/validate.py"]],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/domain_atlas/compiler/library_registry/contract_generation/semantic_decomposition/gap_topology/**", "research/handoffs/gpt-pro-product-ontology-convergence/output-2026-08-27/**"],
        "uncontracted_input_surfaces": ["immutable GPT campaign snapshot contract"],
        "fixed_point_group": None,
        "negative_claims": ["prior_snapshot_does_not_cover_new_atoms", "research_resolution_is_not_ratification"],
    },
    {
        "package_id": "package.closure_program",
        "root": "research/product_ontology/closure_program",
        "package_kind": "deterministic_projection",
        "authority_class": "structural_metadata",
        "dependency_refs": ["package.research_convergence_rebase", "package.solution_synthesis_architecture"],
        "build_commands": [
            ["python3", "research/product_ontology/closure_program/build_program.py"],
            ["python3", "research/product_ontology/closure_program/build_master_frontier.py"],
            ["python3", "research/product_ontology/closure_program/build_program_level_gates.py"],
            ["python3", "research/product_ontology/closure_program/build_program_work_surfaces.py"],
            ["python3", "research/product_ontology/closure_program/build_effective_progress.py"],
        ],
        "validate_commands": [
            ["python3", "research/product_ontology/closure_program/validate.py"],
            ["python3", "research/product_ontology/closure_program/validate_program_level_gates.py"],
            ["python3", "research/product_ontology/closure_program/validate_program_work_surfaces.py"],
        ],
        "rebuild_policy": "on_declared_input_change",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/product_ontology/research_convergence_rebase/**", "research/product_ontology/qualification_program/**", "research/domain_atlas/industries/**", "research/domain_atlas/context_map/**", "research/domain_atlas/universes/**"],
        "uncontracted_input_surfaces": ["qualification, industry, context-map and universe package contracts"],
        "fixed_point_group": None,
        "negative_claims": ["structural_done_is_not_ratified", "evidence_gate_is_not_research_gap"],
    },
    {
        "package_id": "package.global_boundary_research",
        "root": "research/product_ontology/global_boundary_research",
        "package_kind": "fixed_point_projection",
        "authority_class": "research_candidate",
        "dependency_refs": ["package.closure_program"],
        "build_commands": [["python3", "research/product_ontology/global_boundary_research/build_corpus.py"]],
        "validate_commands": [["python3", "research/product_ontology/global_boundary_research/validate_corpus.py"]],
        "rebuild_policy": "repository_fixed_point",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/**", "!research/product_ontology/global_boundary_research/**"],
        "uncontracted_input_surfaces": ["repository-wide package contract closure"],
        "fixed_point_group": "fixed_point.repository_inventory",
        "negative_claims": ["inventory_saturation_is_not_world_completeness"],
    },
    {
        "package_id": "package.corpus_architecture_router",
        "root": "research/product_ontology/corpus_architecture_router",
        "package_kind": "fixed_point_projection",
        "authority_class": "structural_metadata",
        "dependency_refs": ["package.global_boundary_research"],
        "build_commands": [["python3", "research/product_ontology/corpus_architecture_router/build_router.py"]],
        "validate_commands": [["python3", "research/product_ontology/corpus_architecture_router/validate.py"]],
        "rebuild_policy": "repository_fixed_point",
        "write_policy": "package_root_only",
        "execution_enabled": False,
        "input_selectors": ["research/**", "!research/product_ontology/corpus_architecture_router/**"],
        "uncontracted_input_surfaces": ["repository-wide package contract closure"],
        "fixed_point_group": "fixed_point.repository_inventory",
        "negative_claims": ["route_is_not_identity_adjudication", "position_address_is_not_stable_identity"],
    },
    {
        "package_id": "package.product_ontology_aggregate_validation",
        "root": "research/product_ontology",
        "package_kind": "aggregate_validator",
        "authority_class": "structural_metadata",
        "dependency_refs": ["package.corpus_architecture_router", "package.closure_program"],
        "build_commands": [],
        "validate_commands": [["python3", "research/product_ontology/validate_registry.py"]],
        "rebuild_policy": "validate_only",
        "write_policy": "read_only",
        "execution_enabled": True,
        "input_selectors": ["research/**"],
        "uncontracted_input_surfaces": ["read-only aggregate validation accepts explicitly inventoried legacy inputs"],
        "fixed_point_group": None,
        "negative_claims": ["validator_pass_is_bounded_by_encoded_laws"],
    },
]
